// 歌曲：Medley：密友+损友+心甘命抵+早有预谋+罪魁+借过+我也不想这样（live）

(function() {
    const song = {
        id: 145,
        title: "Medley：密友+损友+心甘命抵+早有预谋+罪魁+借过+我也不想这样（live）",
        titleJyutping: ["","","","","","","","mat6","jau5","","syun2","jau5","","sam1","gam1","ming6","dai2","","zou2","jau5","jyu6","mau4","","zeoi6","fui1","","ze3","gwo3","","ngo5","jaa5","bat1","soeng2","ze5","joeng6","","","","","",""],
        artist: "容祖儿",
        artistJyutping: ["jung4","zou2","ji4"],
        lyricist: "",
        lyricistJyutping: [],
        composer: "",
        composerJyutping: [],
        lyrics: [
            { chars: ["《","密","友","》"], jp: ["","mat6","jau5",""] },
            { paragraphBreak: true },
            { chars: ["彼","此","间","再","亲"], jp: ["bei2","ci2","gaan1","zoi3","can1"] },
            { chars: ["而","在","眼","里","都","不","配","衬"], jp: ["ji4","zoi6","ngaan5","lei5","dou1","bat1","pui3","can3"] },
            { chars: ["如","若","靠","近"], jp: ["jyu4","joek6","kaau3","gan6"] },
            { chars: ["途","人","便","会","指","控","变","犯","人"], jp: ["tou4","jan4","bin6","wui6","zi2","hung3","bin3","faan6","jan4"] },
            { chars: ["即","使","关","了","灯"], jp: ["zik1","si2","gwaan1","liu5","dang1"] },
            { chars: ["谁","又","介","意","家","中","接","吻"], jp: ["seoi4","jau6","gaai3","ji3","gaa1","zung1","zip3","man5"] },
            { chars: ["然","后","一","吻"], jp: ["jin4","hau6","jat1","man5"] },
            { chars: ["无","奈","让","我","醒","觉","有","别","人"], jp: ["mou4","noi6","joeng6","ngo5","sing2","gok3","jau5","bit6","jan4"] },
            { chars: ["注","定","伤","心"], jp: ["zyu3","ding6","soeng1","sam1"] },
            { chars: ["谁","明","白","我","已","被","困"], jp: ["seoi4","ming4","baak6","ngo5","ji5","bei6","kwan3"] },
            { chars: ["难","道","我","再","有","力","气","苦","苦","去","等"], jp: ["naan4","dou6","ngo5","zoi3","jau5","lik6","hei3","fu2","fu2","heoi3","dang2"] },
            { chars: ["等","一","天","当","我","不","再","恨"], jp: ["dang2","jat1","tin1","dong1","ngo5","bat1","zoi3","han6"] },
            { chars: ["我","暗","地","里","豁","出","去"], jp: ["ngo5","am3","dei6","lei5","kut3","ceot1","heoi3"] },
            { chars: ["见","面","也","于","家","里"], jp: ["gin3","min6","jaa5","jyu1","gaa1","lei5"] },
            { chars: ["可","惜","那","字","句"], jp: ["ho2","sik1","naa5","zi6","geoi3"] },
            { chars: ["仍","没","法","击","退"], jp: ["jing4","mut6","faat3","gik1","teoi3"] },
            { chars: ["与","密","友","欠","登","对"], jp: ["jyu5","mat6","jau5","him3","dang1","deoi3"] },
            { chars: ["与","密","友","爱","不","对"], jp: ["jyu5","mat6","jau5","ngoi3","bat1","deoi3"] },
            { chars: ["反","对","若","这","样","爱","的","情","侣"], jp: ["faan2","deoi3","joek6","ze5","joeng6","ngoi3","dik1","cing4","leoi5"] },
            { paragraphBreak: true },
            { chars: ["《","损","友","》"], jp: ["","syun2","jau5",""] },
            { paragraphBreak: true },
            { chars: ["愿","能","在","你","失","意","热","情","慰","问"], jp: ["jyun6","nang4","zoi6","nei5","sat1","ji3","jit6","cing4","wai3","man6"] },
            { chars: ["未","能","被","你","酒","后","趁","机","一","吻"], jp: ["mei6","nang4","bei6","nei5","zau2","hau6","can3","gei1","jat1","man5"] },
            { chars: ["谁","人","与","你","成","为","爱","侣"], jp: ["seoi4","jan4","jyu5","nei5","sing4","wai4","ngoi3","leoi5"] },
            { chars: ["能","保","证","绝","无","挂","虑"], jp: ["nang4","bou2","zing3","zyut6","mou4","gwaa3","leoi6"] },
            { chars: ["谈","情","说","爱"], jp: ["taam4","cing4","syut3","ngoi3"] },
            { chars: ["何","日","都","可","告","吹"], jp: ["ho4","jat6","dou1","ho2","gou3","ceoi1"] },
            { chars: ["宁","愿","留","下","友","情"], jp: ["ning4","jyun6","lau4","haa6","jau5","cing4"] },
            { chars: ["伤","心","都","只","可","斗","咀"], jp: ["soeng1","sam1","dou1","zi2","ho2","dau3","zeoi2"] },
            { chars: ["谁","更","清","楚"], jp: ["seoi4","gang1","cing1","co2"] },
            { chars: ["清","楚","你","的","风","流"], jp: ["cing1","co2","nei5","dik1","fung1","lau4"] },
            { chars: ["缠","住","你","手"], jp: ["cin4","zyu6","nei5","sau2"] },
            { chars: ["只","怕","热","泪","会","流"], jp: ["zi2","paa3","jit6","leoi6","wui6","lau4"] },
            { chars: ["和","你","能","扮","演","好","友"], jp: ["wo4","nei5","nang4","baan6","jin2","hou2","jau5"] },
            { chars: ["男","士","那","般","搭","膊","头"], jp: ["naam4","si6","naa5","bun1","daap3","bok3","tau4"] },
            { chars: ["和","你","牵","手"], jp: ["wo4","nei5","hin1","sau2"] },
            { chars: ["只","恐","怕","太","荒","谬"], jp: ["zi2","hung2","paa3","taai3","fong1","mau6"] },
            { chars: ["还","是","当","你","一","位","损","友"], jp: ["waan4","si6","dong1","nei5","jat1","wai6","syun2","jau5"] },
            { chars: ["没","寄","望","没","强","求"], jp: ["mut6","gei3","mong6","mut6","koeng4","kau4"] },
            { chars: ["纵","使","找","到","新","欢"], jp: ["zung3","si2","zaau2","dou3","san1","fun1"] },
            { chars: ["你","也","会","笑","着","不","内","疚"], jp: ["nei5","jaa5","wui6","siu3","zoek6","bat1","noi6","gau3"] },
            { chars: ["谁","昨","晚","共","你","一","起"], jp: ["seoi4","zok6","maan5","gung6","nei5","jat1","hei2"] },
            { chars: ["用","情","如","像","游","戏"], jp: ["jung6","cing4","jyu4","zoeng6","jau4","hei3"] },
            { chars: ["我","没","福","气","去","责","备","你"], jp: ["ngo5","mut6","fuk1","hei3","heoi3","zaak3","bei6","nei5"] },
            { chars: ["无","谓","揭","露","谁","在","妒","忌"], jp: ["mou4","wai6","kit3","lou6","seoi4","zoi6","dou3","gei6"] },
            { chars: ["就","怪","我","太","清","楚"], jp: ["zau6","gwaai3","ngo5","taai3","cing1","co2"] },
            { chars: ["清","楚","你","的","风","流"], jp: ["cing1","co2","nei5","dik1","fung1","lau4"] },
            { chars: ["明","白","你"], jp: ["ming4","baak6","nei5"] },
            { chars: ["一","世","亦","贪","新","厌","旧"], jp: ["jat1","sai3","jik6","taam1","san1","jim3","gau6"] },
            { chars: ["我","宁","愿","当","好","友"], jp: ["ngo5","ning4","jyun6","dong1","hou2","jau5"] },
            { chars: ["无","愁","无","虑","地","碰","头"], jp: ["mou4","sau4","mou4","leoi6","dei6","pung3","tau4"] },
            { chars: ["和","你","牵","手"], jp: ["wo4","nei5","hin1","sau2"] },
            { chars: ["只","恐","怕","太","荒","谬"], jp: ["zi2","hung2","paa3","taai3","fong1","mau6"] },
            { chars: ["还","是","当","最","忠","心","损","友"], jp: ["waan4","si6","dong1","zeoi3","zung1","sam1","syun2","jau5"] },
            { chars: ["没","寄","望","没","强","求"], jp: ["mut6","gei3","mong6","mut6","koeng4","kau4"] },
            { chars: ["若","我","离","开"], jp: ["joek6","ngo5","lei4","hoi1"] },
            { chars: ["你","不","曾","内","疚"], jp: ["nei5","bat1","zang1","noi6","gau3"] },
            { chars: ["是","友","情"," ","没","强","求"], jp: ["si6","jau5","cing4","","mut6","koeng4","kau4"] },
            { chars: ["永","开","不","到","口"], jp: ["wing5","hoi1","bat1","dou3","hau2"] },
            { chars: ["爱","恋","有","没","有"], jp: ["ngoi3","lyun2","jau5","mut6","jau5"] },
            { paragraphBreak: true },
            { chars: ["《","心","甘","命","抵","》"], jp: ["","sam1","gam1","ming6","dai2",""] },
            { paragraphBreak: true },
            { chars: ["还","未","看","到","木","村"], jp: ["waan4","mei6","hon3","dou3","muk6","cyun1"] },
            { chars: ["离","别","当","初","的","队","员"], jp: ["lei4","bit6","dong1","co1","dik1","deoi6","jyun4"] },
            { chars: ["如","你","我","这","就","算"], jp: ["jyu4","nei5","ngo5","ze5","zau6","syun3"] },
            { chars: ["风","光","真","的","太","短"], jp: ["fung1","gwong1","zan1","dik1","taai3","dyun2"] },
            { chars: ["还","未","说","到","木","村"], jp: ["waan4","mei6","syut3","dou3","muk6","cyun1"] },
            { chars: ["何","日","变","节","再","热","恋"], jp: ["ho4","jat6","bin3","zit3","zoi3","jit6","lyun2"] },
            { chars: ["与","你","一","起","给","他","算","算"], jp: ["jyu5","nei5","jat1","hei2","kap1","taa1","syun3","syun3"] },
            { chars: ["也","许","可","扼","多","几","天","寒","暄"], jp: ["jaa5","heoi2","ho2","ak1","do1","gei2","tin1","hon4","hyun1"] },
            { chars: ["你","最","初","答","应","过","我","什","么"], jp: ["nei5","zeoi3","co1","daap3","jing3","gwo3","ngo5","sap6","maa1"] },
            { chars: ["我","最","终","错","过","了","什","么"], jp: ["ngo5","zeoi3","zung1","co3","gwo3","liu5","sap6","maa1"] },
            { chars: ["不","见","得"], jp: ["bat1","gin3","dak1"] },
            { chars: ["曾","讨","好","过","我"], jp: ["zang1","tou2","hou2","gwo3","ngo5"] },
            { chars: ["起","码","也","要","憎","恨","我"], jp: ["hei2","maa5","jaa5","jiu3","zang1","han6","ngo5"] },
            { chars: ["你","至","少","怪","责","我","什","么"], jp: ["nei5","zi3","siu2","gwaai3","zaak3","ngo5","sap6","maa1"] },
            { chars: ["才","清","楚","你","当","我","什","么"], jp: ["coi4","cing1","co2","nei5","dong1","ngo5","sap6","maa1"] },
            { chars: ["纪","念","留","到","够","多"], jp: ["gei2","nim6","lau4","dou3","gau3","do1"] },
            { chars: ["才","能","甘","心","将","错","就","错"], jp: ["coi4","nang4","gam1","sam1","zoeng1","co3","zau6","co3"] },
            { chars: ["眼","泪","还","有","很","多"], jp: ["ngaan5","leoi6","waan4","jau5","han2","do1"] },
            { chars: ["何","必","要","急","于","背","叛","我"], jp: ["ho4","bit1","jiu3","gap1","jyu1","bui3","bun6","ngo5"] },
            { chars: ["还","未","爱","到","我","变","心"], jp: ["waan4","mei6","ngoi3","dou3","ngo5","bin3","sam1"] },
            { chars: ["也","未","吻","到","我","消","沉"], jp: ["jaa5","mei6","man5","dou3","ngo5","siu1","cam4"] },
            { chars: ["何","不","等","等"], jp: ["ho4","bat1","dang2","dang2"] },
            { chars: ["爱","到","恨","都","不","能","恨"], jp: ["ngoi3","dou3","han6","dou1","bat1","nang4","han6"] },
            { chars: ["难","道","我","会","甘","心"], jp: ["naan4","dou6","ngo5","wui6","gam1","sam1"] },
            { chars: ["你","这","么","快","要","撤","退","干","什","么"], jp: ["nei5","ze5","maa1","faai3","jiu3","cit3","teoi3","gon1","sap6","maa1"] },
            { chars: ["我","最","多","再","要","半","秒","怕","什","么"], jp: ["ngo5","zeoi3","do1","zoi3","jiu3","bun3","miu5","paa3","sap6","maa1"] },
            { chars: ["不","要","紧"], jp: ["bat1","jiu3","gan2"] },
            { chars: ["乘","机","鞭","挞","我"], jp: ["sing4","gei1","bin1","taat3","ngo5"] },
            { chars: ["等","我","去","承","认","坎","坷"], jp: ["dang2","ngo5","heoi3","sing4","jing6","ham2","ho2"] },
            { chars: ["我","不","知","你","贡","献","过","我","什","么"], jp: ["ngo5","bat1","zi1","nei5","gung3","hin3","gwo3","ngo5","sap6","maa1"] },
            { chars: ["而","天","知","道","我","欠","了","你","什","么"], jp: ["ji4","tin1","zi1","dou6","ngo5","him3","liu5","nei5","sap6","maa1"] },
            { chars: ["结","局","还","有","很","多"], jp: ["git3","guk6","waan4","jau5","han2","do1"] },
            { chars: ["为","何","只","得","这","个","后","果"], jp: ["wai4","ho4","zi2","dak1","ze5","go3","hau6","gwo2"] },
            { chars: ["劫","难","还","有","很","多"], jp: ["gip3","naan4","waan4","jau5","han2","do1"] },
            { chars: ["何","必","太","心","急","去"], jp: ["ho4","bit1","taai3","sam1","gap1","heoi3"] },
            { chars: ["害","我"], jp: ["hoi6","ngo5"] },
            { paragraphBreak: true },
            { chars: ["《","早","有","预","谋","》"], jp: ["","zou2","jau5","jyu6","mau4",""] },
            { paragraphBreak: true },
            { chars: ["你","说","你","对","我","到","底","不","放","心"], jp: ["nei5","syut3","nei5","deoi3","ngo5","dou3","dai2","bat1","fong3","sam1"] },
            { chars: ["但","愿","在","日","后","亦","饰","演","好","友"], jp: ["daan6","jyun6","zoi6","jat6","hau6","jik6","sik1","jin2","hou2","jau5"] },
            { chars: ["留","下","我"], jp: ["lau4","haa6","ngo5"] },
            { chars: ["无","须","给","我"], jp: ["mou4","seoi1","kap1","ngo5"] },
            { chars: ["坏","理","由"], jp: ["waai6","lei5","jau4"] },
            { chars: ["为","我","加","演","一","晚"], jp: ["wai4","ngo5","gaa1","jin2","jat1","maan5"] },
            { chars: ["无","非","安","心","想","好","聚","时","也","好","散"], jp: ["mou4","fei1","on1","sam1","soeng2","hou2","zeoi6","si4","jaa5","hou2","saan3"] },
            { chars: ["罪","恶","感","会","消","减"], jp: ["zeoi6","ok3","gam2","wui6","siu1","gaam2"] },
            { chars: ["但","我","其","时","完","全","入","信"], jp: ["daan6","ngo5","kei4","si4","jyun4","cyun4","jap6","seon3"] },
            { chars: ["事","情","是","遇","上","转","机"], jp: ["si6","cing4","si6","jyu6","soeng6","zyun2","gei1"] },
            { chars: ["这","夜","重","重","疑","阵","其","实","是","你"], jp: ["ze5","je6","cung5","cung5","ji4","zan6","kei4","sat6","si6","nei5"] },
            { chars: ["临","告","别","上","演","的","好","戏"], jp: ["lam4","gou3","bit6","soeng6","jin2","dik1","hou2","hei3"] },
            { chars: ["原","来","回","光","返","照","以","后"], jp: ["jyun4","loi4","wui4","gwong1","faan2","ziu3","ji5","hau6"] },
            { chars: ["缠","绵","游","戏","到","达","尽","头"], jp: ["cin4","min4","jau4","hei3","dou3","daat6","zeon6","tau4"] },
            { chars: ["你","对","我","就","算","甜","蜜","过"], jp: ["nei5","deoi3","ngo5","zau6","syun3","tim4","mat6","gwo3"] },
            { chars: ["亦","都","早","有","预","谋"], jp: ["jik6","dou1","zou2","jau5","jyu6","mau4"] },
            { chars: ["难","离","难","舍","的","吻","背","后"], jp: ["naan4","lei4","naan4","se3","dik1","man5","bui3","hau6"] },
            { chars: ["原","来","嫌","我","痛","得","不","够"], jp: ["jyun4","loi4","jim4","ngo5","tung3","dak1","bat1","gau3"] },
            { chars: ["你","故","意","让","我","怀","念","你"], jp: ["nei5","gu3","ji3","joeng6","ngo5","waai4","nim6","nei5"] },
            { chars: ["做","完","戏","就","要","走"], jp: ["zou6","jyun4","hei3","zau6","jiu3","zau2"] },
            { chars: ["可","惜","我","不","会","是"], jp: ["ho2","sik1","ngo5","bat1","wui6","si6"] },
            { chars: ["好","的","演","出","对","手"], jp: ["hou2","dik1","jin2","ceot1","deoi3","sau2"] },
            { chars: ["怎","么","吻","都","似","是","木","偶"], jp: ["zam2","maa1","man5","dou1","ci5","si6","muk6","ngau5"] },
            { chars: ["你","声","声","抱","歉"], jp: ["nei5","sing1","sing1","pou5","hip3"] },
            { chars: ["都","不","似","有","内","疚"], jp: ["dou1","bat1","ci5","jau5","noi6","gau3"] },
            { paragraphBreak: true },
            { chars: ["《","罪","魁","》"], jp: ["","zeoi6","fui1",""] },
            { paragraphBreak: true },
            { chars: ["亲","与","戚"], jp: ["can1","jyu5","cik1"] },
            { chars: ["也","很","想","我"], jp: ["jaa5","han2","soeng2","ngo5"] },
            { chars: ["有","好","结","果"], jp: ["jau5","hou2","git3","gwo2"] },
            { chars: ["幻","想","得","太","多","彷","佛","逼","我"], jp: ["waan6","soeng2","dak1","taai3","do1","pong4","fat6","bik1","ngo5"] },
            { chars: ["欢","乐","谐","和"], jp: ["fun1","lok6","haai4","wo4"] },
            { chars: ["但","我","问","我"], jp: ["daan6","ngo5","man6","ngo5"] },
            { chars: ["并","未","快","慰","得","多"], jp: ["bing6","mei6","faai3","wai3","dak1","do1"] },
            { chars: ["我","抱","的","少"], jp: ["ngo5","pou5","dik1","siu2"] },
            { chars: ["抱","我","的","多"], jp: ["pou5","ngo5","dik1","do1"] },
            { chars: ["我","算","过","计","过"], jp: ["ngo5","syun3","gwo3","gai3","gwo3"] },
            { chars: ["也","要","自","私","的","想","我"], jp: ["jaa5","jiu3","zi6","si1","dik1","soeng2","ngo5"] },
            { chars: ["没","有","对","方","仍","怀","念","别","个"], jp: ["mut6","jau5","deoi3","fong1","jing4","waai4","nim6","bit6","go3"] },
            { chars: ["是","我"," ","找","我"], jp: ["si6","ngo5","","zaau2","ngo5"] },
            { chars: ["我","那","忍","心","下","去","继","续","在","扮","傻"], jp: ["ngo5","naa5","jan2","sam1","haa6","heoi3","gai3","zuk6","zoi6","baan6","so4"] },
            { chars: ["为","求","多","一","日","好","过"], jp: ["wai4","kau4","do1","jat1","jat6","hou2","gwo3"] },
            { chars: ["就","任","人","发","现","彼","此","结","果"], jp: ["zau6","jam6","jan4","faat3","jin6","bei2","ci2","git3","gwo2"] },
            { chars: ["是","我"," ","我","最","多"], jp: ["si6","ngo5","","ngo5","zeoi3","do1"] },
            { chars: ["自","认","这","恋","爱","是","全","错"], jp: ["zi6","jing6","ze5","lyun2","ngoi3","si6","cyun4","co3"] },
            { chars: ["跟","爱","人","来","认","错"], jp: ["gan1","ngoi3","jan4","loi4","jing6","co3"] },
            { chars: ["不","太","愉","快","渡","过"], jp: ["bat1","taai3","jyu4","faai3","dou6","gwo3"] },
            { chars: ["我","甚","至","不","认","识","我"], jp: ["ngo5","sam6","zi3","bat1","jing6","sik1","ngo5"] },
            { chars: ["往","日","虽","不","致","白","过"], jp: ["wong5","jat6","seoi1","bat1","zi3","baak6","gwo3"] },
            { chars: ["连","对","象","也","认","错"], jp: ["lin4","deoi3","zoeng6","jaa5","jing6","co3"] },
            { chars: ["不","浪","费","一","个","好","天"], jp: ["bat1","long6","fai3","jat1","go3","hou2","tin1"] },
            { chars: ["不","蹉","跎"], jp: ["bat1","co1","to4"] },
            { chars: ["离","开"], jp: ["lei4","hoi1"] },
            { chars: ["只","懂","得","补","充","一","句","奈","何"], jp: ["zi2","dung2","dak1","bou2","cung1","jat1","geoi3","noi6","ho4"] },
            { chars: ["愉","快","少"], jp: ["jyu4","faai3","siu2"] },
            { chars: ["困","恼","多"], jp: ["kwan3","nou5","do1"] },
            { chars: ["要","放","弃","对","方","那","人","物","是","我"], jp: ["jiu3","fong3","hei3","deoi3","fong1","naa5","jan4","mat6","si6","ngo5"] },
            { chars: ["是","我"," ","我","最","多"], jp: ["si6","ngo5","","ngo5","zeoi3","do1"] },
            { chars: ["自","认","这","恋","爱","是","全","错"], jp: ["zi6","jing6","ze5","lyun2","ngoi3","si6","cyun4","co3"] },
            { chars: ["跟","爱","人","来","认","错"], jp: ["gan1","ngoi3","jan4","loi4","jing6","co3"] },
            { chars: ["不","太","愉","快","渡","过"], jp: ["bat1","taai3","jyu4","faai3","dou6","gwo3"] },
            { chars: ["我","甚","至","不","认","识","我"], jp: ["ngo5","sam6","zi3","bat1","jing6","sik1","ngo5"] },
            { chars: ["若","然","曷","回","望","当","初"], jp: ["joek6","jin4","hot3","wui4","mong6","dong1","co1"] },
            { chars: ["我","欺","骗","人"], jp: ["ngo5","hei1","pin3","jan4"] },
            { chars: ["我","可","以"], jp: ["ngo5","ho2","ji5"] },
            { chars: ["认","错"], jp: ["jing6","co3"] },
            { paragraphBreak: true },
            { chars: ["《","借","过","》"], jp: ["","ze3","gwo3",""] },
            { paragraphBreak: true },
            { chars: ["看","看","你"], jp: ["hon3","hon3","nei5"] },
            { chars: ["谁","人","可","比","你","好"], jp: ["seoi4","jan4","ho2","bei2","nei5","hou2"] },
            { chars: ["好","得","这","么","恐","怖"], jp: ["hou2","dak1","ze5","maa1","hung2","bou3"] },
            { chars: ["真","的","不","知","所","措"], jp: ["zan1","dik1","bat1","zi1","so2","cou3"] },
            { chars: ["连","前","度","那","伤","口"], jp: ["lin4","cin4","dou6","naa5","soeng1","hau2"] },
            { chars: ["也","细","致","的","问","到"], jp: ["jaa5","sai3","zi3","dik1","man6","dou3"] },
            { chars: ["痛","到","那","种","程","度"], jp: ["tung3","dou3","naa5","zung2","cing4","dou6"] },
            { chars: ["迟","一","些","可","会","好"], jp: ["ci4","jat1","se1","ho2","wui6","hou2"] },
            { chars: ["还","提","及","上","次","恋","爱"], jp: ["waan4","tai4","kap6","soeng6","ci3","lyun2","ngoi3"] },
            { chars: ["预","算","与","我","终","老"], jp: ["jyu6","syun3","jyu5","ngo5","zung1","lou5"] },
            { chars: ["现","在","和","她","一","起"], jp: ["jin6","zoi6","wo4","taa1","jat1","hei2"] },
            { chars: ["也","想","起","我","的","好"], jp: ["jaa5","soeng2","hei2","ngo5","dik1","hou2"] },
            { chars: ["伤","我","或","是","害","我"], jp: ["soeng1","ngo5","waak6","si6","hoi6","ngo5"] },
            { chars: ["都","惨","不","过","教","我"], jp: ["dou1","caam2","bat1","gwo3","gaau3","ngo5"] },
            { chars: ["记","得","一","起","幸","福","过"], jp: ["gei3","dak1","jat1","hei2","hang6","fuk1","gwo3"] },
            { chars: ["情","愿","我","听","不","清","楚"], jp: ["cing4","jyun6","ngo5","ting1","bat1","cing1","co2"] },
            { chars: ["当","时","谁","人"], jp: ["dong1","si4","seoi4","jan4"] },
            { chars: ["口","口","声","声","不","会","掉","低","我"], jp: ["hau2","hau2","sing1","sing1","bat1","wui6","diu6","dai1","ngo5"] },
            { chars: ["待","我","差","我","没","有","奈","何"], jp: ["doi6","ngo5","caa1","ngo5","mut6","jau5","noi6","ho4"] },
            { chars: ["为","何","扮","好","心"], jp: ["wai4","ho4","baan6","hou2","sam1"] },
            { chars: ["慰","问","很","挂","念","我","么"], jp: ["wai3","man6","han2","gwaa3","nim6","ngo5","maa1"] },
            { chars: ["还","能","成","为","密","友","么"], jp: ["waan4","nang4","sing4","wai4","mat6","jau5","maa1"] },
            { chars: ["你","说","得","真","轻","松","讲","笑","也"], jp: ["nei5","syut3","dak1","zan1","hing1","cung4","gong2","siu3","jaa5"] },
            { chars: ["别","太","过"], jp: ["bit6","taai3","gwo3"] },
            { paragraphBreak: true },
            { chars: ["《","我","也","不","想","这","样","》"], jp: ["","ngo5","jaa5","bat1","soeng2","ze5","joeng6",""] },
            { paragraphBreak: true },
            { chars: ["你","也","不","想","这","样"], jp: ["nei5","jaa5","bat1","soeng2","ze5","joeng6"] },
            { chars: ["但","别","讲","出","真","相"], jp: ["daan6","bit6","gong2","ceot1","zan1","soeng1"] },
            { chars: ["各","自","缠","着","你","才","会","馨","香"], jp: ["gok3","zi6","cin4","zoek6","nei5","coi4","wui6","hing1","hoeng1"] },
            { chars: ["我","放","得","开","你","最","理","想"], jp: ["ngo5","fong3","dak1","hoi1","nei5","zeoi3","lei5","soeng2"] },
            { chars: ["要","继","续","受","内","伤"], jp: ["jiu3","gai3","zuk6","sau6","noi6","soeng1"] },
            { chars: ["好","过","无","法","可","分","享"], jp: ["hou2","gwo3","mou4","faat3","ho2","fan1","hoeng2"] },
            { chars: ["你","也","不","想","这","样"], jp: ["nei5","jaa5","bat1","soeng2","ze5","joeng6"] },
            { chars: ["利","用","自","己","的","修","养"], jp: ["lei6","jung6","zi6","gei2","dik1","sau1","joeng5"] },
            { chars: ["来","求","你","分","开","不","堪","设","想"], jp: ["loi4","kau4","nei5","fan1","hoi1","bat1","ham1","cit3","soeng2"] },
            { chars: ["如","你","有","歌","请","准","我","陪","着","唱"], jp: ["jyu4","nei5","jau5","go1","cing2","zeon2","ngo5","pui4","zoek6","coeng3"] },
            { chars: ["容","忍","两","把","声","音","不","算","太"], jp: ["jung4","jan2","loeng5","baa2","sing1","jam1","bat1","syun3","taai3"] },
            { chars: ["牵","强"], jp: ["hin1","koeng4"] },
            { chars: ["情","人","太","多"], jp: ["cing4","jan4","taai3","do1"] },
            { chars: ["你","爱","得","几","多","个"], jp: ["nei5","ngoi3","dak1","gei2","do1","go3"] },
            { chars: ["换","口","味","都","不","错"], jp: ["wun6","hau2","mei6","dou1","bat1","co3"] },
            { chars: ["在","你","味","觉","内","存","在","过"], jp: ["zoi6","nei5","mei6","gok3","noi6","cyun4","zoi6","gwo3"] },
            { chars: ["还","敢","追","究","什","么"], jp: ["waan4","gam2","zeoi1","gau3","sap6","maa1"] },
            { chars: ["情","人","再","多"], jp: ["cing4","jan4","zoi3","do1"] },
            { chars: ["我","却","非","爱","你","不","可"], jp: ["ngo5","koek3","fei1","ngoi3","nei5","bat1","ho2"] },
            { chars: ["若","你","愿","瞒","住"], jp: ["joek6","nei5","jyun6","mun4","zyu6"] },
            { chars: ["仍","然","乐","于","扮","傻"], jp: ["jing4","jin4","lok6","jyu1","baan6","so4"] },
            { chars: ["情","敌","会","掠","过"], jp: ["cing4","dik6","wui6","loek6","gwo3"] },
            { chars: ["未","来","便","更","易","过"], jp: ["mei6","loi4","bin6","gang1","ji6","gwo3"] },
            { chars: ["难","过","是","我","的","错"], jp: ["naan4","gwo3","si6","ngo5","dik1","co3"] },
            { chars: ["你","也","不","想","这","样"], jp: ["nei5","jaa5","bat1","soeng2","ze5","joeng6"] },
            { chars: ["但","别","讲","出","真","相"], jp: ["daan6","bit6","gong2","ceot1","zan1","soeng1"] },
            { chars: ["各","自","缠","着","你","才","会","馨","香"], jp: ["gok3","zi6","cin4","zoek6","nei5","coi4","wui6","hing1","hoeng1"] },
            { chars: ["我","放","得","开","你","最","理","想"], jp: ["ngo5","fong3","dak1","hoi1","nei5","zeoi3","lei5","soeng2"] },
            { chars: ["要","继","续","受","内","伤"], jp: ["jiu3","gai3","zuk6","sau6","noi6","soeng1"] },
            { chars: ["好","过","无","法","可","分","享"], jp: ["hou2","gwo3","mou4","faat3","ho2","fan1","hoeng2"] },
            { chars: ["若","我","共","他","同","时","被","你","热","爱"], jp: ["joek6","ngo5","gung6","taa1","tung4","si4","bei6","nei5","jit6","ngoi3"] },
            { chars: ["请","你","去","证","实","两","位","都","不","爱"], jp: ["cing2","nei5","heoi3","zing3","sat6","loeng5","wai6","dou1","bat1","ngoi3"] },
            { chars: ["遇","上","什","么","随","时","话","爱","就","爱"], jp: ["jyu6","soeng6","sap6","maa1","ceoi4","si4","waa6","ngoi3","zau6","ngoi3"] },
            { chars: ["这","性","格","也","未","免","精","彩"], jp: ["ze5","sing3","gaak3","jaa5","mei6","min5","zing1","coi2"] },
            { chars: ["你","也","不","想","这","样"], jp: ["nei5","jaa5","bat1","soeng2","ze5","joeng6"] },
            { chars: ["但","别","讲","出","真","相"], jp: ["daan6","bit6","gong2","ceot1","zan1","soeng1"] },
            { chars: ["各","自","缠","着","你"], jp: ["gok3","zi6","cin4","zoek6","nei5"] },
            { chars: ["才","会","馨","香"], jp: ["coi4","wui6","hing1","hoeng1"] },
            { chars: ["我","放","得","开","你","最","理","想"], jp: ["ngo5","fong3","dak1","hoi1","nei5","zeoi3","lei5","soeng2"] },
            { chars: ["要","继","续","受","内","伤"], jp: ["jiu3","gai3","zuk6","sau6","noi6","soeng1"] },
            { chars: ["好","过","无","法","可","分","享"], jp: ["hou2","gwo3","mou4","faat3","ho2","fan1","hoeng2"] },
            { chars: ["我","也","不","想","这","样"], jp: ["ngo5","jaa5","bat1","soeng2","ze5","joeng6"] },
            { chars: ["利","用","自","己","的","修","养"], jp: ["lei6","jung6","zi6","gei2","dik1","sau1","joeng5"] },
            { chars: ["来","求","你","分","开","不","堪","设","想"], jp: ["loi4","kau4","nei5","fan1","hoi1","bat1","ham1","cit3","soeng2"] },
            { chars: ["如","你","有","歌","请","准","我","陪","着","唱"], jp: ["jyu4","nei5","jau5","go1","cing2","zeon2","ngo5","pui4","zoek6","coeng3"] },
            { chars: ["容","忍","两","把","声","音","不","算","太"], jp: ["jung4","jan2","loeng5","baa2","sing1","jam1","bat1","syun3","taai3"] },
            { chars: ["牵","强"], jp: ["hin1","koeng4"] },
            { chars: ["如","果","多","她","一","位","会","多","一","点","爱"], jp: ["jyu4","gwo2","do1","taa1","jat1","wai6","wui6","do1","jat1","dim2","ngoi3"] },
            { chars: ["两","个","人","被","怜","爱"], jp: ["loeng5","go3","jan4","bei6","lin4","ngoi3"] },
            { chars: ["一","点","都","不","勉","强"], jp: ["jat1","dim2","dou1","bat1","min5","koeng4"] }
        ]
    };
    if (typeof window !== 'undefined' && window.__songs) {
        window.__songs.push(song);
    }
})();
