// 歌曲：Medley：再见我的初恋+痛爱+逃避你+谁来爱我+损友+抱抱+想得太远+习惯失恋+一拍两散+心淡（live）

(function() {
    const song = {
        id: 158,
        title: "Medley：再见我的初恋+痛爱+逃避你+谁来爱我+损友+抱抱+想得太远+习惯失恋+一拍两散+心淡（live）",
        titleJyutping: ["","","","","","","","zoi3","gin3","ngo5","dik1","co1","lyun2","","tung3","ngoi3","","tou4","bei6","nei5","","seoi4","loi4","ngoi3","ngo5","","syun2","jau5","","pou5","pou5","","soeng2","dak1","taai3","jyun5","","zaap6","gwaan3","sat1","lyun2","","jat1","paak3","loeng5","saan3","","sam1","daam6","","","","","",""],
        artist: "容祖儿",
        artistJyutping: ["jung4","zou2","ji4"],
        lyricist: "",
        lyricistJyutping: [],
        composer: "",
        composerJyutping: [],
        lyrics: [
            { chars: ["《","再","见","我","的","初","恋","》"], jp: ["","zoi3","gin3","ngo5","dik1","co1","lyun2",""] },
            { paragraphBreak: true },
            { chars: ["再","见","我","的","初","恋","跟","你","一","起","也","不","枉"], jp: ["zoi3","gin3","ngo5","dik1","co1","lyun2","gan1","nei5","jat1","hei2","jaa5","bat1","wong2"] },
            { chars: ["未","曾","乘","风","出","海","怎","破","浪"], jp: ["mei6","zang1","sing4","fung1","ceot1","hoi2","zam2","po3","long6"] },
            { chars: ["过","去","每","幅","风","景","请","你","随","时","拿","着","看"], jp: ["gwo3","heoi3","mui5","fuk1","fung1","ging2","cing2","nei5","ceoi4","si4","naa4","zoek6","hon3"] },
            { chars: ["别","忘","记","你","我","要","继","续","盛","放"], jp: ["bit6","mong4","gei3","nei5","ngo5","jiu3","gai3","zuk6","sing6","fong3"] },
            { chars: ["为","了","有","太","多","青","春","才","日","夜","换","期","望"], jp: ["wai4","liu5","jau5","taai3","do1","cing1","ceon1","coi4","jat6","je6","wun6","kei4","mong6"] },
            { chars: ["用","有","限","宝","贵","时","光","换","无","限","神","往"], jp: ["jung6","jau5","haan6","bou2","gwai3","si4","gwong1","wun6","mou4","haan6","san4","wong5"] },
            { chars: ["曾","为","你","神","往","亦","要","落","堂"], jp: ["zang1","wai4","nei5","san4","wong5","jik6","jiu3","lok6","tong4"] },
            { paragraphBreak: true },
            { chars: ["《","痛","爱","》"], jp: ["","tung3","ngoi3",""] },
            { paragraphBreak: true },
            { chars: ["喜","欢","你","让","我","下","沉"], jp: ["hei2","fun1","nei5","joeng6","ngo5","haa6","cam4"] },
            { chars: ["喜","欢","你","让","我","哭"], jp: ["hei2","fun1","nei5","joeng6","ngo5","huk1"] },
            { chars: ["能","持","续","获","得","糟","踏","亦","满","足"], jp: ["nang4","ci4","zuk6","wok6","dak1","zou1","daap6","jik6","mun5","zuk1"] },
            { chars: ["喜","欢","你","待","我","薄","情"], jp: ["hei2","fun1","nei5","doi6","ngo5","bok6","cing4"] },
            { chars: ["喜","欢","你","为","人","冷","酷"], jp: ["hei2","fun1","nei5","wai4","jan4","laang5","huk6"] },
            { chars: ["若","是","你","也","发","现"], jp: ["joek6","si6","nei5","jaa5","faat3","jin6"] },
            { chars: ["你","也","喜","欢","亏","待","我"], jp: ["nei5","jaa5","hei2","fun1","kwai1","doi6","ngo5"] },
            { chars: ["我","就","让","你","永","远","痛","爱","着","我"], jp: ["ngo5","zau6","joeng6","nei5","wing5","jyun5","tung3","ngoi3","zoek6","ngo5"] },
            { chars: ["和","谐","甜","美","永","没","有","天","意","弄","人"], jp: ["wo4","haai4","tim4","mei5","wing5","mut6","jau5","tin1","ji3","lung6","jan4"] },
            { chars: ["有","什","么","的","吸","引"], jp: ["jau5","sap6","maa1","dik1","kap1","jan5"] },
            { chars: ["谁","待","我","好","我","就","会","不","过","问"], jp: ["seoi4","doi6","ngo5","hou2","ngo5","zau6","wui6","bat1","gwo3","man6"] },
            { chars: ["偏","偏","碰","着","那","坏","人","全","部","诱","人"], jp: ["pin1","pin1","pung3","zoek6","naa5","waai6","jan4","cyun4","bou6","jau5","jan4"] },
            { chars: ["全","球","情","侣","故","事","也","相","近"], jp: ["cyun4","kau4","cing4","leoi5","gu3","si6","jaa5","soeng1","gan6"] },
            { chars: ["宁","愿","天","昏","地","暗"], jp: ["ning4","jyun6","tin1","fan1","dei6","am3"] },
            { chars: ["要","为","错","的","人","伤","过","恨","过"], jp: ["jiu3","wai4","co3","dik1","jan4","soeng1","gwo3","han6","gwo3"] },
            { chars: ["方","算","是","勇","敢"], jp: ["fong1","syun3","si6","jung5","gam2"] },
            { chars: ["长","世","间","不","喜","欢","开","心","喜","欢","痛","心"], jp: ["coeng4","sai3","gaan1","bat1","hei2","fun1","hoi1","sam1","hei2","fun1","tung3","sam1"] },
            { chars: ["喜","欢","你","让","我","下","沉"], jp: ["hei2","fun1","nei5","joeng6","ngo5","haa6","cam4"] },
            { chars: ["喜","欢","你","让","我","哭"], jp: ["hei2","fun1","nei5","joeng6","ngo5","huk1"] },
            { chars: ["能","持","续","获","得","糟","踏","亦","满","足"], jp: ["nang4","ci4","zuk6","wok6","dak1","zou1","daap6","jik6","mun5","zuk1"] },
            { chars: ["喜","欢","你","待","我","薄","情"], jp: ["hei2","fun1","nei5","doi6","ngo5","bok6","cing4"] },
            { chars: ["喜","欢","你","为","人","冷","酷"], jp: ["hei2","fun1","nei5","wai4","jan4","laang5","huk6"] },
            { chars: ["若","是","你","也","发","现"], jp: ["joek6","si6","nei5","jaa5","faat3","jin6"] },
            { chars: ["你","也","喜","欢","亏","待","我"], jp: ["nei5","jaa5","hei2","fun1","kwai1","doi6","ngo5"] },
            { chars: ["我","愿","让","你","爱","上","我","更","加","多"], jp: ["ngo5","jyun6","joeng6","nei5","ngoi3","soeng6","ngo5","gang1","gaa1","do1"] },
            { chars: ["喜","欢","你","让","我","下","沉"], jp: ["hei2","fun1","nei5","joeng6","ngo5","haa6","cam4"] },
            { chars: ["喜","欢","你","让","我","哭"], jp: ["hei2","fun1","nei5","joeng6","ngo5","huk1"] },
            { chars: ["能","持","续","获","得","糟","踏","亦","满","足"], jp: ["nang4","ci4","zuk6","wok6","dak1","zou1","daap6","jik6","mun5","zuk1"] },
            { chars: ["喜","欢","你","待","我","薄","情"], jp: ["hei2","fun1","nei5","doi6","ngo5","bok6","cing4"] },
            { chars: ["喜","欢","你","为","人","冷","酷"], jp: ["hei2","fun1","nei5","wai4","jan4","laang5","huk6"] },
            { chars: ["若","是","你","也","发","现"], jp: ["joek6","si6","nei5","jaa5","faat3","jin6"] },
            { chars: ["你","也","喜","欢","亏","待","我"], jp: ["nei5","jaa5","hei2","fun1","kwai1","doi6","ngo5"] },
            { chars: ["我","就","让","你","永","远","痛","爱","着","我"], jp: ["ngo5","zau6","joeng6","nei5","wing5","jyun5","tung3","ngoi3","zoek6","ngo5"] },
            { paragraphBreak: true },
            { chars: ["《","逃","避","你","》"], jp: ["","tou4","bei6","nei5",""] },
            { paragraphBreak: true },
            { chars: ["世","界","最","遥","远","的","一","种","相","距","中"], jp: ["sai3","gaai3","zeoi3","jiu4","jyun5","dik1","jat1","zung2","soeng1","keoi5","zung1"] },
            { chars: ["明","明","留","恋","然","而","让","辗","转","的","挂","念","扑","空"], jp: ["ming4","ming4","lau4","lyun2","jin4","ji4","joeng6","zin2","zyun2","dik1","gwaa3","nim6","pok3","hung1"] },
            { chars: ["回","忆","心","里","越","载","越","重"], jp: ["wui4","jik1","sam1","lei5","jyut6","zoi3","jyut6","cung5"] },
            { chars: ["却","不","珍","惜","这","一","次","重","逢"], jp: ["koek3","bat1","zan1","sik1","ze5","jat1","ci3","cung5","fung4"] },
            { chars: ["我","的","思","想","像","完","全","失","控"], jp: ["ngo5","dik1","si1","soeng2","zoeng6","jyun4","cyun4","sat1","hung3"] },
            { chars: ["逃","避","你","却","又","期","待","我","可","跟","你","做","情","人"], jp: ["tou4","bei6","nei5","koek3","jau6","kei4","doi6","ngo5","ho2","gan1","nei5","zou6","cing4","jan4"] },
            { chars: ["而","用","情","的","心","可","天","昏","地","暗"], jp: ["ji4","jung6","cing4","dik1","sam1","ho2","tin1","fan1","dei6","am3"] },
            { chars: ["逃","避","你","爱","是","遥","又","远","得","很"], jp: ["tou4","bei6","nei5","ngoi3","si6","jiu4","jau6","jyun5","dak1","han2"] },
            { chars: ["而","我","始","终","不","敢","靠","近"], jp: ["ji4","ngo5","ci2","zung1","bat1","gam2","kaau3","gan6"] },
            { chars: ["还","是","不","相","信","能","和","你","合","衬"], jp: ["waan4","si6","bat1","soeng1","seon3","nang4","wo4","nei5","hap6","can3"] },
            { paragraphBreak: true },
            { chars: ["《","谁","来","爱","我","》"], jp: ["","seoi4","loi4","ngoi3","ngo5",""] },
            { paragraphBreak: true },
            { chars: ["谁","来","爱","我","小","心","爱","错"], jp: ["seoi4","loi4","ngoi3","ngo5","siu2","sam1","ngoi3","co3"] },
            { chars: ["以","免","彼","此","无","助"], jp: ["ji5","min5","bei2","ci2","mou4","zo6"] },
            { chars: ["还","能","热","恋","谁"], jp: ["waan4","nang4","jit6","lyun2","seoi4"] },
            { chars: ["谁","能","受","得","起","那","么","多"], jp: ["seoi4","nang4","sau6","dak1","hei2","naa5","maa1","do1"] },
            { chars: ["为","何","拿","著","我","消","磨"], jp: ["wai4","ho4","naa4","zyu3","ngo5","siu1","mo4"] },
            { chars: ["谁","来","爱","我","请","好","好","对","我"], jp: ["seoi4","loi4","ngoi3","ngo5","cing2","hou2","hou2","deoi3","ngo5"] },
            { chars: ["犹","如","拿","慑","著","星","火"], jp: ["jau4","jyu4","naa4","sip3","zyu3","sing1","fo2"] },
            { chars: ["认","真","的","我"], jp: ["jing6","zan1","dik1","ngo5"] },
            { chars: ["花","开","了","总","想","结","果"], jp: ["faa1","hoi1","liu5","zung2","soeng2","git3","gwo2"] },
            { chars: ["才","令","你","闪","身","掠","过"], jp: ["coi4","ling6","nei5","sim2","san1","loek6","gwo3"] },
            { paragraphBreak: true },
            { chars: ["《","损","友","》"], jp: ["","syun2","jau5",""] },
            { paragraphBreak: true },
            { chars: ["愿","能","在","你","失","意","热","情","慰","问"], jp: ["jyun6","nang4","zoi6","nei5","sat1","ji3","jit6","cing4","wai3","man6"] },
            { chars: ["未","能","被","你","酒","后","趁","机","一","吻"], jp: ["mei6","nang4","bei6","nei5","zau2","hau6","can3","gei1","jat1","man5"] },
            { chars: ["谁","人","与","你","成","为","爱","侣"], jp: ["seoi4","jan4","jyu5","nei5","sing4","wai4","ngoi3","leoi5"] },
            { chars: ["能","保","证","绝","无","挂","虑"], jp: ["nang4","bou2","zing3","zyut6","mou4","gwaa3","leoi6"] },
            { chars: ["谈","情","说","爱"], jp: ["taam4","cing4","syut3","ngoi3"] },
            { chars: ["何","日","都","可","告","吹"], jp: ["ho4","jat6","dou1","ho2","gou3","ceoi1"] },
            { chars: ["宁","愿","留","下","友","情"], jp: ["ning4","jyun6","lau4","haa6","jau5","cing4"] },
            { chars: ["伤","心","都","只","可","斗","嘴"], jp: ["soeng1","sam1","dou1","zi2","ho2","dau3","zeoi2"] },
            { chars: ["谁","更","清","楚","清","楚","你","的","风","流"], jp: ["seoi4","gang1","cing1","co2","cing1","co2","nei5","dik1","fung1","lau4"] },
            { chars: ["缠","住","你","手","只","怕","热","泪","会","流"], jp: ["cin4","zyu6","nei5","sau2","zi2","paa3","jit6","leoi6","wui6","lau4"] },
            { chars: ["和","你","能","扮","演","好","友"], jp: ["wo4","nei5","nang4","baan6","jin2","hou2","jau5"] },
            { chars: ["男","士","那","般","搭","膊","头"], jp: ["naam4","si6","naa5","bun1","daap3","bok3","tau4"] },
            { chars: ["和","你","牵","手","只","恐","怕","太","荒","谬"], jp: ["wo4","nei5","hin1","sau2","zi2","hung2","paa3","taai3","fong1","mau6"] },
            { chars: ["还","是","当","你","一","位","损","友"], jp: ["waan4","si6","dong1","nei5","jat1","wai6","syun2","jau5"] },
            { chars: ["没","寄","望","没","强","求"], jp: ["mut6","gei3","mong6","mut6","koeng4","kau4"] },
            { chars: ["若","我","离","开","你","不","曾","内","疚"], jp: ["joek6","ngo5","lei4","hoi1","nei5","bat1","zang1","noi6","gau3"] },
            { paragraphBreak: true },
            { chars: ["《","抱","抱","》"], jp: ["","pou5","pou5",""] },
            { paragraphBreak: true },
            { chars: ["跑","车","开","走","怎","舍","得","将","你","当","朋","友"], jp: ["paau2","ce1","hoi1","zau2","zam2","se3","dak1","zoeng1","nei5","dong1","pang4","jau5"] },
            { chars: ["本","想","开","口","开","口","之","后","无","法","抬","头"], jp: ["bun2","soeng2","hoi1","hau2","hoi1","hau2","zi1","hau6","mou4","faat3","toi4","tau4"] },
            { chars: ["天","色","很","好","本","应","值","得","你","伴","我","巡","游"], jp: ["tin1","sik1","han2","hou2","bun2","jing3","zik6","dak1","nei5","bun6","ngo5","ceon4","jau4"] },
            { chars: ["那","种","交","流","暧","昧","也","曾","有","美","丽","时","候"], jp: ["naa5","zung2","gaau1","lau4","oi3","mui6","jaa5","zang1","jau5","mei5","lai6","si4","hau6"] },
            { chars: ["为","何","白","白","地","让","眼","泪","流"], jp: ["wai4","ho4","baak6","baak6","dei6","joeng6","ngaan5","leoi6","lau4"] },
            { chars: ["沦","为","脏","铁","锈"], jp: ["leon4","wai4","zong1","tit3","sau3"] },
            { chars: ["想","抱","但","热","恋","得","不","到","知","已","也","做","不","到"], jp: ["soeng2","pou5","daan6","jit6","lyun2","dak1","bat1","dou3","zi1","ji5","jaa5","zou6","bat1","dou3"] },
            { chars: ["想","不","到","若","是","被","施","舍","拥","抱","之","后","谁","想","吐"], jp: ["soeng2","bat1","dou3","joek6","si6","bei6","si1","se3","jung2","pou5","zi1","hau6","seoi4","soeng2","tou3"] },
            { chars: ["想","抱","但","是","珍","惜","的","友","好","陌","生","后","到","逃","难","跌","倒"], jp: ["soeng2","pou5","daan6","si6","zan1","sik1","dik1","jau5","hou2","mak6","sang1","hau6","dou3","tou4","naan4","dit3","dou2"] },
            { chars: ["若","你","都","警","觉","待","我","太","好"], jp: ["joek6","nei5","dou1","ging2","gok3","doi6","ngo5","taai3","hou2"] },
            { chars: ["但","愿","仍","然","慈","悲","上","路"], jp: ["daan6","jyun6","jing4","jin4","ci4","bei1","soeng6","lou6"] },
            { chars: ["若","我","的","心","事","纯","如","白","雪"], jp: ["joek6","ngo5","dik1","sam1","si6","seon4","jyu4","baak6","syut3"] },
            { chars: ["可","不","可","跟","老","朋","友","天","真","抱","抱"], jp: ["ho2","bat1","ho2","gan1","lou5","pang4","jau5","tin1","zan1","pou5","pou5"] },
            { chars: ["从","来","受","惯","伤","害"], jp: ["cung4","loi4","sau6","gwaan3","soeng1","hoi6"] },
            { chars: ["从","头","为","你","等","待"], jp: ["cung4","tau4","wai4","nei5","dang2","doi6"] },
            { chars: ["别","要","完","全","没","往","来"], jp: ["bit6","jiu3","jyun4","cyun4","mut6","wong5","loi4"] },
            { chars: ["遗","忘","受","过","伤","害"], jp: ["wai4","mong4","sau6","gwo3","soeng1","hoi6"] },
            { chars: ["做","到","相","亲","相","爱"], jp: ["zou6","dou3","soeng1","can1","soeng1","ngoi3"] },
            { chars: ["以","一","笑","融","化","眼","泪"], jp: ["ji5","jat1","siu3","jung4","faa3","ngaan5","leoi6"] },
            { chars: ["也","是","爱"], jp: ["jaa5","si6","ngoi3"] },
            { paragraphBreak: true },
            { chars: ["《","想","得","太","远","》"], jp: ["","soeng2","dak1","taai3","jyun5",""] },
            { paragraphBreak: true },
            { chars: ["凭","什","么","可","以","爱","上","所","爱"], jp: ["pang4","sap6","maa1","ho2","ji5","ngoi3","soeng6","so2","ngoi3"] },
            { chars: ["我","自","问","日","夜","等","待"], jp: ["ngo5","zi6","man6","jat6","je6","dang2","doi6"] },
            { chars: ["结","局","为","何","揭","不","开"], jp: ["git3","guk6","wai4","ho4","kit3","bat1","hoi1"] },
            { chars: ["等","缘","份","信","缘","份"], jp: ["dang2","jyun4","fan6","seon3","jyun4","fan6"] },
            { chars: ["我","们","只","好","相","信"], jp: ["ngo5","mun4","zi2","hou2","soeng1","seon3"] },
            { chars: ["来","来","回","回","难","避","开"], jp: ["loi4","loi4","wui4","wui4","naan4","bei6","hoi1"] },
            { chars: ["大","慨","这","算","是","迷","恋"], jp: ["daai6","koi3","ze5","syun3","si6","mai4","lyun2"] },
            { chars: ["这","路","程","得","几","分","钟","真","是","太","短"], jp: ["ze5","lou6","cing4","dak1","gei2","fan1","zung1","zan1","si6","taai3","dyun2"] },
            { chars: ["大","慨","你","都","想","去","后","乐","园"], jp: ["daai6","koi3","nei5","dou1","soeng2","heoi3","hau6","lok6","jyun4"] },
            { chars: ["却","怕","孤","单","一","个","人","兜","圈"], jp: ["koek3","paa3","gu1","daan1","jat1","go3","jan4","dau1","hyun1"] },
            { chars: ["谁","人","在","挑","选","如","何","被","挑","选"], jp: ["seoi4","jan4","zoi6","tiu1","syun2","jyu4","ho4","bei6","tiu1","syun2"] },
            { chars: ["如","何","教","我","结","识","你","怎","么","相","恋"], jp: ["jyu4","ho4","gaau3","ngo5","git3","sik1","nei5","zam2","maa1","soeng1","lyun2"] },
            { chars: ["为","何","坐","到","那","么","近"], jp: ["wai4","ho4","zo6","dou3","naa5","maa1","gan6"] },
            { chars: ["却","想","得","这","样","远"], jp: ["koek3","soeng2","dak1","ze5","joeng6","jyun5"] },
            { chars: ["人","浪","为","何","会","流","转"], jp: ["jan4","long6","wai4","ho4","wui6","lau4","zyun2"] },
            { chars: ["若","幸","运","一","点","一","早","找","到","你"], jp: ["joek6","hang6","wan6","jat1","dim2","jat1","zou2","zaau2","dou3","nei5"] },
            { chars: ["但","幸","运","可","否","担","保","得","到","你"], jp: ["daan6","hang6","wan6","ho2","fau2","daam1","bou2","dak1","dou3","nei5"] },
            { chars: ["就","望","着","际","遇","铺","展","我","的","天","与","地"], jp: ["zau6","mong6","zoek6","zai3","jyu6","pou1","zin2","ngo5","dik1","tin1","jyu5","dei6"] },
            { chars: ["愿","错","亦","错","得","起"], jp: ["jyun6","co3","jik6","co3","dak1","hei2"] },
            { chars: ["若","命","运","叫","我","只","懂","喜","欢","你"], jp: ["joek6","ming6","wan6","giu3","ngo5","zi2","dung2","hei2","fun1","nei5"] },
            { chars: ["但","愿","亦","有","幸","懂","得","留","住","你"], jp: ["daan6","jyun6","jik6","jau5","hang6","dung2","dak1","lau4","zyu6","nei5"] },
            { chars: ["如","若","过","去","我","太","在","乎"], jp: ["jyu4","joek6","gwo3","heoi3","ngo5","taai3","zoi6","fu4"] },
            { chars: ["相","遇","别","离","请","准","我","预","备"], jp: ["soeng1","jyu6","bit6","lei4","cing2","zeon2","ngo5","jyu6","bei6"] },
            { chars: ["仍","然","未","识","你"], jp: ["jing4","jin4","mei6","sik1","nei5"] },
            { chars: ["却","已","幻","想","那","份","惊","喜"], jp: ["koek3","ji5","waan6","soeng2","naa5","fan6","ging1","hei2"] },
            { paragraphBreak: true },
            { chars: ["《","习","惯","失","恋","》"], jp: ["","zaap6","gwaan3","sat1","lyun2",""] },
            { paragraphBreak: true },
            { chars: ["不","担","心","自","尊","心","这","么","受","损"], jp: ["bat1","daam1","sam1","zi6","zyun1","sam1","ze5","maa1","sau6","syun2"] },
            { chars: ["只","担","心","我","将","我","看","穿"], jp: ["zi2","daam1","sam1","ngo5","zoeng1","ngo5","hon3","cyun1"] },
            { chars: ["我","怕","我","以","后","太","习","惯","了","失","恋"], jp: ["ngo5","paa3","ngo5","ji5","hau6","taai3","zaap6","gwaan3","liu5","sat1","lyun2"] },
            { chars: ["理","所","当","然","我","的","错"], jp: ["lei5","so2","dong1","jin4","ngo5","dik1","co3"] },
            { chars: ["令","你","忽","然","离","开","也","是","我","错","么"], jp: ["ling6","nei5","fat1","jin4","lei4","hoi1","jaa5","si6","ngo5","co3","maa1"] },
            { chars: ["为","何","这","么","快","看","清","楚"], jp: ["wai4","ho4","ze5","maa1","faai3","hon3","cing1","co2"] },
            { chars: ["落","得","这","结","果"], jp: ["lok6","dak1","ze5","git3","gwo2"] },
            { chars: ["知","我","是","个","无","法","讨","好","的","人"], jp: ["zi1","ngo5","si6","go3","mou4","faat3","tou2","hou2","dik1","jan4"] },
            { chars: ["相","恋","一","刻","只","是","我","的","侥","幸"], jp: ["soeng1","lyun2","jat1","hak1","zi2","si6","ngo5","dik1","hiu1","hang6"] },
            { chars: ["然","而","回","头","诚","实","去","自","问"], jp: ["jin4","ji4","wui4","tau4","sing4","sat6","heoi3","zi6","man6"] },
            { chars: ["我","可","讨","厌","到","如","此","乞","你","憎"], jp: ["ngo5","ho2","tou2","jim3","dou3","jyu4","ci2","hat1","nei5","zang1"] },
            { chars: ["知","我","连","眼","泪","也","绝","不","感","人"], jp: ["zi1","ngo5","lin4","ngaan5","leoi6","jaa5","zyut6","bat1","gam2","jan4"] },
            { chars: ["只","知","怎","么","考","验","你","的","操","行"], jp: ["zi2","zi1","zam2","maa1","haau2","jim6","nei5","dik1","cou1","hang4"] },
            { chars: ["从","前","为","何","缠","在","你","附","近"], jp: ["cung4","cin4","wai4","ho4","cin4","zoi6","nei5","fu6","gan6"] },
            { chars: ["到","底","这","个","故","事","有","没","有","发","生"], jp: ["dou3","dai2","ze5","go3","gu3","si6","jau5","mut6","jau5","faat3","sang1"] },
            { paragraphBreak: true },
            { chars: ["《","一","拍","两","散","》"], jp: ["","jat1","paak3","loeng5","saan3",""] },
            { paragraphBreak: true },
            { chars: ["当","初","枉","我","未","拍","拖","曾","这","样","讲","过"], jp: ["dong1","co1","wong2","ngo5","mei6","paak3","to1","zang1","ze5","joeng6","gong2","gwo3"] },
            { chars: ["外","遇","那","些","女","主","角","迟","早","惹","出","祸"], jp: ["ngoi6","jyu6","naa5","se1","neoi5","zyu2","gok3","ci4","zou2","je5","ceot1","wo6"] },
            { chars: ["谁","料","那","个","是","我","又","能","如","何","恨","我"], jp: ["seoi4","liu6","naa5","go3","si6","ngo5","jau6","nang4","jyu4","ho4","han6","ngo5"] },
            { chars: ["没","法","面","对","自","我","其","实","最","痛","楚"], jp: ["mut6","faat3","min6","deoi3","zi6","ngo5","kei4","sat6","zeoi3","tung3","co2"] },
            { chars: ["谁","都","会","散","怎","知","一","拍","便","会","散"], jp: ["seoi4","dou1","wui6","saan3","zam2","zi1","jat1","paak3","bin6","wui6","saan3"] },
            { chars: ["怪","我","自","己","作","反","明","明","我","不","应","再","拣"], jp: ["gwaai3","ngo5","zi6","gei2","zok3","faan2","ming4","ming4","ngo5","bat1","jing3","zoi3","gaan2"] },
            { chars: ["忠","贞","怎","可","以","贪","给","抛","弃","亦","已","很","惯"], jp: ["zung1","zing1","zam2","ho2","ji5","taam1","kap1","paau1","hei3","jik6","ji5","han2","gwaan3"] },
            { chars: ["不","惯","去","承","认","自","私","移","情","别","爱","太","奸"], jp: ["bat1","gwaan3","heoi3","sing4","jing6","zi6","si1","ji4","cing4","bit6","ngoi3","taai3","gaan1"] },
            { chars: ["迟","早","都","散","散","得","清","脆","未","算","惨"], jp: ["ci4","zou2","dou1","saan3","saan3","dak1","cing1","ceoi3","mei6","syun3","caam2"] },
            { chars: ["我","却","要","忠","变","奸","斗","胆","一","脚","踏","两","船"], jp: ["ngo5","koek3","jiu3","zung1","bin3","gaan1","dau3","daam2","jat1","goek3","daap6","loeng5","syun4"] },
            { chars: ["想","上","岸","时","又","晏","无","面","目","再","解","释"], jp: ["soeng2","soeng6","ngon6","si4","jau6","aan3","mou4","min6","muk6","zoi3","gaai2","sik1"] },
            { chars: ["自","费","了","承","诺","是","否","太","斗","胆"], jp: ["zi6","fai3","liu5","sing4","nok6","si6","fau2","taai3","dau3","daam2"] },
            { paragraphBreak: true },
            { chars: ["《","心","淡","》"], jp: ["","sam1","daam6",""] },
            { paragraphBreak: true },
            { chars: ["由","这","一","分","钟","开","始","计","起","春","风","秋","雨","间"], jp: ["jau4","ze5","jat1","fan1","zung1","hoi1","ci2","gai3","hei2","ceon1","fung1","cau1","jyu5","gaan1"] },
            { chars: ["恨","我","对","你","以","半","年","时","间","慢","慢","的","心","淡"], jp: ["han6","ngo5","deoi3","nei5","ji5","bun3","nin4","si4","gaan1","maan6","maan6","dik1","sam1","daam6"] },
            { chars: ["付","清","账","单"], jp: ["fu6","cing1","zoeng3","daan1"] },
            { chars: ["平","静","的","对","你","热","度","退","减"], jp: ["ping4","zing6","dik1","deoi3","nei5","jit6","dou6","teoi3","gaam2"] },
            { chars: ["一","天","一","点","伤","心","过","这","一","百","数","十","晚"], jp: ["jat1","tin1","jat1","dim2","soeng1","sam1","gwo3","ze5","jat1","baak3","sou3","sap6","maan5"] },
            { chars: ["大","概","也","够","我","送","我","来","回","地","狱","又","折","返","人","间"], jp: ["daai6","koi3","jaa5","gau3","ngo5","sung3","ngo5","loi4","wui4","dei6","juk6","jau6","zit3","faan2","jan4","gaan1"] },
            { chars: ["春","天","分","手","秋","天","会","习","惯"], jp: ["ceon1","tin1","fan1","sau2","cau1","tin1","wui6","zaap6","gwaan3"] },
            { chars: ["苦","冲","开","了","便","淡"], jp: ["fu2","cung1","hoi1","liu5","bin6","daam6"] },
            { chars: ["说","甚","么","再","平","反"], jp: ["syut3","sam6","maa1","zoi3","ping4","faan2"] },
            { chars: ["只","怕","被","迫","一","起","更","碍","眼"], jp: ["zi2","paa3","bei6","baak1","jat1","hei2","gang1","ngoi6","ngaan5"] },
            { chars: ["往","后","这","半","年","间"], jp: ["wong5","hau6","ze5","bun3","nin4","gaan1"] },
            { chars: ["只","爱","自","己","虽","说","不","太","习","惯"], jp: ["zi2","ngoi3","zi6","gei2","seoi1","syut3","bat1","taai3","zaap6","gwaan3"] },
            { chars: ["毕","竟","有","限","就","当","过","关"], jp: ["bat1","ging2","jau5","haan6","zau6","dong1","gwo3","gwaan1"] },
            { chars: ["由","这","一","分","钟","开","始","计","起","春","风","秋","雨","间"], jp: ["jau4","ze5","jat1","fan1","zung1","hoi1","ci2","gai3","hei2","ceon1","fung1","cau1","jyu5","gaan1"] },
            { chars: ["恨","我","对","你","以","半","年","时","间","慢","慢","的","心","淡"], jp: ["han6","ngo5","deoi3","nei5","ji5","bun3","nin4","si4","gaan1","maan6","maan6","dik1","sam1","daam6"] },
            { chars: ["付","清","账","单"], jp: ["fu6","cing1","zoeng3","daan1"] },
            { chars: ["平","静","的","对","你","热","度","退","减"], jp: ["ping4","zing6","dik1","deoi3","nei5","jit6","dou6","teoi3","gaam2"] },
            { chars: ["一","天","一","点","伤","心","过","这","一","百","数","十","晚"], jp: ["jat1","tin1","jat1","dim2","soeng1","sam1","gwo3","ze5","jat1","baak3","sou3","sap6","maan5"] },
            { chars: ["大","概","也","够","我","送","我","来","回","地","狱","又","折","返","人","间"], jp: ["daai6","koi3","jaa5","gau3","ngo5","sung3","ngo5","loi4","wui4","dei6","juk6","jau6","zit3","faan2","jan4","gaan1"] },
            { chars: ["春","天","分","手","秋","天","会","习","惯"], jp: ["ceon1","tin1","fan1","sau2","cau1","tin1","wui6","zaap6","gwaan3"] },
            { chars: ["苦","冲","开","了","便","淡"], jp: ["fu2","cung1","hoi1","liu5","bin6","daam6"] },
            { chars: ["由","这","一","分","钟","开","始","计","起","春","风","秋","雨","间"], jp: ["jau4","ze5","jat1","fan1","zung1","hoi1","ci2","gai3","hei2","ceon1","fung1","cau1","jyu5","gaan1"] },
            { chars: ["限","我","对","你","以","半","年","时","间","慢","慢","的","心","淡"], jp: ["haan6","ngo5","deoi3","nei5","ji5","bun3","nin4","si4","gaan1","maan6","maan6","dik1","sam1","daam6"] },
            { chars: ["付","清","账","单"], jp: ["fu6","cing1","zoeng3","daan1"] },
            { chars: ["平","静","的","对","你","热","度","退","减"], jp: ["ping4","zing6","dik1","deoi3","nei5","jit6","dou6","teoi3","gaam2"] },
            { chars: ["一","天","一","点","伤","心","过","这","一","百","数","十","晚"], jp: ["jat1","tin1","jat1","dim2","soeng1","sam1","gwo3","ze5","jat1","baak3","sou3","sap6","maan5"] },
            { chars: ["大","概","也","够","我","送","我","来","回","地","狱","又","折","返","人","间"], jp: ["daai6","koi3","jaa5","gau3","ngo5","sung3","ngo5","loi4","wui4","dei6","juk6","jau6","zit3","faan2","jan4","gaan1"] },
            { chars: ["春","天","分","手","秋","天","会","习","惯"], jp: ["ceon1","tin1","fan1","sau2","cau1","tin1","wui6","zaap6","gwaan3"] },
            { chars: ["苦","冲","开","了","便","淡"], jp: ["fu2","cung1","hoi1","liu5","bin6","daam6"] }
        ]
    };
    if (typeof window !== 'undefined' && window.__songs) {
        window.__songs.push(song);
    }
})();
