// 歌曲：Medley：还+借（live）

(function() {
    const song = {
        id: 183,
        title: "Medley：还+借（live）",
        titleJyutping: ["","","","","","","","waan4","","ze3","","","","","",""],
        artist: "郑融",
        artistJyutping: ["zeng6","jung4"],
        lyricist: "陈少琪",
        lyricistJyutping: ["can4","siu2","kei4"],
        composer: "邓智伟",
        composerJyutping: ["dang6","zi3","wai5"],
        lyrics: [
            { chars: ["（", "i", "n", "t", "r", "o", "）"], jp: ["", "i", "n", "t", "r", "o", ""] },
            { chars: ["《", "成", "人", "对", "待", "》"], jp: ["", "sing4", "jan4", "deoi3", "doi6", ""] },
            { chars: ["成", "人", "年", "纪", "今", "天", "但", "求", "成", "年", "人", "对", "待"], jp: ["sing4", "jan4", "nin4", "gei2", "gam1", "tin1", "daan6", "kau4", "sing4", "nin4", "jan4", "deoi3", "doi6"] },
            { chars: ["完", "全", "能", "将", "小", "公", "主", "心", "态", "放", "开"], jp: ["jyun4", "cyun4", "nang4", "zoeng1", "siu2", "gung1", "zyu2", "sam1", "taai3", "fong3", "hoi1"] },
            { chars: ["《", "红", "花", "会", "》"], jp: ["", "hung4", "faa1", "wui6", ""] },
            { chars: ["若", "各", "路", "姊", "妹", " ", "旧", "日", "极", "心", "灰"], jp: ["joek6", "gok3", "lou6", "zi2", "mui6", "", "gau6", "jat6", "gik6", "sam1", "fui1"] },
            { chars: ["将", "教", "诲", "每", "天", "死", "背"], jp: ["zoeng1", "gaau3", "fui3", "mui5", "tin1", "sei2", "bui3"] },
            { chars: ["为", "日", "后", "干", "杯", " ", "没", "绝", "望", "分", "会"], jp: ["wai4", "jat6", "hau6", "gon1", "bui1", "", "mut6", "zyut6", "mong6", "fan1", "wui6"] },
            { chars: ["《", "爱", "得", "耐", "》"], jp: ["", "ngoi3", "dak1", "noi6", ""] },
            { chars: ["一", "爱", "得", "耐", " ", "梗", "有", "伤", "害"], jp: ["jat1", "ngoi3", "dak1", "noi6", "", "gang2", "jau5", "soeng1", "hoi6"] },
            { chars: ["纯", "白"], jp: ["seon4", "baak6"] },
            { chars: ["《", "H", "o", "n", "e", "y", "》"], jp: ["", "H", "o", "n", "e", "y", ""] },
            { chars: ["不", "要", "忏", "悔", " ", "(", "H", "o", "n", "e", "y", ")"], jp: ["bat1", "jiu3", "caam3", "fui3", "", "", "H", "o", "n", "e", "y", ""] },
            { chars: ["不", "够", "放", "胆", " ", "(", "下", "次", ")"], jp: ["bat1", "gau3", "fong3", "daam2", "", "", "haa6", "ci3", ""] },
            { chars: ["不", "够", "细", "致", " ", "为", "我", "乱", "去", "白", "费", "心", "思"], jp: ["bat1", "gau3", "sai3", "zi3", "", "wai4", "ngo5", "lyun6", "heoi3", "baak6", "fai3", "sam1", "si1"] },
            { chars: ["《", "大", "女", "仔", "》"], jp: ["", "daai6", "neoi5", "zai2", ""] },
            { chars: ["请", "各", "位", "无", "谓", "封", "闭"], jp: ["cing2", "gok3", "wai6", "mou4", "wai6", "fung1", "bai3"] },
            { chars: ["大", "女", "仔", "最", "不", "爱", "受", "管", "制"], jp: ["daai6", "neoi5", "zai2", "zeoi3", "bat1", "ngoi3", "sau6", "gun2", "zai3"] },
            { chars: ["不", "怕", "丑"], jp: ["bat1", "paa3", "cau2"] },
            { chars: ["《", "M", "e", " ", "V", "s", " ", "M", "e", "》"], jp: ["", "M", "e", "", "V", "s", "", "M", "e", ""] },
            { chars: ["潮", "流", "世", "界", "的", "统", "治", " ", "实", "在", "小", "圈", "子", "政", "治"], jp: ["ciu4", "lau4", "sai3", "gaai3", "dik1", "tung2", "zi6", "", "sat6", "zoi6", "siu2", "hyun1", "zi2", "zing3", "zi6"] },
            { chars: ["从", "来", "有", "我", "的", "本", "事"], jp: ["cung4", "loi4", "jau5", "ngo5", "dik1", "bun2", "si6"] },
            { chars: ["《", "2", "3", "》"], jp: ["", "ji6", "saam1", ""] },
            { chars: ["不", "规", "则", "的", "每", "天", " ", "这", "三", "百", "多", "天"], jp: ["bat1", "kwai1", "zak1", "dik1", "mui5", "tin1", "", "ze5", "saam1", "baak3", "do1", "tin1"] },
            { chars: ["我", "两", "脚", "跳", "动", "发", "电", " ", "勇", "气", "在", "两", "肩"], jp: ["ngo5", "loeng5", "goek3", "tiu3", "dung6", "faat3", "din6", "", "jung5", "hei3", "zoi6", "loeng5", "gin1"] },
            { chars: ["《", "红", "绿", "灯", "》"], jp: ["", "hung4", "luk6", "dang1", ""] },
            { chars: ["明", "明", "绿", "灯", " ", "转", "眼", "变", "成", "红", "灯"], jp: ["ming4", "ming4", "luk6", "dang1", "", "zyun2", "ngaan5", "bin3", "sing4", "hung4", "dang1"] },
            { chars: ["假", "使", "相", "当", "勇", "敢", " ", "怎", "可", "挽", "回", "自", "身"], jp: ["gaa2", "si2", "soeng1", "dong1", "jung5", "gam2", "", "zam2", "ho2", "waan5", "wui4", "zi6", "san1"] },
            { chars: ["《", "K", "i", "s", "s", " ", "K", "i", "s", "s", " ", "K", "i", "s", "s", "》"], jp: ["", "K", "i", "s", "s", "", "K", "i", "s", "s", "", "K", "i", "s", "s", ""] },
            { chars: ["唇", "上", "限", "量", "限", "量", "对", "象", " ", "K", "i", "s", "s", ",", "K", "i", "s", "s", ",", "K", "i", "s", "s"], jp: ["seon4", "soeng6", "haan6", "loeng4", "haan6", "loeng4", "deoi3", "zoeng6", "", "K", "i", "s", "s", "", "K", "i", "s", "s", "", "K", "i", "s", "s"] },
            { chars: ["一", "沾", "上", "就", "发", "亮"], jp: ["jat1", "zim1", "soeng6", "zau6", "faat3", "loeng6"] },
            { chars: ["唇", "上"], jp: ["seon4", "soeng6"] },
            { chars: ["《", "第", "五", "类", "》"], jp: ["", "dai6", "ng5", "leoi6", ""] },
            { chars: ["小", "心", "好", "吗"], jp: ["siu2", "sam1", "hou2", "maa1"] },
            { chars: ["小", "心", "我", " ", "我", "会", "热", "烫", "到", "一", "触", "即", "发"], jp: ["siu2", "sam1", "ngo5", "", "ngo5", "wui6", "jit6", "tong3", "dou3", "jat1", "zuk1", "zik1", "faat3"] },
            { chars: ["《", "爆", "》"], jp: ["", "baau3", ""] },
            { chars: ["忘", "掉", "你", "是", "我", "的", "新", "志", "愿", " ", "仿", "如", "拆", "下", "炸", "弹", "点", "火", "线"], jp: ["mong4", "diu6", "nei5", "si6", "ngo5", "dik1", "san1", "zi3", "jyun6", "", "fong2", "jyu4", "caak3", "haa6", "zaa3", "daan6", "dim2", "fo2", "sin3"] },
            { paragraphBreak: true },
            { chars: ["（", "正", "篇", "）"], jp: ["", "zing3", "pin1", ""] },
            { paragraphBreak: true },
            { chars: ["《", "还", "》"], jp: ["", "waan4", ""] },
            { paragraphBreak: true },
            { chars: ["你", "说", "话", "太", "吞", "吐", " ", "这", "告", "别", "太", "辛", "劳"], jp: ["nei5", "syut3", "waa6", "taai3", "tan1", "tou3", "", "ze5", "gou3", "bit6", "taai3", "san1", "lou4"] },
            { chars: ["语", "气", "令", "到", "我", "真", "的", "以", "为", "有", "何", "要", "宣", "布"], jp: ["jyu5", "hei3", "ling6", "dou3", "ngo5", "zan1", "dik1", "ji5", "wai4", "jau5", "ho4", "jiu3", "syun1", "bou3"] },
            { chars: ["你", "处", "事", "太", "周", "到", " ", "我", "爱", "是", "你", "虚", "无"], jp: ["nei5", "cyu5", "si6", "taai3", "zau1", "dou3", "", "ngo5", "ngoi3", "si6", "nei5", "heoi1", "mou4"] },
            { chars: ["你", "决", "定", "要", "走", "这", "种", "过", "程", "有", "谁", "要", "挡", "路"], jp: ["nei5", "kyut3", "ding6", "jiu3", "zau2", "ze5", "zung2", "gwo3", "cing4", "jau5", "seoi4", "jiu3", "dong2", "lou6"] },
            { paragraphBreak: true },
            { chars: ["知", "不", "知", "先", "不", "应", "怕", "输", "再", "热", "爱"], jp: ["zi1", "bat1", "zi1", "sin1", "bat1", "jing3", "paa3", "syu1", "zoi3", "jit6", "ngoi3"] },
            { chars: ["当", "分", "开", "我", "放", "弃", "才", "能", "慷", "慨"], jp: ["dong1", "fan1", "hoi1", "ngo5", "fong3", "hei3", "coi4", "nang4", "kong2", "koi3"] },
            { chars: ["知", "不", "知", "只", "需", "讲", "当", "天", "当", "你", "抱", "紧", "我"], jp: ["zi1", "bat1", "zi1", "zi2", "seoi1", "gong2", "dong1", "tin1", "dong1", "nei5", "pou5", "gan2", "ngo5"] },
            { chars: ["在", "那", "刻", " ", "动", "过", "真", "爱"], jp: ["zoi6", "naa5", "hak1", "", "dung6", "gwo3", "zan1", "ngoi3"] },
            { paragraphBreak: true },
            { chars: ["恋", "爱", "是", "容", "易", "谈", "容", "易", "淡", " ", "从", "来", "是", "十", "分", "花", "时", "间"], jp: ["lyun2", "ngoi3", "si6", "jung4", "ji6", "taam4", "jung4", "ji6", "daam6", "", "cung4", "loi4", "si6", "sap6", "fan1", "faa1", "si4", "gaan1"] },
            { chars: ["明", "了", "历", "尽", "几", "多", "难", "关", " ", "快", "乐", "过", "悲", "伤", "要", "用", "年", "月", "去", "摊", "还"], jp: ["ming4", "liu5", "lik6", "zeon6", "gei2", "do1", "naan4", "gwaan1", "", "faai3", "lok6", "gwo3", "bei1", "soeng1", "jiu3", "jung6", "nin4", "jyut6", "heoi3", "taan1", "waan4"] },
            { chars: ["心", "痛", "是", "容", "易", "烦", "容", "易", "惯", " ", "为", "何", "日", "落", "担", "心", "傍", "晚"], jp: ["sam1", "tung3", "si6", "jung4", "ji6", "faan4", "jung4", "ji6", "gwaan3", "", "wai4", "ho4", "jat6", "lok6", "daam1", "sam1", "bong6", "maan5"] },
            { chars: ["明", "明", "道", "别", "不", "需", "留", "一", "眼", " ", "别", "多", "关", "心", "我", "睡", "眠", "太", "冷"], jp: ["ming4", "ming4", "dou6", "bit6", "bat1", "seoi1", "lau4", "jat1", "ngaan5", "", "bit6", "do1", "gwaan1", "sam1", "ngo5", "seoi6", "min4", "taai3", "laang5"] },
            { paragraphBreak: true },
            { chars: ["《", "借", "》"], jp: ["", "ze3", ""] },
            { paragraphBreak: true },
            { chars: ["传", "闻", "说", "你", "正", "与", "她", "吵", "架", "不", "见", "面", "了"], jp: ["cyun4", "man4", "syut3", "nei5", "zing3", "jyu5", "taa1", "caau2", "gaa3", "bat1", "gin3", "min6", "liu5"] },
            { chars: ["传", "闻", "说", "你", "仍", "留", "下", "共", "她", "所", "有", "合", "照"], jp: ["cyun4", "man4", "syut3", "nei5", "jing4", "lau4", "haa6", "gung6", "taa1", "so2", "jau5", "hap6", "ziu3"] },
            { chars: ["上", "分", "钟", " ", "上", "一", "秒", " ", "你", "说", "心", "不", "再", "困", "扰"], jp: ["soeng6", "fan1", "zung1", "", "soeng6", "jat1", "miu5", "", "nei5", "syut3", "sam1", "bat1", "zoi3", "kwan3", "jiu2"] },
            { chars: ["下", "分", "钟", " ", "下", "一", "秒", " ", "你", "眼", "睛", "通", "红", "似", "发", "烧"], jp: ["haa6", "fan1", "zung1", "", "haa6", "jat1", "miu5", "", "nei5", "ngaan5", "zing1", "tung1", "hung4", "ci5", "faat3", "siu1"] },
            { paragraphBreak: true },
            { chars: ["为", "何", "每", "个", "礼", "拜", "消", "遣", "都", "早", "约", "定", "了"], jp: ["wai4", "ho4", "mui5", "go3", "lai5", "baai3", "siu1", "hin2", "dou1", "zou2", "joek3", "ding6", "liu5"] },
            { chars: ["谁", "人", "个", "唱", "那", "里", "自", "助", "餐", "都", "已", "订", "票"], jp: ["seoi4", "jan4", "go3", "coeng3", "naa5", "lei5", "zi6", "zo6", "caan1", "dou1", "ji5", "ding3", "piu3"] },
            { chars: ["是", "开", "始", " ", "又", "不", "对", " ", "对", "你", "所", "知", "道", "太", "少"], jp: ["si6", "hoi1", "ci2", "", "jau6", "bat1", "deoi3", "", "deoi3", "nei5", "so2", "zi1", "dou6", "taai3", "siu2"] },
            { chars: ["是", "知", "己", " ", "亦", "不", "对", " ", "你", "太", "好", "的", "人", "缘", " ", "知", "己", "哪", "会", "缺", "少"], jp: ["si6", "zi1", "gei2", "", "jik6", "bat1", "deoi3", "", "nei5", "taai3", "hou2", "dik1", "jan4", "jyun4", "", "zi1", "gei2", "naa5", "wui6", "kyut3", "siu2"] },
            { paragraphBreak: true },
            { chars: ["如", "果", "你", "习", "惯", " ", "有", "备", "无", "患", " ", "只", "怕", "独", "个", "晚", "餐"], jp: ["jyu4", "gwo2", "nei5", "zaap6", "gwaan3", "", "jau5", "bei6", "mou4", "waan6", "", "zi2", "paa3", "duk6", "go3", "maan5", "caan1"] },
            { chars: ["才", "想", "到", "让", "我", "借", "用", "时", "间", " ", "借", "用", "完", "没", "法", "还"], jp: ["coi4", "soeng2", "dou3", "joeng6", "ngo5", "ze3", "jung6", "si4", "gaan1", "", "ze3", "jung6", "jyun4", "mut6", "faat3", "waan4"] },
            { chars: ["如", "果", "破", "掉", "灯", "泡", "借", "烛", "光", "用", "一", "晚", " ", "是", "你", "是", "你", "大", "贪"], jp: ["jyu4", "gwo2", "po3", "diu6", "dang1", "paau1", "ze3", "zuk1", "gwong1", "jung6", "jat1", "maan5", "", "si6", "nei5", "si6", "nei5", "daai6", "taam1"] },
            { chars: ["大", "贪", "得", "竟", "搅", "错", "我", "是", "哪", "种", "人"], jp: ["daai6", "taam1", "dak1", "ging2", "gaau2", "co3", "ngo5", "si6", "naa5", "zung2", "jan4"] },
            { paragraphBreak: true },
            { chars: ["如", "果", "你", "习", "惯", " ", "有", "备", "无", "患", " ", "只", "怕", "独", "个", "晚", "餐"], jp: ["jyu4", "gwo2", "nei5", "zaap6", "gwaan3", "", "jau5", "bei6", "mou4", "waan6", "", "zi2", "paa3", "duk6", "go3", "maan5", "caan1"] },
            { chars: ["才", "想", "到", "让", "我", "借", "用", "时", "间", " ", "借", "用", "完", "没", "法", "还"], jp: ["coi4", "soeng2", "dou3", "joeng6", "ngo5", "ze3", "jung6", "si4", "gaan1", "", "ze3", "jung6", "jyun4", "mut6", "faat3", "waan4"] },
            { chars: ["如", "果", "破", "掉", "灯", "泡", "借", "烛", "光", "用", "一", "晚", " ", "是", "你", "是", "你", "大", "贪"], jp: ["jyu4", "gwo2", "po3", "diu6", "dang1", "paau1", "ze3", "zuk1", "gwong1", "jung6", "jat1", "maan5", "", "si6", "nei5", "si6", "nei5", "daai6", "taam1"] },
            { chars: ["大", "贪", "得", "竟", "搅", "错", "我", "是", "哪", "种", "人", " ", "接", "吻", "就", "能", "合", "眼"], jp: ["daai6", "taam1", "dak1", "ging2", "gaau2", "co3", "ngo5", "si6", "naa5", "zung2", "jan4", "", "zip3", "man5", "zau6", "nang4", "hap6", "ngaan5"] },
            { chars: ["有", "雨", "没", "提", "著", "伞"], jp: ["jau5", "jyu5", "mut6", "tai4", "zyu3", "saan3"] }
        ]
    };
    if (typeof window !== 'undefined' && window.__songs) {
        window.__songs.push(song);
    }
})();
