// 歌曲：Medley: 垃圾 + 绝 + 失乐园 + 大开眼戒 (Live)

(function() {
    const song = {
        id: 291,
        title: "Medley:垃圾+绝+失乐园+大开眼戒(Live)",
        titleJyutping: ["M","e","d","l","e","y","","","laap6","saap3","","","","zyut6","","","","sat1","lok6","jyun4","","","","daai6","hoi1","ngaan5","gaai3","","","L","i","v","e",""],
        artist: "张敬轩",
        artistJyutping: ["zoeng1","ging3","hin1"],
        lyricist: "",
        lyricistJyutping: [],
        composer: "",
        composerJyutping: [],
        lyrics: [
            { chars: ["《","垃","圾","》"], jp: ["","laap6","saap3",""] },
            { paragraphBreak: true },
            { chars: ["如","果","我","是","半","张","废","纸"], jp: ["jyu4","gwo2","ngo5","si6","bun3","zoeng1","fai3","zi2"] },
            { chars: ["让","我","　","化","蝶"], jp: ["joeng6","ngo5","","faa3","dip6"] },
            { chars: ["如","果","我","是","个","空","罐","子"], jp: ["jyu4","gwo2","ngo5","si6","go3","hung1","gun3","zi2"] },
            { chars: ["为","你","　","铁","了","心"], jp: ["wai4","nei5","","tit3","liu5","sam1"] },
            { chars: ["被","你","浪","费"], jp: ["bei6","nei5","long6","fai3"] },
            { chars: ["被","你","活","埋"], jp: ["bei6","nei5","wut6","maai4"] },
            { chars: ["让","我","愉","快"], jp: ["joeng6","ngo5","jyu4","faai3"] },
            { chars: ["让","我","瓦","解"], jp: ["joeng6","ngo5","ngaa5","gaai2"] },
            { chars: ["为","你","盛","放"], jp: ["wai4","nei5","sing6","fong3"] },
            { chars: ["颓","废","中"], jp: ["teoi4","fai3","zung1"] },
            { chars: ["那","媚","态"], jp: ["naa5","mei6","taai3"] },
            { paragraphBreak: true },
            { chars: ["留","我","做","个","垃","圾"], jp: ["lau4","ngo5","zou6","go3","laap6","saap3"] },
            { chars: ["长","留","恋","于","你","家"], jp: ["coeng4","lau4","lyun2","jyu1","nei5","gaa1"] },
            { chars: ["从","沉","溺","中","结","疤"], jp: ["cung4","cam4","nik6","zung1","git3","baa1"] },
            { chars: ["再","发","芽"], jp: ["zoi3","faat3","ngaa4"] },
            { chars: ["情","爱","就","似","垃","圾"], jp: ["cing4","ngoi3","zau6","ci5","laap6","saap3"] },
            { chars: ["残","骸","虽","会","腐","化"], jp: ["caan4","haai4","seoi1","wui6","fu6","faa3"] },
            { chars: ["庭","园","中","最","后","也"], jp: ["ting4","jyun4","zung1","zeoi3","hau6","jaa5"] },
            { chars: ["开","满","花"], jp: ["hoi1","mun5","faa1"] },
            { paragraphBreak: true },
            { chars: ["被","世","界","遗","弃"], jp: ["bei6","sai3","gaai3","wai4","hei3"] },
            { chars: ["不","可","怕"], jp: ["bat1","ho2","paa3"] },
            { chars: ["喜","欢","你"], jp: ["hei2","fun1","nei5"] },
            { chars: ["有","时","还","可","怕"], jp: ["jau5","si4","waan4","ho2","paa3"] },
            { chars: ["没","法","再","做","那","些","牵","挂"], jp: ["mut6","faat3","zoi3","zou6","naa5","se1","hin1","gwaa3"] },
            { chars: ["比","不","上"], jp: ["bei2","bat1","soeng6"] },
            { chars: ["在","你","手","中","火","化"], jp: ["zoi6","nei5","sau2","zung1","fo2","faa3"] },
            { chars: ["不","需","要"], jp: ["bat1","seoi1","jiu3"] },
            { chars: ["完","美","得","可","怕"], jp: ["jyun4","mei5","dak1","ho2","paa3"] },
            { chars: ["太","快","乐"], jp: ["taai3","faai3","lok6"] },
            { chars: ["如","何","招","架"], jp: ["jyu4","ho4","ziu1","gaa3"] },
            { chars: ["残","忍","不","好","吗"], jp: ["caan4","jan2","bat1","hou2","maa1"] },
            { paragraphBreak: true },
            { chars: ["被","世","界","遗","弃"], jp: ["bei6","sai3","gaai3","wai4","hei3"] },
            { chars: ["不","可","怕"], jp: ["bat1","ho2","paa3"] },
            { chars: ["喜","欢","你"], jp: ["hei2","fun1","nei5"] },
            { chars: ["有","时","还","可","怕"], jp: ["jau5","si4","waan4","ho2","paa3"] },
            { chars: ["没","法","再","做","那","些","牵","挂"], jp: ["mut6","faat3","zoi3","zou6","naa5","se1","hin1","gwaa3"] },
            { chars: ["比","不","上"], jp: ["bei2","bat1","soeng6"] },
            { chars: ["在","你","手","中","火","化"], jp: ["zoi6","nei5","sau2","zung1","fo2","faa3"] },
            { chars: ["不","需","要"], jp: ["bat1","seoi1","jiu3"] },
            { chars: ["完","美","得","可","怕"], jp: ["jyun4","mei5","dak1","ho2","paa3"] },
            { chars: ["太","快","乐"], jp: ["taai3","faai3","lok6"] },
            { chars: ["如","何","招","架"], jp: ["jyu4","ho4","ziu1","gaa3"] },
            { chars: ["残","忍","不","好","吗"], jp: ["caan4","jan2","bat1","hou2","maa1"] },
            { paragraphBreak: true },
            { chars: ["灰","烬","里"], jp: ["fui1","zeon6","lei5"] },
            { chars: ["被","彻","底","消","化"], jp: ["bei6","cit3","dai2","siu1","faa3"] },
            { chars: ["我","以","后"], jp: ["ngo5","ji5","hau6"] },
            { chars: ["全","无","牵","挂"], jp: ["cyun4","mou4","hin1","gwaa3"] },
            { chars: ["什","么","都","不","怕"], jp: ["sap6","maa1","dou1","bat1","paa3"] },
            { paragraphBreak: true },
            { chars: ["《","绝","》"], jp: ["","zyut6",""] },
            { paragraphBreak: true },
            { chars: ["宁","愿","滞","留","在","此","处"], jp: ["ning4","jyun6","zai6","lau4","zoi6","ci2","cyu5"] },
            { chars: ["宁","愿","叫","时","间","中","止"], jp: ["ning4","jyun6","giu3","si4","gaan1","zung1","zi2"] },
            { chars: ["我","不","会","再","信","未","来"], jp: ["ngo5","bat1","wui6","zoi3","seon3","mei6","loi4"] },
            { chars: ["我","不","要","再","看","历","史"], jp: ["ngo5","bat1","jiu3","zoi3","hon3","lik6","si2"] },
            { chars: ["还","能","活","才","是","讽","刺"], jp: ["waan4","nang4","wut6","coi4","si6","fung3","ci3"] },
            { chars: ["故","此","不","用","做","傻","事"], jp: ["gu3","ci2","bat1","jung6","zou6","so4","si6"] },
            { chars: ["让","痛","苦"], jp: ["joeng6","tung3","fu2"] },
            { chars: ["轮","回","千","次"], jp: ["leon4","wui4","cin1","ci3"] },
            { chars: ["彰","显","那","快","乐","有","尽","时"], jp: ["zoeng1","hin2","naa5","faai3","lok6","jau5","zeon6","si4"] },
            { chars: ["曙","光","全","部","熄","灭"], jp: ["cyu5","gwong1","cyun4","bou6","sik1","mit6"] },
            { chars: ["杀","掉","我","影","子"], jp: ["saat3","diu6","ngo5","jing2","zi2"] },
            { chars: ["我","只","能","独","处"], jp: ["ngo5","zi2","nang4","duk6","cyu5"] },
            { chars: ["背","后","全","没","有","支","柱"], jp: ["bui3","hau6","cyun4","mut6","jau5","zi1","cyu5"] },
            { paragraphBreak: true },
            { chars: ["甚","么","叫","绝","望"], jp: ["sam6","maa1","giu3","zyut6","mong6"] },
            { chars: ["抬","起","眼","望","望"], jp: ["toi4","hei2","ngaan5","mong6","mong6"] },
            { chars: ["如","今","我","在","你","面","前","呈","堂"], jp: ["jyu4","gam1","ngo5","zoi6","nei5","min6","cin4","cing4","tong4"] },
            { chars: ["随","便","收","看"], jp: ["ceoi4","bin6","sau1","hon3"] },
            { chars: ["灵","魂","被","抽","干"], jp: ["ling4","wan4","bei6","cau1","gon1"] },
            { chars: ["残","留","著","躯","干"], jp: ["caan4","lau4","zyu3","keoi1","gon1"] },
            { chars: ["从","此","与","未","了","愿","同","存","亡"], jp: ["cung4","ci2","jyu5","mei6","liu5","jyun6","tung4","cyun4","mong4"] },
            { chars: ["地","老","天","荒"], jp: ["dei6","lou5","tin1","fong1"] },
            { paragraphBreak: true },
            { chars: ["还","不","够","绝","望"], jp: ["waan4","bat1","gau3","zyut6","mong6"] },
            { chars: ["尚","可","更","绝","望"], jp: ["soeng6","ho2","gang1","zyut6","mong6"] },
            { chars: ["留","给","我","日","后","用","来","形","容","前","面","境","况"], jp: ["lau4","kap1","ngo5","jat6","hau6","jung6","loi4","jing4","jung4","cin4","min6","ging2","fong3"] },
            { chars: ["能","够","这","样"], jp: ["nang4","gau3","ze5","joeng6"] },
            { chars: ["谢","谢","你","帮","忙"], jp: ["ze6","ze6","nei5","bong1","mong4"] },
            { chars: ["将","仅","有","愿","望","都","风","光","殓","葬"], jp: ["zoeng1","gan2","jau5","jyun6","mong6","dou1","fung1","gwong1","lim5","zong3"] },
            { paragraphBreak: true },
            { chars: ["甚","么","叫","绝","望"], jp: ["sam6","maa1","giu3","zyut6","mong6"] },
            { chars: ["抬","起","眼","望","望"], jp: ["toi4","hei2","ngaan5","mong6","mong6"] },
            { chars: ["如","今","我","在","你","面","前","呈","堂"], jp: ["jyu4","gam1","ngo5","zoi6","nei5","min6","cin4","cing4","tong4"] },
            { chars: ["随","便","收","看"], jp: ["ceoi4","bin6","sau1","hon3"] },
            { chars: ["灵","魂","被","抽","干"], jp: ["ling4","wan4","bei6","cau1","gon1"] },
            { chars: ["残","留","著","躯","干"], jp: ["caan4","lau4","zyu3","keoi1","gon1"] },
            { chars: ["从","此","与","未","了","愿","同","存","亡"], jp: ["cung4","ci2","jyu5","mei6","liu5","jyun6","tung4","cyun4","mong4"] },
            { chars: ["地","老","天","荒"], jp: ["dei6","lou5","tin1","fong1"] },
            { paragraphBreak: true },
            { chars: ["还","不","够","绝","望"], jp: ["waan4","bat1","gau3","zyut6","mong6"] },
            { chars: ["尚","可","更","绝","望"], jp: ["soeng6","ho2","gang1","zyut6","mong6"] },
            { chars: ["留","给","我","日","后","用","来","形","容","前","面","境","况"], jp: ["lau4","kap1","ngo5","jat6","hau6","jung6","loi4","jing4","jung4","cin4","min6","ging2","fong3"] },
            { chars: ["能","够","这","样"], jp: ["nang4","gau3","ze5","joeng6"] },
            { chars: ["谢","谢","你","帮","忙"], jp: ["ze6","ze6","nei5","bong1","mong4"] },
            { chars: ["将","仅","有","愿","望","都","风","光","殓","葬"], jp: ["zoeng1","gan2","jau5","jyun6","mong6","dou1","fung1","gwong1","lim5","zong3"] },
            { paragraphBreak: true },
            { chars: ["能","够","这","样"], jp: ["nang4","gau3","ze5","joeng6"] },
            { chars: ["全","靠","你","帮","忙"], jp: ["cyun4","kaau3","nei5","bong1","mong4"] },
            { chars: ["将","恋","爱","绝","后","的","标","准","答","案"], jp: ["zoeng1","lyun2","ngoi3","zyut6","hau6","dik1","biu1","zeon2","daap3","on3"] },
            { paragraphBreak: true },
            { chars: ["《","失","乐","园","》"], jp: ["","sat1","lok6","jyun4",""] },
            { paragraphBreak: true },
            { chars: ["结","果","我","共","你"], jp: ["git3","gwo2","ngo5","gung6","nei5"] },
            { chars: ["仍","然","逃","不","过"], jp: ["jing4","jin4","tou4","bat1","gwo3"] },
            { chars: ["被","围","攻"], jp: ["bei6","wai4","gung1"] },
            { chars: ["被","舍","弃"], jp: ["bei6","se3","hei3"] },
            { chars: ["爱","得","惊","天","动","地"], jp: ["ngoi3","dak1","ging1","tin1","dung6","dei6"] },
            { chars: ["总","算","运","气"], jp: ["zung2","syun3","wan6","hei3"] },
            { chars: ["无","论","褒","贬","尊","与","卑"], jp: ["mou4","leon6","bou1","bin2","zyun1","jyu5","bei1"] },
            { paragraphBreak: true },
            { chars: ["爱","可","有","定","理"], jp: ["ngoi3","ho2","jau5","ding6","lei5"] },
            { chars: ["谈","情","谁","讲","理"], jp: ["taam4","cing4","seoi4","gong2","lei5"] },
            { chars: ["越","无","理"], jp: ["jyut6","mou4","lei5"] },
            { chars: ["越","凄","美"], jp: ["jyut6","cai1","mei5"] },
            { chars: ["就","算","飞","天","遁","地"], jp: ["zau6","syun3","fei1","tin1","deon6","dei6"] },
            { chars: ["万","年","千","里"], jp: ["maan6","nin4","cin1","lei5"] },
            { chars: ["亦","决","定","要","共","你","一","起"], jp: ["jik6","kyut3","ding6","jiu3","gung6","nei5","jat1","hei2"] },
            { paragraphBreak: true },
            { chars: ["苦","恋","注","定","难"], jp: ["fu2","lyun2","zyu3","ding6","naan4"] },
            { chars: ["我","已","经","习","惯"], jp: ["ngo5","ji5","ging1","zaap6","gwaan3"] },
            { chars: ["沿","途","承","受","不","留","情","的","双","眼"], jp: ["jyun4","tou4","sing4","sau6","bat1","lau4","cing4","dik1","soeng1","ngaan5"] },
            { chars: ["请","给","我","负","担"], jp: ["cing2","kap1","ngo5","fu6","daam1"] },
            { chars: ["叫","世","上","人","间"], jp: ["giu3","sai3","soeng6","jan4","gaan1"] },
            { chars: ["平","凡","情","侣","为","你","共","我","轰","烈","汗","颜"], jp: ["ping4","faan4","cing4","leoi5","wai4","nei5","gung6","ngo5","gwang1","lit6","hon6","ngaan4"] },
            { paragraphBreak: true },
            { chars: ["苦","恋","注","定","难"], jp: ["fu2","lyun2","zyu3","ding6","naan4"] },
            { chars: ["我","却","这","样","贪"], jp: ["ngo5","koek3","ze5","joeng6","taam1"] },
            { chars: ["途","人","凝","望","中"], jp: ["tou4","jan4","jing4","mong6","zung1"] },
            { chars: ["寂","静","的","称","赞"], jp: ["zik6","zing6","dik1","cing1","zaan3"] },
            { chars: ["请","给","我","负","担"], jp: ["cing2","kap1","ngo5","fu6","daam1"] },
            { chars: ["叫","世","上","人","间"], jp: ["giu3","sai3","soeng6","jan4","gaan1"] },
            { chars: ["惶","惶","情","侣"], jp: ["wong4","wong4","cing4","leoi5"] },
            { chars: ["在","美","丽","与","悲","哀","之","间"], jp: ["zoi6","mei5","lai6","jyu5","bei1","oi1","zi1","gaan1"] },
            { paragraphBreak: true },
            { chars: ["苦","恋","注","定","难"], jp: ["fu2","lyun2","zyu3","ding6","naan4"] },
            { chars: ["我","却","这","样","贪"], jp: ["ngo5","koek3","ze5","joeng6","taam1"] },
            { chars: ["途","人","凝","望","中"], jp: ["tou4","jan4","jing4","mong6","zung1"] },
            { chars: ["寂","静","的","称","赞"], jp: ["zik6","zing6","dik1","cing1","zaan3"] },
            { chars: ["请","给","我","负","担"], jp: ["cing2","kap1","ngo5","fu6","daam1"] },
            { chars: ["叫","世","上","人","间"], jp: ["giu3","sai3","soeng6","jan4","gaan1"] },
            { chars: ["惶","惶","情","侣"], jp: ["wong4","wong4","cing4","leoi5"] },
            { chars: ["在","美","丽","与","悲","哀","之","间"], jp: ["zoi6","mei5","lai6","jyu5","bei1","oi1","zi1","gaan1"] },
            { chars: ["为","恋","爱","平","反"], jp: ["wai4","lyun2","ngoi3","ping4","faan2"] },
            { paragraphBreak: true },
            { chars: ["《","大","开","眼","戒","》"], jp: ["","daai6","hoi1","ngaan5","gaai3",""] },
            { paragraphBreak: true },
            { chars: ["不","要","着","灯"], jp: ["bat1","jiu3","zoek6","dang1"] },
            { chars: ["能","否","先","跟","我"], jp: ["nang4","fau2","sin1","gan1","ngo5"] },
            { chars: ["摸","黑","吻","一","吻"], jp: ["mo2","hak1","man5","jat1","man5"] },
            { chars: ["如","果","我"], jp: ["jyu4","gwo2","ngo5"] },
            { chars: ["露","出","了","真","身"], jp: ["lou6","ceot1","liu5","zan1","san1"] },
            { chars: ["可","会","被","抱","紧"], jp: ["ho2","wui6","bei6","pou5","gan2"] },
            { chars: ["惊","破","坏","气","氛"], jp: ["ging1","po3","waai6","hei3","fan1"] },
            { chars: ["谁","都","不","知","我"], jp: ["seoi4","dou1","bat1","zi1","ngo5"] },
            { chars: ["心","底","有","多","暗"], jp: ["sam1","dai2","jau5","do1","am3"] },
            { chars: ["如","本","性"], jp: ["jyu4","bun2","sing3"] },
            { chars: ["是","这","么","低","等"], jp: ["si6","ze5","maa1","dai1","dang2"] },
            { chars: ["怎","跟","你","相","衬"], jp: ["zam2","gan1","nei5","soeng1","can3"] },
            { paragraphBreak: true },
            { chars: ["情","人","如","若","很","好","奇"], jp: ["cing4","jan4","jyu4","joek6","han2","hou2","kei4"] },
            { chars: ["要","有","被","我","吓","怕","的","准","备"], jp: ["jiu3","jau5","bei6","ngo5","haak3","paa3","dik1","zeon2","bei6"] },
            { chars: ["试","问","谁","可"], jp: ["si3","man6","seoi4","ho2"] },
            { chars: ["洁","白","无","比"], jp: ["git3","baak6","mou4","bei2"] },
            { chars: ["如","何","承","受","这","好","奇"], jp: ["jyu4","ho4","sing4","sau6","ze5","hou2","kei4"] },
            { chars: ["答","案","大","概","似","剃","刀","锋","利"], jp: ["daap3","on3","daai6","koi3","ci5","tai3","dou1","fung1","lei6"] },
            { chars: ["愿","赤","裸","相","对","时"], jp: ["jyun6","cek3","lo2","soeng1","deoi3","si4"] },
            { chars: ["能","够","不","伤","你"], jp: ["nang4","gau3","bat1","soeng1","nei5"] },
            { paragraphBreak: true },
            { chars: ["几","双","手"], jp: ["gei2","soeng1","sau2"] },
            { chars: ["几","双","腿"], jp: ["gei2","soeng1","teoi2"] },
            { chars: ["方","会","令","你","喜","欢","我"], jp: ["fong1","wui6","ling6","nei5","hei2","fun1","ngo5"] },
            { chars: ["顺","利","无","阻"], jp: ["seon6","lei6","mou4","zo2"] },
            { chars: ["你","爱","我"], jp: ["nei5","ngoi3","ngo5"] },
            { chars: ["别","管","我"], jp: ["bit6","gun2","ngo5"] },
            { chars: ["几","双","耳","朵"], jp: ["gei2","soeng1","ji5","do2"] },
            { chars: ["共","我","放","心","探","戈"], jp: ["gung6","ngo5","fong3","sam1","taam3","gwo1"] },
            { paragraphBreak: true },
            { chars: ["情","人","如","若","很","好","奇"], jp: ["cing4","jan4","jyu4","joek6","han2","hou2","kei4"] },
            { chars: ["要","有","被","我","吓","怕","的","准","备"], jp: ["jiu3","jau5","bei6","ngo5","haak3","paa3","dik1","zeon2","bei6"] },
            { chars: ["试","问","谁","可"], jp: ["si3","man6","seoi4","ho2"] },
            { chars: ["洁","白","无","比"], jp: ["git3","baak6","mou4","bei2"] },
            { chars: ["如","何","承","受","这","好","奇"], jp: ["jyu4","ho4","sing4","sau6","ze5","hou2","kei4"] },
            { chars: ["你","有","没","有","爱","我","的","准","备"], jp: ["nei5","jau5","mut6","jau5","ngoi3","ngo5","dik1","zeon2","bei6"] },
            { paragraphBreak: true },
            { chars: ["若","你","喜","欢","怪","人"], jp: ["joek6","nei5","hei2","fun1","gwaai3","jan4"] },
            { chars: ["其","实","我","很","美"], jp: ["kei4","sat6","ngo5","han2","mei5"] }
        ]
    };
    if (typeof window !== 'undefined' && window.__songs) {
        window.__songs.push(song);
    }
})();
