// 歌曲：一千零一个

(function() {
    const song = {
        id: 361,
        title: "一千零一个",
        titleJyutping: ["jat1","cin1","ling4","jat1","go3"],
        artist: "杨千嬅",
        artistJyutping: ["joeng4","cin1","waa6"],
        lyricist: "林夕",
        lyricistJyutping: ["lam4","zik6"],
        composer: "陈韵如",
        composerJyutping: ["can4","wan6","jyu4"],
        lyrics: [
            { chars: ["嫌","阿","拉","丁","神","灯","的","角","色","俗","套","又","怀","旧"], jp: ["jim4","aa3","laai1","ding1","san4","dang1","dik1","gok3","sik1","zuk6","tou3","jau6","waai4","gau6"] },
            { chars: ["难","道","讲","一","讲","你","的","新","朋","友"], jp: ["naan4","dou6","gong2","jat1","gong2","nei5","dik1","san1","pang4","jau5"] },
            { chars: ["嫌","神","话","说","够"], jp: ["jim4","san4","waa6","syut3","gau3"] },
            { chars: ["再","用","梁","祝","伴","奏"], jp: ["zoi3","jung6","loeng4","zuk1","bun6","zau3"] },
            { chars: ["留","下","听","一","千","个","故","事","至","准","走"], jp: ["lau4","haa6","ting1","jat1","cin1","go3","gu3","si6","zi3","zeon2","zau2"] },
            { paragraphBreak: true },
            { chars: ["闻","说","某","君","和","她","的","情","人","快","活","过","之","后"], jp: ["man4","syut3","mau5","gwan1","wo4","taa1","dik1","cing4","jan4","faai3","wut6","gwo3","zi1","hau6"] },
            { chars: ["才","承","认","往","日","满","足","感","未","够"], jp: ["coi4","sing4","jing6","wong5","jat6","mun5","zuk1","gam2","mei6","gau3"] },
            { chars: ["然","而","留","下","了","坏","帐","会","令","余","生","内","疚"], jp: ["jin4","ji4","lau4","haa6","liu5","waai6","zoeng3","wui6","ling6","jyu4","sang1","noi6","gau3"] },
            { chars: ["你","猜","他","能","否","开","口"], jp: ["nei5","caai1","taa1","nang4","fau2","hoi1","hau2"] },
            { paragraphBreak: true },
            { chars: ["未","够","痴","缠","吧"], jp: ["mei6","gau3","ci1","cin4","baa6"] },
            { chars: ["让","我","讲","多","一","个"], jp: ["joeng6","ngo5","gong2","do1","jat1","go3"] },
            { chars: ["其","实","都","关","于","我"], jp: ["kei4","sat6","dou1","gwaan1","jyu1","ngo5"] },
            { chars: ["你","大","概","清","楚"], jp: ["nei5","daai6","koi3","cing1","co2"] },
            { paragraphBreak: true },
            { chars: ["游","戏","都","一","早","玩","完"], jp: ["jau4","hei3","dou1","jat1","zou2","wun6","jyun4"] },
            { chars: ["赢","便","庆","祝"], jp: ["jing4","bin6","hing3","zuk1"] },
            { chars: ["输","了","气","便","断"], jp: ["syu1","liu5","hei3","bin6","dyun6"] },
            { chars: ["来","吧","你","想","杀","便","杀"], jp: ["loi4","baa6","nei5","soeng2","saat3","bin6","saat3"] },
            { chars: ["不","必","心","软","只","望","你","心","酸"], jp: ["bat1","bit1","sam1","jyun5","zi2","mong6","nei5","sam1","syun1"] },
            { chars: ["活","了","这","一","千","天"], jp: ["wut6","liu5","ze5","jat1","cin1","tin1"] },
            { chars: ["已","完","成","宏","愿"], jp: ["ji5","jyun4","sing4","wang4","jyun6"] },
            { chars: ["尽","管","苦","短"], jp: ["zeon6","gun2","fu2","dyun2"] },
            { chars: ["情","话","若","果","一","早","已","说","完"], jp: ["cing4","waa6","joek6","gwo2","jat1","zou2","ji5","syut3","jyun4"] },
            { chars: ["童","话","亦","逼","不","得","已"], jp: ["tung4","waa6","jik6","bik1","bat1","dak1","ji5"] },
            { chars: ["讲","过","便","算"], jp: ["gong2","gwo3","bin6","syun3"] },
            { paragraphBreak: true },
            { chars: ["传","说","有","一","男","一","女","同","偕","到","白","发","之","后"], jp: ["cyun4","syut3","jau5","jat1","naam4","jat1","neoi5","tung4","gaai1","dou3","baak6","faat3","zi1","hau6"] },
            { chars: ["才","怀","念","刻","骨","铭","心","的","旧","友"], jp: ["coi4","waai4","nim6","hak1","gwat1","ming4","sam1","dik1","gau6","jau5"] },
            { chars: ["回","头","陪","着","那","合","照"], jp: ["wui4","tau4","pui4","zoek6","naa5","hap6","ziu3"] },
            { chars: ["块","肉","余","生","渡","过"], jp: ["faai3","juk6","jyu4","sang1","dou6","gwo3"] },
            { chars: ["你","猜","猜","谁","敢","分","手"], jp: ["nei5","caai1","caai1","seoi4","gam2","fan1","sau2"] },
            { chars: ["未","够","痴","缠","吧"], jp: ["mei6","gau3","ci1","cin4","baa6"] },
            { chars: ["让","我","讲","多","一","个"], jp: ["joeng6","ngo5","gong2","do1","jat1","go3"] },
            { chars: ["其","实","都","关","于","我"], jp: ["kei4","sat6","dou1","gwaan1","jyu1","ngo5"] },
            { chars: ["你","大","概","清","楚"], jp: ["nei5","daai6","koi3","cing1","co2"] },
            { paragraphBreak: true },
            { chars: ["游","戏","都","一","早","玩","完"], jp: ["jau4","hei3","dou1","jat1","zou2","wun6","jyun4"] },
            { chars: ["赢","便","庆","祝"], jp: ["jing4","bin6","hing3","zuk1"] },
            { chars: ["输","了","气","便","断"], jp: ["syu1","liu5","hei3","bin6","dyun6"] },
            { chars: ["来","吧","你","想","杀","便","杀"], jp: ["loi4","baa6","nei5","soeng2","saat3","bin6","saat3"] },
            { chars: ["不","必","心","软","只","望","你","心","酸"], jp: ["bat1","bit1","sam1","jyun5","zi2","mong6","nei5","sam1","syun1"] },
            { chars: ["活","了","这","一","千","天"], jp: ["wut6","liu5","ze5","jat1","cin1","tin1"] },
            { chars: ["已","完","成","宏","愿"], jp: ["ji5","jyun4","sing4","wang4","jyun6"] },
            { chars: ["尽","管","苦","短"], jp: ["zeon6","gun2","fu2","dyun2"] },
            { chars: ["情","话","若","果","一","早","已","说","完"], jp: ["cing4","waa6","joek6","gwo2","jat1","zou2","ji5","syut3","jyun4"] },
            { chars: ["童","话","亦","逼","不","得","已"], jp: ["tung4","waa6","jik6","bik1","bat1","dak1","ji5"] },
            { chars: ["讲","过","便","算"], jp: ["gong2","gwo3","bin6","syun3"] },
            { paragraphBreak: true },
            { chars: ["游","戏","都","一","早","玩","完"], jp: ["jau4","hei3","dou1","jat1","zou2","wun6","jyun4"] },
            { chars: ["赢","便","庆","祝"], jp: ["jing4","bin6","hing3","zuk1"] },
            { chars: ["输","了","气","便","断"], jp: ["syu1","liu5","hei3","bin6","dyun6"] },
            { chars: ["来","吧","你","想","杀","便","杀"], jp: ["loi4","baa6","nei5","soeng2","saat3","bin6","saat3"] },
            { chars: ["不","必","心","软","只","望","你","心","酸"], jp: ["bat1","bit1","sam1","jyun5","zi2","mong6","nei5","sam1","syun1"] },
            { chars: ["活","了","这","一","千","天"], jp: ["wut6","liu5","ze5","jat1","cin1","tin1"] },
            { chars: ["已","完","成","宏","愿"], jp: ["ji5","jyun4","sing4","wang4","jyun6"] },
            { chars: ["尽","管","苦","短"], jp: ["zeon6","gun2","fu2","dyun2"] },
            { chars: ["情","话","若","果","一","早","已","说","完"], jp: ["cing4","waa6","joek6","gwo2","jat1","zou2","ji5","syut3","jyun4"] },
            { chars: ["童","话","亦","逼","不","得","已"], jp: ["tung4","waa6","jik6","bik1","bat1","dak1","ji5"] },
            { chars: ["讲","过","便","算"], jp: ["gong2","gwo3","bin6","syun3"] }
        ]
    };
    if (typeof window !== 'undefined' && window.__songs) {
        window.__songs.push(song);
    }
})();
