// 歌曲：七百年后

(function() {
    const song = {
        id: 305,
        title: "七百年后",
        titleJyutping: ["cat1","baak3","nin4","hau6"],
        artist: "陈奕迅",
        artistJyutping: ["can4","jik6","seon3"],
        lyricist: "林若宁",
        lyricistJyutping: ["lam4","joek6","ning4"],
        composer: "柳重言",
        composerJyutping: ["lau5","cung5","jin4"],
        lyrics: [
            { chars: ["你","那","太","空","舱"], jp: ["nei5","naa5","taai3","hung1","cong1"] },
            { chars: ["能","够","发","出","金","色","的","光"], jp: ["nang4","gau3","faat3","ceot1","gam1","sik1","dik1","gwong1"] },
            { chars: ["我","废","置","一","方"], jp: ["ngo5","fai3","zi3","jat1","fong1"] },
            { chars: ["抬","头","便","会","为","你","守","望"], jp: ["toi4","tau4","bin6","wui6","wai4","nei5","sau2","mong6"] },
            { chars: ["一","天","天","摧","迫","生","活","在","现","代","化"], jp: ["jat1","tin1","tin1","ceoi1","baak1","sang1","wut6","zoi6","jin6","doi6","faa3"] },
            { chars: ["缤","纷","星","空","抛","低","我","寄","存","繁","荣","垃","圾","缸"], jp: ["ban1","fan1","sing1","hung1","paau1","dai1","ngo5","gei3","cyun4","faan4","wing4","laap6","saap3","gong1"] },
            { chars: ["多","得","你","原","谅","我","肮","脏"], jp: ["do1","dak1","nei5","jyun4","loeng6","ngo5","kon3","zong1"] },
            { paragraphBreak: true },
            { chars: ["送","你","破","黑","胶"], jp: ["sung3","nei5","po3","hak1","gaau1"] },
            { chars: ["廉","价","发","出","歌","声","依","稀"], jp: ["lim4","gaai3","faat3","ceot1","go1","sing1","ji1","hei1"] },
            { chars: ["送","你","破","灯","泡"], jp: ["sung3","nei5","po3","dang1","paau1"] },
            { chars: ["便","宜","地","照","亮","你","天","地"], jp: ["bin6","ji4","dei6","ziu3","loeng6","nei5","tin1","dei6"] },
            { chars: ["一","箱","卡","式","带","一","直","没","落","仍","能","回","味"], jp: ["jat1","soeng1","kaa1","sik1","daai3","jat1","zik6","mut6","lok6","jing4","nang4","wui4","mei6"] },
            { chars: ["那","套","旧","文","艺","戏"], jp: ["naa5","tou3","gau6","man4","ngai6","hei3"] },
            { chars: ["生","生","不","息","的","凄","美","爱","情","逾","越","物","质","跨","过","世","纪"], jp: ["sang1","sang1","bat1","sik1","dik1","cai1","mei5","ngoi3","cing4","jyu4","jyut6","mat6","zat1","kwaa3","gwo3","sai3","gei2"] },
            { paragraphBreak: true },
            { chars: ["文","明","能","压","碎"], jp: ["man4","ming4","nang4","aat3","seoi3"] },
            { chars: ["情","怀","不","衰"], jp: ["cing4","waai4","bat1","seoi1"] },
            { chars: ["无","论","枯","干","山","水"], jp: ["mou4","leon6","fu1","gon1","saan1","seoi2"] },
            { chars: ["旧","时","年","月","投","入","垃","圾","里"], jp: ["gau6","si4","nin4","jyut6","tau4","jap6","laap6","saap3","lei5"] },
            { chars: ["你","我","一","起","同","居"], jp: ["nei5","ngo5","jat1","hei2","tung4","geoi1"] },
            { chars: ["仍","然","能","送","你"], jp: ["jing4","jin4","nang4","sung3","nei5"] },
            { chars: ["儿","时","玩","具"], jp: ["ji4","si4","wun6","geoi6"] },
            { chars: ["老","地","方","抱","著","一","起","安","睡"], jp: ["lou5","dei6","fong1","pou5","zyu3","jat1","hei2","on1","seoi6"] },
            { chars: ["七","百","年"], jp: ["cat1","baak3","nin4"] },
            { chars: ["潮","流","里"], jp: ["ciu4","lau4","lei5"] },
            { chars: ["瞬","息","过","去"], jp: ["seon3","sik1","gwo3","heoi3"] },
            { paragraphBreak: true },
            { chars: ["弃","置","那","棵","花"], jp: ["hei3","zi3","naa5","fo2","faa1"] },
            { chars: ["容","我","带","它","的","根","归","家"], jp: ["jung4","ngo5","daai3","taa1","dik1","gan1","gwai1","gaa1"] },
            { chars: ["送","你","这","棵","花"], jp: ["sung3","nei5","ze5","fo2","faa1"] },
            { chars: ["来","怀","念","已","逝","去","初","夏"], jp: ["loi4","waai4","nim6","ji5","sai6","heoi3","co1","haa6"] },
            { chars: ["漆","黑","的","星","体","花","叶","树","木","无","从","留","下"], jp: ["cat1","hak1","dik1","sing1","tai2","faa1","jip6","syu6","muk6","mou4","cung4","lau4","haa6"] },
            { chars: ["你","会","在","流","泪","吗"], jp: ["nei5","wui6","zoi6","lau4","leoi6","maa1"] },
            { chars: ["花","开","的","沙","丘","滋","养","我","们","贫","穷","地","方","优","美","似","画"], jp: ["faa1","hoi1","dik1","saa1","jau1","zi1","joeng5","ngo5","mun4","pan4","kung4","dei6","fong1","jau1","mei5","ci5","waak6"] },
            { paragraphBreak: true },
            { chars: ["文","明","能","压","碎"], jp: ["man4","ming4","nang4","aat3","seoi3"] },
            { chars: ["情","怀","不","衰"], jp: ["cing4","waai4","bat1","seoi1"] },
            { chars: ["无","论","枯","干","山","水"], jp: ["mou4","leon6","fu1","gon1","saan1","seoi2"] },
            { chars: ["旧","时","年","月","投","入","垃","圾","里"], jp: ["gau6","si4","nin4","jyut6","tau4","jap6","laap6","saap3","lei5"] },
            { chars: ["你","我","一","起","同","居"], jp: ["nei5","ngo5","jat1","hei2","tung4","geoi1"] },
            { chars: ["仍","然","能","送","你"], jp: ["jing4","jin4","nang4","sung3","nei5"] },
            { chars: ["儿","时","玩","具"], jp: ["ji4","si4","wun6","geoi6"] },
            { chars: ["老","地","方","抱","著","一","起","安","睡"], jp: ["lou5","dei6","fong1","pou5","zyu3","jat1","hei2","on1","seoi6"] },
            { chars: ["七","百","年"], jp: ["cat1","baak3","nin4"] },
            { chars: ["潮","流","里"], jp: ["ciu4","lau4","lei5"] },
            { chars: ["建","筑","统","统","破","碎"], jp: ["gin3","zuk1","tung2","tung2","po3","seoi3"] },
            { paragraphBreak: true },
            { chars: ["天","天","进","化","热","潮","已","记","不","起"], jp: ["tin1","tin1","zeon3","faa3","jit6","ciu4","ji5","gei3","bat1","hei2"] },
            { chars: ["用","霓","虹","去","建","设","欢","喜"], jp: ["jung6","ngai4","hung4","heoi3","gin3","cit3","fun1","hei2"] },
            { chars: ["虽","则","你","我","被","每","粒","星","唾","弃"], jp: ["seoi1","zak1","nei5","ngo5","bei6","mui5","nap1","sing1","to3","hei3"] },
            { chars: ["我","们","贫","乏","却","去","到","金","禧"], jp: ["ngo5","mun4","pan4","fat6","koek3","heoi3","dou3","gam1","hei1"] },
            { paragraphBreak: true },
            { chars: ["文","明","能","压","碎"], jp: ["man4","ming4","nang4","aat3","seoi3"] },
            { chars: ["情","怀","不","衰"], jp: ["cing4","waai4","bat1","seoi1"] },
            { chars: ["无","论","枯","干","山","水"], jp: ["mou4","leon6","fu1","gon1","saan1","seoi2"] },
            { chars: ["旧","时","年","月","投","入","垃","圾","里"], jp: ["gau6","si4","nin4","jyut6","tau4","jap6","laap6","saap3","lei5"] },
            { chars: ["你","我","一","起","同","居"], jp: ["nei5","ngo5","jat1","hei2","tung4","geoi1"] },
            { chars: ["仍","然","能","送","你"], jp: ["jing4","jin4","nang4","sung3","nei5"] },
            { chars: ["儿","时","玩","具"], jp: ["ji4","si4","wun6","geoi6"] },
            { chars: ["老","地","方","抱","著"], jp: ["lou5","dei6","fong1","pou5","zyu3"] },
            { chars: ["一","起","安","睡"], jp: ["jat1","hei2","on1","seoi6"] },
            { chars: ["七","百","年"], jp: ["cat1","baak3","nin4"] },
            { chars: ["随","年","岁"], jp: ["ceoi4","nin4","seoi3"] },
            { chars: ["记","忆","老","去"], jp: ["gei3","jik1","lou5","heoi3"] },
            { paragraphBreak: true },
            { chars: ["仍","然","有","你","的","忠","心","爱","侣"], jp: ["jing4","jin4","jau5","nei5","dik1","zung1","sam1","ngoi3","leoi5"] }
        ]
    };
    if (typeof window !== 'undefined' && window.__songs) {
        window.__songs.push(song);
    }
})();
