// 歌曲：世上只有

(function() {
    const song = {
        id: 217,
        title: "世上只有",
        titleJyutping: ["sai3","soeng6","zi2","jau5"],
        artist: "容祖儿",
        artistJyutping: ["jung4","zou2","ji4"],
        lyricist: "黄伟文",
        lyricistJyutping: ["wong4","wai5","man4"],
        composer: "陈光荣",
        composerJyutping: ["can4","gwong1","wing4"],
        lyrics: [
            { chars: ["望", "着", "你", "讲"], jp: ["mong6", "zoek6", "nei5", "gong2"] },
            { chars: ["也", "许", "更", "易"], jp: ["jaa5", "heoi2", "gang1", "ji6"] },
            { chars: ["浓", "于", "水", "的", "三", "个", "字"], jp: ["nung4", "jyu1", "seoi2", "dik1", "saam1", "go3", "zi6"] },
            { chars: ["从", "我", "降", "世"], jp: ["cung4", "ngo5", "gong3", "sai3"] },
            { chars: ["一", "开", "始"], jp: ["jat1", "hoi1", "ci2"] },
            { chars: ["到", "永", "远"], jp: ["dou3", "wing5", "jyun5"] },
            { chars: ["不", "休", "止"], jp: ["bat1", "jau1", "zi2"] },
            { chars: ["你", "亦", "是", "我", "支", "柱"], jp: ["nei5", "jik6", "si6", "ngo5", "zi1", "cyu5"] },
            { chars: ["动", "力", "和", "意", "义"], jp: ["dung6", "lik6", "wo4", "ji3", "ji6"] },
            { paragraphBreak: true },
            { chars: ["Y", "o", "u", "m", "a", "k", "e", "m", "e", "c", "r", "y", "m", "a", "k", "e", "m", "e", "s", "m", "i", "l", "e"], jp: ["Y", "o", "u", "m", "a", "k", "e", "m", "e", "c", "r", "y", "m", "a", "k", "e", "m", "e", "s", "m", "i", "l", "e"] },
            { chars: ["M", "a", "k", "e", "m", "e", "f", "e", "e", "l", "t", "h", "e", "l", "o", "v", "e", "i", "s", "t", "r", "u", "e"], jp: ["M", "a", "k", "e", "m", "e", "f", "e", "e", "l", "t", "h", "e", "l", "o", "v", "e", "i", "s", "t", "r", "u", "e"] },
            { chars: ["谢", "谢", "你", "的", "关", "顾"], jp: ["ze6", "ze6", "nei5", "dik1", "gwaan1", "gu3"] },
            { chars: ["与", "及", "无", "偿", "的", "爱", "护"], jp: ["jyu5", "kap6", "mou4", "soeng4", "dik1", "ngoi3", "wu6"] },
            { chars: ["年", "月", "漫", "漫"], jp: ["nin4", "jyut6", "maan6", "maan6"] },
            { chars: ["多", "艰", "苦"], jp: ["do1", "gaan1", "fu2"] },
            { chars: ["你", "也", "永", "远", "优", "先", "担", "心", "我", "喜", "恶"], jp: ["nei5", "jaa5", "wing5", "jyun5", "jau1", "sin1", "daam1", "sam1", "ngo5", "hei2", "ok3"] },
            { chars: ["唯", "恐", "我", "并", "未", "得", "到"], jp: ["wai4", "hung2", "ngo5", "bing6", "mei6", "dak1", "dou3"] },
            { chars: ["最", "贴", "身", "保", "护"], jp: ["zeoi3", "tip3", "san1", "bou2", "wu6"] },
            { chars: ["O", "h", "I", "l", "o", "v", "e", "y", "o", "u"], jp: ["O", "h", "I", "l", "o", "v", "e", "y", "o", "u"] },
            { paragraphBreak: true },
            { chars: ["但", "是", "我", "知"], jp: ["daan6", "si6", "ngo5", "zi1"] },
            { chars: ["你", "都", "有", "梦"], jp: ["nei5", "dou1", "jau5", "mung6"] },
            { chars: ["仍", "将", "一", "生", "给", "我", "用"], jp: ["jing4", "zoeng1", "jat1", "sang1", "kap1", "ngo5", "jung6"] },
            { chars: ["全", "个", "世", "界"], jp: ["cyun4", "go3", "sai3", "gaai3"] },
            { chars: ["几", "多", "种"], jp: ["gei2", "do1", "zung2"] },
            { chars: ["爱", "与", "爱"], jp: ["ngoi3", "jyu5", "ngoi3"] },
            { chars: ["在", "互", "动"], jp: ["zoi6", "wu6", "dung6"] },
            { chars: ["也", "未", "及", "这", "种", "爱"], jp: ["jaa5", "mei6", "kap6", "ze5", "zung2", "ngoi3"] },
            { chars: ["能", "完", "全", "献", "奉"], jp: ["nang4", "jyun4", "cyun4", "hin3", "fung6"] },
            { paragraphBreak: true },
            { chars: ["Y", "o", "u", "m", "a", "k", "e", "m", "e", "c", "r", "y", "m", "a", "k", "e", "m", "e", "s", "m", "i", "l", "e"], jp: ["Y", "o", "u", "m", "a", "k", "e", "m", "e", "c", "r", "y", "m", "a", "k", "e", "m", "e", "s", "m", "i", "l", "e"] },
            { chars: ["M", "a", "k", "e", "m", "e", "f", "e", "e", "l", "t", "h", "e", "l", "o", "v", "e", "i", "s", "t", "r", "u", "e"], jp: ["M", "a", "k", "e", "m", "e", "f", "e", "e", "l", "t", "h", "e", "l", "o", "v", "e", "i", "s", "t", "r", "u", "e"] },
            { chars: ["谢", "谢", "你", "的", "关", "顾"], jp: ["ze6", "ze6", "nei5", "dik1", "gwaan1", "gu3"] },
            { chars: ["与", "及", "无", "偿", "的", "爱", "护"], jp: ["jyu5", "kap6", "mou4", "soeng4", "dik1", "ngoi3", "wu6"] },
            { chars: ["年", "月", "漫", "漫"], jp: ["nin4", "jyut6", "maan6", "maan6"] },
            { chars: ["多", "艰", "苦"], jp: ["do1", "gaan1", "fu2"] },
            { chars: ["你", "也", "永", "远", "优", "先", "担", "心", "我", "喜", "恶"], jp: ["nei5", "jaa5", "wing5", "jyun5", "jau1", "sin1", "daam1", "sam1", "ngo5", "hei2", "ok3"] },
            { chars: ["唯", "恐", "我", "并", "未", "得", "到"], jp: ["wai4", "hung2", "ngo5", "bing6", "mei6", "dak1", "dou3"] },
            { chars: ["最", "贴", "身", "保", "护"], jp: ["zeoi3", "tip3", "san1", "bou2", "wu6"] },
            { chars: ["O", "h", "I", "l", "o", "v", "e", "y", "o", "u"], jp: ["O", "h", "I", "l", "o", "v", "e", "y", "o", "u"] },
            { paragraphBreak: true },
            { chars: ["Y", "e", "s", "I", "d", "o", "　", "I", "a", "l", "w", "a", "y", "s", "d", "o"], jp: ["Y", "e", "s", "I", "d", "o", "", "I", "a", "l", "w", "a", "y", "s", "d", "o"] },
            { chars: ["M", "a", "k", "e", "m", "e", "c", "r", "y", "　", "M", "a", "k", "e", "m", "e", "s", "m", "i", "l", "e"], jp: ["M", "a", "k", "e", "m", "e", "c", "r", "y", "", "M", "a", "k", "e", "m", "e", "s", "m", "i", "l", "e"] },
            { chars: ["M", "a", "k", "e", "m", "e", "f", "e", "e", "l", "t", "h", "e", "l", "o", "v", "e", "i", "s", "t", "r", "u", "e"], jp: ["M", "a", "k", "e", "m", "e", "f", "e", "e", "l", "t", "h", "e", "l", "o", "v", "e", "i", "s", "t", "r", "u", "e"] },
            { chars: ["谢", "谢", "你", "的", "看", "顾"], jp: ["ze6", "ze6", "nei5", "dik1", "hon3", "gu3"] },
            { chars: ["与", "历", "年", "来", "的", "爱", "护"], jp: ["jyu5", "lik6", "nin4", "loi4", "dik1", "ngoi3", "wu6"] },
            { chars: ["年", "月", "漫", "漫"], jp: ["nin4", "jyut6", "maan6", "maan6"] },
            { chars: ["多", "艰", "苦"], jp: ["do1", "gaan1", "fu2"] },
            { chars: ["我", "再", "重", "也", "不", "肯", "抛", "低", "我", "不", "顾"], jp: ["ngo5", "zoi3", "cung5", "jaa5", "bat1", "hang2", "paau1", "dai1", "ngo5", "bat1", "gu3"] },
            { chars: ["从", "不", "会", "立", "下", "私", "心"], jp: ["cung4", "bat1", "wui6", "lap6", "haa6", "si1", "sam1"] },
            { chars: ["怕", "会", "给", "辜", "负"], jp: ["paa3", "wui6", "kap1", "gu1", "fu6"] },
            { chars: ["O", "h", "I", "l", "o", "v", "e", "y", "o", "u"], jp: ["O", "h", "I", "l", "o", "v", "e", "y", "o", "u"] },
            { chars: ["Y", "e", "s", "I", "l", "o", "v", "e", "y", "o", "u"], jp: ["Y", "e", "s", "I", "l", "o", "v", "e", "y", "o", "u"] },
            { chars: ["I", "a", "l", "w", "a", "y", "s", "d", "o"], jp: ["I", "a", "l", "w", "a", "y", "s", "d", "o"] }
        ]
    };
    if (typeof window !== 'undefined' && window.__songs) {
        window.__songs.push(song);
    }
})();
