// 歌曲：习惯失恋

(function() {
    const song = {
        id: 38,
        title: "习惯失恋",
        titleJyutping: ["zaap6","gwaan3","sat1","lyun2"],
        artist: "容祖儿",
        artistJyutping: ["jung4","zou2","ji4"],
        lyricist: "林夕",
        lyricistJyutping: ["lam4","zik6"],
        composer: "舒文",
        composerJyutping: ["syu1","man4"],
        lyrics: [
            { chars: ["不","拖","手"," ","或","者","都","可","堪","称","热","恋"], jp: ["bat1","to1","sau2","","waak6","ze2","dou1","ho2","ham1","cing1","jit6","lyun2"] },
            { chars: ["一","拖","手"," ","比","咳","嗽","更","短"], jp: ["jat1","to1","sau2","","bei2","kat1","sau3","gang1","dyun2"] },
            { chars: ["太","快","了"," ","我","未","快","乐","过","已","失","恋"], jp: ["taai3","faai3","liu5","","ngo5","mei6","faai3","lok6","gwo3","ji5","sat1","lyun2"] },
            { paragraphBreak: true },
            { chars: ["想","不","起"," ","被","爱","是","如","何","温","暖"], jp: ["soeng2","bat1","hei2","","bei6","ngoi3","si6","jyu4","ho4","wan1","nyun5"] },
            { chars: ["想","不","通"," ","未","够","资","格","使","你","心","软"], jp: ["soeng2","bat1","tung1","","mei6","gau3","zi1","gaak3","si2","nei5","sam1","jyun5"] },
            { chars: ["但","也","知","道","心","会","这","么","酸"], jp: ["daan6","jaa5","zi1","dou6","sam1","wui6","ze5","maa1","syun1"] },
            { paragraphBreak: true },
            { chars: ["理","所","当","然","我","的","错"], jp: ["lei5","so2","dong1","jin4","ngo5","dik1","co3"] },
            { chars: ["令","你","忽","然","离","开","半","路","留","下","我"], jp: ["ling6","nei5","fat1","jin4","lei4","hoi1","bun3","lou6","lau4","haa6","ngo5"] },
            { chars: ["为","何","这","么","快","看","清","楚"," ","落","得","这","结","果"], jp: ["wai4","ho4","ze5","maa1","faai3","hon3","cing1","co2","","lok6","dak1","ze5","git3","gwo2"] },
            { paragraphBreak: true },
            { chars: ["知","我","是","个","无","法","讨","好","的","人"], jp: ["zi1","ngo5","si6","go3","mou4","faat3","tou2","hou2","dik1","jan4"] },
            { chars: ["相","恋","一","刻","只","是","我","的","侥","幸"], jp: ["soeng1","lyun2","jat1","hak1","zi2","si6","ngo5","dik1","hiu1","hang6"] },
            { chars: ["然","而","回","头","诚","实","去","自","问"], jp: ["jin4","ji4","wui4","tau4","sing4","sat6","heoi3","zi6","man6"] },
            { chars: ["我","可","讨","厌","到","如","此","乞","你","憎"], jp: ["ngo5","ho2","tou2","jim3","dou3","jyu4","ci2","hat1","nei5","zang1"] },
            { chars: ["知","我","连","眼","泪","也","绝","不","感","人"], jp: ["zi1","ngo5","lin4","ngaan5","leoi6","jaa5","zyut6","bat1","gam2","jan4"] },
            { chars: ["只","知","怎","么","考","验","你","的","操","行"], jp: ["zi2","zi1","zam2","maa1","haau2","jim6","nei5","dik1","cou1","hang4"] },
            { chars: ["从","前","为","何","缠","在","你","附","近"], jp: ["cung4","cin4","wai4","ho4","cin4","zoi6","nei5","fu6","gan6"] },
            { chars: ["你","不","寂","寞","便","嫌","我","笨"], jp: ["nei5","bat1","zik6","mok6","bin6","jim4","ngo5","ban6"] },
            { chars: ["难","道","我","未","够","好","未","懂","得","热","吻"], jp: ["naan4","dou6","ngo5","mei6","gau3","hou2","mei6","dung2","dak1","jit6","man5"] },
            { chars: ["足","够","令","你","怜","悯"," ","勾","不","起","你","的","兴","奋"], jp: ["zuk1","gau3","ling6","nei5","lin4","man5","","ngau1","bat1","hei2","nei5","dik1","hing1","fan5"] },
            { paragraphBreak: true },
            { chars: ["不","担","心"," ","自","尊","心","这","么","受","损"], jp: ["bat1","daam1","sam1","","zi6","zyun1","sam1","ze5","maa1","sau6","syun2"] },
            { chars: ["只","担","心"," ","我","将","我","看","穿"], jp: ["zi2","daam1","sam1","","ngo5","zoeng1","ngo5","hon3","cyun1"] },
            { chars: ["我","怕","我"," ","以","后","太","习","惯","了","失","恋"], jp: ["ngo5","paa3","ngo5","","ji5","hau6","taai3","zaap6","gwaan3","liu5","sat1","lyun2"] },
            { paragraphBreak: true },
            { chars: ["理","所","当","然","我","的","错"], jp: ["lei5","so2","dong1","jin4","ngo5","dik1","co3"] },
            { chars: ["令","你","忽","然","离","开","也","是","我","错","么"], jp: ["ling6","nei5","fat1","jin4","lei4","hoi1","jaa5","si6","ngo5","co3","maa1"] },
            { chars: ["为","何","这","么","快","看","清","楚"," ","落","得","这","结","果"], jp: ["wai4","ho4","ze5","maa1","faai3","hon3","cing1","co2","","lok6","dak1","ze5","git3","gwo2"] },
            { paragraphBreak: true },
            { chars: ["知","我","是","个","无","法","讨","好","的","人"], jp: ["zi1","ngo5","si6","go3","mou4","faat3","tou2","hou2","dik1","jan4"] },
            { chars: ["相","恋","一","刻","只","是","我","的","侥","幸"], jp: ["soeng1","lyun2","jat1","hak1","zi2","si6","ngo5","dik1","hiu1","hang6"] },
            { chars: ["然","而","回","头","诚","实","去","自","问"], jp: ["jin4","ji4","wui4","tau4","sing4","sat6","heoi3","zi6","man6"] },
            { chars: ["我","可","讨","厌","到","如","此","乞","你","憎"], jp: ["ngo5","ho2","tou2","jim3","dou3","jyu4","ci2","hat1","nei5","zang1"] },
            { chars: ["知","我","连","眼","泪","也","绝","不","感","人"], jp: ["zi1","ngo5","lin4","ngaan5","leoi6","jaa5","zyut6","bat1","gam2","jan4"] },
            { chars: ["只","知","怎","么","考","验","你","的","操","行"], jp: ["zi2","zi1","zam2","maa1","haau2","jim6","nei5","dik1","cou1","hang4"] },
            { chars: ["从","前","为","何","缠","在","你","附","近"], jp: ["cung4","cin4","wai4","ho4","cin4","zoi6","nei5","fu6","gan6"] },
            { chars: ["更","加","速","发","觉","原","本","都","不","相","衬"], jp: ["gang1","gaa1","cuk1","faat3","gok3","jyun4","bun2","dou1","bat1","soeng1","can3"] },
            { chars: ["我","未","够","吸","引"," ","你","未","够","狠"], jp: ["ngo5","mei6","gau3","kap1","jan5","","nei5","mei6","gau3","han2"] },
            { paragraphBreak: true },
            { chars: ["知","我","是","个","无","法","讨","好","的","人"], jp: ["zi1","ngo5","si6","go3","mou4","faat3","tou2","hou2","dik1","jan4"] },
            { chars: ["相","恋","一","刻","只","是","我","的","侥","幸"], jp: ["soeng1","lyun2","jat1","hak1","zi2","si6","ngo5","dik1","hiu1","hang6"] },
            { chars: ["然","而","回","头","诚","实","去","自","问"], jp: ["jin4","ji4","wui4","tau4","sing4","sat6","heoi3","zi6","man6"] },
            { chars: ["我","可","讨","厌","到","如","此","乞","你","憎"], jp: ["ngo5","ho2","tou2","jim3","dou3","jyu4","ci2","hat1","nei5","zang1"] },
            { chars: ["知","我","连","眼","泪","也","绝","不","感","人"], jp: ["zi1","ngo5","lin4","ngaan5","leoi6","jaa5","zyut6","bat1","gam2","jan4"] },
            { chars: ["只","知","怎","么","考","验","你","的","操","行"], jp: ["zi2","zi1","zam2","maa1","haau2","jim6","nei5","dik1","cou1","hang4"] },
            { chars: ["从","前","为","何","缠","在","你","附","近"], jp: ["cung4","cin4","wai4","ho4","cin4","zoi6","nei5","fu6","gan6"] },
            { chars: ["到","底","这","个","故","事"," ","有","没","有","发","生"], jp: ["dou3","dai2","ze5","go3","gu3","si6","","jau5","mut6","jau5","faat3","sang1"] },
            { paragraphBreak: true },
            { chars: ["何","必","受","罪"," ","心","即","使","碎","一","碎"], jp: ["ho4","bit1","sau6","zeoi6","","sam1","zik1","si2","seoi3","jat1","seoi3"] },
            { chars: ["我","仍","能"," ","继","续","追"], jp: ["ngo5","jing4","nang4","","gai3","zuk6","zeoi1"] },
            { chars: ["愿", "那", "一", "刻", "共", "聚", " ", "懂", "得", "怎", "去", "相", "爱"], jp: ["jyun6", "naa5", "jat1", "hak1", "gung6", "zeoi6", "", "dung2", "dak1", "zam2", "heoi3", "soeng1", "ngoi3"] },
            { chars: ["爱","人","难"," ","我","肯","学"," ","定","能","爱","下","去"], jp: ["ngoi3","jan4","naan4","","ngo5","hang2","hok6","","ding6","nang4","ngoi3","haa6","heoi3"] }
        ]
    };
    if (typeof window !== 'undefined' && window.__songs) {
        window.__songs.push(song);
    }
})();
