// 歌曲：假如让我说下去

(function() {
    const song = {
        id: 329,
        title: "假如让我说下去",
        titleJyutping: ["gaa2","jyu4","joeng6","ngo5","syut3","haa6","heoi3"],
        artist: "杨千嬅",
        artistJyutping: ["joeng4","cin1","waa6"],
        lyricist: "林夕",
        lyricistJyutping: ["lam4","zik6"],
        composer: "于逸尧",
        composerJyutping: ["jyu1","jat6","jiu4"],
        lyrics: [
            { chars: ["任","我","想"], jp: ["jam6","ngo5","soeng2"] },
            { chars: ["我","最","多","想","一","觉","睡","去"], jp: ["ngo5","zeoi3","do1","soeng2","jat1","gok3","seoi6","heoi3"] },
            { chars: ["期","待","你"], jp: ["kei4","doi6","nei5"] },
            { chars: ["也","至","少","劝","我","别","劳","累"], jp: ["jaa5","zi3","siu2","hyun3","ngo5","bit6","lou4","leoi6"] },
            { chars: ["但","我","把"], jp: ["daan6","ngo5","baa2"] },
            { chars: ["谈","情","的","气","力","转","赠","谁"], jp: ["taam4","cing4","dik1","hei3","lik6","zyun2","zang6","seoi4"] },
            { chars: ["跟","你","电","话","之","中","讲","再","会"], jp: ["gan1","nei5","din6","waa6","zi1","zung1","gong2","zoi3","wui6"] },
            { chars: ["再","会","谁"], jp: ["zoi3","wui6","seoi4"] },
            { paragraphBreak: true },
            { chars: ["暴","雨","天"], jp: ["bou6","jyu5","tin1"] },
            { chars: ["我","至","少","想","讲","挂","念","你"], jp: ["ngo5","zi3","siu2","soeng2","gong2","gwaa3","nim6","nei5"] },
            { chars: ["然","后","你"], jp: ["jin4","hau6","nei5"] },
            { chars: ["你","最","多","会","笑","着","回","避"], jp: ["nei5","zeoi3","do1","wui6","siu3","zoek6","wui4","bei6"] },
            { chars: ["避","到","底"], jp: ["bei6","dou3","dai2"] },
            { chars: ["明", "明", "不", "筋", "竭", "都", "力", "疲"], jp: ["ming4", "ming4", "bat1", "gan1", "kit3", "dou1", "lik6", "pei4"] },
            { chars: ["就","当","我","还","未","放","松","自","己"], jp: ["zau6","dong1","ngo5","waan4","mei6","fong3","cung4","zi6","gei2"] },
            { paragraphBreak: true },
            { chars: ["我","想","哭"], jp: ["ngo5","soeng2","huk1"] },
            { chars: ["你","可","不","可","以","暂","时","别","要","睡"], jp: ["nei5","ho2","bat1","ho2","ji5","zaam6","si4","bit6","jiu3","seoi6"] },
            { chars: ["陪","着","我"], jp: ["pui4","zoek6","ngo5"] },
            { chars: ["像","最","初","相","识","我","当","时","未","怕","累"], jp: ["zoeng6","zeoi3","co1","soeng1","sik1","ngo5","dong1","si4","mei6","paa3","leoi6"] },
            { chars: ["但","如","果"], jp: ["daan6","jyu4","gwo2"] },
            { chars: ["但","如","果","说","下","去"], jp: ["daan6","jyu4","gwo2","syut3","haa6","heoi3"] },
            { chars: ["或","者","　","傻","得","我"], jp: ["waak6","ze2","","so4","dak1","ngo5"] },
            { chars: ["彼","此","怎","能","爱","下","去"], jp: ["bei2","ci2","zam2","nang4","ngoi3","haa6","heoi3"] },
            { paragraphBreak: true },
            { chars: ["暴","雨","中"], jp: ["bou6","jyu5","zung1"] },
            { chars: ["我","到","底","怎","么","要","害","怕"], jp: ["ngo5","dou3","dai2","zam2","maa1","jiu3","hoi6","paa3"] },
            { chars: ["难","道","你"], jp: ["naan4","dou6","nei5"] },
            { chars: ["无","台","风","会","决","定","留","下"], jp: ["mou4","toi4","fung1","wui6","kyut3","ding6","lau4","haa6"] },
            { chars: ["但","我","想"], jp: ["daan6","ngo5","soeng2"] },
            { chars: ["如","楼","底","这","夜","倒","下","来"], jp: ["jyu4","lau4","dai2","ze5","je6","dou2","haa6","loi4"] },
            { chars: ["就","算","临","别","亦","有","通","电","话"], jp: ["zau6","syun3","lam4","bit6","jik6","jau5","tung1","din6","waa6"] },
            { paragraphBreak: true },
            { chars: ["我","怕","死"], jp: ["ngo5","paa3","sei2"] },
            { chars: ["你","可","不","可","以","暂","时","别","要","睡"], jp: ["nei5","ho2","bat1","ho2","ji5","zaam6","si4","bit6","jiu3","seoi6"] },
            { chars: ["陪","着","我"], jp: ["pui4","zoek6","ngo5"] },
            { chars: ["让","我","可","以","不","靠","安","眠","药","进","睡"], jp: ["joeng6","ngo5","ho2","ji5","bat1","kaau3","on1","min4","joek6","zeon3","seoi6"] },
            { chars: ["但","如","果"], jp: ["daan6","jyu4","gwo2"] },
            { chars: ["但","如","果","说","下","去"], jp: ["daan6","jyu4","gwo2","syut3","haa6","heoi3"] },
            { chars: ["亦","无","非","逼","你"], jp: ["jik6","mou4","fei1","bik1","nei5"] },
            { chars: ["一","句","话"], jp: ["jat1","geoi3","waa6"] },
            { chars: ["如","今","跟","某","位","同","居"], jp: ["jyu4","gam1","gan1","mau5","wai6","tung4","geoi1"] },
            { paragraphBreak: true },
            { chars: ["我","的","天"], jp: ["ngo5","dik1","tin1"] },
            { chars: ["你","可","不","可","以","暂","时","让","我","睡"], jp: ["nei5","ho2","bat1","ho2","ji5","zaam6","si4","joeng6","ngo5","seoi6"] },
            { chars: ["忘","掉","爱"], jp: ["mong4","diu6","ngoi3"] },
            { chars: ["尚","有","多","少","工","作","失","眠","亦","有","罪"], jp: ["soeng6","jau5","do1","siu2","gung1","zok3","sat1","min4","jik6","jau5","zeoi6"] },
            { chars: ["但","如","果"], jp: ["daan6","jyu4","gwo2"] },
            { chars: ["但","如","果","怨","下","去"], jp: ["daan6","jyu4","gwo2","jyun3","haa6","heoi3"] },
            { chars: ["或","者","　","傻","得","我"], jp: ["waak6","ze2","","so4","dak1","ngo5"] },
            { chars: ["通","宵","找","谁","接","下","去"], jp: ["tung1","siu1","zaau2","seoi4","zip3","haa6","heoi3"] },
            { paragraphBreak: true },
            { chars: ["离","开","　","不","应","再","打","搅","爱","人"], jp: ["lei4","hoi1","","bat1","jing3","zoi3","daa2","gaau2","ngoi3","jan4"] },
            { chars: ["对","不","对"], jp: ["deoi3","bat1","deoi3"] }
        ]
    };
    if (typeof window !== 'undefined' && window.__songs) {
        window.__songs.push(song);
    }
})();
