// 歌曲：再见二丁目

(function() {
    const song = {
        id: 359,
        title: "再见二丁目",
        titleJyutping: ["zoi3","gin3","ji6","ding1","muk6"],
        artist: "杨千嬅",
        artistJyutping: ["joeng4","cin1","waa6"],
        lyricist: "林夕",
        lyricistJyutping: ["lam4","zik6"],
        composer: "于逸尧",
        composerJyutping: ["jyu1","jat6","jiu4"],
        lyrics: [
            { chars: ["满","街","脚","步"], jp: ["mun5","gaai1","goek3","bou6"] },
            { chars: ["突","然","静","了"], jp: ["dat6","jin4","zing6","liu5"] },
            { chars: ["满","天","柏","树"], jp: ["mun5","tin1","paak3","syu6"] },
            { chars: ["突","然","没","有","动","摇"], jp: ["dat6","jin4","mut6","jau5","dung6","jiu4"] },
            { chars: ["这","一","刹"], jp: ["ze5","jat1","caat3"] },
            { chars: ["我","只","需","要"], jp: ["ngo5","zi2","seoi1","jiu3"] },
            { chars: ["一","罐","热","茶","吧"], jp: ["jat1","gun3","jit6","caa4","baa6"] },
            { chars: ["那","味","道"], jp: ["naa5","mei6","dou6"] },
            { chars: ["似","是","什","么"], jp: ["ci5","si6","sap6","maa1"] },
            { chars: ["都","不","紧","要"], jp: ["dou1","bat1","gan2","jiu3"] },
            { paragraphBreak: true },
            { chars: ["唱","片","店","内"], jp: ["coeng3","pin3","dim3","noi6"] },
            { chars: ["传","来","异","国","民","谣"], jp: ["cyun4","loi4","ji6","gwok3","man4","jiu4"] },
            { chars: ["那","种","快","乐"], jp: ["naa5","zung2","faai3","lok6"] },
            { chars: ["突","然","被","我","需","要"], jp: ["dat6","jin4","bei6","ngo5","seoi1","jiu3"] },
            { chars: ["不","亲","切"], jp: ["bat1","can1","cit3"] },
            { chars: ["至","少","不","似"], jp: ["zi3","siu2","bat1","ci5"] },
            { chars: ["想","你","般","奥","妙"], jp: ["soeng2","nei5","bun1","ou3","miu6"] },
            { chars: ["情","和","调"], jp: ["cing4","wo4","diu6"] },
            { chars: ["随","著","怀","缅"], jp: ["ceoi4","zyu3","waai4","min5"] },
            { chars: ["变","得","萧","条"], jp: ["bin3","dak1","siu1","tiu4"] },
            { paragraphBreak: true },
            { chars: ["原","来","过","得","很","快","乐"], jp: ["jyun4","loi4","gwo3","dak1","han2","faai3","lok6"] },
            { chars: ["只","我","一","人","未","发","觉"], jp: ["zi2","ngo5","jat1","jan4","mei6","faat3","gok3"] },
            { chars: ["如","能","忘","掉","渴","望"], jp: ["jyu4","nang4","mong4","diu6","hot3","mong6"] },
            { chars: ["岁","月","长"], jp: ["seoi3","jyut6","coeng4"] },
            { chars: ["衣","裳","薄"], jp: ["ji1","soeng4","bok6"] },
            { chars: ["无","论","于","什","么","角","落"], jp: ["mou4","leon6","jyu1","sap6","maa1","gok3","lok6"] },
            { chars: ["不","假","设","你","或","会","在","旁"], jp: ["bat1","gaa2","cit3","nei5","waak6","wui6","zoi6","pong4"] },
            { chars: ["我","也","可","畅","游","异","国"], jp: ["ngo5","jaa5","ho2","coeng3","jau4","ji6","gwok3"] },
            { chars: ["放","心","吃","喝"], jp: ["fong3","sam1","hek3","hot3"] },
            { paragraphBreak: true },
            { chars: ["转","街","过","巷"], jp: ["zyun2","gaai1","gwo3","hong6"] },
            { chars: ["就","如","滑","过","浪","潮"], jp: ["zau6","jyu4","waat6","gwo3","long6","ciu4"] },
            { chars: ["听","天","说","地"], jp: ["ting1","tin1","syut3","dei6"] },
            { chars: ["仍","然","剩","我","心","跳"], jp: ["jing4","jin4","sing6","ngo5","sam1","tiu3"] },
            { chars: ["关","于","你"], jp: ["gwaan1","jyu1","nei5"] },
            { chars: ["冥","想","不","了"], jp: ["ming4","soeng2","bat1","liu5"] },
            { chars: ["可","免","都","免","掉"], jp: ["ho2","min5","dou1","min5","diu6"] },
            { chars: ["情","和","欲"], jp: ["cing4","wo4","juk6"] },
            { chars: ["留","待","下","个","化","身","燃","烧"], jp: ["lau4","doi6","haa6","go3","faa3","san1","jin4","siu1"] },
            { paragraphBreak: true },
            { chars: ["原","来","过","得","很","快","乐"], jp: ["jyun4","loi4","gwo3","dak1","han2","faai3","lok6"] },
            { chars: ["只","我","一","人","未","发","觉"], jp: ["zi2","ngo5","jat1","jan4","mei6","faat3","gok3"] },
            { chars: ["如","能","忘","掉","渴","望"], jp: ["jyu4","nang4","mong4","diu6","hot3","mong6"] },
            { chars: ["岁","月","长"], jp: ["seoi3","jyut6","coeng4"] },
            { chars: ["衣","裳","薄"], jp: ["ji1","soeng4","bok6"] },
            { chars: ["无","论","于","什","么","角","落"], jp: ["mou4","leon6","jyu1","sap6","maa1","gok3","lok6"] },
            { chars: ["不","假","设","你","或","会","在","旁"], jp: ["bat1","gaa2","cit3","nei5","waak6","wui6","zoi6","pong4"] },
            { chars: ["我","也","可","畅","游","异","国"], jp: ["ngo5","jaa5","ho2","coeng3","jau4","ji6","gwok3"] },
            { chars: ["放","心","吃","喝"], jp: ["fong3","sam1","hek3","hot3"] },
            { paragraphBreak: true },
            { chars: ["原","来","我","非","不","快","乐"], jp: ["jyun4","loi4","ngo5","fei1","bat1","faai3","lok6"] },
            { chars: ["只","我","一","人","未","发","觉"], jp: ["zi2","ngo5","jat1","jan4","mei6","faat3","gok3"] },
            { chars: ["如","能","忘","掉","渴","望"], jp: ["jyu4","nang4","mong4","diu6","hot3","mong6"] },
            { chars: ["岁","月","长"], jp: ["seoi3","jyut6","coeng4"] },
            { chars: ["衣","裳","薄"], jp: ["ji1","soeng4","bok6"] },
            { chars: ["无","论","于","什","么","角","落"], jp: ["mou4","leon6","jyu1","sap6","maa1","gok3","lok6"] },
            { chars: ["不","假","设","你","或","会","在","旁"], jp: ["bat1","gaa2","cit3","nei5","waak6","wui6","zoi6","pong4"] },
            { chars: ["我","也","可","畅","游","异","国"], jp: ["ngo5","jaa5","ho2","coeng3","jau4","ji6","gwok3"] },
            { chars: ["再","找","记","托"], jp: ["zoi3","zaau2","gei3","tok3"] },
            { chars: ["我","也","可","畅","游","异","国"], jp: ["ngo5","jaa5","ho2","coeng3","jau4","ji6","gwok3"] },
            { chars: ["再","找","记","托"], jp: ["zoi3","zaau2","gei3","tok3"] }
        ]
    };
    if (typeof window !== 'undefined' && window.__songs) {
        window.__songs.push(song);
    }
})();
