// 歌曲：冰点

(function() {
    const song = {
        id: 383,
        title: "冰点",
        titleJyutping: ["bing1","dim2"],
        artist: "杨千嬅",
        artistJyutping: ["joeng4","cin1","waa6"],
        lyricist: "林夕",
        lyricistJyutping: ["lam4","zik6"],
        composer: "于逸尧",
        composerJyutping: ["jyu1","jat6","jiu4"],
        lyrics: [
            { chars: ["有","心","散","心"], jp: ["jau5","sam1","saan3","sam1"] },
            { chars: ["当","心","跳","不","再","受","控"], jp: ["dong1","sam1","tiu3","bat1","zoi3","sau6","hung3"] },
            { chars: ["面","前","有","风","听","风"], jp: ["min6","cin4","jau5","fung1","ting1","fung1"] },
            { chars: ["沉","默","得","响","起","暗","涌"], jp: ["cam4","mak6","dak1","hoeng2","hei2","am3","cung1"] },
            { chars: ["我","知","我","蠢"], jp: ["ngo5","zi1","ngo5","ceon2"] },
            { chars: ["还","未","听","懂"], jp: ["waan4","mei6","ting1","dung2"] },
            { chars: ["你","说","分","手","的","震","动"], jp: ["nei5","syut3","fan1","sau2","dik1","zan3","dung6"] },
            { chars: ["曾","令","视","野","灰","朦"], jp: ["zang1","ling6","si6","je5","fui1","mung4"] },
            { chars: ["却","不","忘","那","天","很","冻"], jp: ["koek3","bat1","mong4","naa5","tin1","han2","dung3"] },
            { paragraphBreak: true },
            { chars: ["何","谓","冻"], jp: ["ho4","wai6","dung3"] },
            { chars: ["趁","冰","点","时","份","止","步"], jp: ["can3","bing1","dim2","si4","fan6","zi2","bou6"] },
            { chars: ["其","实","冻"], jp: ["kei4","sat6","dung3"] },
            { chars: ["冻","不","过","那","条","路"], jp: ["dung3","bat1","gwo3","naa5","tiu4","lou6"] },
            { chars: ["赤","裸","裸","感","到"], jp: ["cek3","lo2","lo2","gam2","dou3"] },
            { chars: ["做","过","的","不","可","再","做"], jp: ["zou6","gwo3","dik1","bat1","ho2","zoi3","zou6"] },
            { chars: ["如","异","国","境","迁","谁","可","为","谁","弥","补"], jp: ["jyu4","ji6","gwok3","ging2","cin1","seoi4","ho2","wai4","seoi4","nei4","bou2"] },
            { chars: ["后","悔","我","没","有","阻","挡","你","去","路"], jp: ["hau6","fui3","ngo5","mut6","jau5","zo2","dong2","nei5","heoi3","lou6"] },
            { chars: ["还","未","知","道"], jp: ["waan4","mei6","zi1","dou6"] },
            { chars: ["风","雪","会","真","的","飞","舞"], jp: ["fung1","syut3","wui6","zan1","dik1","fei1","mou5"] },
            { chars: ["如","下","次","再","见"], jp: ["jyu4","haa6","ci3","zoi3","gin3"] },
            { chars: ["眉","毛","有","多","少","给","我","数"], jp: ["mei4","mou4","jau5","do1","siu2","kap1","ngo5","sou3"] },
            { paragraphBreak: true },
            { chars: ["有","花","看","花"], jp: ["jau5","faa1","hon3","faa1"] },
            { chars: ["零","度","之","中"], jp: ["ling4","dou6","zi1","zung1"] },
            { chars: ["难","道","等","樱","花","染","红"], jp: ["naan4","dou6","dang2","jing1","faa1","jim5","hung4"] },
            { chars: ["曾","冒","过","雪","的","人"], jp: ["zang1","mou6","gwo3","syut3","dik1","jan4"] },
            { chars: ["也","知","融","雪","怎","么","冻"], jp: ["jaa5","zi1","jung4","syut3","zam2","maa1","dung3"] },
            { paragraphBreak: true },
            { chars: ["何","谓","冻"], jp: ["ho4","wai6","dung3"] },
            { chars: ["趁","冰","点","时","分","止","步"], jp: ["can3","bing1","dim2","si4","fan1","zi2","bou6"] },
            { chars: ["其","实","冻"], jp: ["kei4","sat6","dung3"] },
            { chars: ["冻","不","过","那","条","路"], jp: ["dung3","bat1","gwo3","naa5","tiu4","lou6"] },
            { chars: ["赤","裸","裸","感","到"], jp: ["cek3","lo2","lo2","gam2","dou3"] },
            { chars: ["做","过","的","不","可","再","做"], jp: ["zou6","gwo3","dik1","bat1","ho2","zoi3","zou6"] },
            { chars: ["如","异","国","境","迁","谁","可","为","谁","弥","补"], jp: ["jyu4","ji6","gwok3","ging2","cin1","seoi4","ho2","wai4","seoi4","nei4","bou2"] },
            { chars: ["后","悔","我","没","有","阻","挡","你","去","路"], jp: ["hau6","fui3","ngo5","mut6","jau5","zo2","dong2","nei5","heoi3","lou6"] },
            { chars: ["还","未","知","道"], jp: ["waan4","mei6","zi1","dou6"] },
            { chars: ["风","雪","会","真","的","飞","舞"], jp: ["fung1","syut3","wui6","zan1","dik1","fei1","mou5"] },
            { chars: ["如","下","次","再","见"], jp: ["jyu4","haa6","ci3","zoi3","gin3"] },
            { chars: ["眉","毛","有","多","少","给","我","数"], jp: ["mei4","mou4","jau5","do1","siu2","kap1","ngo5","sou3"] },
            { paragraphBreak: true },
            { chars: ["后","悔","我","没","有","加","速","我","脚","步"], jp: ["hau6","fui3","ngo5","mut6","jau5","gaa1","cuk1","ngo5","goek3","bou6"] },
            { chars: ["还","未","肯","相","信","你"], jp: ["waan4","mei6","hang2","soeng1","seon3","nei5"] },
            { chars: ["经","不","起","苍","老"], jp: ["ging1","bat1","hei2","cong1","lou5"] },
            { chars: ["如","下","次","碰","见"], jp: ["jyu4","haa6","ci3","pung3","gin3"] },
            { chars: ["想","却","步"], jp: ["soeng2","koek3","bou6"] },
            { chars: ["不","要","紧"], jp: ["bat1","jiu3","gan2"] },
            { chars: ["抱","一","抱"], jp: ["pou5","jat1","pou5"] }
        ]
    };
    if (typeof window !== 'undefined' && window.__songs) {
        window.__songs.push(song);
    }
})();
