// 歌曲：千千阙歌

(function() {
    const song =     {
        id: 6,
        title: "千千阙歌",
        titleJyutping: ["cin1","cin1","kyut3","go1"],
        artist: "陈慧娴",
        artistJyutping: ["can4","wai6","haan4"],
        lyricist: "林振强",
        lyricistJyutping: ["lam4","zan3","koeng4"],
        composer: "Makaino Koji",
        composerJyutping: ["m","a","k","a","i","n","o","","k","o","j","i"],
        lyrics: [
            { chars: ["徐","徐","回","望"," ","曾","属","于","彼","此","的","晚","上"], jp: ["ceoi4","ceoi4","wui4","mong6","","cang4","suk6","jyu1","bei2","ci2","dik1","maan5","soeng6"] },
            { chars: ["红","红","仍","是","你"," ","赠","我","的","心","中","艳","阳"], jp: ["hung4","hung4","jing4","si6","nei5","","zang6","ngo5","dik1","sam1","zung1","jim6","joeng4"] },
            { chars: ["如","流","傻","泪"," ","祈","望","可","体","恤","兼","见","谅"], jp: ["jyu4","lau4","so4","leoi6","","kei4","mong6","ho2","tai2","seot1","gim1","gin3","loeng6"] },
            { chars: ["明","晨","离","别","你"," ","路","也","许","孤","单","得","漫","长"], jp: ["ming4","san4","lei4","bit6","nei5","","lou6","jaa5","heoi2","gu1","daan1","dak1","maan6","coeng4"] },
            { paragraphBreak: true },
            { chars: ["一","瞬","间"," ","太","多","东","西","要","讲"], jp: ["jat1","seon3","gaan1","","taai3","do1","dung1","sai1","jiu3","gong2"] },
            { chars: ["可","惜","即","将","在","各","一","方"], jp: ["ho2","sik1","zik1","zoeng1","zoi6","gok3","jat1","fong1"] },
            { chars: ["只","好","深","深","把","这","刻","尽","凝","望"], jp: ["zi2","hou2","sam1","sam1","baa2","ze5","hak1","zeon6","jing4","mong6"] },
            { paragraphBreak: true },
            { chars: ["来","日","纵","使","千","千","阙","歌"], jp: ["loi4","jat6","zung3","si2","cin1","cin1","kyut3","go1"] },
            { chars: ["飘","于","远","方","我","路","上"], jp: ["piu1","jyu1","jyun5","fong1","ngo5","lou6","soeng6"] },
            { chars: ["来","日","纵","使","千","千","晚","星"], jp: ["loi4","jat6","zung3","si2","cin1","cin1","maan5","sing1"] },
            { chars: ["亮","过","今","晚","月","亮"], jp: ["loeng6","gwo3","gam1","maan5","jyut6","loeng6"] },
            { chars: ["都","比","不","起","这","宵","美","丽"], jp: ["dou1","bei2","bat1","hei2","ze5","siu1","mei5","lai6"] },
            { chars: ["亦","绝","不","可","使","我","更","欣","赏"], jp: ["jik6","zyut6","bat1","ho2","si2","ngo5","gang3","jan1","soeng2"] },
            { chars: ["Ah"," ","因","你","今","晚","共","我","唱"], jp: ["Ah","","jan1","nei5","gam1","maan5","gung6","ngo5","coeng3"] },
            { paragraphBreak: true },
            { chars: ["临","行","临","别"," ","才","顿","感","哀","伤","的","漂","亮"], jp: ["lam4","hang4","lam4","bit6","","coi4","deon6","gam2","oi1","soeng1","dik1","piu1","loeng6"] },
            { chars: ["原","来","全","是","你"," ","令","我","的","思","忆","漫","长"], jp: ["jyun4","loi4","cyun4","si6","nei5","","ling6","ngo5","dik1","si1","jik1","maan6","coeng4"] },
            { chars: ["何","年","何","月"," ","才","又","可","今","宵","一","样"], jp: ["ho4","nin4","ho4","jyut6","","coi4","jau6","ho2","gam1","siu1","jat1","joeng6"] },
            { chars: ["停","留","凝","望","里"," ","让","眼","睛","讲","彼","此","立","场"], jp: ["ting4","lau4","jing4","mong6","leoi5","","joeng6","ngaan5","zeng1","gong2","bei2","ci2","lap6","coeng4"] },
            { paragraphBreak: true },
            { chars: ["当","某","天"," ","雨","点","轻","敲","你","窗"], jp: ["dong1","mau5","tin1","","jyu5","dim2","hing1","haau1","nei5","coeng1"] },
            { chars: ["当","风","声","吹","乱","你","构","想"], jp: ["dong1","fung1","seng1","ceoi1","lyun6","nei5","kau3","soeng2"] },
            { chars: ["可","否","抽","空","想","这","张","旧","模","样"], jp: ["ho2","fau2","cau1","hung1","soeng2","ze5","zoeng1","gau6","mou4","joeng6"] },
            { paragraphBreak: true },
            { chars: ["来","日","纵","使","千","千","阙","歌"], jp: ["loi4","jat6","zung3","si2","cin1","cin1","kyut3","go1"] },
            { chars: ["飘","于","远","方","我","路","上"], jp: ["piu1","jyu1","jyun5","fong1","ngo5","lou6","soeng6"] },
            { chars: ["来","日","纵","使","千","千","晚","星"], jp: ["loi4","jat6","zung3","si2","cin1","cin1","maan5","sing1"] },
            { chars: ["亮","过","今","晚","月","亮"], jp: ["loeng6","gwo3","gam1","maan5","jyut6","loeng6"] },
            { chars: ["都","比","不","起","这","宵","美","丽"], jp: ["dou1","bei2","bat1","hei2","ze5","siu1","mei5","lai6"] },
            { chars: ["亦","绝","不","可","使","我","更","欣","赏"], jp: ["jik6","zyut6","bat1","ho2","si2","ngo5","gang3","jan1","soeng2"] },
            { chars: ["Ah"," ","因","你","今","晚","共","我","唱"], jp: ["Ah","","jan1","nei5","gam1","maan5","gung6","ngo5","coeng3"] },
            { paragraphBreak: true },
            { chars: ["Ah"," ","怎","都","比","不","起","这","宵","美","丽"], jp: ["Ah","","zam2","dou1","bei2","bat1","hei2","ze5","siu1","mei5","lai6"] },
            { chars: ["亦","绝","不","可","使","我","更","欣","赏"], jp: ["jik6","zyut6","bat1","ho2","si2","ngo5","gang3","jan1","soeng2"] },
            { chars: ["因","今","宵","的","我","可","共","你","唱"], jp: ["jan1","gam1","siu1","dik1","ngo5","ho2","gung6","nei5","coeng3"] },
            { paragraphBreak: true },
            { chars: ["来","日","纵","使","千","千","阙","歌"], jp: ["loi4","jat6","zung3","si2","cin1","cin1","kyut3","go1"] },
            { chars: ["飘","于","远","方","我","路","上"], jp: ["piu1","jyu1","jyun5","fong1","ngo5","lou6","soeng6"] },
            { chars: ["来","日","纵","使","千","千","晚","星"], jp: ["loi4","jat6","zung3","si2","cin1","cin1","maan5","sing1"] },
            { chars: ["亮","过","今","晚","月","亮"], jp: ["loeng6","gwo3","gam1","maan5","jyut6","loeng6"] },
            { chars: ["都","比","不","起","这","宵","美","丽"], jp: ["dou1","bei2","bat1","hei2","ze5","siu1","mei5","lai6"] },
            { chars: ["亦","绝","不","可","使","我","更","欣","赏"], jp: ["jik6","zyut6","bat1","ho2","si2","ngo5","gang3","jan1","soeng2"] },
            { chars: ["Ah"," ","因","你","今","晚","共","我","唱"], jp: ["Ah","","jan1","nei5","gam1","maan5","gung6","ngo5","coeng3"] },
            { paragraphBreak: true },
            { chars: ["来","日","纵","使","千","千","阙","歌"], jp: ["loi4","jat6","zung3","si2","cin1","cin1","kyut3","go1"] },
            { chars: ["飘","于","远","方","我","路","上"], jp: ["piu1","jyu1","jyun5","fong1","ngo5","lou6","soeng6"] },
            { chars: ["来","日","纵","使","千","千","晚","星"], jp: ["loi4","jat6","zung3","si2","cin1","cin1","maan5","sing1"] },
            { chars: ["亮","过","今","晚","月","亮"], jp: ["loeng6","gwo3","gam1","maan5","jyut6","loeng6"] },
            { chars: ["都","比","不","起","这","宵","美","丽"], jp: ["dou1","bei2","bat1","hei2","ze5","siu1","mei5","lai6"] },
            { chars: ["都","洗","不","清","今","晚","我","所","想"], jp: ["dou1","sai2","bat1","cing1","gam1","maan5","ngo5","so2","soeng2"] },
            { chars: ["因","不","知","哪","天","再","共","你","唱"], jp: ["jan1","bat1","zi1","naa5","tin1","zoi3","gung6","nei5","coeng3"] }
        ]
    };
    if (typeof window !== 'undefined' && window.__songs) {
        window.__songs.push(song);
    }
})();
