// 歌曲：可惜我是水瓶座

(function() {
    const song = {
        id: 355,
        title: "可惜我是水瓶座",
        titleJyutping: ["ho2","sik1","ngo5","si6","seoi2","ping4","zo6"],
        artist: "杨千嬅",
        artistJyutping: ["joeng4","cin1","waa6"],
        lyricist: "黄伟文",
        lyricistJyutping: ["wong4","wai5","man4"],
        composer: "雷颂德",
        composerJyutping: ["leoi4","zung6","dak1"],
        lyrics: [
            { chars: ["原","来","你","这","样","珍","惜","我"], jp: ["jyun4","loi4","nei5","ze5","joeng6","zan1","sik1","ngo5"] },
            { chars: ["从","前","在","热","恋","中","都","未","听","讲","过"], jp: ["cung4","cin4","zoi6","jit6","lyun2","zung1","dou1","mei6","ting1","gong2","gwo3"] },
            { chars: ["别","说"," ","这","种","行","货","哪","里","留","得","住","我"], jp: ["bit6","syut3","","ze5","zung2","hang4","fo3","naa5","lei5","lau4","dak1","zyu6","ngo5"] },
            { chars: ["到","底","是","为","什","么","分","手"], jp: ["dou3","dai2","si6","wai4","sap6","maa1","fan1","sau2"] },
            { chars: ["你","很","清","楚"], jp: ["nei5","han2","cing1","co2"] },
            { paragraphBreak: true },
            { chars: ["如","何","笨","到","底"], jp: ["jyu4","ho4","ban6","dou3","dai2"] },
            { chars: ["但","到","底","还","是","我"], jp: ["daan6","dou3","dai2","waan4","si6","ngo5"] },
            { chars: ["谁","人","待","我","好"], jp: ["seoi4","jan4","doi6","ngo5","hou2"] },
            { chars: ["待","我","差"], jp: ["doi6","ngo5","caa1"] },
            { chars: ["太","清","楚"], jp: ["taai3","cing1","co2"] },
            { chars: ["想","继","续","装","傻"], jp: ["soeng2","gai3","zuk6","zong1","so4"] },
            { chars: ["却","又","无","力","受","折","磨"], jp: ["koek3","jau6","mou4","lik6","sau6","zit3","mo4"] },
            { chars: ["心","里","羡","慕","那","些","人"], jp: ["sam1","lei5","sin6","mou6","naa5","se1","jan4"] },
            { chars: ["盲","目","到","不","计","后","果"], jp: ["maang4","muk6","dou3","bat1","gai3","hau6","gwo2"] },
            { paragraphBreak: true },
            { chars: ["我","就","回","去"], jp: ["ngo5","zau6","wui4","heoi3"] },
            { chars: ["别","引","出","我","泪","水"], jp: ["bit6","jan5","ceot1","ngo5","leoi6","seoi2"] },
            { chars: ["尤","其","明","知","水","瓶","座","最","爱","是","流","泪"], jp: ["jau4","kei4","ming4","zi1","seoi2","ping4","zo6","zeoi3","ngoi3","si6","lau4","leoi6"] },
            { chars: ["若","然","道","别","是","下","一","句"], jp: ["joek6","jin4","dou6","bit6","si6","haa6","jat1","geoi3"] },
            { chars: ["可","以","闭","上","了","你","的","嘴"], jp: ["ho2","ji5","bai3","soeng6","liu5","nei5","dik1","zeoi2"] },
            { chars: ["无","谓","再","会"], jp: ["mou4","wai6","zoi3","wui6"] },
            { chars: ["要","是","再","会"], jp: ["jiu3","si6","zoi3","wui6"] },
            { chars: ["更","加","心","碎"], jp: ["gang1","gaa1","sam1","seoi3"] },
            { paragraphBreak: true },
            { chars: ["要","是","回","去","没","有","止","痛","药","水"], jp: ["jiu3","si6","wui4","heoi3","mut6","jau5","zi2","tung3","joek6","seoi2"] },
            { chars: ["拿","来","长","岛","冰","茶","换","我","半","晚","安","睡"], jp: ["naa4","loi4","coeng4","dou2","bing1","caa4","wun6","ngo5","bun3","maan5","on1","seoi6"] },
            { chars: ["十","年","后","或","现","在","失","去"], jp: ["sap6","nin4","hau6","waak6","jin6","zoi6","sat1","heoi3"] },
            { chars: ["反","正","到","最","尾","也","唏","嘘"], jp: ["faan2","zing3","dou3","zeoi3","mei5","jaa5","hei1","heoi1"] },
            { chars: ["够","绝","情"], jp: ["gau3","zyut6","cing4"] },
            { chars: ["我","都","赶","我","自","己","出","去"], jp: ["ngo5","dou1","gon2","ngo5","zi6","gei2","ceot1","heoi3"] },
            { paragraphBreak: true },
            { chars: ["犹","如","最","结","实","的","堡","垒"], jp: ["jau4","jyu4","zeoi3","git3","sat6","dik1","bou2","leoi5"] },
            { chars: ["原","来","在","逐","点","崩","溃"], jp: ["jyun4","loi4","zoi6","zuk6","dim2","bang1","kui2"] },
            { chars: ["逐","点","粉","碎"], jp: ["zuk6","dim2","fan2","seoi3"] },
            { chars: ["极","固","执","的","如","我","也","会","捱","不","下","去"], jp: ["gik6","gu3","zap1","dik1","jyu4","ngo5","jaa5","wui6","ngaai4","bat1","haa6","heoi3"] },
            { chars: ["每","天","扮","着","幸","福"], jp: ["mui5","tin1","baan6","zoek6","hang6","fuk1"] },
            { chars: ["始","终","有","些","心","虚"], jp: ["ci2","zung1","jau5","se1","sam1","heoi1"] },
            { paragraphBreak: true },
            { chars: ["如","何","笨","到","底"], jp: ["jyu4","ho4","ban6","dou3","dai2"] },
            { chars: ["但","到","底","还","是","我"], jp: ["daan6","dou3","dai2","waan4","si6","ngo5"] },
            { chars: ["谁","人","待","我","好"], jp: ["seoi4","jan4","doi6","ngo5","hou2"] },
            { chars: ["待","我","差"], jp: ["doi6","ngo5","caa1"] },
            { chars: ["太","清","楚"], jp: ["taai3","cing1","co2"] },
            { chars: ["想","继","续","装","傻"], jp: ["soeng2","gai3","zuk6","zong1","so4"] },
            { chars: ["却","又","无","力","受","折","磨"], jp: ["koek3","jau6","mou4","lik6","sau6","zit3","mo4"] },
            { chars: ["心","里","羡","慕","有","些","人"], jp: ["sam1","lei5","sin6","mou6","jau5","se1","jan4"] },
            { chars: ["盲","目","到","不","计","后","果"], jp: ["maang4","muk6","dou3","bat1","gai3","hau6","gwo2"] },
            { paragraphBreak: true },
            { chars: ["我","就","回","去"], jp: ["ngo5","zau6","wui4","heoi3"] },
            { chars: ["别","引","出","我","泪","水"], jp: ["bit6","jan5","ceot1","ngo5","leoi6","seoi2"] },
            { chars: ["尤","其","明","知","水","瓶","座","最","爱","是","流","泪"], jp: ["jau4","kei4","ming4","zi1","seoi2","ping4","zo6","zeoi3","ngoi3","si6","lau4","leoi6"] },
            { chars: ["若","然","道","别","是","下","一","句"], jp: ["joek6","jin4","dou6","bit6","si6","haa6","jat1","geoi3"] },
            { chars: ["可","以","闭","上","了","你","的","嘴"], jp: ["ho2","ji5","bai3","soeng6","liu5","nei5","dik1","zeoi2"] },
            { chars: ["无","谓","再","会"], jp: ["mou4","wai6","zoi3","wui6"] },
            { chars: ["要","是","再","会"], jp: ["jiu3","si6","zoi3","wui6"] },
            { chars: ["更","加","心","碎"], jp: ["gang1","gaa1","sam1","seoi3"] },
            { paragraphBreak: true },
            { chars: ["要","是","回","去","没","有","止","痛","药","水"], jp: ["jiu3","si6","wui4","heoi3","mut6","jau5","zi2","tung3","joek6","seoi2"] },
            { chars: ["拿","来","长","岛","冰","茶","换","我","半","晚","安","睡"], jp: ["naa4","loi4","coeng4","dou2","bing1","caa4","wun6","ngo5","bun3","maan5","on1","seoi6"] },
            { chars: ["十","年","后","或","现","在","失","去"], jp: ["sap6","nin4","hau6","waak6","jin6","zoi6","sat1","heoi3"] },
            { chars: ["反","正","到","最","尾","也","唏","嘘"], jp: ["faan2","zing3","dou3","zeoi3","mei5","jaa5","hei1","heoi1"] },
            { chars: ["够","绝","情"], jp: ["gau3","zyut6","cing4"] },
            { chars: ["我","都","赶","我","自","己","出","去"], jp: ["ngo5","dou1","gon2","ngo5","zi6","gei2","ceot1","heoi3"] }
        ]
    };
    if (typeof window !== 'undefined' && window.__songs) {
        window.__songs.push(song);
    }
})();
