// 歌曲：告别我的恋人们

(function() {
    const song = {
        id: 14,
        title: "告别我的恋人们",
        titleJyutping: ["gou3","bit6","ngo5","dik1","lyun2","jan4","mun4"],
        artist: "古巨基",
        artistJyutping: ["gu2","geoi6","gei1"],
        lyricist: "黄伟文",
        lyricistJyutping: ["wong4","wai5","man4"],
        composer: "郭文纬",
        composerJyutping: ["gwok3","man4","wai5"],
        lyrics: [
            { chars: ["谁","没","有","得","到","更","多"], jp: ["seoi4","mut6","jau5","dak1","dou3","gang3","do1"] },
            { chars: ["错","误","错","得","可","玩","味"], jp: ["co3","ng6","co3","dak1","ho2","wun6","mei6"] },
            { chars: ["未","留","下","也","算","好","结","果"], jp: ["mei6","lau4","haa6","jaa5","syun3","hou2","git3","gwo2"] },
            { paragraphBreak: true },
            { chars: ["擦","亮","你","的","也","擦","伤","我"], jp: ["caat3","loeng6","nei5","dik1","jaa5","caat3","soeng1","ngo5"] },
            { chars: ["难","捱","亦","值","得","被","庆","贺"], jp: ["naan4","ngaai4","jik6","zik6","dak1","bei6","hing3","ho6"] },
            { chars: ["忍","痛","着","切","磋"," ","只","贪","求","下","个"," ","更","好","过"], jp: ["jan2","tung3","zoek6","cit3","co1","","zi2","taam1","kau4","haa6","go3","","gang3","hou2","gwo3"] },
            { paragraphBreak: true },
            { chars: ["总","会","复","元","吧"," ","痛","快","得","快","乐","吗"], jp: ["zung2","wui5","fuk6","jyun4","baa6","","tung3","faai3","dak1","faai3","lok6","maa1"] },
            { paragraphBreak: true },
            { chars: ["曾","经","风","吹","雨","打"," ","才","对","得","住","炎","夏"], jp: ["cang4","ging1","fung1","ceoi1","jyu5","daa2","","coi4","deoi3","dak1","zyu6","jim4","haa6"] },
            { chars: ["要","是","从","未","伤","心","到","害","怕"], jp: ["jiu3","si6","cung4","mei6","soeng1","sam1","dou3","hoi6","paa3"] },
            { chars: ["没","有","承","受","过","多","少","牵","挂"], jp: ["mut6","jau5","sing4","sau6","gwo3","do1","siu2","hin1","gwaa3"] },
            { chars: ["又","怎","证","实","感","情","开","过","花"], jp: ["jau6","zam2","zing3","sat6","gam2","cing4","hoi1","gwo3","faa1"] },
            { paragraphBreak: true },
            { chars: ["又","怎","容","纳","下","个","她"], jp: ["jau6","zam2","jung4","naap6","haa6","go3","taa1"] },
            { chars: ["早","已","复","元","吧"," ","会","爱","得","更","易","吗"], jp: ["zou2","ji5","fuk6","jyun4","baa6","","wui5","ngoi3","dak1","gang3","ji6","maa1"] },
            { chars: ["还","枯","萎","几","扎","花"," ","才","爱","出","一","个","家"], jp: ["waan4","fu1","wai2","gei2","zaat3","faa1","","coi4","ngoi3","ceot1","jat1","go3","gaa1"] },
            { chars: ["学","习","成","熟","也","因","天","真","过"], jp: ["hok6","zaap6","sing4","suk6","jaa5","jan1","tin1","zan1","gwo3"] },
            { chars: ["乐","与","苦"," ","同","样","无","价"], jp: ["lok6","jyu5","fu2","","tung4","joeng6","mou4","gaa3"] },
            { chars: ["我","们","也","应","感","激","这","些"," ","爱","的","代","价"], jp: ["ngo5","mun4","jaa5","jing1","gam2","gik1","ze5","se1","","ngoi3","dik1","doi6","gaa3"] },
            { paragraphBreak: true },
            { chars: ["偶","遇","我","的","恋","人","们"], jp: ["ngau5","jyu6","ngo5","dik1","lyun2","jan4","mun4"] },
            { chars: ["谁","情","愿","被","不","断","替","换"], jp: ["seoi4","cing4","jyun6","bei6","bat1","dyun6","tai3","wun6"] },
            { chars: ["坚","拒","被","割","损"," ","怎","可","磨","合","到"," ","那","一","半"], jp: ["gin1","keoi5","bei6","got3","syun2","","zam2","ho2","mo4","hap6","dou3","","naa5","jat1","bun3"] },
            { paragraphBreak: true },
            { chars: ["总","会","复","元","吧"," ","痛","快","得","快","乐","吗"], jp: ["zung2","wui5","fuk6","jyun4","baa6","","tung3","faai3","dak1","faai3","lok6","maa1"] },
            { paragraphBreak: true },
            { chars: ["曾","经","风","吹","雨","打"," ","才","对","得","住","炎","夏"], jp: ["cang4","ging1","fung1","ceoi1","jyu5","daa2","","coi4","deoi3","dak1","zyu6","jim4","haa6"] },
            { chars: ["要","是","从","未","伤","心","到","害","怕"], jp: ["jiu3","si6","cung4","mei6","soeng1","sam1","dou3","hoi6","paa3"] },
            { chars: ["没","有","承","受","过","多","少","牵","挂"], jp: ["mut6","jau5","sing4","sau6","gwo3","do1","siu2","hin1","gwaa3"] },
            { chars: ["又","怎","证","实","感","情","开","过","花"], jp: ["jau6","zam2","zing3","sat6","gam2","cing4","hoi1","gwo3","faa1"] },
            { paragraphBreak: true },
            { chars: ["又","怎","容","纳","下","个","她"], jp: ["jau6","zam2","jung4","naap6","haa6","go3","taa1"] },
            { chars: ["回","望","初","恋","为","何","未","杀","出","血","路"], jp: ["wui4","mong6","co1","lyun2","wai4","ho4","mei6","saat3","ceot1","hyut3","lou6"] },
            { chars: ["才","能","体","会","到"], jp: ["coi4","nang4","tai2","wui5","dou3"] },
            { chars: ["爱","只","懂","容","纳","爱"," ","说","永","恒","还","太","早"], jp: ["ngoi3","zi2","dung2","jung4","naap6","ngoi3","","syut3","wing5","hang4","waan4","taai3","zou2"] },
            { paragraphBreak: true },
            { chars: ["早","已","复","元","吧"," ","会","爱","得","更","易","吗"], jp: ["zou2","ji5","fuk6","jyun4","baa6","","wui5","ngoi3","dak1","gang3","ji6","maa1"] },
            { chars: ["留","低","多","少","个","疤"," ","才","爱","出","一","个","家"], jp: ["lau4","dai1","do1","siu2","go3","baa1","","coi4","ngoi3","ceot1","jat1","go3","gaa1"] },
            { chars: ["学","习","成","熟","也","因","天","真","过"], jp: ["hok6","zaap6","sing4","suk6","jaa5","jan1","tin1","zan1","gwo3"] },
            { chars: ["乐","与","苦"," ","同","样","无","价"], jp: ["lok6","jyu5","fu2","","tung4","joeng6","mou4","gaa3"] },
            { chars: ["往","日","年","少","怎","欣","赏","那","首"," ","爱","的","代","价"], jp: ["wong5","jat6","nin4","siu2","zam2","jan1","soeng2","naa5","sau2","","ngoi3","dik1","doi6","gaa3"] },
            { paragraphBreak: true },
            { chars: ["告","别","我","的","恋","人","们"], jp: ["gou3","bit6","ngo5","dik1","lyun2","jan4","mun4"] },
            { chars: ["其","实","你","听","得","到","吗"], jp: ["kei4","sat6","nei5","ting1","dak1","dou3","maa1"] }
        ]
    };
    window.__songs.push(song);
})();
