// 歌曲：咬唇

(function() {
    const song = {
        id: 365,
        title: "咬唇",
        titleJyutping: ["ngaau5","seon4"],
        artist: "杨千嬅",
        artistJyutping: ["joeng4","cin1","waa6"],
        lyricist: "黄伟文",
        lyricistJyutping: ["wong4","wai5","man4"],
        composer: "伍乐城",
        composerJyutping: ["ng5","lok6","sing4"],
        lyrics: [
            { chars: ["逆","境","大","战"], jp: ["jik6","ging2","daai6","zin3"] },
            { chars: ["咬","着","唇","昂","然","接","受"], jp: ["ngaau5","zoek6","seon4","ngong4","jin4","zip3","sau6"] },
            { chars: ["幸","福","誓","约"], jp: ["hang6","fuk1","sai6","joek3"] },
            { chars: ["为","何","无","勇","气","承","受"], jp: ["wai4","ho4","mou4","jung5","hei3","sing4","sau6"] },
            { chars: ["钻","戒","这","样","重"], jp: ["zyun3","gaai3","ze5","joeng6","cung5"] },
            { chars: ["任","务","空","前","绝","后"], jp: ["jam6","mou6","hung1","cin4","zyut6","hau6"] },
            { chars: ["护","送","它","犹","如","长","途","竞","赛"], jp: ["wu6","sung3","taa1","jau4","jyu4","coeng4","tou4","ging6","coi3"] },
            { chars: ["只","怕","被","你","甩","开","了","手"], jp: ["zi2","paa3","bei6","nei5","lat1","hoi1","liu5","sau2"] },
            { paragraphBreak: true },
            { chars: ["别","人","都","知","道","我","火","爆"], jp: ["bit6","jan4","dou1","zi1","dou6","ngo5","fo2","baau3"] },
            { chars: ["直","行","直","冲","不","守","礼","貌"], jp: ["zik6","hang4","zik6","cung1","bat1","sau2","lai5","maau6"] },
            { chars: ["若","决","心","跟","了","你"], jp: ["joek6","kyut3","sam1","gan1","liu5","nei5"] },
            { chars: ["就","不","计","较"], jp: ["zau6","bat1","gai3","gaau3"] },
            { chars: ["要","和","谁","人","绝","了","交"], jp: ["jiu3","wo4","seoi4","jan4","zyut6","liu5","gaau1"] },
            { paragraphBreak: true },
            { chars: ["若","情","感","需","要","这","执","拗"], jp: ["joek6","cing4","gam2","seoi1","jiu3","ze5","zap1","aau2"] },
            { chars: ["落","场","后","只","许","尽","力","去","跑"], jp: ["lok6","coeng4","hau6","zi2","heoi2","zeon6","lik6","heoi3","paau2"] },
            { chars: ["咬","着","唇","边"], jp: ["ngaau5","zoek6","seon4","bin1"] },
            { chars: ["穿","起","婚","纱","上","路"], jp: ["cyun1","hei2","fan1","saa1","soeng6","lou6"] },
            { chars: ["余","生","请","你","指","教"], jp: ["jyu4","sang1","cing2","nei5","zi2","gaau3"] },
            { paragraphBreak: true },
            { chars: ["自","古","大","将","咬","着","唇","完","成","战","事"], jp: ["zi6","gu2","daai6","zoeng1","ngaau5","zoek6","seon4","jyun4","sing4","zin3","si6"] },
            { chars: ["热","恋","大","概"], jp: ["jit6","lyun2","daai6","koi3"] },
            { chars: ["亦","是","类","似","这","回","事"], jp: ["jik6","si6","leoi6","ci5","ze5","wui4","si6"] },
            { chars: ["借","我","一","啖","气"], jp: ["ze3","ngo5","jat1","daam6","hei3"] },
            { chars: ["现","在","从","容","就","义"], jp: ["jin6","zoi6","cung4","jung4","zau6","ji6"] },
            { chars: ["是","说","谎","或","是","浓","情","蜜","意"], jp: ["si6","syut3","fong1","waak6","si6","nung4","cing4","mat6","ji3"] },
            { chars: ["不","爱","下","去","怎","么","会","知"], jp: ["bat1","ngoi3","haa6","heoi3","zam2","maa1","wui6","zi1"] },
            { paragraphBreak: true },
            { chars: ["别","人","都","知","道","我","火","爆"], jp: ["bit6","jan4","dou1","zi1","dou6","ngo5","fo2","baau3"] },
            { chars: ["直","行","直","冲","不","守","礼","貌"], jp: ["zik6","hang4","zik6","cung1","bat1","sau2","lai5","maau6"] },
            { chars: ["若","决","心","跟","了","你"], jp: ["joek6","kyut3","sam1","gan1","liu5","nei5"] },
            { chars: ["就","不","计","较"], jp: ["zau6","bat1","gai3","gaau3"] },
            { chars: ["要","和","谁","人","绝","了","交"], jp: ["jiu3","wo4","seoi4","jan4","zyut6","liu5","gaau1"] },
            { paragraphBreak: true },
            { chars: ["若","情","感","需","要","这","执","拗"], jp: ["joek6","cing4","gam2","seoi1","jiu3","ze5","zap1","aau2"] },
            { chars: ["落","场","后","只","许","尽","力","去","跑"], jp: ["lok6","coeng4","hau6","zi2","heoi2","zeon6","lik6","heoi3","paau2"] },
            { chars: ["咬","着","唇","边"], jp: ["ngaau5","zoek6","seon4","bin1"] },
            { chars: ["穿","起","婚","纱","上","路"], jp: ["cyun1","hei2","fan1","saa1","soeng6","lou6"] },
            { chars: ["余","生","请","你","指","教"], jp: ["jyu4","sang1","cing2","nei5","zi2","gaau3"] },
            { paragraphBreak: true },
            { chars: ["问","谁","可","保","证","你","可","靠"], jp: ["man6","seoi4","ho2","bou2","zing3","nei5","ho2","kaau3"] },
            { chars: ["诺","言","是","否","终","生","有","效"], jp: ["nok6","jin4","si6","fau2","zung1","sang1","jau5","haau6"] },
            { chars: ["望","见","几","多","爱","侣","直","冲","过","去"], jp: ["mong6","gin3","gei2","do1","ngoi3","leoi5","zik6","cung1","gwo3","heoi3"] },
            { chars: ["到","头","来","全","是","气","泡"], jp: ["dou3","tau4","loi4","cyun4","si6","hei3","paau1"] },
            { paragraphBreak: true },
            { chars: ["若","情","感","需","要","这","执","拗"], jp: ["joek6","cing4","gam2","seoi1","jiu3","ze5","zap1","aau2"] },
            { chars: ["像","盲","目","选","手","尽","力","去","跑"], jp: ["zoeng6","maang4","muk6","syun2","sau2","zeon6","lik6","heoi3","paau2"] },
            { chars: ["我","就","从","今","将","一","生","都","押","下"], jp: ["ngo5","zau6","cung4","gam1","zoeng1","jat1","sang1","dou1","aat3","haa6"] },
            { chars: ["唇","都","不","咬","一","咬"], jp: ["seon4","dou1","bat1","ngaau5","jat1","ngaau5"] }
        ]
    };
    if (typeof window !== 'undefined' && window.__songs) {
        window.__songs.push(song);
    }
})();
