// 歌曲：喜帖街

(function() {
    const song = {
        id: 29,
        title: "喜帖街",
        titleJyutping: ["hei2","tip3","gaai1"],
        artist: "谢安琪",
        artistJyutping: ["ze6","on1","kei4"],
        lyricist: "黄伟文",
        lyricistJyutping: ["wong4","wai5","man4"],
        composer: "郭伟亮",
        composerJyutping: ["gwok3","wai5","loeng6"],
        lyrics: [
            { chars: ["忘","掉","种","过","的","花"], jp: ["mong4","diu6","zung2","gwo3","dik1","faa1"] },
            { chars: ["重","新","的","出","发"," ","放","弃","理","想","吧"], jp: ["cung5","san1","dik1","ceot1","faat3","","fong3","hei3","lei5","soeng2","baa6"] },
            { chars: ["别","再","看","尘","封","的","囍","帖"], jp: ["bit6","zoi3","hon3","can4","fung1","dik1","hei2","tip3"] },
            { chars: ["你","正","在","要","搬","家"], jp: ["nei5","zing3","zoi6","jiu3","bun1","gaa1"] },
            { paragraphBreak: true },
            { chars: ["筑","得","起"], jp: ["zuk1","dak1","hei2"] },
            { chars: ["人","应","该","接","受","都","有","日","倒","下"], jp: ["jan4","jing3","goi1","zip3","sau6","dou1","jau5","jat6","dou2","haa6"] },
            { chars: ["其","实","没","有","一","种","安","稳","快","乐"], jp: ["kei4","sat6","mut6","jau5","jat1","zung2","on1","wan2","faai3","lok6"] },
            { chars: ["永","远","也","不","差"], jp: ["wing5","jyun5","jaa5","bat1","caa1"] },
            { paragraphBreak: true },
            { chars: ["就","似","这","一","区"], jp: ["zau6","ci5","ze5","jat1","keoi1"] },
            { chars: ["曾","经","称","得","上","美","满","甲","天","下"], jp: ["zang1","ging1","cing1","dak1","soeng6","mei5","mun5","gaap3","tin1","haa6"] },
            { chars: ["但","霎","眼"], jp: ["daan6","saap3","ngaan5"] },
            { chars: ["全","街","的","单","位","快","要","住","满","乌","鸦"], jp: ["cyun4","gaai1","dik1","daan1","wai6","faai3","jiu3","zyu6","mun5","wu1","aa1"] },
            { paragraphBreak: true },
            { chars: ["好","景","不","会","每","日","常","在"], jp: ["hou2","ging2","bat1","wui6","mui5","jat6","soeng4","zoi6"] },
            { chars: ["天","梯","不","可","只","往","上","爬"], jp: ["tin1","tai1","bat1","ho2","zi2","wong5","soeng6","paa4"] },
            { chars: ["爱","的","人","没","有","一","生","一","世","吗","？"], jp: ["ngoi3","dik1","jan4","mut6","jau5","jat1","sang1","jat1","sai3","maa1",""] },
            { chars: ["大","概","不","需","要","害","怕"], jp: ["daai6","koi3","bat1","seoi1","jiu3","hoi6","paa3"] },
            { paragraphBreak: true },
            { chars: ["忘","掉","爱","过","的","他"], jp: ["mong4","diu6","ngoi3","gwo3","dik1","taa1"] },
            { chars: ["当","初","的","囍","帖","金","箔","印","着","那","位","他"], jp: ["dong1","co1","dik1","hei2","tip3","gam1","bok6","jan3","zoek6","naa5","wai6","taa1"] },
            { chars: ["裱","起","婚","纱","照","那","道","墙"], jp: ["biu2","hei2","fan1","saa1","ziu3","naa5","dou6","coeng4"] },
            { chars: ["及","一","切","美","丽","旧","年","华"], jp: ["kap6","jat1","cit3","mei5","lai6","gau6","nin4","waa4"] },
            { chars: ["明","日","同","步","拆","下"], jp: ["ming4","jat6","tung4","bou6","caak3","haa6"] },
            { paragraphBreak: true },
            { chars: ["忘","掉","有","过","的","家"], jp: ["mong4","diu6","jau5","gwo3","dik1","gaa1"] },
            { chars: ["小","餐","枱","沙","发"," ","雪","柜","及","两","份","红","茶"], jp: ["siu2","caan1","toi2","saa1","faat3","","syut3","gwai6","kap6","loeng5","fan6","hung4","caa4"] },
            { chars: ["温","馨","的","光","境","不","过","借","出","到","期","拿","回","吗","？"], jp: ["wan1","hing1","dik1","gwong1","ging2","bat1","gwo3","ze3","ceot1","dou3","kei4","naa4","wui4","maa1",""] },
            { chars: ["等","不","到","下","一","代","是","吗","？"], jp: ["dang2","bat1","dou3","haa6","jat1","doi6","si6","maa1",""] },
            { paragraphBreak: true },
            { chars: ["忘","掉","砌","过","的","沙"], jp: ["mong4","diu6","cai3","gwo3","dik1","saa1"] },
            { chars: ["回","忆","的","堡","垒"," ","刹","那","已","倒","下"], jp: ["wui4","jik1","dik1","bou2","leoi5","","caat3","naa5","ji5","dou2","haa6"] },
            { chars: ["面","对","这","坟","起","的","荒","土"], jp: ["min6","deoi3","ze5","fan4","hei2","dik1","fong1","tou2"] },
            { chars: ["你","注","定","学","会","潇","洒"], jp: ["nei5","zyu3","ding6","hok6","wui6","siu1","saa2"] },
            { paragraphBreak: true },
            { chars: ["阶","砖","不","会","拒","绝","磨","蚀"], jp: ["gaai1","zyun1","bat1","wui6","keoi5","zyut6","mo4","sik6"] },
            { chars: ["窗","花","不","可","幽","禁","落","霞"], jp: ["coeng1","faa1","bat1","ho2","jau1","gam3","lok6","haa4"] },
            { chars: ["有","感","情","就","会","一","生","一","世","吗","？"], jp: ["jau5","gam2","cing4","zau6","wui6","jat1","sang1","jat1","sai3","maa1",""] },
            { chars: ["又","再","惋","惜","有","用","吗","？"], jp: ["jau6","zoi3","wun2","sik1","jau5","jung6","maa1",""] },
            { paragraphBreak: true },
            { chars: ["忘","掉","爱","过","的","他"], jp: ["mong4","diu6","ngoi3","gwo3","dik1","taa1"] },
            { chars: ["当","初","的","囍","帖","金","箔","印","着","那","位","他"], jp: ["dong1","co1","dik1","hei2","tip3","gam1","bok6","jan3","zoek6","naa5","wai6","taa1"] },
            { chars: ["裱","起","婚","纱","照","那","道","墙"], jp: ["biu2","hei2","fan1","saa1","ziu3","naa5","dou6","coeng4"] },
            { chars: ["及","一","切","美","丽","旧","年","华"], jp: ["kap6","jat1","cit3","mei5","lai6","gau6","nin4","waa4"] },
            { chars: ["明","日","同","步","拆","下"], jp: ["ming4","jat6","tung4","bou6","caak3","haa6"] },
            { paragraphBreak: true },
            { chars: ["忘","掉","有","过","的","家"], jp: ["mong4","diu6","jau5","gwo3","dik1","gaa1"] },
            { chars: ["小","餐","枱","沙","发"," ","雪","柜","及","两","份","红","茶"], jp: ["siu2","caan1","toi2","saa1","faat3","","syut3","gwai6","kap6","loeng5","fan6","hung4","caa4"] },
            { chars: ["温","馨","的","光","境","不","过","借","出"], jp: ["wan1","hing1","dik1","gwong1","ging2","bat1","gwo3","ze3","ceot1"] },
            { chars: ["到","期","拿","回","吗","？"], jp: ["dou3","kei4","naa4","wui4","maa1",""] },
            { chars: ["终","须","会","时","辰","到","别","怕"], jp: ["zung1","seoi1","wui6","si4","san4","dou3","bit6","paa3"] },
            { paragraphBreak: true },
            { chars: ["请","放","下","手","里","那","锁","匙","好","吗","？"], jp: ["cing2","fong3","haa6","sau2","lei5","naa5","so2","ci4","hou2","maa1",""] }
        ]
    };
    if (typeof window !== 'undefined' && window.__songs) {
        window.__songs.push(song);
    }
})();
