// 歌曲：垃圾（live）

(function() {
    const song = {
        id: 239,
        title: "垃圾（live）",
        titleJyutping: ["laap6","saap3","","l","i","v","e",""],
        artist: "陈奕迅",
        artistJyutping: ["can4","jik6","seon3"],
        lyricist: "黄伟文",
        lyricistJyutping: ["wong4","wai5","man4"],
        composer: "陈辉阳",
        composerJyutping: ["can4","fai1","joeng4"],
        lyrics: [
            { chars: ["如","果","我","是","半","张","废","纸"], jp: ["jyu4","gwo2","ngo5","si6","bun3","zoeng1","fai3","zi2"] },
            { chars: ["让","我"," ","化","蝶"], jp: ["joeng6","ngo5","","faa3","dip6"] },
            { chars: ["如","果","我","是","个","空","罐","子"], jp: ["jyu4","gwo2","ngo5","si6","go3","hung1","gun3","zi2"] },
            { chars: ["为","你"," ","铁","了","心"], jp: ["wai4","nei5","","tit3","liu5","sam1"] },
            { chars: ["被","你","遗","弃"], jp: ["bei6","nei5","wai4","hei3"] },
            { chars: ["被","你","活","埋"], jp: ["bei6","nei5","wut6","maai4"] },
            { chars: ["让","我","愉","快"], jp: ["joeng6","ngo5","jyu4","faai3"] },
            { chars: ["让","我","瓦","解"], jp: ["joeng6","ngo5","ngaa5","gaai2"] },
            { chars: ["让","我","盛","放"], jp: ["joeng6","ngo5","sing6","fong3"] },
            { chars: ["颓","废","中"], jp: ["teoi4","fai3","zung1"] },
            { chars: ["那","媚","态"], jp: ["naa5","mei6","taai3"] },
            { paragraphBreak: true },
            { chars: ["留","我","做","个","垃","圾"], jp: ["lau4","ngo5","zou6","go3","laap6","saap3"] },
            { chars: ["长","留","恋","于","你","家"], jp: ["coeng4","lau4","lyun2","jyu1","nei5","gaa1"] },
            { chars: ["从","沉","溺","中","结","疤"], jp: ["cung4","cam4","nik6","zung1","git3","baa1"] },
            { chars: ["再","发","芽"], jp: ["zoi3","faat3","ngaa4"] },
            { chars: ["情","爱","就","似","垃","圾"], jp: ["cing4","ngoi3","zau6","ci5","laap6","saap3"] },
            { chars: ["残","骸","虽","会","腐","化"], jp: ["caan4","haai4","seoi1","wui6","fu6","faa3"] },
            { chars: ["庭","园","中","最","后","也","开","满","花"], jp: ["ting4","jyun4","zung1","zeoi3","hau6","jaa5","hoi1","mun5","faa1"] },
            { paragraphBreak: true },
            { chars: ["被","世","界","遗","弃","不","可","怕"], jp: ["bei6","sai3","gaai3","wai4","hei3","bat1","ho2","paa3"] },
            { chars: ["喜","欢","你"], jp: ["hei2","fun1","nei5"] },
            { chars: ["有","时","还","可","怕"], jp: ["jau5","si4","waan4","ho2","paa3"] },
            { chars: ["没","法","再","做","那","些","牵","挂"], jp: ["mut6","faat3","zoi3","zou6","naa5","se1","hin1","gwaa3"] },
            { chars: ["比","不","上"], jp: ["bei2","bat1","soeng6"] },
            { chars: ["在","你","手","中","火","化"], jp: ["zoi6","nei5","sau2","zung1","fo2","faa3"] },
            { chars: ["不","需","要"], jp: ["bat1","seoi1","jiu3"] },
            { chars: ["完","美","得","可","怕"], jp: ["jyun4","mei5","dak1","ho2","paa3"] },
            { chars: ["太","快","乐"], jp: ["taai3","faai3","lok6"] },
            { chars: ["如","何","招","架"], jp: ["jyu4","ho4","ziu1","gaa3"] },
            { chars: ["残","忍","不","好","吗"], jp: ["caan4","jan2","bat1","hou2","maa1"] },
            { paragraphBreak: true },
            { chars: ["被","世","界","遗","弃","不","可","怕"], jp: ["bei6","sai3","gaai3","wai4","hei3","bat1","ho2","paa3"] },
            { chars: ["喜","欢","你"], jp: ["hei2","fun1","nei5"] },
            { chars: ["有","时","还","可","怕"], jp: ["jau5","si4","waan4","ho2","paa3"] },
            { chars: ["没","法","再","做","那","些","牵","挂"], jp: ["mut6","faat3","zoi3","zou6","naa5","se1","hin1","gwaa3"] },
            { chars: ["比","不","上"], jp: ["bei2","bat1","soeng6"] },
            { chars: ["在","你","手","中","火","化"], jp: ["zoi6","nei5","sau2","zung1","fo2","faa3"] },
            { chars: ["不","需","要"], jp: ["bat1","seoi1","jiu3"] },
            { chars: ["完","美","得","可","怕"], jp: ["jyun4","mei5","dak1","ho2","paa3"] },
            { chars: ["太","快","乐"], jp: ["taai3","faai3","lok6"] },
            { chars: ["如","何","招","架"], jp: ["jyu4","ho4","ziu1","gaa3"] },
            { chars: ["残","忍","不","好","吗"], jp: ["caan4","jan2","bat1","hou2","maa1"] },
            { paragraphBreak: true },
            { chars: ["灰","烬","里"], jp: ["fui1","zeon6","lei5"] },
            { chars: ["被","彻","底","消","化"], jp: ["bei6","cit3","dai2","siu1","faa3"] },
            { chars: ["我","以","后"], jp: ["ngo5","ji5","hau6"] },
            { chars: ["全","无","牵","挂"], jp: ["cyun4","mou4","hin1","gwaa3"] },
            { chars: ["什","么","都","不","怕"], jp: ["sap6","maa1","dou1","bat1","paa3"] }
        ]
    };
    if (typeof window !== 'undefined' && window.__songs) {
        window.__songs.push(song);
    }
})();
