// 歌曲：天之骄女

(function() {
    const song = {
        id: 30,
        title: "天之骄女",
        titleJyutping: ["tin1","zi1","giu1","neoi5"],
        artist: "容祖儿",
        artistJyutping: ["jung4","zou2","ji4"],
        lyricist: "林夕",
        lyricistJyutping: ["lam4","zik6"],
        composer: "曾奕文",
        composerJyutping: ["zang1","jik6","man4"],
        lyrics: [
            { chars: ["悠","长","工","作"," ","过","后","仍","是","工","作"], jp: ["jau4","coeng4","gung1","zok3","","gwo3","hau6","jing4","si6","gung1","zok3"] },
            { chars: ["回","来","一","觉"," ","都","不","可","跟","你","享","乐"], jp: ["wui4","loi4","jat1","gok3","","dou1","bat1","ho2","gan1","nei5","hoeng2","lok6"] },
            { chars: ["还","是","发","觉"," ","再","没","有","多","少","话","讲"], jp: ["waan4","si6","faat3","gok3","","zoi3","mut6","jau5","do1","siu2","waa6","gong2"] },
            { chars: ["难","道","有","事","业","会","没","承","诺"], jp: ["naan4","dou6","jau5","si6","jip6","wui6","mut6","sing4","nok6"] },
            { paragraphBreak: true },
            { chars: ["随","着","我"," ","上","进","心"," ","已","跟","顶","峰","这","样","近"], jp: ["ceoi4","zoek6","ngo5","","soeng6","zeon3","sam1","","ji5","gan1","ding2","fung1","ze5","joeng6","gan6"] },
            { chars: ["你","的","娇","小","自","尊","伤","损","太","深"], jp: ["nei5","dik1","giu1","siu2","zi6","zyun1","soeng1","syun2","taai3","sam1"] },
            { chars: ["旁","人","话","我","看","起","你","居","然","拣","你"], jp: ["pong4","jan4","waa6","ngo5","hon3","hei2","nei5","geoi1","jin4","gaan2","nei5"] },
            { chars: ["别","理","世","间","这","么","势","利"], jp: ["bit6","lei5","sai3","gaan1","ze5","maa1","sai3","lei6"] },
            { chars: ["明","日","变","成","恋","爱","传","奇"], jp: ["ming4","jat6","bin3","sing4","lyun2","ngoi3","cyun4","kei4"] },
            { chars: ["觅","个","办","法","做","个","预","算"], jp: ["mik6","go3","baan6","faat3","zou6","go3","jyu6","syun3"] },
            { chars: ["每","分","每","刻","每","日","都","于","一","起"], jp: ["mui5","fan1","mui5","hak1","mui5","jat6","dou1","jyu1","jat1","hei2"] },
            { chars: ["但","是","你","我","都","欠","见","地"], jp: ["daan6","si6","nei5","ngo5","dou1","him3","gin3","dei6"] },
            { chars: ["情","人","就","似","好","的","知","己"], jp: ["cing4","jan4","zau6","ci5","hou2","dik1","zi1","gei2"] },
            { chars: ["但","若","你","有","别","的","女","子"], jp: ["daan6","joek6","nei5","jau5","bit6","dik1","neoi5","zi2"] },
            { chars: ["也","许","我","都","永","不","会","知","从","何","管","起"], jp: ["jaa5","heoi2","ngo5","dou1","wing5","bat1","wui6","zi1","cung4","ho4","gun2","hei2"] },
            { chars: ["无","时","候","陪","你"," ","这","一","生","不","够"], jp: ["mou4","si4","hau6","pui4","nei5","","ze5","jat1","sang1","bat1","gau3"] },
            { chars: ["十","个","星","期","真","可","交","给","你"], jp: ["sap6","go3","sing1","kei4","zan1","ho2","gaau1","kap1","nei5"] },
            { chars: ["但","我","有","余","下","半","日"," ","仍","是","爱","着","你"], jp: ["daan6","ngo5","jau5","jyu4","haa6","bun3","jat6","","jing4","si6","ngoi3","zoek6","nei5"] },
            { paragraphBreak: true },
            { chars: ["忙","来","赶","去"," ","我","们","如","何","可","追"], jp: ["mong4","loi4","gon2","heoi3","","ngo5","mun4","jyu4","ho4","ho2","zeoi1"] },
            { chars: ["如","何","争","取"," ","这","圈","子","充","满","恐","惧"], jp: ["jyu4","ho4","zang1","ceoi2","","ze5","hyun1","zi2","cung1","mun5","hung2","geoi6"] },
            { chars: ["明","日","百","变"," ","我","没","有","芳","心","能","许"], jp: ["ming4","jat6","baak3","bin3","","ngo5","mut6","jau5","fong1","sam1","nang4","heoi2"] },
            { chars: ["流","泪","也","是","人","叫","便","流","泪"], jp: ["lau4","leoi6","jaa5","si6","jan4","giu3","bin6","lau4","leoi6"] },
            { chars: ["旁","人","话","我","看","起","你","居","然","拣","你"], jp: ["pong4","jan4","waa6","ngo5","hon3","hei2","nei5","geoi1","jin4","gaan2","nei5"] },
            { chars: ["别","理","世","间","这","么","势","利"], jp: ["bit6","lei5","sai3","gaan1","ze5","maa1","sai3","lei6"] },
            { chars: ["明","日","变","成","恋","爱","传","奇"], jp: ["ming4","jat6","bin3","sing4","lyun2","ngoi3","cyun4","kei4"] },
            { chars: ["觅","个","办","法","做","个","预","算"], jp: ["mik6","go3","baan6","faat3","zou6","go3","jyu6","syun3"] },
            { chars: ["每","分","每","刻","每","日","都","于","一","起"], jp: ["mui5","fan1","mui5","hak1","mui5","jat6","dou1","jyu1","jat1","hei2"] },
            { chars: ["但","是","你","我","都","欠","见","地"], jp: ["daan6","si6","nei5","ngo5","dou1","him3","gin3","dei6"] },
            { chars: ["情","人","就","似","好","的","知","己"], jp: ["cing4","jan4","zau6","ci5","hou2","dik1","zi1","gei2"] },
            { chars: ["但","没","有","转","机"," ","没","法","说","起"], jp: ["daan6","mut6","jau5","zyun2","gei1","","mut6","faat3","syut3","hei2"] },
            { chars: ["只","因","彼","此","投","入","到","不","相","关","的","影","戏"], jp: ["zi2","jan1","bei2","ci2","tau4","jap6","dou3","bat1","soeng1","gwaan1","dik1","jing2","hei3"] },
            { chars: ["连","平","日","我","工","作","痛","苦","都","不","敢","说","起"], jp: ["lin4","ping4","jat6","ngo5","gung1","zok3","tung3","fu2","dou1","bat1","gam2","syut3","hei2"] },
            { paragraphBreak: true },
            { chars: ["诚","恳","讲","对","不","起","你","多","委","屈","你"], jp: ["sing4","han2","gong2","deoi3","bat1","hei2","nei5","do1","wai2","wat1","nei5"] },
            { chars: ["任","那","世","间","诸","多","妒","忌"], jp: ["jam6","naa5","sai3","gaan1","zyu1","do1","dou3","gei6"] },
            { chars: ["谁","话","好","奇","总","有","好","奇"], jp: ["seoi4","waa6","hou2","kei4","zung2","jau5","hou2","kei4"] },
            { chars: ["觅","个","办","法","做","个","预","算"], jp: ["mik6","go3","baan6","faat3","zou6","go3","jyu6","syun3"] },
            { chars: ["每","分","每","刻","每","日","都","于","一","起"], jp: ["mui5","fan1","mui5","hak1","mui5","jat6","dou1","jyu1","jat1","hei2"] },
            { chars: ["就","让","我","迷","恋"," ","惹","妒","忌"], jp: ["zau6","joeng6","ngo5","mai4","lyun2","","je5","dou3","gei6"] },
            { chars: ["而","其","实","我","都","输","不","起"], jp: ["ji4","kei4","sat6","ngo5","dou1","syu1","bat1","hei2"] },
            { chars: ["就","让","你","的","爱","心","储","起","记","忆"], jp: ["zau6","joeng6","nei5","dik1","ngoi3","sam1","cyu5","hei2","gei3","jik1"] },
            { chars: ["储","起","有","关","你","的","没","人","可","比"], jp: ["cyu5","hei2","jau5","gwaan1","nei5","dik1","mut6","jan4","ho2","bei2"] },
            { chars: ["仍","然","奉","承","你"," ","是","毕","生","好","友"], jp: ["jing4","jin4","fung6","sing4","nei5","","si6","bat1","sang1","hou2","jau5"] },
            { chars: ["就","似","演","员","都","必","需","交","戏"], jp: ["zau6","ci5","jin2","jyun4","dou1","bit1","seoi1","gaau1","hei3"] },
            { chars: ["但","我","柔","情","蜜","意","全","为","你","起"], jp: ["daan6","ngo5","jau4","cing4","mat6","ji3","cyun4","wai4","nei5","hei2"] },
            { chars: ["这","段","爱","一","定","有","转","机"], jp: ["ze5","dyun6","ngoi3","jat1","ding6","jau5","zyun2","gei1"] },
            { chars: ["脚","步","愿","放","慢","迎","合","去","就","你"], jp: ["goek3","bou6","jyun6","fong3","maan6","jing4","hap6","heoi3","zau6","nei5"] }
        ]
    };
    if (typeof window !== 'undefined' && window.__songs) {
        window.__songs.push(song);
    }
})();
