// 歌曲：姊妹

(function() {
    const song = {
        id: 367,
        title: "姊妹",
        titleJyutping: ["zi2","mui6"],
        artist: "杨千嬅",
        artistJyutping: ["joeng4","cin1","waa6"],
        lyricist: "林夕",
        lyricistJyutping: ["lam4","zik6"],
        composer: "C.Y.Kong",
        composerJyutping: ["","","","","","","",""],
        lyrics: [
            { chars: ["听","过","你","太","多","心","事"], jp: ["ting1","gwo3","nei5","taai3","do1","sam1","si6"] },
            { chars: ["但","已","经","不","再","重","要"], jp: ["daan6","ji5","ging1","bat1","zoi3","cung5","jiu3"] },
            { chars: ["眼","见","你","快","做","新","娘"], jp: ["ngaan5","gin3","nei5","faai3","zou6","san1","noeng4"] },
            { chars: ["做","蜜","友","的","真","想","撒","娇"], jp: ["zou6","mat6","jau5","dik1","zan1","soeng2","saat3","giu1"] },
            { paragraphBreak: true },
            { chars: ["我","与","你","太","好","姐","妹"], jp: ["ngo5","jyu5","nei5","taai3","hou2","ze2","mui6"] },
            { chars: ["为","你","竟","哭","了","又","笑"], jp: ["wai4","nei5","ging2","huk1","liu5","jau6","siu3"] },
            { chars: ["时","装","都","弃","掉"], jp: ["si4","zong1","dou1","hei3","diu6"] },
            { chars: ["穿","一","世","婚","纱","算","了"], jp: ["cyun1","jat1","sai3","fan1","saa1","syun3","liu5"] },
            { paragraphBreak: true },
            { chars: ["唯","求","好","姊","妹","抱","我","一","抱"], jp: ["wai4","kau4","hou2","zi2","mui6","pou5","ngo5","jat1","pou5"] },
            { chars: ["唯","有","我","听","过","你","对","我","哭","诉"], jp: ["wai4","jau5","ngo5","ting1","gwo3","nei5","deoi3","ngo5","huk1","sou3"] },
            { chars: ["蜜","运","后","又","离","又","合"], jp: ["mat6","wan6","hau6","jau6","lei4","jau6","hap6"] },
            { chars: ["苦","心","得","好","报"], jp: ["fu2","sam1","dak1","hou2","bou3"] },
            { chars: ["我","都","有","听","你","劝","告"], jp: ["ngo5","dou1","jau5","ting1","nei5","hyun3","gou3"] },
            { chars: ["不","要","计","数"], jp: ["bat1","jiu3","gai3","sou3"] },
            { chars: ["他","错","了","要","故","意","扮","成","糊","涂"], jp: ["taa1","co3","liu5","jiu3","gu3","ji3","baan6","sing4","wu4","tou4"] },
            { chars: ["终","于","你","守","得","到","怎","么","我","和","我","的","他"], jp: ["zung1","jyu1","nei5","sau2","dak1","dou3","zam2","maa1","ngo5","wo4","ngo5","dik1","taa1"] },
            { chars: ["忍","不","到"], jp: ["jan2","bat1","dou3"] },
            { paragraphBreak: true },
            { chars: ["每","当","我","爱","到","跌","入","漩","涡"], jp: ["mui5","dong1","ngo5","ngoi3","dou3","dit3","jap6","syun4","wo1"] },
            { chars: ["将","错","就","错","关","系","亦","出","错"], jp: ["zoeng1","co3","zau6","co3","gwaan1","hai6","jik6","ceot1","co3"] },
            { chars: ["我","总","太","爱","人"], jp: ["ngo5","zung2","taai3","ngoi3","jan4"] },
            { chars: ["逼","到","爱","人"], jp: ["bik1","dou3","ngoi3","jan4"] },
            { chars: ["变","做","朋","友","再","变","生","疏"], jp: ["bin3","zou6","pang4","jau5","zoi3","bin3","sang1","so1"] },
            { paragraphBreak: true },
            { chars: ["若","我","说","我","愿","意","谁","在","乎","过"], jp: ["joek6","ngo5","syut3","ngo5","jyun6","ji3","seoi4","zoi6","fu4","gwo3"] },
            { chars: ["你","知","道","那","答","案","快","提","示","我"], jp: ["nei5","zi1","dou6","naa5","daap3","on3","faai3","tai4","si6","ngo5"] },
            { chars: ["分","半","点","福","气","给","我"], jp: ["fan1","bun3","dim2","fuk1","hei3","kap1","ngo5"] },
            { chars: ["不","准","留","低","我","一","个"], jp: ["bat1","zeon2","lau4","dai1","ngo5","jat1","go3"] },
            { paragraphBreak: true },
            { chars: ["我","信","我","有","这","一","日"], jp: ["ngo5","seon3","ngo5","jau5","ze5","jat1","jat6"] },
            { chars: ["伴","侣","肯","专","注","待","我"], jp: ["bun6","leoi5","hang2","zyun1","zyu3","doi6","ngo5"] },
            { chars: ["每","晚","也","固","定","安","乐"], jp: ["mui5","maan5","jaa5","gu3","ding6","on1","lok6"] },
            { chars: ["像","俗","语","讲","开","花","结","果"], jp: ["zoeng6","zuk6","jyu5","gong2","hoi1","faa1","git3","gwo2"] },
            { paragraphBreak: true },
            { chars: ["却","怕","我","爱","得","轰","烈"], jp: ["koek3","paa3","ngo5","ngoi3","dak1","gwang1","lit6"] },
            { chars: ["没","信","心","可","以","渡","过"], jp: ["mut6","seon3","sam1","ho2","ji5","dou6","gwo3"] },
            { chars: ["情","感","可","错","赠"], jp: ["cing4","gam2","ho2","co3","zang6"] },
            { chars: ["婚","纱","照","不","敢","拍","错"], jp: ["fan1","saa1","ziu3","bat1","gam2","paak3","co3"] },
            { paragraphBreak: true },
            { chars: ["唯","求","好","姊","妹","抱","我","一","抱"], jp: ["wai4","kau4","hou2","zi2","mui6","pou5","ngo5","jat1","pou5"] },
            { chars: ["唯","有","我","听","过","你","对","我","哭","诉"], jp: ["wai4","jau5","ngo5","ting1","gwo3","nei5","deoi3","ngo5","huk1","sou3"] },
            { chars: ["蜜","运","后","又","离","又","合"], jp: ["mat6","wan6","hau6","jau6","lei4","jau6","hap6"] },
            { chars: ["苦","心","得","好","报"], jp: ["fu2","sam1","dak1","hou2","bou3"] },
            { chars: ["我","都","有","听","你","劝","告"], jp: ["ngo5","dou1","jau5","ting1","nei5","hyun3","gou3"] },
            { chars: ["不","要","计","数"], jp: ["bat1","jiu3","gai3","sou3"] },
            { chars: ["他","错","了","要","故","意","扮","成","糊","涂"], jp: ["taa1","co3","liu5","jiu3","gu3","ji3","baan6","sing4","wu4","tou4"] },
            { chars: ["终","于","你","守","得","到","怎","么","我","和","我","的","他"], jp: ["zung1","jyu1","nei5","sau2","dak1","dou3","zam2","maa1","ngo5","wo4","ngo5","dik1","taa1"] },
            { chars: ["忍","不","到"], jp: ["jan2","bat1","dou3"] },
            { paragraphBreak: true },
            { chars: ["每","当","我","爱","到","跌","入","漩","涡"], jp: ["mui5","dong1","ngo5","ngoi3","dou3","dit3","jap6","syun4","wo1"] },
            { chars: ["将","错","就","错","关","系","亦","出","错"], jp: ["zoeng1","co3","zau6","co3","gwaan1","hai6","jik6","ceot1","co3"] },
            { chars: ["我","总","太","爱","人"], jp: ["ngo5","zung2","taai3","ngoi3","jan4"] },
            { chars: ["逼","到","爱","人"], jp: ["bik1","dou3","ngoi3","jan4"] },
            { chars: ["变","做","朋","友","再","变","了","生","疏"], jp: ["bin3","zou6","pang4","jau5","zoi3","bin3","liu5","sang1","so1"] },
            { paragraphBreak: true },
            { chars: ["若","我","说","我","愿","意","谁","在","乎","过"], jp: ["joek6","ngo5","syut3","ngo5","jyun6","ji3","seoi4","zoi6","fu4","gwo3"] },
            { chars: ["你","知","道","那","答","案","快","提","示","我"], jp: ["nei5","zi1","dou6","naa5","daap3","on3","faai3","tai4","si6","ngo5"] },
            { chars: ["分","半","点","福","气","给","我"], jp: ["fan1","bun3","dim2","fuk1","hei3","kap1","ngo5"] },
            { chars: ["不","准","留","低","我","一","个"], jp: ["bat1","zeon2","lau4","dai1","ngo5","jat1","go3"] },
            { paragraphBreak: true },
            { chars: ["若","我","说","我","愿","意","谁","在","乎","过"], jp: ["joek6","ngo5","syut3","ngo5","jyun6","ji3","seoi4","zoi6","fu4","gwo3"] },
            { chars: ["你","知","道","那","答","案","快","提","示","我"], jp: ["nei5","zi1","dou6","naa5","daap3","on3","faai3","tai4","si6","ngo5"] },
            { chars: ["总","有","天","亲","耳","听","到"], jp: ["zung2","jau5","tin1","can1","ji5","ting1","dou3"] },
            { chars: ["我","爱","侣","对","天","宣","布"], jp: ["ngo5","ngoi3","leoi5","deoi3","tin1","syun1","bou3"] },
            { paragraphBreak: true },
            { chars: ["生","与","死","都","爱","惜","我"], jp: ["sang1","jyu5","sei2","dou1","ngoi3","sik1","ngo5"] },
            { chars: ["我","要","讲"], jp: ["ngo5","jiu3","gong2"] },
            { chars: ["我","愿","意","谁","在","乎","过"], jp: ["ngo5","jyun6","ji3","seoi4","zoi6","fu4","gwo3"] },
            { chars: ["你","知","道","那","答","案","快","提","示","我"], jp: ["nei5","zi1","dou6","naa5","daap3","on3","faai3","tai4","si6","ngo5"] },
            { chars: ["总","有","天","找","到","一","个","真","的","值","得","我"], jp: ["zung2","jau5","tin1","zaau2","dou3","jat1","go3","zan1","dik1","zik6","dak1","ngo5"] }
        ]
    };
    if (typeof window !== 'undefined' && window.__songs) {
        window.__songs.push(song);
    }
})();
