// 歌曲：嫁妆

(function() {
    const song = {
        id: 202,
        title: "嫁妆",
        titleJyutping: ["gaa3","zong1"],
        artist: "陈慧琳",
        artistJyutping: ["can4","wai6","lam4"],
        lyricist: "黄伟文",
        lyricistJyutping: ["wong4","wai5","man4"],
        composer: "陈光荣",
        composerJyutping: ["can4","gwong1","wing4"],
        lyrics: [
            { chars: ["珍","珠","色","婚","纱"," ","香","槟","色","襟","花"," ","还","好","吗"], jp: ["zan1","zyu1","sik1","fan1","saa1","","hoeng1","ban1","sik1","kam1","faa1","","waan4","hou2","maa1"] },
            { paragraphBreak: true },
            { chars: ["你","两","个","说","过"," ","想","跟","我","出","嫁"," ","还","想","吗"], jp: ["nei5","loeng5","go3","syut3","gwo3","","soeng2","gan1","ngo5","ceot1","gaa3","","waan4","soeng2","maa1"] },
            { paragraphBreak: true },
            { chars: ["我","却","太","抱","歉"," ","结","果","有","变","化"," ","新","计","划","吗"," ","随","缘","吧"], jp: ["ngo5","koek3","taai3","pou5","hip3","","git3","gwo2","jau5","bin3","faa3","","san1","gai3","waak6","maa1","","ceoi4","jyun4","baa6"] },
            { paragraphBreak: true },
            { chars: ["本","应","想","跟","他"," ","组","织","新","的","家"," ","如","今","怕","．","．","．"], jp: ["bun2","jing3","soeng2","gan1","taa1","","zou2","zik1","san1","dik1","gaa1","","jyu4","gam1","paa3","","",""] },
            { paragraphBreak: true },
            { chars: ["永","远","搁","置","了"," ","真","的","有","点","化"," ","停","一","下"], jp: ["wing5","jyun5","gok3","zi3","liu5","","zan1","dik1","jau5","dim2","faa3","","ting4","jat1","haa6"] },
            { paragraphBreak: true },
            { chars: ["爱","侣","爱","错","了"," ","嫁","妆","买","错","吗"," ","只","爱","自","己"," ","未","算","差"], jp: ["ngoi3","leoi5","ngoi3","co3","liu5","","gaa3","zong1","maai5","co3","maa1","","zi2","ngoi3","zi6","gei2","","mei6","syun3","caa1"] },
            { paragraphBreak: true },
            { chars: ["一","早","拣","好","的","嫁","妆"," ","始","终","都","未","有","希","望"], jp: ["jat1","zou2","gaan2","hou2","dik1","gaa3","zong1","","ci2","zung1","dou1","mei6","jau5","hei1","mong6"] },
            { paragraphBreak: true },
            { chars: ["手","牵","手","跟","他","看","看"," ","一","生","都","为","了","失","恋"," ","那","样","忙"], jp: ["sau2","hin1","sau2","gan1","taa1","hon3","hon3","","jat1","sang1","dou1","wai4","liu5","sat1","lyun2","","naa5","joeng6","mong4"] },
            { paragraphBreak: true },
            { chars: ["如","童","话","般","的","婚","礼"," ","那","风","光"], jp: ["jyu4","tung4","waa6","bun1","dik1","fan1","lai5","","naa5","fung1","gwong1"] },
            { paragraphBreak: true },
            { chars: ["犹","如","在","眼","前","从","来","走","不","进","的"," ","教","堂"], jp: ["jau4","jyu4","zoi6","ngaan5","cin4","cung4","loi4","zau2","bat1","zeon3","dik1","","gaau3","tong4"] },
            { paragraphBreak: true },
            { chars: ["可","不","可","穿","起","嫁","妆"," ","大","路","上","任","我","闯","荡"], jp: ["ho2","bat1","ho2","cyun1","hei2","gaa3","zong1","","daai6","lou6","soeng6","jam6","ngo5","cong2","dong6"] },
            { paragraphBreak: true },
            { chars: ["好","东","西","他","不","爱","看"," ","就","学","习","自","我","欣","赏"," ","继","续","忙"], jp: ["hou2","dung1","sai1","taa1","bat1","ngoi3","hon3","","zau6","hok6","zaap6","zi6","ngo5","jan1","soeng2","","gai3","zuk6","mong4"] },
            { paragraphBreak: true },
            { chars: ["仍","能","比","新","娘","好","看"," ","化","起","妆"], jp: ["jing4","nang4","bei2","san1","noeng4","hou2","hon3","","faa3","hei2","zong1"] },
            { paragraphBreak: true },
            { chars: ["无","人","望","见"," ","仍","然","能","闪","闪","发","光"," ","再","盛","放"], jp: ["mou4","jan4","mong6","gin3","","jing4","jin4","nang4","sim2","sim2","faat3","gwong1","","zoi3","sing6","fong3"] },
            { paragraphBreak: true },
            { chars: ["再","盛","放"], jp: ["zoi3","sing6","fong3"] },
            { paragraphBreak: true },
            { chars: ["温","室","的","小","花"," ","失","恋","的","专","家"," ","成","长","吗"], jp: ["wan1","sat1","dik1","siu2","faa1","","sat1","lyun2","dik1","zyun1","gaa1","","sing4","coeng4","maa1"] },
            { paragraphBreak: true },
            { chars: ["过","去","你","信","你"," ","终","于","也","会","嫁"," ","还","敢","吗"], jp: ["gwo3","heoi3","nei5","seon3","nei5","","zung1","jyu1","jaa5","wui6","gaa3","","waan4","gam2","maa1"] },
            { paragraphBreak: true },
            { chars: ["你","爱","戴","钻","戒"," ","要","他","爱","戴","吗"," ","依","靠","自","己"," ","别","靠","他"], jp: ["nei5","ngoi3","daai3","zyun3","gaai3","","jiu3","taa1","ngoi3","daai3","maa1","","ji1","kaau3","zi6","gei2","","bit6","kaau3","taa1"] },
            { paragraphBreak: true },
            { chars: ["一","早","拣","好","的","嫁","妆"," ","始","终","都","未","有","希","望"], jp: ["jat1","zou2","gaan2","hou2","dik1","gaa3","zong1","","ci2","zung1","dou1","mei6","jau5","hei1","mong6"] },
            { paragraphBreak: true },
            { chars: ["手","牵","手","跟","他","看","看"," ","一","生","都","为","了","失","恋"," ","那","样","忙"], jp: ["sau2","hin1","sau2","gan1","taa1","hon3","hon3","","jat1","sang1","dou1","wai4","liu5","sat1","lyun2","","naa5","joeng6","mong4"] },
            { paragraphBreak: true },
            { chars: ["如","童","话","般","的","婚","礼"," ","那","风","光"], jp: ["jyu4","tung4","waa6","bun1","dik1","fan1","lai5","","naa5","fung1","gwong1"] },
            { paragraphBreak: true },
            { chars: ["犹","如","在","眼","前","从","来","走","不","进","的"," ","教","堂"], jp: ["jau4","jyu4","zoi6","ngaan5","cin4","cung4","loi4","zau2","bat1","zeon3","dik1","","gaau3","tong4"] },
            { paragraphBreak: true },
            { chars: ["可","不","可","穿","起","嫁","妆"," ","大","路","上","任","我","闯","荡"], jp: ["ho2","bat1","ho2","cyun1","hei2","gaa3","zong1","","daai6","lou6","soeng6","jam6","ngo5","cong2","dong6"] },
            { paragraphBreak: true },
            { chars: ["好","东","西","他","不","爱","看"," ","就","学","习","自","我","欣","赏"," ","继","续","忙"], jp: ["hou2","dung1","sai1","taa1","bat1","ngoi3","hon3","","zau6","hok6","zaap6","zi6","ngo5","jan1","soeng2","","gai3","zuk6","mong4"] },
            { paragraphBreak: true },
            { chars: ["仍","能","比","新","娘","好","看"," ","化","起","妆"], jp: ["jing4","nang4","bei2","san1","noeng4","hou2","hon3","","faa3","hei2","zong1"] },
            { paragraphBreak: true },
            { chars: ["无","人","望","见"," ","仍","然","能","闪","闪","发","光"," ","再","盛","放"], jp: ["mou4","jan4","mong6","gin3","","jing4","jin4","nang4","sim2","sim2","faat3","gwong1","","zoi3","sing6","fong3"] },
            { paragraphBreak: true },
            { chars: ["若","然","是","后","悔","因","他","那","样","狂"], jp: ["joek6","jin4","si6","hau6","fui3","jan1","taa1","naa5","joeng6","kong4"] },
            { paragraphBreak: true },
            { chars: ["还","何","必","等","他","一","吻"," ","去","叨","光"], jp: ["waan4","ho4","bit1","dang2","taa1","jat1","man5","","heoi3","tou1","gwong1"] },
            { paragraphBreak: true },
            { chars: ["原","本","自","爱"," ","随","时","能","比","他","眼","光"], jp: ["jyun4","bun2","zi6","ngoi3","","ceoi4","si4","nang4","bei2","taa1","ngaan5","gwong1"] },
            { paragraphBreak: true },
            { chars: ["更","耐","看"," ","更","耐","看"," ","比","恋","爱"," ","更","耐","看"], jp: ["gang1","noi6","hon3","","gang1","noi6","hon3","","bei2","lyun2","ngoi3","","gang1","noi6","hon3"] }
        ]
    };
    if (typeof window !== 'undefined' && window.__songs) {
        window.__songs.push(song);
    }
})();
