// 歌曲：富士山下

(function() {
    const song =     {
        id: 4,
        title: "富士山下",
        titleJyutping: ["fu2","si6","saan1","haa6"],
        artist: "陈奕迅",
        artistJyutping: ["can4","jan6","hin3"],
        lyricist: "林夕",
        lyricistJyutping: ["lam4","zik6"],
        composer: "Christopher Chak",
        composerJyutping: ["c","h","r","i","s","t","o","p","h","e","r","","c","h","a","k"],
        lyrics: [
            { chars: ["拦","路","雨","偏","似","雪","花"," ","饮","泣","的","你","冻","吗","？"], jp: ["laan4","lou6","jyu5","pin1","ci5","syut3","faa1","","jam2","kap1","dik1","nei5","dung3","maa3",""] },
            { chars: ["这","风","褛","我","给","你","磨","到","有","襟","花"], jp: ["ze5","fung1","lau6","ngo5","kap1","nei5","mo4","dou3","jau5","kam1","faa1"] },
            { chars: ["连","调","了","职","也","不","怕"," ","怎","么","始","终","牵","挂","？"], jp: ["lin4","tiu4","liu5","zik1","jaa5","bat1","paa3","","zam2","mo1","ci2","zung1","hin1","gwaa3",""] },
            { chars: ["苦","心","选","中","今","天","想","车","你","回","家"], jp: ["fu2","sam1","syun2","zung1","gam1","tin1","soeng2","ce1","nei5","wui4","gaa1"] },
            { paragraphBreak: true },
            { chars: ["原","谅","我","不","再","送","花"," ","伤","口","应","要","结","疤"], jp: ["jyun4","loeng6","ngo5","bat1","zoi3","sung3","faa1","","soeng1","hau2","jing1","jiu3","git3","baa1"] },
            { chars: ["花","瓣","铺","满","心","里","坟","场","才","害","怕"], jp: ["faa1","faan6","pou1","mun5","sam1","leoi5","fan4","coeng4","coi4","hoi3","paa3"] },
            { chars: ["如","若","你","非","我","不","嫁"," ","彼","此","终","必","火","化"], jp: ["jyu4","joek6","nei5","fei1","ngo5","bat1","gaa3","","bei2","ci2","zung1","bit1","fo2","faa3"] },
            { chars: ["一","生","一","世","等","一","天","需","要","代","价"], jp: ["jat1","saang1","jat1","sai3","dang2","jat1","tin1","seoi1","jiu3","doi6","gaa3"] },
            { paragraphBreak: true },
            { chars: ["谁","都","只","得","那","双","手"," ","靠","拥","抱","亦","难","任","你","拥","有"], jp: ["seoi4","dou1","zi2","dak1","naa5","soeng1","sau2","","kaau3","jung2","pou5","jik6","naan4","jam6","nei5","jung2","jau5"] },
            { chars: ["要","拥","有","必","先","懂","失","去","怎","接","受"], jp: ["jiu3","jung2","jau5","bit1","sin1","dung2","sat1","heoi3","zam2","zip3","sau6"] },
            { chars: ["曾","沿","着","雪","路","浪","游"," ","为","何","为","好","事","泪","流","？"], jp: ["cang4","jyun4","zoek6","syut3","lou6","long6","jau4","","wai6","ho4","wai6","hou2","si6","leoi6","lau4",""] },
            { chars: ["谁","能","凭","爱","意","要","富","士","山","私","有","？"], jp: ["seoi4","nang4","bang4","oi3","ji3","jiu3","fu3","si6","saan1","si1","jau5",""] },
            { paragraphBreak: true },
            { chars: ["何","不","把","悲","哀","感","觉"," ","假","设","是","来","自","你","虚","构","？"], jp: ["ho4","bat1","baa2","bei1","oi1","gam2","gok3","","gaa2","cit3","si6","loi4","zi6","nei5","heoi1","kau3",""] },
            { chars: ["试","管","里","找","不","到","它","染","污","眼","眸"], jp: ["si3","gun2","leoi5","zaau2","bat1","dou3","taa1","jim5","wu1","ngaan5","mau4"] },
            { chars: ["前","尘","硬","化","像","石","头"," ","随","缘","地","抛","下","便","逃","走"], jp: ["cin4","can4","ngaang6","faa3","zoeng6","sek6","tau4","","ceoi4","jyun4","dei6","paau1","haa6","bin6","tou4","zau2"] },
            { chars: ["我","绝","不","罕","有"," ","往","街","里","绕","过","一","周"," ","我","便","化","乌","有"], jp: ["ngo5","zyut6","bat1","hon2","jau5","","wong5","gaai1","leoi5","jiu6","gwo3","jat1","zau1","","ngo5","bin6","faa3","wu1","jau5"] },
            { paragraphBreak: true },
            { chars: ["情","人","节","不","要","说","穿"," ","只","敢","抚","你","发","端"], jp: ["cing4","jan4","zit3","bat1","jiu3","syut3","cyun1","","zi2","gam2","fu2","nei5","faat3","dyun1"] },
            { chars: ["这","种","姿","态","可","会","令","你","更","心","酸","？"], jp: ["ze5","zung2","zi1","taai3","ho2","wui5","ling6","nei5","gang3","sam1","syun1",""] },
            { chars: ["留","在","汽","车","里","取","暖"," ","应","该","怎","么","规","劝","？"], jp: ["lau4","zoi6","hei3","ce1","leoi5","ceoi2","nyun5","","jing1","goi1","zam2","mo1","kwai1","hyun3",""] },
            { chars: ["怎","么","可","以","将","手","腕","忍","痛","划","损","？"], jp: ["zam2","mo1","ho2","ji5","zoeng1","sau2","wun2","jan2","tung3","waak6","syun2",""] },
            { paragraphBreak: true },
            { chars: ["人","活","到","几","岁","算","短","？"," ","失","恋","只","有","更","短"], jp: ["jan4","wut6","dou3","gei2","seoi3","syun3","dyun2","","","sat1","lyun2","zi2","jau5","gang3","dyun2"] },
            { chars: ["归","家","需","要","几","里","路"," ","谁","能","预","算","？"], jp: ["gwai1","gaa1","seoi1","jiu3","gei2","lei5","lou6","","seoi4","nang4","jyu6","syun3",""] },
            { chars: ["忘","掉","我","跟","你","恩","怨"," ","樱","花","开","了","几","转"], jp: ["mong4","diu6","ngo5","gan1","nei5","jan1","jyun3","","jing1","faa1","hoi1","liu5","gei2","zyun3"] },
            { chars: ["东","京","之","旅","一","早","比","一","世","遥","远"], jp: ["dung1","ging1","zi1","leoi5","jat1","zou2","bei2","jat1","sai3","jiu4","jyun5"] },
            { paragraphBreak: true },
            { chars: ["谁","都","只","得","那","双","手"," ","靠","拥","抱","亦","难","任","你","拥","有"], jp: ["seoi4","dou1","zi2","dak1","naa5","soeng1","sau2","","kaau3","jung2","pou5","jik6","naan4","jam6","nei5","jung2","jau5"] },
            { chars: ["要","拥","有","必","先","懂","失","去","怎","接","受"], jp: ["jiu3","jung2","jau5","bit1","sin1","dung2","sat1","heoi3","zam2","zip3","sau6"] },
            { chars: ["曾","沿","着","雪","路","浪","游"," ","为","何","为","好","事","泪","流","？"], jp: ["cang4","jyun4","zoek6","syut3","lou6","long6","jau4","","wai6","ho4","wai6","hou2","si6","leoi6","lau4",""] },
            { chars: ["谁","能","凭","爱","意","要","富","士","山","私","有","？"], jp: ["seoi4","nang4","bang4","oi3","ji3","jiu3","fu3","si6","saan1","si1","jau5",""] },
            { paragraphBreak: true },
            { chars: ["何","不","把","悲","哀","感","觉"," ","假","设","是","来","自","你","虚","构","？"], jp: ["ho4","bat1","baa2","bei1","oi1","gam2","gok3","","gaa2","cit3","si6","loi4","zi6","nei5","heoi1","kau3",""] },
            { chars: ["试","管","里","找","不","到","它","染","污","眼","眸"], jp: ["si3","gun2","leoi5","zaau2","bat1","dou3","taa1","jim5","wu1","ngaan5","mau4"] },
            { chars: ["前","尘","硬","化","像","石","头"," ","随","缘","地","抛","下","便","逃","走"], jp: ["cin4","can4","ngaang6","faa3","zoeng6","sek6","tau4","","ceoi4","jyun4","dei6","paau1","haa6","bin6","tou4","zau2"] },
            { chars: ["我","绝","不","罕","有"," ","往","街","里","绕","过","一","周"," ","我","便","化","乌","有"], jp: ["ngo5","zyut6","bat1","hon2","jau5","","wong5","gaai1","leoi5","jiu6","gwo3","jat1","zau1","","ngo5","bin6","faa3","wu1","jau5"] },
            { paragraphBreak: true },
            { chars: ["谁","都","只","得","那","双","手"," ","靠","拥","抱","亦","难","任","你","拥","有"], jp: ["seoi4","dou1","zi2","dak1","naa5","soeng1","sau2","","kaau3","jung2","pou5","jik6","naan4","jam6","nei5","jung2","jau5"] },
            { chars: ["要","拥","有","必","先","懂","失","去","怎","接","受"], jp: ["jiu3","jung2","jau5","bit1","sin1","dung2","sat1","heoi3","zam2","zip3","sau6"] },
            { chars: ["曾","沿","着","雪","路","浪","游"," ","为","何","为","好","事","泪","流","？"], jp: ["cang4","jyun4","zoek6","syut3","lou6","long6","jau4","","wai6","ho4","wai6","hou2","si6","leoi6","lau4",""] },
            { chars: ["谁","能","凭","爱","意","要","富","士","山","私","有","？"], jp: ["seoi4","nang4","bang4","oi3","ji3","jiu3","fu3","si6","saan1","si1","jau5",""] },
            { paragraphBreak: true },
            { chars: ["何","不","把","悲","哀","感","觉"," ","假","设","是","来","自","你","虚","构","？"], jp: ["ho4","bat1","baa2","bei1","oi1","gam2","gok3","","gaa2","cit3","si6","loi4","zi6","nei5","heoi1","kau3",""] },
            { chars: ["试","管","里","找","不","到","它","染","污","眼","眸"], jp: ["si3","gun2","leoi5","zaau2","bat1","dou3","taa1","jim5","wu1","ngaan5","mau4"] },
            { chars: ["前","尘","硬","化","像","石","头"," ","随","缘","地","抛","下","便","逃","走"], jp: ["cin4","can4","ngaang6","faa3","zoeng6","sek6","tau4","","ceoi4","jyun4","dei6","paau1","haa6","bin6","tou4","zau2"] },
            { chars: ["我","绝","不","罕","有"," ","往","街","里","绕","过","一","周"," ","我","便","化","乌","有"], jp: ["ngo5","zyut6","bat1","hon2","jau5","","wong5","gaai1","leoi5","jiu6","gwo3","jat1","zau1","","ngo5","bin6","faa3","wu1","jau5"] },
            { paragraphBreak: true },
            { chars: ["你","还","嫌","不","够"," ","我","把","这","陈","年","风","褛","送","赠","你","解","咒"], jp: ["nei5","waan4","jim4","bat1","gau3","","ngo5","baa2","ze5","can4","nin4","fung1","lau6","sung3","zang6","nei5","gaai2","zau3"] }
        ]
;
    if (typeof window !== 'undefined' && window.__songs) {
        window.__songs.push(song);
    }
})();
