// 歌曲：寒舍

(function() {
    const song = {
        id: 371,
        title: "寒舍",
        titleJyutping: ["hon4","se3"],
        artist: "杨千嬅",
        artistJyutping: ["joeng4","cin1","waa6"],
        lyricist: "于逸尧",
        lyricistJyutping: ["jyu1","jat6","jiu4"],
        composer: "伍乐城",
        composerJyutping: ["ng5","lok6","sing4"],
        lyrics: [
            { chars: ["不","理","闷","烦","事","情"], jp: ["bat1","lei5","mun6","faan4","si6","cing4"] },
            { chars: ["不","见","路","过","蜻","蜓"], jp: ["bat1","gin3","lou6","gwo3","cing1","ting4"] },
            { chars: ["这","新","居","多","么","宁","静"], jp: ["ze5","san1","geoi1","do1","maa1","ning4","zing6"] },
            { chars: ["秒","针","的","跳","声","沉","默","地","聆","听"], jp: ["miu5","zam1","dik1","tiu3","sing1","cam4","mak6","dei6","ling4","ting1"] },
            { chars: ["烦","闷","用","冷","静","回","应"], jp: ["faan4","mun6","jung6","laang5","zing6","wui4","jing3"] },
            { paragraphBreak: true },
            { chars: ["如","无","聊","就","看","海"], jp: ["jyu4","mou4","liu4","zau6","hon3","hoi2"] },
            { chars: ["不","必","追","逐","真","爱"], jp: ["bat1","bit1","zeoi1","zuk6","zan1","ngoi3"] },
            { chars: ["间","中","孤","单","亦","可","爱"], jp: ["gaan1","zung1","gu1","daan1","jik6","ho2","ngoi3"] },
            { chars: ["于","沙","发","上","托","腮","静","静","盼","望","露","台","花","开"], jp: ["jyu1","saa1","faat3","soeng6","tok3","soi1","zing6","zing6","paan3","mong6","lou6","toi4","faa1","hoi1"] },
            { chars: ["是","否","更","觉","精","彩"], jp: ["si6","fau2","gang1","gok3","zing1","coi2"] },
            { paragraphBreak: true },
            { chars: ["曾","认","识","恋","爱","家"], jp: ["zang1","jing6","sik1","lyun2","ngoi3","gaa1"] },
            { chars: ["曾","受","伤","变","害","怕"], jp: ["zang1","sau6","soeng1","bin3","hoi6","paa3"] },
            { chars: ["害","怕","遍","地","的","雪","花"], jp: ["hoi6","paa3","pin3","dei6","dik1","syut3","faa1"] },
            { chars: ["圣","诞","除","夕","过","冬"], jp: ["sing3","daan3","ceoi4","zik6","gwo3","dung1"] },
            { chars: ["可","有","节","目","吗"], jp: ["ho2","jau5","zit3","muk6","maa1"] },
            { chars: ["没","有","节","目","太","脱","俗"], jp: ["mut6","jau5","zit3","muk6","taai3","tyut3","zuk6"] },
            { chars: ["怕","看","到","烟","花"], jp: ["paa3","hon3","dou3","jin1","faa1"] },
            { paragraphBreak: true },
            { chars: ["求","自","已","摆","脱","他","还","付","出","了","代","价"], jp: ["kau4","zi6","ji5","baai2","tyut3","taa1","waan4","fu6","ceot1","liu5","doi6","gaai3"] },
            { chars: ["放","弃","爱","情","搬","了","家"], jp: ["fong3","hei3","ngoi3","cing4","bun1","liu5","gaa1"] },
            { chars: ["圣","诞","前","离","别","了","他","的","家"], jp: ["sing3","daan3","cin4","lei4","bit6","liu5","taa1","dik1","gaa1"] },
            { chars: ["将","门","牌","倒","挂"], jp: ["zoeng1","mun4","paai4","dou2","gwaa3"] },
            { chars: ["纵","是","后","悔","了","也","找","不","到","他","的","号","码"], jp: ["zung3","si6","hau6","fui3","liu5","jaa5","zaau2","bat1","dou3","taa1","dik1","hou6","maa5"] },
            { paragraphBreak: true },
            { chars: ["不","怕","淡","忘","热","情"], jp: ["bat1","paa3","daam6","mong4","jit6","cing4"] },
            { chars: ["只","怕","上","帝","显","灵"], jp: ["zi2","paa3","soeng6","dai3","hin2","ling4"] },
            { chars: ["说","他","终","于","也","承","认"], jp: ["syut3","taa1","zung1","jyu1","jaa5","sing4","jing6"] },
            { chars: ["付","出","不","够","多"], jp: ["fu6","ceot1","bat1","gau3","do1"] },
            { chars: ["其","实","在","乎","我"], jp: ["kei4","sat6","zoi6","fu4","ngo5"] },
            { chars: ["无","奈","令","我","亦","难","过"], jp: ["mou4","noi6","ling6","ngo5","jik6","naan4","gwo3"] },
            { paragraphBreak: true },
            { chars: ["试","过","了","没","结","果"], jp: ["si3","gwo3","liu5","mut6","git3","gwo2"] },
            { chars: ["不","管","怎","样","出","错"], jp: ["bat1","gun2","zam2","joeng6","ceot1","co3"] },
            { chars: ["我","只","想","今","后","好","过"], jp: ["ngo5","zi2","soeng2","gam1","hau6","hou2","gwo3"] },
            { chars: ["即","使","再","度","拍","拖","我","也","不","要","飘","泊","巅","簸"], jp: ["zik1","si2","zoi3","dou6","paak3","to1","ngo5","jaa5","bat1","jiu3","piu1","bok6","din1","bo3"] },
            { chars: ["住","我","家"], jp: ["zyu6","ngo5","gaa1"] },
            { chars: ["上","我","的","锁"], jp: ["soeng6","ngo5","dik1","so2"] },
            { paragraphBreak: true },
            { chars: ["曾","认","识","恋","爱","家"], jp: ["zang1","jing6","sik1","lyun2","ngoi3","gaa1"] },
            { chars: ["曾","受","伤","变","害","怕"], jp: ["zang1","sau6","soeng1","bin3","hoi6","paa3"] },
            { chars: ["害","怕","遍","地","的","雪","花"], jp: ["hoi6","paa3","pin3","dei6","dik1","syut3","faa1"] },
            { chars: ["圣","诞","除","夕","过","冬"], jp: ["sing3","daan3","ceoi4","zik6","gwo3","dung1"] },
            { chars: ["可","有","节","目","吗"], jp: ["ho2","jau5","zit3","muk6","maa1"] },
            { chars: ["没","有","节","目","太","脱","俗"], jp: ["mut6","jau5","zit3","muk6","taai3","tyut3","zuk6"] },
            { chars: ["怕","看","到","烟","花"], jp: ["paa3","hon3","dou3","jin1","faa1"] },
            { paragraphBreak: true },
            { chars: ["求","自","已","摆","脱","他","还","付","出","了","代","价"], jp: ["kau4","zi6","ji5","baai2","tyut3","taa1","waan4","fu6","ceot1","liu5","doi6","gaai3"] },
            { chars: ["放","弃","爱","情","搬","了","家"], jp: ["fong3","hei3","ngoi3","cing4","bun1","liu5","gaa1"] },
            { chars: ["圣","诞","前","离","别","了","他","的","家"], jp: ["sing3","daan3","cin4","lei4","bit6","liu5","taa1","dik1","gaa1"] },
            { chars: ["将","门","牌","倒","挂"], jp: ["zoeng1","mun4","paai4","dou2","gwaa3"] },
            { chars: ["纵","是","后","悔","了","也","找","不","到","他","的","号","码"], jp: ["zung3","si6","hau6","fui3","liu5","jaa5","zaau2","bat1","dou3","taa1","dik1","hou6","maa5"] },
            { paragraphBreak: true },
            { chars: ["我","已","搬","家"], jp: ["ngo5","ji5","bun1","gaa1"] },
            { chars: ["忘","掉","他","不","见","他"], jp: ["mong4","diu6","taa1","bat1","gin3","taa1"] },
            { chars: ["曾","受","伤","会","害","怕"], jp: ["zang1","sau6","soeng1","wui6","hoi6","paa3"] },
            { chars: ["害","怕","遍","地","的","雪","花"], jp: ["hoi6","paa3","pin3","dei6","dik1","syut3","faa1"] },
            { chars: ["圣","诞","除","夕","过","冬"], jp: ["sing3","daan3","ceoi4","zik6","gwo3","dung1"] },
            { chars: ["可","有","节","目","吗"], jp: ["ho2","jau5","zit3","muk6","maa1"] },
            { chars: ["没","有","节","目"], jp: ["mut6","jau5","zit3","muk6"] },
            { chars: ["怕","会","嫌","我","太","潇","洒"], jp: ["paa3","wui6","jim4","ngo5","taai3","siu1","saa2"] },
            { paragraphBreak: true },
            { chars: ["能","尽","早","摆","脱","他"], jp: ["nang4","zeon6","zou2","baai2","tyut3","taa1"] },
            { chars: ["情","愿","不","理","代","价"], jp: ["cing4","jyun6","bat1","lei5","doi6","gaai3"] },
            { chars: ["放","弃","爱","情","搬","了","家"], jp: ["fong3","hei3","ngoi3","cing4","bun1","liu5","gaa1"] },
            { chars: ["圣","诞","前","如","若","有","一","天","真","的","分","开","了"], jp: ["sing3","daan3","cin4","jyu4","joek6","jau5","jat1","tin1","zan1","dik1","fan1","hoi1","liu5"] },
            { chars: ["我","亦","能","笑","说"], jp: ["ngo5","jik6","nang4","siu3","syut3"] },
            { chars: ["正","好","早","点","归","家","渡","假"], jp: ["zing3","hou2","zou2","dim2","gwai1","gaa1","dou6","gaa2"] }
        ]
    };
    if (typeof window !== 'undefined' && window.__songs) {
        window.__songs.push(song);
    }
})();
