// 歌曲：少女的祈祷

(function() {
    const song = {
        id: 331,
        title: "少女的祈祷",
        titleJyutping: ["siu2","neoi5","dik1","kei4","tou2"],
        artist: "杨千嬅",
        artistJyutping: ["joeng4","cin1","waa6"],
        lyricist: "林夕",
        lyricistJyutping: ["lam4","zik6"],
        composer: "陈辉阳",
        composerJyutping: ["can4","fai1","joeng4"],
        lyrics: [
            { chars: ["沿","途","与","他","车","厢","中","私","奔","般","恋","爱"], jp: ["jyun4","tou4","jyu5","taa1","ce1","soeng1","zung1","si1","ban1","bun1","lyun2","ngoi3"] },
            { chars: ["再","挤","逼","都","不","放","开"], jp: ["zoi3","zai1","bik1","dou1","bat1","fong3","hoi1"] },
            { chars: ["祈","求","在","路","上","没","任","何","的","阻","碍"], jp: ["kei4","kau4","zoi6","lou6","soeng6","mut6","jam6","ho4","dik1","zo2","ngoi6"] },
            { chars: ["令","愉","快","旅","程","变","悲","哀"], jp: ["ling6","jyu4","faai3","leoi5","cing4","bin3","bei1","oi1"] },
            { chars: ["连","气","两","次","绿","灯","都","过","渡","了"], jp: ["lin4","hei3","loeng5","ci3","luk6","dang1","dou1","gwo3","dou6","liu5"] },
            { chars: ["与","他","再","爱","几","公","里"], jp: ["jyu5","taa1","zoi3","ngoi3","gei2","gung1","lei5"] },
            { chars: ["当","这","盏","灯","转","红","便","会","别","离"], jp: ["dong1","ze5","zaan2","dang1","zyun2","hung4","bin6","wui6","bit6","lei4"] },
            { chars: ["凭","运","气","决","定","我","生","死"], jp: ["pang4","wan6","hei3","kyut3","ding6","ngo5","sang1","sei2"] },
            { paragraphBreak: true },
            { chars: ["祈","求","天","地","放","过","一","双","恋","人"], jp: ["kei4","kau4","tin1","dei6","fong3","gwo3","jat1","soeng1","lyun2","jan4"] },
            { chars: ["怕","发","生","的","永","远","别","发","生"], jp: ["paa3","faat3","sang1","dik1","wing5","jyun5","bit6","faat3","sang1"] },
            { chars: ["从","来","未","顺","利","遇","上","好","景","降","临"], jp: ["cung4","loi4","mei6","seon6","lei6","jyu6","soeng6","hou2","ging2","gong3","lam4"] },
            { chars: ["如","何","能","重","拾","信","心"], jp: ["jyu4","ho4","nang4","cung5","sap6","seon3","sam1"] },
            { chars: ["祈","求","天","父","做","十","分","钟","好","人"], jp: ["kei4","kau4","tin1","fu6","zou6","sap6","fan1","zung1","hou2","jan4"] },
            { chars: ["赐","我","他","的","吻"], jp: ["ci3","ngo5","taa1","dik1","man5"] },
            { chars: ["如","怜","悯","罪","人"], jp: ["jyu4","lin4","man5","zeoi6","jan4"] },
            { chars: ["我","爱","主"], jp: ["ngo5","ngoi3","zyu2"] },
            { chars: ["同","时","亦","爱","一","位","世","人"], jp: ["tung4","si4","jik6","ngoi3","jat1","wai6","sai3","jan4"] },
            { chars: ["祈","求","沿","途","未","变","心"], jp: ["kei4","kau4","jyun4","tou4","mei6","bin3","sam1"] },
            { chars: ["请","给","我","护","荫"], jp: ["cing2","kap1","ngo5","wu6","jam1"] },
            { paragraphBreak: true },
            { chars: ["为","了","他"], jp: ["wai4","liu5","taa1"] },
            { chars: ["不","懂","祷","告","都","敢","祷","告"], jp: ["bat1","dung2","tou2","gou3","dou1","gam2","tou2","gou3"] },
            { chars: ["谁","愿","眷","顾","这","种","信","徒"], jp: ["seoi4","jyun6","gyun3","gu3","ze5","zung2","seon3","tou4"] },
            { chars: ["用","两","手","遮","掩","双","眼","专","心","倾","诉"], jp: ["jung6","loeng5","sau2","ze1","jim2","soeng1","ngaan5","zyun1","sam1","king1","sou3"] },
            { chars: ["宁","愿","答","案"], jp: ["ning4","jyun6","daap3","on3"] },
            { chars: ["望","不","到"], jp: ["mong6","bat1","dou3"] },
            { chars: ["唯","求","与","他","车","厢","中","可","抵","达","未","来"], jp: ["wai4","kau4","jyu5","taa1","ce1","soeng1","zung1","ho2","dai2","daat6","mei6","loi4"] },
            { chars: ["到","车","毁","都","不","放","开"], jp: ["dou3","ce1","wai2","dou1","bat1","fong3","hoi1"] },
            { chars: ["无","论","路","上","历","尽","任","何","的","伤","害"], jp: ["mou4","leon6","lou6","soeng6","lik6","zeon6","jam6","ho4","dik1","soeng1","hoi6"] },
            { chars: ["任","由","我","决","定","爱","不","爱"], jp: ["jam6","jau4","ngo5","kyut3","ding6","ngoi3","bat1","ngoi3"] },
            { paragraphBreak: true },
            { chars: ["祈","求","天","地","放","过","一","双","恋","人"], jp: ["kei4","kau4","tin1","dei6","fong3","gwo3","jat1","soeng1","lyun2","jan4"] },
            { chars: ["怕","发","生","的","永","远","别","发","生"], jp: ["paa3","faat3","sang1","dik1","wing5","jyun5","bit6","faat3","sang1"] },
            { chars: ["从","来","未","顺","利","遇","上","好","景","降","临"], jp: ["cung4","loi4","mei6","seon6","lei6","jyu6","soeng6","hou2","ging2","gong3","lam4"] },
            { chars: ["如","何","能","重","拾","信","心"], jp: ["jyu4","ho4","nang4","cung5","sap6","seon3","sam1"] },
            { chars: ["祈","求","天","父","做","十","分","钟","好","人"], jp: ["kei4","kau4","tin1","fu6","zou6","sap6","fan1","zung1","hou2","jan4"] },
            { chars: ["赐","我","他","的","吻"], jp: ["ci3","ngo5","taa1","dik1","man5"] },
            { chars: ["如","怜","悯","罪","人"], jp: ["jyu4","lin4","man5","zeoi6","jan4"] },
            { chars: ["我","爱","主"], jp: ["ngo5","ngoi3","zyu2"] },
            { chars: ["同","时","亦","爱","一","位","爱","人"], jp: ["tung4","si4","jik6","ngoi3","jat1","wai6","ngoi3","jan4"] },
            { chars: ["祈","求","　","沿","途","未","变","心"], jp: ["kei4","kau4","","jyun4","tou4","mei6","bin3","sam1"] },
            { chars: ["请","给","我","护","荫"], jp: ["cing2","kap1","ngo5","wu6","jam1"] },
            { paragraphBreak: true },
            { chars: ["为","了","他"], jp: ["wai4","liu5","taa1"] },
            { chars: ["不","懂","祷","告","都","敢","祷","告"], jp: ["bat1","dung2","tou2","gou3","dou1","gam2","tou2","gou3"] },
            { chars: ["谁","愿","眷","顾","这","种","信","徒"], jp: ["seoi4","jyun6","gyun3","gu3","ze5","zung2","seon3","tou4"] },
            { chars: ["太","爱","他","怎","么","想","到","这","么","恐","怖"], jp: ["taai3","ngoi3","taa1","zam2","maa1","soeng2","dou3","ze5","maa1","hung2","bou3"] },
            { chars: ["对","绿","灯"], jp: ["deoi3","luk6","dang1"] },
            { chars: ["去","哀","求","哭","诉"], jp: ["heoi3","oi1","kau4","huk1","sou3"] },
            { paragraphBreak: true },
            { chars: ["然","而","天","父","并","未","体","恤","好","人"], jp: ["jin4","ji4","tin1","fu6","bing6","mei6","tai2","seot1","hou2","jan4"] },
            { chars: ["到","我","睁","开","眼"], jp: ["dou3","ngo5","zang1","hoi1","ngaan5"] },
            { chars: ["无","明","灯","指","引"], jp: ["mou4","ming4","dang1","zi2","jan5"] },
            { chars: ["我","爱","主"], jp: ["ngo5","ngoi3","zyu2"] },
            { chars: ["为","何","任","我","身","边","爱","人"], jp: ["wai4","ho4","jam6","ngo5","san1","bin1","ngoi3","jan4"] },
            { chars: ["离","弃","了","我","下","了","车"], jp: ["lei4","hei3","liu5","ngo5","haa6","liu5","ce1"] },
            { chars: ["你","怎","可","答","允"], jp: ["nei5","zam2","ho2","daap3","wan5"] }
        ]
    };
    if (typeof window !== 'undefined' && window.__songs) {
        window.__songs.push(song);
    }
})();
