// 歌曲：忍

(function() {
    const song = {
        id: 33,
        title: "忍",
        titleJyutping: ["jan2"],
        artist: "林欣彤",
        artistJyutping: ["lam4","jan1","tung4"],
        lyricist: "林夕",
        lyricistJyutping: ["lam4","zik6"],
        composer: "黄思律/Larry Wong",
        composerJyutping: ["wong4","si1","leot6","","","","","","","","","","",""],
        lyrics: [
            { chars: ["自","少","听","得","多","爱","是","细","水","长","流"], jp: ["zi6","siu2","ting1","dak1","do1","ngoi3","si6","sai3","seoi2","coeng4","lau4"] },
            { chars: ["吞","声","忍","气","够"," ","只","能","包","庇"], jp: ["tan1","sing1","jan2","hei3","gau3","","zi2","nang4","baau1","bei3"] },
            { chars: ["延","续","你","的","下","流"], jp: ["jin4","zuk6","nei5","dik1","haa6","lau4"] },
            { paragraphBreak: true },
            { chars: ["或","者","苦","中","苦","吃","罢","我","居","然","能","承","受"], jp: ["waak6","ze2","fu2","zung1","fu2","hek3","baa6","ngo5","geoi1","jin4","nang4","sing4","sau6"] },
            { chars: ["良","心","已"," ","硬","似","石","头"], jp: ["loeng4","sam1","ji5","","ngaang6","ci5","sek6","tau4"] },
            { chars: ["就","算","死","都","要","在","你","手"], jp: ["zau6","syun3","sei2","dou1","jiu3","zoi6","nei5","sau2"] },
            { paragraphBreak: true },
            { chars: ["是","我"," ","我","也","会","顺","手","糟","质","这","个","自","己"], jp: ["si6","ngo5","","ngo5","jaa5","wui6","seon6","sau2","zou1","zat1","ze5","go3","zi6","gei2"] },
            { chars: ["凭","什","么","使","你","爱","上","这","奴","婢"], jp: ["pang4","sap6","maa1","si2","nei5","ngoi3","soeng6","ze5","nou4","pei5"] },
            { chars: ["谁","还","自","以","为","仍","停","留","十","八","世","纪"], jp: ["seoi4","waan4","zi6","ji5","wai4","jing4","ting4","lau4","sap6","baat3","sai3","gei2"] },
            { paragraphBreak: true },
            { chars: ["什","么","都","有","底","线"," ","为","何","要","忍"], jp: ["sap6","maa1","dou1","jau5","dai2","sin3","","wai4","ho4","jiu3","jan2"] },
            { chars: ["什","么","使","你","胆","敢"," ","横","蛮","至","今"], jp: ["sap6","maa1","si2","nei5","daam2","gam2","","waang4","maan4","zi3","gam1"] },
            { chars: ["若","为","了","怕","与","你","吵","架"], jp: ["joek6","wai4","liu5","paa3","jyu5","nei5","caau2","gaa3"] },
            { chars: ["沉","默","却","何","曾","让","我","像","个","人"], jp: ["cam4","mak6","koek3","ho4","zang1","joeng6","ngo5","zoeng6","go3","jan4"] },
            { paragraphBreak: true },
            { chars: ["什","么","好","处","使","我"," ","仍","然","要","忍"], jp: ["sap6","maa1","hou2","cyu5","si2","ngo5","","jing4","jin4","jiu3","jan2"] },
            { chars: ["未","讨","好","你","先","鄙","视","自","己"], jp: ["mei6","tou2","hou2","nei5","sin1","pei2","si6","zi6","gei2"] },
            { chars: ["害","你","饰","演","惯","坏","人"], jp: ["hoi6","nei5","sik1","jin2","gwaan3","waai6","jan4"] },
            { chars: ["原","谅","你","也","难","容","许","我"], jp: ["jyun4","loeng6","nei5","jaa5","naan4","jung4","heoi2","ngo5"] },
            { chars: ["长","期","难","受","都","忍"," ","也","是","瘾"], jp: ["coeng4","kei4","naan4","sau6","dou1","jan2","","jaa5","si6","jan5"] },
            { paragraphBreak: true },
            { chars: ["或","者","应","该","撕","破","脸","再","不","回","头"], jp: ["waak6","ze2","jing3","goi1","si1","po3","lim5","zoi3","bat1","wui4","tau4"] },
            { chars: ["谁","知","我"," ","未","敢","生","气"], jp: ["seoi4","zi1","ngo5","","mei6","gam2","sang1","hei3"] },
            { chars: ["被","放","生","苦","过","被","困","死"], jp: ["bei6","fong3","sang1","fu2","gwo3","bei6","kwan3","sei2"] },
            { paragraphBreak: true },
            { chars: ["问","我"," ","爱","到","了","自","卑","自","贱","没","有","人","味"], jp: ["man6","ngo5","","ngoi3","dou3","liu5","zi6","bei1","zi6","zin6","mut6","jau5","jan4","mei6"] },
            { chars: ["平","日","不","必","照","镜","也","会","嫌","弃"], jp: ["ping4","jat6","bat1","bit1","ziu3","geng3","jaa5","wui6","jim4","hei3"] },
            { chars: ["凭","贤","淑","纵","容","狂","人","同","样","也","可","鄙"], jp: ["pang4","jin4","suk6","zung3","jung4","kong4","jan4","tung4","joeng6","jaa5","ho2","pei2"] },
            { paragraphBreak: true },
            { chars: ["什","么","都","有","底","线"," ","为","何","要","忍"], jp: ["sap6","maa1","dou1","jau5","dai2","sin3","","wai4","ho4","jiu3","jan2"] },
            { chars: ["什","么","使","你","胆","敢"," ","横","蛮","至","今"], jp: ["sap6","maa1","si2","nei5","daam2","gam2","","waang4","maan4","zi3","gam1"] },
            { chars: ["若","为","了","怕","与","你","吵","架"], jp: ["joek6","wai4","liu5","paa3","jyu5","nei5","caau2","gaa3"] },
            { chars: ["沉","默","却","何","曾","让","我","像","个","人"], jp: ["cam4","mak6","koek3","ho4","zang1","joeng6","ngo5","zoeng6","go3","jan4"] },
            { paragraphBreak: true },
            { chars: ["什","么","好","处","使","我"," ","仍","然","要","忍"], jp: ["sap6","maa1","hou2","cyu5","si2","ngo5","","jing4","jin4","jiu3","jan2"] },
            { chars: ["未","讨","好","你","先","鄙","视","自","己"], jp: ["mei6","tou2","hou2","nei5","sin1","pei2","si6","zi6","gei2"] },
            { chars: ["害","你","饰","演","惯","坏","人"], jp: ["hoi6","nei5","sik1","jin2","gwaan3","waai6","jan4"] },
            { chars: ["原","谅","你","也","难","容","许","我"], jp: ["jyun4","loeng6","nei5","jaa5","naan4","jung4","heoi2","ngo5"] },
            { chars: ["长","期","难","受","都","忍"," ","也","是","瘾"], jp: ["coeng4","kei4","naan4","sau6","dou1","jan2","","jaa5","si6","jan5"] },
            { paragraphBreak: true },
            { chars: ["可","笑","是","我","也","真","的","以","为"], jp: ["ho2","siu3","si6","ngo5","jaa5","zan1","dik1","ji5","wai4"] },
            { chars: ["能","屈","都","应","该","能","伸"], jp: ["nang4","wat1","dou1","jing3","goi1","nang4","san1"] },
            { paragraphBreak: true },
            { chars: ["什","么","都","有","底","线"," ","为","何","要","忍"], jp: ["sap6","maa1","dou1","jau5","dai2","sin3","","wai4","ho4","jiu3","jan2"] },
            { chars: ["什","么","使","你","胆","敢"," ","横","蛮","至","今"], jp: ["sap6","maa1","si2","nei5","daam2","gam2","","waang4","maan4","zi3","gam1"] },
            { chars: ["若","命","里","要","与","你","吵","架"], jp: ["joek6","ming6","lei5","jiu3","jyu5","nei5","caau2","gaa3"] },
            { chars: ["沉","默","也","未","能","成","金"," ","怎","么","吞"], jp: ["cam4","mak6","jaa5","mei6","nang4","sing4","gam1","","zam2","maa1","tan1"] },
            { paragraphBreak: true },
            { chars: ["为","得","到","那","点","爱"," ","何","尝","靠","忍"], jp: ["wai4","dak1","dou3","naa5","dim2","ngoi3","","ho4","soeng4","kaau3","jan2"] },
            { chars: ["付","出","的","却","可","毁","掉","人","生"], jp: ["fu6","ceot1","dik1","koek3","ho2","wai2","diu6","jan4","sang1"] },
            { chars: ["被","爱","得","不","似","活","人"], jp: ["bei6","ngoi3","dak1","bat1","ci5","wut6","jan4"] },
            { chars: ["其","实","我","亦","高","攀","着","你"], jp: ["kei4","sat6","ngo5","jik6","gou1","paan1","zoek6","nei5"] },
            { chars: ["奴","隶","可","能"," ","合","衬"], jp: ["nou4","dai6","ho2","nang4","","hap6","can3"] }
        ]
    };
    if (typeof window !== 'undefined' && window.__songs) {
        window.__songs.push(song);
    }
})();
