// 歌曲：抱拥这分钟

(function() {
    const song = {
        id: 299,
        title: "抱拥这分钟",
        titleJyutping: ["pou5","jung2","ze5","fan1","zung1"],
        artist: "陈奕迅",
        artistJyutping: ["can4","jik6","seon3"],
        lyricist: "潘源良",
        lyricistJyutping: ["pun1","jyun4","loeng4"],
        composer: "李振权",
        composerJyutping: ["lei5","zan3","kyun4"],
        lyrics: [
            { chars: ["忘","记","了","世","界","这","分","钟"], jp: ["mong4","gei3","liu5","sai3","gaai3","ze5","fan1","zung1"] },
            { chars: ["跌","进","了","这","爱","的","裂","缝"], jp: ["dit3","zeon3","liu5","ze5","ngoi3","dik1","lit6","fung4"] },
            { chars: ["燃","亮","烛","光"], jp: ["jin4","loeng6","zuk1","gwong1"] },
            { chars: ["只","管","相","拥"], jp: ["zi2","gun2","soeng1","jung2"] },
            { chars: ["来","占","据","了","这","晚","星","空"], jp: ["loi4","zim1","geoi3","liu5","ze5","maan5","sing1","hung1"] },
            { chars: ["捉","紧","一","刹","那","的","认","同"], jp: ["zuk1","gan2","jat1","caat3","naa5","dik1","jing6","tung4"] },
            { chars: ["如","梦","的","将","来"], jp: ["jyu4","mung6","dik1","zoeng1","loi4"] },
            { chars: ["尽","管","一","点","不","懂"], jp: ["zeon6","gun2","jat1","dim2","bat1","dung2"] },
            { paragraphBreak: true },
            { chars: ["完","全","明","白","是","放","纵"], jp: ["jyun4","cyun4","ming4","baak6","si6","fong3","zung3"] },
            { chars: ["但","是","只","得","这","刻","可","相","信"], jp: ["daan6","si6","zi2","dak1","ze5","hak1","ho2","soeng1","seon3"] },
            { chars: ["未","来","又","怕","会","终","于","都","扑","空"], jp: ["mei6","loi4","jau6","paa3","wui6","zung1","jyu1","dou1","pok3","hung1"] },
            { paragraphBreak: true },
            { chars: ["你","叫","我","最","快","乐"], jp: ["nei5","giu3","ngo5","zeoi3","faai3","lok6"] },
            { chars: ["你","也","叫","我","最","心","痛"], jp: ["nei5","jaa5","giu3","ngo5","zeoi3","sam1","tung3"] },
            { chars: ["爱","在","迷","惘","中"], jp: ["ngoi3","zoi6","mai4","mong5","zung1"] },
            { chars: ["你","叫","我","最","渴","望"], jp: ["nei5","giu3","ngo5","zeoi3","hot3","mong6"] },
            { chars: ["却","也","叫","我","猜","不","中"], jp: ["koek3","jaa5","giu3","ngo5","caai1","bat1","zung1"] },
            { chars: ["谁","可","以","这","样","折","衷"], jp: ["seoi4","ho2","ji5","ze5","joeng6","zit3","zung1"] },
            { paragraphBreak: true },
            { chars: ["曾","与","你","爱","过","却","匆","匆"], jp: ["zang1","jyu5","nei5","ngoi3","gwo3","koek3","cung1","cung1"] },
            { chars: ["过","去","己","有","太","多","类","同"], jp: ["gwo3","heoi3","gei2","jau5","taai3","do1","leoi6","tung4"] },
            { chars: ["谁","在","心","中"], jp: ["seoi4","zoi6","sam1","zung1"] },
            { chars: ["怎","猜","得","准"], jp: ["zam2","caai1","dak1","zeon2"] },
            { chars: ["能","跌","进","这","晚","爱","光","中"], jp: ["nang4","dit3","zeon3","ze5","maan5","ngoi3","gwong1","zung1"] },
            { chars: ["彷","佛","一","切","已","经","共","同"], jp: ["pong4","fat6","jat1","cit3","ji5","ging1","gung6","tung4"] },
            { chars: ["仍","是","不","敢","祈","求","热","恋","多","一","分","钟"], jp: ["jing4","si6","bat1","gam2","kei4","kau4","jit6","lyun2","do1","jat1","fan1","zung1"] },
            { paragraphBreak: true },
            { chars: ["完","全","明","白","是","放","纵"], jp: ["jyun4","cyun4","ming4","baak6","si6","fong3","zung3"] },
            { chars: ["但","是","只","得","这","刻","可","相","信"], jp: ["daan6","si6","zi2","dak1","ze5","hak1","ho2","soeng1","seon3"] },
            { chars: ["未","来","又","怕","会","终","于","都","扑","空"], jp: ["mei6","loi4","jau6","paa3","wui6","zung1","jyu1","dou1","pok3","hung1"] },
            { paragraphBreak: true },
            { chars: ["你","叫","我","最","快","乐"], jp: ["nei5","giu3","ngo5","zeoi3","faai3","lok6"] },
            { chars: ["你","也","叫","我","最","心","痛"], jp: ["nei5","jaa5","giu3","ngo5","zeoi3","sam1","tung3"] },
            { chars: ["爱","在","迷","惘","中"], jp: ["ngoi3","zoi6","mai4","mong5","zung1"] },
            { chars: ["你","叫","我","最","渴","望"], jp: ["nei5","giu3","ngo5","zeoi3","hot3","mong6"] },
            { chars: ["却","也","叫","我","猜","不","中"], jp: ["koek3","jaa5","giu3","ngo5","caai1","bat1","zung1"] },
            { chars: ["谁","可","以","这","样","折","衷"], jp: ["seoi4","ho2","ji5","ze5","joeng6","zit3","zung1"] },
            { paragraphBreak: true },
            { chars: ["要","说","永","远","爱","吧"], jp: ["jiu3","syut3","wing5","jyun5","ngoi3","baa6"] },
            { chars: ["却","怕","仍","然","未","相","信"], jp: ["koek3","paa3","jing4","jin4","mei6","soeng1","seon3"] },
            { chars: ["永","未","能","看","通"], jp: ["wing5","mei6","nang4","hon3","tung1"] },
            { chars: ["要","说","这","晚","算","吧"], jp: ["jiu3","syut3","ze5","maan5","syun3","baa6"] },
            { chars: ["却","觉","爱","己","经","失","控"], jp: ["koek3","gok3","ngoi3","gei2","ging1","sat1","hung3"] },
            { chars: ["宁","愿","再","继","续","抱","拥"], jp: ["ning4","jyun6","zoi3","gai3","zuk6","pou5","jung2"] },
            { paragraphBreak: true },
            { chars: ["完","全","明","白","是","放","纵"], jp: ["jyun4","cyun4","ming4","baak6","si6","fong3","zung3"] },
            { chars: ["但","是","只","得","这","刻","可","相","信"], jp: ["daan6","si6","zi2","dak1","ze5","hak1","ho2","soeng1","seon3"] },
            { chars: ["未","来","又","怕","会","终","于","都","扑","空"], jp: ["mei6","loi4","jau6","paa3","wui6","zung1","jyu1","dou1","pok3","hung1"] },
            { paragraphBreak: true },
            { chars: ["你","叫","我","最","快","乐"], jp: ["nei5","giu3","ngo5","zeoi3","faai3","lok6"] },
            { chars: ["你","也","叫","我","最","心","痛"], jp: ["nei5","jaa5","giu3","ngo5","zeoi3","sam1","tung3"] },
            { chars: ["爱","在","迷","惘","中"], jp: ["ngoi3","zoi6","mai4","mong5","zung1"] },
            { chars: ["你","叫","我","最","渴","望"], jp: ["nei5","giu3","ngo5","zeoi3","hot3","mong6"] },
            { chars: ["却","也","叫","我","猜","不","中"], jp: ["koek3","jaa5","giu3","ngo5","caai1","bat1","zung1"] },
            { chars: ["谁","可","以","这","样","折","衷"], jp: ["seoi4","ho2","ji5","ze5","joeng6","zit3","zung1"] },
            { paragraphBreak: true },
            { chars: ["要","说","永","远","爱","吧"], jp: ["jiu3","syut3","wing5","jyun5","ngoi3","baa6"] },
            { chars: ["却","怕","仍","然","未","相","信"], jp: ["koek3","paa3","jing4","jin4","mei6","soeng1","seon3"] },
            { chars: ["永","未","能","看","通"], jp: ["wing5","mei6","nang4","hon3","tung1"] },
            { chars: ["要","说","这","晚","算","吧"], jp: ["jiu3","syut3","ze5","maan5","syun3","baa6"] },
            { chars: ["却","觉","爱","己","经","失","控"], jp: ["koek3","gok3","ngoi3","gei2","ging1","sat1","hung3"] },
            { chars: ["宁","愿","再","继","续","抱","拥"], jp: ["ning4","jyun6","zoi3","gai3","zuk6","pou5","jung2"] },
            { paragraphBreak: true },
            { chars: ["相","拥"," ","心","痛"], jp: ["soeng1","jung2","","sam1","tung3"] }
        ]
    };
    if (typeof window !== 'undefined' && window.__songs) {
        window.__songs.push(song);
    }
})();
