// 歌曲：杨千嬅

(function() {
    const song = {
        id: 375,
        title: "杨千嬅",
        titleJyutping: ["joeng4","cin1","waa6"],
        artist: "杨千嬅",
        artistJyutping: ["joeng4","cin1","waa6"],
        lyricist: "林夕",
        lyricistJyutping: ["lam4","zik6"],
        composer: "Eric Kwok",
        composerJyutping: ["","","","","","","","",""],
        lyrics: [
            { chars: ["讲","啲","嘢","俾","你","听"], jp: ["gong2","di1","je5","bei2","nei5","ting1"] },
            { paragraphBreak: true },
            { chars: ["谁","人","曾","爱","过","你"], jp: ["seoi4","jan4","zang1","ngoi3","gwo3","nei5"] },
            { chars: ["你","尽","量","幻","想","他","贪","你","什","么"], jp: ["nei5","zeon6","loeng4","waan6","soeng2","taa1","taam1","nei5","sap6","maa1"] },
            { chars: ["好","心","地","也","不","错"], jp: ["hou2","sam1","dei6","jaa5","bat1","co3"] },
            { chars: ["谁","人","曾","厌","弃","你"], jp: ["seoi4","jan4","zang1","jim3","hei3","nei5"] },
            { chars: ["你","问","问","自","己","他","憎","你","什","么"], jp: ["nei5","man6","man6","zi6","gei2","taa1","zang1","nei5","sap6","maa1"] },
            { chars: ["或","是","怕","你","会","肚","饿"], jp: ["waak6","si6","paa3","nei5","wui6","tou5","ngo6"] },
            { paragraphBreak: true },
            { chars: ["如","果","想","照","耀","万","人"], jp: ["jyu4","gwo2","soeng2","ziu3","jiu6","maan6","jan4"] },
            { chars: ["请","加","点","信","心"], jp: ["cing2","gaa1","dim2","seon3","sam1"] },
            { chars: ["如","果","想","抱","住","情","人"], jp: ["jyu4","gwo2","soeng2","pou5","zyu6","cing4","jan4"] },
            { chars: ["请","吸","取","教","训"], jp: ["cing2","kap1","ceoi2","gaau3","fan3"] },
            { chars: ["如","果","想","快","乐","做","人"], jp: ["jyu4","gwo2","soeng2","faai3","lok6","zou6","jan4"] },
            { chars: ["请","敲","敲","你","心"], jp: ["cing2","haau1","haau1","nei5","sam1"] },
            { chars: ["如","果","可","磊","落","做","人"], jp: ["jyu4","gwo2","ho2","leoi5","lok6","zou6","jan4"] },
            { chars: ["你","会","更","吸","引"], jp: ["nei5","wui6","gang1","kap1","jan5"] },
            { paragraphBreak: true },
            { chars: ["童","年","时","那","个","你"], jp: ["tung4","nin4","si4","naa5","go3","nei5"] },
            { chars: ["与","弟","弟","在","家","中","演","你","自","己"], jp: ["jyu5","dai6","dai6","zoi6","gaa1","zung1","jin2","nei5","zi6","gei2"] },
            { chars: ["哭","只","因","你","欢","喜"], jp: ["huk1","zi2","jan1","nei5","fun1","hei2"] },
            { chars: ["成","年","人","劝","过","你"], jp: ["sing4","nin4","jan4","hyun3","gwo3","nei5"] },
            { chars: ["你","现","在","大","个","需","要","做","大","戏"], jp: ["nei5","jin6","zoi6","daai6","go3","seoi1","jiu3","zou6","daai6","hei3"] },
            { chars: ["但","别","要","太","过","顾","忌"], jp: ["daan6","bit6","jiu3","taai3","gwo3","gu3","gei6"] },
            { paragraphBreak: true },
            { chars: ["如","果","想","照","耀","万","人"], jp: ["jyu4","gwo2","soeng2","ziu3","jiu6","maan6","jan4"] },
            { chars: ["请","加","点","信","心"], jp: ["cing2","gaa1","dim2","seon3","sam1"] },
            { chars: ["如","果","想","抱","住","情","人"], jp: ["jyu4","gwo2","soeng2","pou5","zyu6","cing4","jan4"] },
            { chars: ["请","吸","取","教","训"], jp: ["cing2","kap1","ceoi2","gaau3","fan3"] },
            { chars: ["如","果","想","快","乐","做","人"], jp: ["jyu4","gwo2","soeng2","faai3","lok6","zou6","jan4"] },
            { chars: ["请","敲","敲","你","心"], jp: ["cing2","haau1","haau1","nei5","sam1"] },
            { chars: ["如","果","可","磊","落","做","人"], jp: ["jyu4","gwo2","ho2","leoi5","lok6","zou6","jan4"] },
            { chars: ["你","会","更","吸","引"], jp: ["nei5","wui6","gang1","kap1","jan5"] },
            { paragraphBreak: true },
            { chars: ["你","有","个","个","也","有"], jp: ["nei5","jau5","go3","go3","jaa5","jau5"] },
            { chars: ["你","有","爸","爸","妈","妈"], jp: ["nei5","jau5","baa1","baa1","maa1","maa1"] },
            { chars: ["你","有","占","过","卦"], jp: ["nei5","jau5","zim1","gwo3","gwaa3"] },
            { chars: ["你","有","几","口","一","家"], jp: ["nei5","jau5","gei2","hau2","jat1","gaa1"] },
            { chars: ["你","亦","有","收","过","花","得","过","初","吻","放","过","烟","花"], jp: ["nei5","jik6","jau5","sau1","gwo3","faa1","dak1","gwo3","co1","man5","fong3","gwo3","jin1","faa1"] },
            { chars: ["你","的","八","字","看","透","了","吗"], jp: ["nei5","dik1","baat3","zi6","hon3","tau3","liu5","maa1"] },
            { chars: ["你","有","苦","恋","的","他"], jp: ["nei5","jau5","fu2","lyun2","dik1","taa1"] },
            { chars: ["你","有","胆","却","怕"], jp: ["nei5","jau5","daam2","koek3","paa3"] },
            { chars: ["你","有","许","多","牵","挂"], jp: ["nei5","jau5","heoi2","do1","hin1","gwaa3"] },
            { chars: ["你","未","有","却","恨","有"], jp: ["nei5","mei6","jau5","koek3","han6","jau5"] },
            { chars: ["有","时","笑","对","你","说","过","来","吧"], jp: ["jau5","si4","siu3","deoi3","nei5","syut3","gwo3","loi4","baa6"] },
            { paragraphBreak: true },
            { chars: ["如","果","想","照","耀","万","人"], jp: ["jyu4","gwo2","soeng2","ziu3","jiu6","maan6","jan4"] },
            { chars: ["请","加","点","信","心"], jp: ["cing2","gaa1","dim2","seon3","sam1"] },
            { chars: ["如","果","想","抱","住","情","人"], jp: ["jyu4","gwo2","soeng2","pou5","zyu6","cing4","jan4"] },
            { chars: ["请","吸","取","教","训"], jp: ["cing2","kap1","ceoi2","gaau3","fan3"] },
            { chars: ["如","果","想","快","乐","做","人"], jp: ["jyu4","gwo2","soeng2","faai3","lok6","zou6","jan4"] },
            { chars: ["请","敲","敲","你","心"], jp: ["cing2","haau1","haau1","nei5","sam1"] },
            { chars: ["如","果","可","磊","落","做","人"], jp: ["jyu4","gwo2","ho2","leoi5","lok6","zou6","jan4"] },
            { chars: ["你","会","更","吸","引"], jp: ["nei5","wui6","gang1","kap1","jan5"] },
            { paragraphBreak: true },
            { chars: ["童","年","时","那","个","你"], jp: ["tung4","nin4","si4","naa5","go3","nei5"] },
            { chars: ["与","弟","弟","在","家","中","演","你","自","己"], jp: ["jyu5","dai6","dai6","zoi6","gaa1","zung1","jin2","nei5","zi6","gei2"] },
            { chars: ["哭","只","因","你","欢","喜"], jp: ["huk1","zi2","jan1","nei5","fun1","hei2"] },
            { chars: ["成","年","人","劝","过","你"], jp: ["sing4","nin4","jan4","hyun3","gwo3","nei5"] },
            { chars: ["你","现","在","大","个","需","要","做","大","戏"], jp: ["nei5","jin6","zoi6","daai6","go3","seoi1","jiu3","zou6","daai6","hei3"] },
            { chars: ["但","是","我","永","远","爱","你"], jp: ["daan6","si6","ngo5","wing5","jyun5","ngoi3","nei5"] }
        ]
    };
    if (typeof window !== 'undefined' && window.__songs) {
        window.__songs.push(song);
    }
})();
