// 歌曲：沙龙

(function() {
    const song = {
        id: 418,
        title: "沙龙",
        titleJyutping: ["saa1","lung4"],
        artist: "陈奕迅",
        artistJyutping: ["can4","jik6","seon3"],
        lyricist: "黄伟文",
        lyricistJyutping: ["wong4","wai5","man4"],
        composer: "陈奕迅",
        composerJyutping: ["can4","jik6","seon3"],
        lyrics: [
            { chars: ["对","焦"," ","她","的","爱"], jp: ["deoi3","ziu1","","taa1","dik1","ngoi3"] },
            { chars: ["对","慢","了"], jp: ["deoi3","maan6","liu5"] },
            { chars: ["爱","人","会","失","去","可","爱"], jp: ["ngoi3","jan4","wui6","sat1","heoi3","ho2","ngoi3"] },
            { chars: ["记","低"," ","这","感","慨"], jp: ["gei3","dai1","","ze5","gam2","koi3"] },
            { chars: ["世","事","变"], jp: ["sai3","si6","bin3"] },
            { chars: ["有","没","有","将","你","淹","盖"], jp: ["jau5","mut6","jau5","zoeng1","nei5","jim1","goi3"] },
            { paragraphBreak: true },
            { chars: ["只","一","格"], jp: ["zi2","jat1","gaak3"] },
            { chars: ["经","典","的","偶","遇","已"], jp: ["ging1","din2","dik1","ngau5","jyu6","ji5"] },
            { chars: ["不","再"], jp: ["bat1","zoi3"] },
            { chars: ["尽","量","框","住","目","前","大","概"], jp: ["zeon6","loeng4","kwaang1","zyu6","muk6","cin4","daai6","koi3"] },
            { paragraphBreak: true },
            { chars: ["留","住"," ","温","度"," ","速","度"," ","温","柔","和","愤","怒"], jp: ["lau4","zyu6","","wan1","dou6","","cuk1","dou6","","wan1","jau4","wo4","fan5","nou6"] },
            { chars: ["凝","住"," ","今","日"," ","怎","样"," ","好"], jp: ["jing4","zyu6","","gam1","jat6","","zam2","joeng6","","hou2"] },
            { chars: ["捉","紧"," ","生","命","浓","度"], jp: ["zuk1","gan2","","sang1","ming6","nung4","dou6"] },
            { chars: ["坦","白","流","露"], jp: ["taan2","baak6","lau4","lou6"] },
            { chars: ["感","情","和","态","度"], jp: ["gam2","cing4","wo4","taai3","dou6"] },
            { chars: ["留","下"," ","浮","光"," ","掠","影"," ","飞","舞"], jp: ["lau4","haa6","","fau4","gwong1","","loek6","jing2","","fei1","mou5"] },
            { paragraphBreak: true },
            { chars: ["每","张"," ","都","罕","有"], jp: ["mui5","zoeng1","","dou1","hon2","jau5"] },
            { chars: ["拍","下","过"], jp: ["paak3","haa6","gwo3"] },
            { chars: ["记","住","过"], jp: ["gei3","zyu6","gwo3"] },
            { chars: ["好","过","拥","有"], jp: ["hou2","gwo3","jung2","jau5"] },
            { chars: ["光","圈","爱","漫","游"], jp: ["gwong1","hyun1","ngoi3","maan6","jau4"] },
            { chars: ["眼","睛","等","色","诱"], jp: ["ngaan5","zing1","dang2","sik1","jau5"] },
            { chars: ["有","人","性"], jp: ["jau5","jan4","sing3"] },
            { chars: ["镜","头","里","总","有","丰","收"], jp: ["geng3","tau4","lei5","zung2","jau5","fung1","sau1"] },
            { paragraphBreak: true },
            { chars: ["虽","则","那"], jp: ["seoi1","zak1","naa5"] },
            { chars: ["即","影","即","有","售","罄"], jp: ["zik1","jing2","zik1","jau5","sau6","hing3"] },
            { chars: ["菲","林","都","已","拆","走"], jp: ["fei2","lam4","dou1","ji5","caak3","zau2"] },
            { chars: ["但","是","冲","动","用","完"], jp: ["daan6","si6","cung1","dung6","jung6","jyun4"] },
            { chars: ["又","再","有"], jp: ["jau6","zoi3","jau5"] },
            { paragraphBreak: true },
            { chars: ["留","住"," ","温","度"," ","速","度"," ","温","柔","和","愤","怒"], jp: ["lau4","zyu6","","wan1","dou6","","cuk1","dou6","","wan1","jau4","wo4","fan5","nou6"] },
            { chars: ["凝","住"," ","今","日"," ","怎","样"," ","好"], jp: ["jing4","zyu6","","gam1","jat6","","zam2","joeng6","","hou2"] },
            { chars: ["捉","紧"," ","生","命","浓","度"], jp: ["zuk1","gan2","","sang1","ming6","nung4","dou6"] },
            { chars: ["坦","白","流","露"], jp: ["taan2","baak6","lau4","lou6"] },
            { chars: ["感","情","和","态","度"], jp: ["gam2","cing4","wo4","taai3","dou6"] },
            { chars: ["停","下","时","光"], jp: ["ting4","haa6","si4","gwong1"] },
            { chars: ["静","止","衰","老"], jp: ["zing6","zi2","seoi1","lou5"] },
            { paragraphBreak: true },
            { chars: ["登","高","峰","一","秒"], jp: ["dang1","gou1","fung1","jat1","miu5"] },
            { chars: ["得","奖","一","秒"], jp: ["dak1","zoeng2","jat1","miu5"] },
            { chars: ["再","破","纪","录","的","一","秒"], jp: ["zoi3","po3","gei2","luk6","dik1","jat1","miu5"] },
            { chars: ["港","湾","晚","灯"], jp: ["gong2","waan1","maan5","dang1"] },
            { chars: ["山","顶","破","晓"], jp: ["saan1","ding2","po3","hiu2"] },
            { chars: ["摘","下","怀","念"], jp: ["zaak6","haa6","waai4","nim6"] },
            { chars: ["记","住","美","妙"], jp: ["gei3","zyu6","mei5","miu6"] },
            { chars: ["升","职","那","刻"], jp: ["sing1","zik1","naa5","hak1"] },
            { chars: ["新","婚","那","朝"], jp: ["san1","fan1","naa5","ciu4"] },
            { chars: ["成","为","父","母","的","一","秒"], jp: ["sing4","wai4","fu6","mou5","dik1","jat1","miu5"] },
            { chars: ["要","拍","照","的","事"], jp: ["jiu3","paak3","ziu3","dik1","si6"] },
            { chars: ["可","不","少"], jp: ["ho2","bat1","siu2"] },
            { paragraphBreak: true },
            { chars: ["音","乐"," ","话","剧"," ","诗","词","和","舞","蹈"], jp: ["jam1","lok6","","waa6","kek6","","si1","ci4","wo4","mou5","dou6"] },
            { chars: ["揉","合"," ","生","命"," ","千","样","好"], jp: ["jau4","hap6","","sang1","ming6","","cin1","joeng6","hou2"] },
            { chars: ["摄","入","相","簿"], jp: ["sip3","jap6","soeng1","bou6"] },
            { chars: ["绚","烂","如","电"], jp: ["hyun3","laan6","jyu4","din6"] },
            { chars: ["虚","幻","如","雾"], jp: ["heoi1","waan6","jyu4","mou6"] },
            { chars: ["哀","愁","和","仰","慕"], jp: ["oi1","sau4","wo4","joeng5","mou6"] },
            { chars: ["游","乐","人","间"], jp: ["jau4","lok6","jan4","gaan1"] },
            { chars: ["活","得","好"], jp: ["wut6","dak1","hou2"] },
            { chars: ["谈","何","容","易"], jp: ["taam4","ho4","jung4","ji6"] },
            { chars: ["拍","着","照","片"], jp: ["paak3","zoek6","ziu3","pin3"] },
            { chars: ["一","路","同","步"], jp: ["jat1","lou6","tung4","bou6"] },
            { chars: ["坦","白","流","露"], jp: ["taan2","baak6","lau4","lou6"] },
            { chars: ["感","情","和","态","度"], jp: ["gam2","cing4","wo4","taai3","dou6"] },
            { chars: ["其","实"," ","人","生","并","非","虚","耗"], jp: ["kei4","sat6","","jan4","sang1","bing6","fei1","heoi1","hou3"] },
            { paragraphBreak: true },
            { chars: ["何","来","尘","埃","飞","舞"], jp: ["ho4","loi4","can4","oi1","fei1","mou5"] }
        ]
    };
    if (typeof window !== 'undefined' && window.__songs) {
        window.__songs.push(song);
    }
})();
