// 歌曲：游乐场

(function() {
    const song = {
        id: 27,
        title: "游乐场",
        titleJyutping: ["jau4","lok6","coeng4"],
        artist: "谢霆锋",
        artistJyutping: ["ze6","ting4","fung1"],
        lyricist: "林夕",
        lyricistJyutping: ["lam4","zik6"],
        composer: "谢霆锋",
        composerJyutping: ["ze6","ting4","fung1"],
        lyrics: [
            { chars: ["逐","个","字","逐","个","字","逐","个","认","识"], jp: ["zuk6","go3","zi6","zuk6","go3","zi6","zuk6","go3","jing6","sik1"] },
            { chars: ["糖","是","甜","唇","是","红","谁","是","奇","迹"], jp: ["tong4","si6","tim4","seon4","si6","hung4","seoi4","si6","kei4","zik1"] },
            { chars: ["看","懂","了"], jp: ["hon3","dung2","liu5"] },
            { chars: ["然","后","寻","觅","寻","觅","另","一","种","价","值"], jp: ["jin4","hau6","cam4","mik6","cam4","mik6","ling6","jat1","zung2","gaai3","zik6"] },
            { chars: ["逐","个","梦","逐","副","脸","逐","次","累","积"], jp: ["zuk6","go3","mung6","zuk6","fu3","lim5","zuk6","ci3","leoi6","zik1"] },
            { chars: ["抱","起","过","放","低","了","然","后","回","忆"], jp: ["pou5","hei2","gwo3","fong3","dai1","liu5","jin4","hau6","wui4","jik1"] },
            { chars: ["然","后","期","期","待","期","待","期","待","下","一","位","接","力"], jp: ["jin4","hau6","kei4","kei4","doi6","kei4","doi6","kei4","doi6","haa6","jat1","wai6","zip3","lik6"] },
            { paragraphBreak: true },
            { chars: ["你","与","我","仍","心","跳"], jp: ["nei5","jyu5","ngo5","jing4","sam1","tiu3"] },
            { chars: ["一","切","都","不","重","要"], jp: ["jat1","cit3","dou1","bat1","cung5","jiu3"] },
            { chars: ["你","与","我","仍","相","信","如","何","不","得","了"], jp: ["nei5","jyu5","ngo5","jing4","soeng1","seon3","jyu4","ho4","bat1","dak1","liu5"] },
            { chars: ["烟","火","最","后","也","会","退","烧"], jp: ["jin1","fo2","zeoi3","hau6","jaa5","wui6","teoi3","siu1"] },
            { paragraphBreak: true },
            { chars: ["最","缤","纷","的","花","园","游","乐","过"], jp: ["zeoi3","ban1","fan1","dik1","faa1","jyun4","jau4","lok6","gwo3"] },
            { chars: ["但","求","动","心"], jp: ["daan6","kau4","dung6","sam1"] },
            { chars: ["就","算","是","世","间","末","日","抚","心","自","问"], jp: ["zau6","syun3","si6","sai3","gaan1","mut6","jat6","fu2","sam1","zi6","man6"] },
            { chars: ["都","想","秒","秒","惊","心"], jp: ["dou1","soeng2","miu5","miu5","ging1","sam1"] },
            { chars: ["最","宽","广","的","公","园","游","乐","过"], jp: ["zeoi3","fun1","gwong2","dik1","gung1","jyun4","jau4","lok6","gwo3"] },
            { chars: ["为","何","认","真"], jp: ["wai4","ho4","jing6","zan1"] },
            { chars: ["若","我","尚","占","一","席","位","都","想","入","座"], jp: ["joek6","ngo5","soeng6","zim1","jat1","zik6","wai6","dou1","soeng2","jap6","zo6"] },
            { chars: ["观","赏","这","个","惊","险","人","生"], jp: ["gun1","soeng2","ze5","go3","ging1","him2","jan4","sang1"] },
            { paragraphBreak: true },
            { chars: ["做","对","事","做","错","事","换","个","脸","色"], jp: ["zou6","deoi3","si6","zou6","co3","si6","wun6","go3","lim5","sik1"] },
            { chars: ["对","不","起","对","得","起","留","下","评","击"], jp: ["deoi3","bat1","hei2","deoi3","dak1","hei2","lau4","haa6","ping4","gik1"] },
            { chars: ["看","开","了","然","后","承","受","承","受"], jp: ["hon3","hoi1","liu5","jin4","hau6","sing4","sau6","sing4","sau6"] },
            { chars: ["另","一","种","压","力"], jp: ["ling6","jat1","zung2","aat3","lik6"] },
            { chars: ["会","过","面","道","过","别","直","到","熟","悉"], jp: ["wui6","gwo3","min6","dou6","gwo3","bit6","zik6","dou3","suk6","sik1"] },
            { chars: ["看","一","眼","吻","一","次","留","下","痕","迹"], jp: ["hon3","jat1","ngaan5","man5","jat1","ci3","lau4","haa6","han4","zik1"] },
            { chars: ["爱","不","够","然","后","存","在","存","在"], jp: ["ngoi3","bat1","gau3","jin4","hau6","cyun4","zoi6","cyun4","zoi6"] },
            { chars: ["另","一","种","角","力"], jp: ["ling6","jat1","zung2","gok3","lik6"] },
            { paragraphBreak: true },
            { chars: ["你","与","我","仍","心","跳"], jp: ["nei5","jyu5","ngo5","jing4","sam1","tiu3"] },
            { chars: ["一","切","都","不","重","要"], jp: ["jat1","cit3","dou1","bat1","cung5","jiu3"] },
            { chars: ["你","与","我","仍","相","信","如","何","不","得","了"], jp: ["nei5","jyu5","ngo5","jing4","soeng1","seon3","jyu4","ho4","bat1","dak1","liu5"] },
            { chars: ["烟","火","最","后","也","会","退","烧"], jp: ["jin1","fo2","zeoi3","hau6","jaa5","wui6","teoi3","siu1"] },
            { paragraphBreak: true },
            { chars: ["最","缤","纷","的","花","园","游","乐","过"], jp: ["zeoi3","ban1","fan1","dik1","faa1","jyun4","jau4","lok6","gwo3"] },
            { chars: ["但","求","动","心"], jp: ["daan6","kau4","dung6","sam1"] },
            { chars: ["就","算","是","世","界","末","日","抚","心","自","问"], jp: ["zau6","syun3","si6","sai3","gaai3","mut6","jat6","fu2","sam1","zi6","man6"] },
            { chars: ["都","想","秒","秒","惊","心"], jp: ["dou1","soeng2","miu5","miu5","ging1","sam1"] },
            { chars: ["最","宽","广","的","公","园","游","乐","过"], jp: ["zeoi3","fun1","gwong2","dik1","gung1","jyun4","jau4","lok6","gwo3"] },
            { chars: ["为","何","认","真"], jp: ["wai4","ho4","jing6","zan1"] },
            { chars: ["若","我","尚","占","一","席","位","都","想","入","座"], jp: ["joek6","ngo5","soeng6","zim1","jat1","zik6","wai6","dou1","soeng2","jap6","zo6"] },
            { chars: ["观","赏","这","个","惊","险","人","生"], jp: ["gun1","soeng2","ze5","go3","ging1","him2","jan4","sang1"] },
            { paragraphBreak: true },
            { chars: ["最","缤","纷","的","花","园","游","乐","过"], jp: ["zeoi3","ban1","fan1","dik1","faa1","jyun4","jau4","lok6","gwo3"] },
            { chars: ["但","求","动","心"], jp: ["daan6","kau4","dung6","sam1"] },
            { chars: ["就","算","是","世","界","末","日","抚","心","自","问"], jp: ["zau6","syun3","si6","sai3","gaai3","mut6","jat6","fu2","sam1","zi6","man6"] },
            { chars: ["都","想","秒","秒","惊","心"], jp: ["dou1","soeng2","miu5","miu5","ging1","sam1"] },
            { chars: ["最","宽","广","的","公","园","游","乐","过"], jp: ["zeoi3","fun1","gwong2","dik1","gung1","jyun4","jau4","lok6","gwo3"] },
            { chars: ["为","何","认","真"], jp: ["wai4","ho4","jing6","zan1"] },
            { chars: ["若","我","尚","占","一","席","位","都","想","入","座"], jp: ["joek6","ngo5","soeng6","zim1","jat1","zik6","wai6","dou1","soeng2","jap6","zo6"] },
            { chars: ["观","赏","这","个","惊","险","人","生"], jp: ["gun1","soeng2","ze5","go3","ging1","him2","jan4","sang1"] }
        ]
    };
    window.__songs.push(song);
}());

// ⚠️ 重要：请在 index.html 的 songFiles 数组中添加以下一行：
// 'lyrics/游乐场.js',
