// 歌曲：爱人

(function() {
    const song = {
        id: 381,
        title: "爱人",
        titleJyutping: ["ngoi3","jan4"],
        artist: "杨千嬅",
        artistJyutping: ["joeng4","cin1","waa6"],
        lyricist: "林夕",
        lyricistJyutping: ["lam4","zik6"],
        composer: "于逸尧",
        composerJyutping: ["jyu1","jat6","jiu4"],
        lyrics: [
            { chars: ["看","着","你","来"], jp: ["hon3","zoek6","nei5","loi4"] },
            { chars: ["随","背","影","掩","盖"], jp: ["ceoi4","bui3","jing2","jim2","goi3"] },
            { chars: ["我","没","法","不","爱"], jp: ["ngo5","mut6","faat3","bat1","ngoi3"] },
            { chars: ["我","是","行","李"], jp: ["ngo5","si6","hang4","lei5"] },
            { chars: ["你","是","游","客"], jp: ["nei5","si6","jau4","haak3"] },
            { chars: ["笑","着","来"], jp: ["siu3","zoek6","loi4"] },
            { chars: ["要","笑","着","离","开"], jp: ["jiu3","siu3","zoek6","lei4","hoi1"] },
            { paragraphBreak: true },
            { chars: ["背","后","有","床"], jp: ["bui3","hau6","jau5","cong4"] },
            { chars: ["不","需","有","爱"], jp: ["bat1","seoi1","jau5","ngoi3"] },
            { chars: ["睡","醒","不","怕","另","有","将","来"], jp: ["seoi6","sing2","bat1","paa3","ling6","jau5","zoeng1","loi4"] },
            { chars: ["如","早","知","道","夏","季","不","再","来"], jp: ["jyu4","zou2","zi1","dou6","haa6","gwai3","bat1","zoi3","loi4"] },
            { chars: ["斜","阳","垂","下","了"], jp: ["ce4","joeng4","seoi4","haa6","liu5"] },
            { chars: ["蔷","薇","仍","是","会","开"], jp: ["coeng4","mei4","jing4","si6","wui6","hoi1"] },
            { paragraphBreak: true },
            { chars: ["只","怪","我","一","心","爱","人"], jp: ["zi2","gwaai3","ngo5","jat1","sam1","ngoi3","jan4"] },
            { chars: ["忘","掉","随","手","抚","摸","得","到","的","伤","痕"], jp: ["mong4","diu6","ceoi4","sau2","fu2","mo2","dak1","dou3","dik1","soeng1","han4"] },
            { chars: ["坏","了","千","万","盏","灯"], jp: ["waai6","liu5","cin1","maan6","zaan2","dang1"] },
            { chars: ["烧","光","每","段","眼","神"], jp: ["siu1","gwong1","mui5","dyun6","ngaan5","san4"] },
            { chars: ["只","发","现","和","你","衣","不","称","身"], jp: ["zi2","faat3","jin6","wo4","nei5","ji1","bat1","cing1","san1"] },
            { paragraphBreak: true },
            { chars: ["对","不","起"], jp: ["deoi3","bat1","hei2"] },
            { chars: ["我","不","过","为","爱","人"], jp: ["ngo5","bat1","gwo3","wai4","ngoi3","jan4"] },
            { chars: ["从","未","曾","天","真","得","相","信","永","生"], jp: ["cung4","mei6","zang1","tin1","zan1","dak1","soeng1","seon3","wing5","sang1"] },
            { chars: ["曾","共","你","一","起"], jp: ["zang1","gung6","nei5","jat1","hei2"] },
            { chars: ["即","使","毫","无","好","处"], jp: ["zik1","si2","hou4","mou4","hou2","cyu5"] },
            { chars: ["起","码","能","回","味","那","边","脸","被","吻"], jp: ["hei2","maa5","nang4","wui4","mei6","naa5","bin1","lim5","bei6","man5"] },
            { paragraphBreak: true },
            { chars: ["近","在","眼","神"], jp: ["gan6","zoi6","ngaan5","san4"] },
            { chars: ["时","间","刚","刚","好"], jp: ["si4","gaan1","gong1","gong1","hou2"] },
            { chars: ["去","让","你","知","道"], jp: ["heoi3","joeng6","nei5","zi1","dou6"] },
            { chars: ["见","面","愉","快"], jp: ["gin3","min6","jyu4","faai3"] },
            { chars: ["告","别","难","过"], jp: ["gou3","bit6","naan4","gwo3"] },
            { chars: ["我","仍","然"], jp: ["ngo5","jing4","jin4"] },
            { chars: ["会","笑","着","祈","祷"], jp: ["wui6","siu3","zoek6","kei4","tou2"] },
            { paragraphBreak: true },
            { chars: ["有","没","有"], jp: ["jau5","mut6","jau5"] },
            { chars: ["谁","心","中","有","数"], jp: ["seoi4","sam1","zung1","jau5","sou3"] },
            { chars: ["怎","么","双","眼","尚","有","失","望"], jp: ["zam2","maa1","soeng1","ngaan5","soeng6","jau5","sat1","mong6"] },
            { chars: ["明","天","将","会","更","好","的","信","徒"], jp: ["ming4","tin1","zoeng1","wui6","gang1","hou2","dik1","seon3","tou4"] },
            { chars: ["如","害","怕","烦","恼"], jp: ["jyu4","hoi6","paa3","faan4","nou5"] },
            { chars: ["为","何","期","望","太","高"], jp: ["wai4","ho4","kei4","mong6","taai3","gou1"] },
            { paragraphBreak: true },
            { chars: ["只","怪","我","一","心","爱","人"], jp: ["zi2","gwaai3","ngo5","jat1","sam1","ngoi3","jan4"] },
            { chars: ["忘","掉","随","手","抚","摸","得","到","的","伤","痕"], jp: ["mong4","diu6","ceoi4","sau2","fu2","mo2","dak1","dou3","dik1","soeng1","han4"] },
            { chars: ["坏","了","千","万","盏","灯"], jp: ["waai6","liu5","cin1","maan6","zaan2","dang1"] },
            { chars: ["烧","光","每","段","眼","神"], jp: ["siu1","gwong1","mui5","dyun6","ngaan5","san4"] },
            { chars: ["只","发","现","和","你","衣","不","称","身"], jp: ["zi2","faat3","jin6","wo4","nei5","ji1","bat1","cing1","san1"] },
            { paragraphBreak: true },
            { chars: ["对","不","起"], jp: ["deoi3","bat1","hei2"] },
            { chars: ["我","不","过","为","爱","人"], jp: ["ngo5","bat1","gwo3","wai4","ngoi3","jan4"] },
            { chars: ["从","未","曾","天","真","得","相","信","永","生"], jp: ["cung4","mei6","zang1","tin1","zan1","dak1","soeng1","seon3","wing5","sang1"] },
            { chars: ["曾","共","你","一","起"], jp: ["zang1","gung6","nei5","jat1","hei2"] },
            { chars: ["即","使","毫","无","好","处"], jp: ["zik1","si2","hou4","mou4","hou2","cyu5"] },
            { chars: ["起","码","能","回","味","那","边","脸","被","吻"], jp: ["hei2","maa5","nang4","wui4","mei6","naa5","bin1","lim5","bei6","man5"] },
            { paragraphBreak: true },
            { chars: ["只","怪","我","一","心","爱","人"], jp: ["zi2","gwaai3","ngo5","jat1","sam1","ngoi3","jan4"] },
            { chars: ["忘","掉","随","手","抚","摸","得","到","的","伤","痕"], jp: ["mong4","diu6","ceoi4","sau2","fu2","mo2","dak1","dou3","dik1","soeng1","han4"] },
            { chars: ["坏","了","千","万","盏","灯"], jp: ["waai6","liu5","cin1","maan6","zaan2","dang1"] },
            { chars: ["烧","光","每","段","眼","神"], jp: ["siu1","gwong1","mui5","dyun6","ngaan5","san4"] },
            { chars: ["只","发","现","和","你","衣","不","称","身"], jp: ["zi2","faat3","jin6","wo4","nei5","ji1","bat1","cing1","san1"] },
            { paragraphBreak: true },
            { chars: ["对","不","起"], jp: ["deoi3","bat1","hei2"] },
            { chars: ["我","不","过","为","爱","人"], jp: ["ngo5","bat1","gwo3","wai4","ngoi3","jan4"] },
            { chars: ["从","未","曾","天","真","得","相","信","永","生"], jp: ["cung4","mei6","zang1","tin1","zan1","dak1","soeng1","seon3","wing5","sang1"] },
            { chars: ["难","共","你","一","起"], jp: ["naan4","gung6","nei5","jat1","hei2"] },
            { chars: ["即","使","毫","无","希","冀"], jp: ["zik1","si2","hou4","mou4","hei1","kei3"] },
            { chars: ["起","码","能","期","待","这","边","脸","被","吻"], jp: ["hei2","maa5","nang4","kei4","doi6","ze5","bin1","lim5","bei6","man5"] }
        ]
    };
    if (typeof window !== 'undefined' && window.__songs) {
        window.__songs.push(song);
    }
})();
