// 歌曲：爱得太迟

(function() {
    const song = {
        id: 9,
        title: "爱得太迟",
        titleJyutping: ["ngoi3","dak1","taai3","ci4"],
        artist: "古巨基",
        artistJyutping: ["gu2","geoi6","gei1"],
        lyricist: "林夕",
        lyricistJyutping: ["lam4","zik6"],
        composer: "杨镇邦",
        composerJyutping: ["joeng4","zan3","bong1"],
        lyrics: [
            { chars: ["我","过","去"," ","那","死","党","早","晚","共","对"], jp: ["ngo5","gwo3","heoi3","","naa5","sei2","dong2","zou2","maan5","gung6","deoi3"] },
            { chars: ["各","也","扎","职","以","后"," ","没","法","畅","聚"], jp: ["gok3","jaa5","zaat3","zik1","ji5","hau6","","mut6","faat3","coeng3","zeoi6"] },
            { chars: ["而","终","于","相","约","到"], jp: ["ji4","zung1","jyu1","soeng1","joek3","dou3"] },
            { chars: ["但","无","言","共","对"," ","疏","淡","如","水"], jp: ["daan6","mou4","jin4","gung6","deoi3","","so1","taam6","jyu4","seoi2"] },
            { paragraphBreak: true },
            { chars: ["日","夜","做"," ","见","爸","爸"," ","刚","好","想","呻"], jp: ["jat6","je6","zou6","","gin3","baa1","baa1","","gong1","hou2","soeng2","san1"] },
            { chars: ["却","霎","眼"," ","看","出","他"," ","多","了","皱","纹"], jp: ["koek3","saap3","ngaan5","","hon3","ceot1","taa1","","do1","liu5","zau3","man4"] },
            { chars: ["而","他","的","苍","老","感"], jp: ["ji4","taa1","dik1","cong1","lou5","gam2"] },
            { chars: ["是","从","来","未","觉"," ","太","内","疚","担","心"], jp: ["si6","cung4","loi4","mei6","gok3","","taai3","noi6","gau3","daam1","sam1"] },
            { paragraphBreak: true },
            { chars: ["最","心","痛","是"," ","爱","得","太","迟"], jp: ["zeoi3","sam1","tung3","si6","","ngoi3","dak1","taai3","ci4"] },
            { chars: ["有","些","心","意"," ","不","可","等","某","个","日","子"], jp: ["jau5","se1","sam1","ji3","","bat1","ho2","dang2","mau5","go3","jat6","zi2"] },
            { chars: ["盲","目","地","发","奋"," ","忙","忙","忙","其","实","自","私"], jp: ["maang4","muk6","dei6","faat3","fan5","","mong4","mong4","mong4","kei4","sat6","zi6","si1"] },
            { chars: ["梦","中","也","习","惯"," ","有","压","力","要","我","得","志"], jp: ["mung6","zung1","jaa5","zaap6","gwaan3","","jau5","aat3","lik6","jiu3","ngo5","dak1","zi3"] },
            { paragraphBreak: true },
            { chars: ["最","可","怕","是"," ","爱","需","要","及","时"], jp: ["zeoi3","ho2","paa3","si6","","ngoi3","seoi1","jiu3","kap6","si4"] },
            { chars: ["只","差","一","秒"," ","心","声","都","已","变","历","史"], jp: ["zi2","caa1","jat1","miu5","","sam1","sing1","dou1","ji5","bin3","lik6","si2"] },
            { chars: ["忙","极","亦","放","肆"," ","见","我","爱","见","的","相","知"], jp: ["mong4","gik6","jik6","fong3","si3","","gin3","ngo5","ngoi3","gin3","dik1","soeng1","zi1"] },
            { chars: ["要","抱"," ","要","吻"," ","要","怎","么","也","好"], jp: ["jiu3","pou5","","jiu3","man5","","jiu3","zam2","mo1","jaa5","hou2"] },
            { chars: ["偏","要","推","说","等","下","一","次"], jp: ["pin1","jiu3","teoi1","syut3","dang2","haa6","jat1","ci3"] },
            { paragraphBreak: true },
            { chars: ["我","也","觉"," ","我","体","质"," ","仿","似","下","降"], jp: ["ngo5","jaa5","gok3","","ngo5","tai2","zat1","","fong2","ci5","haa6","gong3"] },
            { chars: ["看","了","症"," ","得","到","是"," ","别","要","太","忙"], jp: ["hon3","liu5","zing3","","dak1","dou3","si6","","bit6","jiu3","taai3","mong4"] },
            { chars: ["而","影","碟"," ","都","扫","光"], jp: ["ji4","jing2","dip6","","dou1","sou3","gwong1"] },
            { chars: ["但","从","来","未","看"," ","因","有","事","赶"], jp: ["daan6","cung4","loi4","mei6","hon3","","jan1","jau5","si6","gon2"] },
            { paragraphBreak: true },
            { chars: ["日","夜","做"," ","储","的","钱"," ","都","应","该","够"], jp: ["jat6","je6","zou6","","cou5","dik1","cin4","","dou1","jing1","goi1","gau3"] },
            { chars: ["到","圣","诞"," ","正","好","讲"," ","跟","我","白","头"], jp: ["dou3","sing3","daan3","","zing3","hou2","gong2","","gan1","ngo5","baak6","tau4"] },
            { chars: ["谁","知","她","开","了","口"], jp: ["seoi4","zi1","taa1","hoi1","liu5","hau2"] },
            { chars: ["未","能","挨","下","去"," ","已","恨","我","很","久"], jp: ["mei6","nang4","aai1","haa6","heoi3","","ji5","han6","ngo5","han2","gau2"] },
            { paragraphBreak: true },
            { chars: ["错","失","太","易"," ","爱","得","太","迟"], jp: ["co3","sat1","taai3","ji6","","ngoi3","dak1","taai3","ci4"] },
            { chars: ["我","怎","想","到"," ","她","忍","不","到","那","日","子"], jp: ["ngo5","zam2","soeng2","dou3","","taa1","jan2","bat1","dou3","naa5","jat6","zi2"] },
            { chars: ["盲","目","地","发","奋"," ","忙","忙","忙","从","来","未","知"], jp: ["maang4","muk6","dei6","faat3","fan5","","mong4","mong4","mong4","cung4","loi4","mei6","zi1"] },
            { chars: ["幸","福","会","掠","过"," ","再","也","没","法","说","钟","意"], jp: ["hang6","fuk1","wui5","loek6","gwo3","","zoi3","jaa5","mut6","faat3","syut3","zung1","ji3"] },
            { paragraphBreak: true },
            { chars: ["爱","一","个","字"," ","也","需","要","及","时"], jp: ["ngoi3","jat1","go3","zi6","","jaa5","seoi1","jiu3","kap6","si4"] },
            { chars: ["只","差","一","秒"," ","心","声","都","已","变","历","史"], jp: ["zi2","caa1","jat1","miu5","","sam1","sing1","dou1","ji5","bin3","lik6","si2"] },
            { chars: ["为","何","未","放","肆"," ","见","我","爱","见","的","相","知"], jp: ["wai4","ho4","mei6","fong3","si3","","gin3","ngo5","ngoi3","gin3","dik1","soeng1","zi1"] },
            { chars: ["要","抱"," ","要","吻"," ","要","怎","么","也","好"], jp: ["jiu3","pou5","","jiu3","man5","","jiu3","zam2","mo1","jaa5","hou2"] },
            { chars: ["不","要","相","信","一","切","有","下","次"], jp: ["bat1","jiu3","soeng1","seon3","jat1","cai3","jau5","haa6","ci3"] },
            { paragraphBreak: true },
            { chars: ["相","拥","我","所","爱","又","花","几","多","秒"], jp: ["soeng1","jung2","ngo5","so2","ngoi3","jau6","faa1","gei2","do1","miu5"] },
            { chars: ["这","几","秒"," ","能","够","做","到","又","有","多","少"], jp: ["ze5","gei2","miu5","","nang4","gau3","zou6","dou3","jau6","jau5","do1","siu2"] },
            { chars: ["未","算","少"," ","足","够","遗","憾","忘","掉"], jp: ["mei6","syun3","siu2","","zuk1","gau3","wai4","ham6","mong4","diu6"] },
            { paragraphBreak: true },
            { chars: ["多","少","抱","憾"," ","多","少","过","路","人"], jp: ["do1","siu2","pou5","ham6","","do1","siu2","gwo3","lou6","jan4"] },
            { chars: ["太","懂","估","计"," ","却","不","懂","爱","惜","自","身"], jp: ["taai3","dung2","gu2","gai3","","koek3","bat1","dung2","ngoi3","sek3","zi6","san1"] },
            { chars: ["人","人","在","发","奋"," ","想","起","他","朝","都","兴","奋"], jp: ["jan4","jan4","zoi6","faat3","fan5","","soeng2","hei2","taa1","ziu1","dou1","hing1","fan5"] },
            { chars: ["但","今","晚","未","过"," ","你","要","过","也","很","吸","引"], jp: ["daan6","gam1","maan5","mei6","gwo3","","nei5","jiu3","gwo3","jaa5","han2","kap1","jan5"] },
            { paragraphBreak: true },
            { chars: ["纵","不","信","运"," ","你","不","过","是","人"], jp: ["zung3","bat1","seon3","wan6","","nei5","bat1","gwo3","si6","jan4"] },
            { chars: ["理","想","很","远"," ","爱","于","咫","尺","却","在","等"], jp: ["lei5","soeng2","han2","jyun5","","ngoi3","jyu1","zi2","cek3","koek3","zoi6","dang2"] },
            { chars: ["来","日","别","操","心"," ","趁","你","有","能","力","开","心"], jp: ["loi4","jat6","bit6","cou1","sam1","","can3","nei5","jau5","nang4","lik6","hoi1","sam1"] },
            { chars: ["世","界","有","太","多","东","西","发","生"], jp: ["sai3","gaai3","jau5","taai3","do1","dung1","sai1","faat3","sang1"] },
            { chars: ["不","要","等","到","天","上","俯","瞰"], jp: ["bat1","jiu3","dang2","dou3","tin1","soeng6","fu2","ham3"] }
        ]
    };
    if (typeof window !== 'undefined' && window.__songs) {
        window.__songs.push(song);
    }
})();
