// 歌曲：紧急联络人

(function() {
    const song = {
        id: 15,
        title: "紧急联络人",
        titleJyutping: ["gan2","gap1","lyun4","lok3","jan4"],
        artist: "汤令山",
        artistJyutping: ["tong1","ling6","saan1"],
        lyricist: "黄伟文",
        lyricistJyutping: ["wong4","wai5","man4"],
        composer: "汤令山/叶崇恩",
        composerJyutping: ["tong1","ling6","saan1","","jip6","sung4","jan1"],
        lyrics: [
            { chars: ["传","来","法","语","问","你","是","我","的","家","属","吧"], jp: ["cyun4","loi4","faat3","jyu5","man6","nei5","si6","ngo5","dik1","gaa1","suk6","baa6"] },
            { chars: ["原","来","我","已","自","那","白","朗","之","巅","堕","下"], jp: ["jyun4","loi4","ngo5","ji5","zi6","naa5","baak6","long5","zi1","din1","do6","haa6"] },
            { chars: ["明","明","分","开"," ","为","何","打","这","号","码"], jp: ["ming4","ming4","fan1","hoi1","","wai4","ho4","daa2","ze5","hou6","maa5"] },
            { chars: ["你","可","会","很","不","解"," ","我","怎","不","删","了","它"], jp: ["nei5","ho2","wui6","han2","bat1","gaai2","","ngo5","zam2","bat1","saan1","liu5","taa1"] },
            { paragraphBreak: true },
            { chars: ["我","知","不","该"," ","但","是","不","改"], jp: ["ngo5","zi1","bat1","goi1","","daan6","si6","bat1","goi2"] },
            { chars: ["像","某","种","流","亡","的","爱","千","里","之","外"], jp: ["zoeng6","mau5","zung2","lau4","mong4","dik1","ngoi3","cin1","lei5","zi1","ngoi6"] },
            { chars: ["联","系","还","是","依","在"], jp: ["lyun4","hai6","waan4","si6","ji1","zoi6"] },
            { paragraphBreak: true },
            { chars: ["有","没","有","一","丝","半","秒","伤","悲"], jp: ["jau5","mut6","jau5","jat1","si1","bun3","miu5","soeng1","bei1"] },
            { chars: ["要","是","我","今","晚","异","地","断","气"], jp: ["jiu3","si6","ngo5","gam1","maan5","ji6","dei6","dyun6","hei3"] },
            { chars: ["问","你","可","肯","即","夜","赶","搭","通","宵","客","机"], jp: ["man6","nei5","ho2","hang2","zik1","je6","gon2","daap3","tung1","siu1","haak3","gei1"] },
            { paragraphBreak: true },
            { chars: ["有","没","有","一","丝","半","秒","欢","喜"], jp: ["jau5","mut6","jau5","jat1","si1","bun3","miu5","fun1","hei2"] },
            { chars: ["再","无","人","以","后","来","烦","住","你"], jp: ["zoi3","mou4","jan4","ji5","hau6","loi4","faan4","zyu6","nei5"] },
            { chars: ["若","觉","得","将","这","责","任","加","诸","很","离","奇"], jp: ["joek6","gok3","dak1","zoeng1","ze5","zaak3","jam6","gaa1","zyu1","han2","lei4","kei4"] },
            { chars: ["是","我","自","私"," ","今","世","最","后","骚","扰","的","人","儿"], jp: ["si6","ngo5","zi6","si1","","gam1","sai3","zeoi3","hau6","sou1","jiu2","dik1","jan4","ji4"] },
            { chars: ["只","想","是","你"], jp: ["zi2","soeng2","si6","nei5"] },
            { paragraphBreak: true },
            { chars: ["谁","联","络","你"," ","若","我","在","某","冰","川","遇","难"], jp: ["seoi4","lyun4","lok3","nei5","","joek6","ngo5","zoi6","mau5","bing1","cyun1","jyu6","naan4"] },
            { chars: ["然","而","教","你","负","痛"," ","亦","算","黑","色","浪","漫"], jp: ["jin4","ji4","gaau3","nei5","fu6","tung3","","jik6","syun3","hak1","sik1","long6","maan6"] },
            { paragraphBreak: true },
            { chars: ["甜","蜜","那","阵","时"], jp: ["tim4","mat6","naa5","zan6","si4"] },
            { chars: ["鳏","寡","日","子"," ","总","讲","到","带","泪","眼"], jp: ["gwaan1","gwaa2","jat6","zi2","","zung2","gong2","dou3","daai3","leoi6","ngaan5"] },
            { chars: ["谁","料","情","感","无","常"," ","这","假","设","太","简","单"], jp: ["seoi4","liu6","cing4","gam2","mou4","soeng4","","ze5","gaa2","cit3","taai3","gaan2","daan1"] },
            { paragraphBreak: true },
            { chars: ["你","有","没","有","一","丝","半","秒","伤","悲"], jp: ["nei5","jau5","mut6","jau5","jat1","si1","bun3","miu5","soeng1","bei1"] },
            { chars: ["要","是","我","今","晚","异","地","断","气"], jp: ["jiu3","si6","ngo5","gam1","maan5","ji6","dei6","dyun6","hei3"] },
            { chars: ["问","你","可","肯","即","夜","赶","搭","通","宵","客","机"], jp: ["man6","nei5","ho2","hang2","zik1","je6","gon2","daap3","tung1","siu1","haak3","gei1"] },
            { paragraphBreak: true },
            { chars: ["有","没","有","一","丝","半","秒","欢","喜"], jp: ["jau5","mut6","jau5","jat1","si1","bun3","miu5","fun1","hei2"] },
            { chars: ["再","无","人","以","后","去","牵","绊","你"], jp: ["zoi3","mou4","jan4","ji5","hau6","heoi3","hin1","bun6","nei5"] },
            { chars: ["若","觉","得","将","这","责","任","加","诸","很","离","奇"], jp: ["joek6","gok3","dak1","zoeng1","ze5","zaak3","jam6","gaa1","zyu1","han2","lei4","kei4"] },
            { chars: ["是","我","自","私"," ","今","世","最","后","骚","扰","的","人","儿"], jp: ["si6","ngo5","zi6","si1","","gam1","sai3","zeoi3","hau6","sou1","jiu2","dik1","jan4","ji4"] },
            { chars: ["只","想","是","你"], jp: ["zi2","soeng2","si6","nei5"] },
            { paragraphBreak: true },
            { chars: ["必","须","是","你"], jp: ["bit1","seoi1","si6","nei5"] },
            { chars: ["很","想","被","念","记"], jp: ["han2","soeng2","bei6","nim6","gei3"] },
            { chars: ["即","使","淡","淡","微","微"], jp: ["zik1","si2","daam6","daam6","mei4","mei4"] },
            { paragraphBreak: true },
            { chars: ["就","算","在","生","亦","被","嫌","弃"], jp: ["zau6","syun3","zoi6","sang1","jik6","bei6","jim4","hei3"] },
            { chars: ["都","想","藉","遗","言","说","好","想","你"], jp: ["dou1","soeng2","zik6","wai4","jin4","syut3","hou2","soeng2","nei5"] },
            { chars: ["可","惜","最","尾","未","够","运","气"," ","一","起"], jp: ["ho2","sik1","zeoi3","mei5","mei6","gau3","wan6","hei3","","jat1","hei2"] },
            { paragraphBreak: true },
            { chars: ["有","没","有","一","丝"], jp: ["jau5","mut6","jau5","jat1","si1"] },
            { chars: ["要","是","我","今","晚"," ","h","m"], jp: ["jiu3","si6","ngo5","gam1","maan5","","",""] },
            { chars: ["话","到","嘴","边","打","住"], jp: ["waa6","dou3","zeoi2","bin1","daa2","zyu6"] },
            { chars: ["早","变","陌","路","人","尚","有","幻","想","是","大","忌"], jp: ["zou2","bin3","mak6","lou6","jan4","soeng6","jau5","waan6","soeng2","si6","daai6","gei6"] },
            { paragraphBreak: true },
            { chars: ["这","号","码","应","该","长","眠","于","手","机"], jp: ["ze5","hou6","maa5","jing3","goi1","coeng4","min4","jyu1","sau2","gei1"] },
            { chars: ["就","算","死","亦","别","再","骚","扰","你"], jp: ["zau6","syun3","sei2","jik6","bit6","zoi3","sou1","jiu2","nei5"] },
            { chars: ["若","觉","得","这","恶","作","剧","真","的","很","顽","皮"], jp: ["joek6","gok3","dak1","ze5","ok3","zok3","kek6","zan1","dik1","han2","waan4","pei4"] },
            { chars: ["在","告","别","式","给","我","带","泪","奔","丧","的","情","人"], jp: ["zoi6","gou3","bit6","sik1","kap1","ngo5","daai3","leoi6","ban1","song1","dik1","cing4","jan4"] },
            { chars: ["只","想","是","你"], jp: ["zi2","soeng2","si6","nei5"] }
        ]
    };
    window.__songs.push(song);
}());

// ⚠️ 重要：请在 index.html 的 songFiles 数组中添加以下一行：
// 'lyrics/紧急联络人.js',
