// 歌曲：约定（live）

(function() {
    const song = {
        id: 303,
        title: "约定（live）",
        titleJyutping: ["joek3","ding6","","l","i","v","e",""],
        artist: "陈奕迅",
        artistJyutping: ["can4","jik6","seon3"],
        lyricist: "林夕",
        lyricistJyutping: ["lam4","zik6"],
        composer: "陈小霞",
        composerJyutping: ["can4","siu2","haa4"],
        lyrics: [
            { chars: ["还","记","得","当","天","旅","馆","的","门","牌"], jp: ["waan4","gei3","dak1","dong1","tin1","leoi5","gun2","dik1","mun4","paai4"] },
            { chars: ["还","留","住","笑","著","离","开","的","神","态"], jp: ["waan4","lau4","zyu6","siu3","zyu3","lei4","hoi1","dik1","san4","taai3"] },
            { chars: ["当","天","整","个","城","市"], jp: ["dong1","tin1","zing2","go3","sing4","si5"] },
            { chars: ["那","样","轻","快"], jp: ["naa5","joeng6","hing1","faai3"] },
            { chars: ["沿","路","一","起","走","半","哩","长","街"], jp: ["jyun4","lou6","jat1","hei2","zau2","bun3","li1","coeng4","gaai1"] },
            { chars: ["还","记","得","街","灯","照","出","一","脸","黄"], jp: ["waan4","gei3","dak1","gaai1","dang1","ziu3","ceot1","jat1","lim5","wong4"] },
            { chars: ["还","燃","亮","那","份","微","温","的","便","当"], jp: ["waan4","jin4","loeng6","naa5","fan6","mei4","wan1","dik1","bin6","dong1"] },
            { chars: ["剪","影","的","你","轮","廓"], jp: ["zin2","jing2","dik1","nei5","leon4","gwok3"] },
            { chars: ["太","好","看"], jp: ["taai3","hou2","hon3"] },
            { chars: ["凝","住","眼","泪","才","敢","细","看"], jp: ["jing4","zyu6","ngaan5","leoi6","coi4","gam2","sai3","hon3"] },
            { paragraphBreak: true },
            { chars: ["忘","掉","天","地"], jp: ["mong4","diu6","tin1","dei6"] },
            { chars: ["仿","佛","也","想","不","起","自","己"], jp: ["fong2","fat6","jaa5","soeng2","bat1","hei2","zi6","gei2"] },
            { chars: ["仍","未","忘","相","约","看","漫","天","黄","叶","远","飞"], jp: ["jing4","mei6","mong4","soeng1","joek3","hon3","maan6","tin1","wong4","jip6","jyun5","fei1"] },
            { chars: ["就","算","会","与","你","分","离"], jp: ["zau6","syun3","wui6","jyu5","nei5","fan1","lei4"] },
            { chars: ["凄","绝","的","戏"], jp: ["cai1","zyut6","dik1","hei3"] },
            { chars: ["要","决","心","忘","记"], jp: ["jiu3","kyut3","sam1","mong4","gei3"] },
            { chars: ["我","便","记","不","起"], jp: ["ngo5","bin6","gei3","bat1","hei2"] },
            { chars: ["明","日","天","地"], jp: ["ming4","jat6","tin1","dei6"] },
            { chars: ["只","恐","怕","认","不","出","自","己"], jp: ["zi2","hung2","paa3","jing6","bat1","ceot1","zi6","gei2"] },
            { chars: ["仍","未","忘","跟","你","约","定","假","如","没","有","死"], jp: ["jing4","mei6","mong4","gan1","nei5","joek3","ding6","gaa2","jyu4","mut6","jau5","sei2"] },
            { chars: ["就","算","你","壮","阔","胸","膛"], jp: ["zau6","syun3","nei5","zong3","fut3","hung1","tong4"] },
            { chars: ["不","敌","天","气"], jp: ["bat1","dik6","tin1","hei3"] },
            { chars: ["两","鬓","斑","白"], jp: ["loeng5","ban3","baan1","baak6"] },
            { chars: ["都","可","认","得","你"], jp: ["dou1","ho2","jing6","dak1","nei5"] },
            { paragraphBreak: true },
            { chars: ["还","记","得","当","天","结","他","的","和","弦"], jp: ["waan4","gei3","dak1","dong1","tin1","git3","taa1","dik1","wo4","jin4"] },
            { chars: ["还","明","白","每","段","旋","律","的","伏","线"], jp: ["waan4","ming4","baak6","mui5","dyun6","syun4","leot6","dik1","fuk6","sin3"] },
            { chars: ["当","天","街","角","流","过","你","声","线"], jp: ["dong1","tin1","gaai1","gok3","lau4","gwo3","nei5","sing1","sin3"] },
            { chars: ["沿","路","旅","程","如","歌","褪","变"], jp: ["jyun4","lou6","leoi5","cing4","jyu4","go1","tan3","bin3"] },
            { paragraphBreak: true },
            { chars: ["忘","掉","天","地"], jp: ["mong4","diu6","tin1","dei6"] },
            { chars: ["仿","佛","也","想","不","起","自","己"], jp: ["fong2","fat6","jaa5","soeng2","bat1","hei2","zi6","gei2"] },
            { chars: ["仍","未","忘","相","约","看","漫","天","黄","叶","远","飞"], jp: ["jing4","mei6","mong4","soeng1","joek3","hon3","maan6","tin1","wong4","jip6","jyun5","fei1"] },
            { chars: ["就","算","会","与","你","分","离"], jp: ["zau6","syun3","wui6","jyu5","nei5","fan1","lei4"] },
            { chars: ["凄","绝","的","戏"], jp: ["cai1","zyut6","dik1","hei3"] },
            { chars: ["要","决","心","忘","记"], jp: ["jiu3","kyut3","sam1","mong4","gei3"] },
            { chars: ["我","便","记","不","起"], jp: ["ngo5","bin6","gei3","bat1","hei2"] },
            { chars: ["明","日","天","地"], jp: ["ming4","jat6","tin1","dei6"] },
            { chars: ["只","恐","怕","认","不","出","自","己"], jp: ["zi2","hung2","paa3","jing6","bat1","ceot1","zi6","gei2"] },
            { chars: ["仍","未","忘","跟","你","约","定","假","如","没","有","死"], jp: ["jing4","mei6","mong4","gan1","nei5","joek3","ding6","gaa2","jyu4","mut6","jau5","sei2"] },
            { chars: ["就","算","你","壮","阔","胸","膛"], jp: ["zau6","syun3","nei5","zong3","fut3","hung1","tong4"] },
            { chars: ["不","敌","天","气"], jp: ["bat1","dik6","tin1","hei3"] },
            { chars: ["两","鬓","斑","白"], jp: ["loeng5","ban3","baan1","baak6"] },
            { chars: ["都","可","认","得","你"], jp: ["dou1","ho2","jing6","dak1","nei5"] },
            { paragraphBreak: true },
            { chars: ["就","算","你","壮","阔","胸","膛"], jp: ["zau6","syun3","nei5","zong3","fut3","hung1","tong4"] },
            { chars: ["不","敌","天","气"], jp: ["bat1","dik6","tin1","hei3"] },
            { chars: ["两","鬓","斑","白"], jp: ["loeng5","ban3","baan1","baak6"] },
            { chars: ["都","可","认","得","你"], jp: ["dou1","ho2","jing6","dak1","nei5"] }
        ]
    };
    if (typeof window !== 'undefined' && window.__songs) {
        window.__songs.push(song);
    }
})();
