// 歌曲：美中不足

(function() {
    const song = {
        id: 35,
        title: "美中不足",
        titleJyutping: ["mei5","zung1","bat1","zuk1"],
        artist: "许志安",
        artistJyutping: ["heoi2","zi3","on1"],
        lyricist: "黄伟文",
        lyricistJyutping: ["wong4","wai5","man4"],
        composer: "雷颂德",
        composerJyutping: ["leoi4","zung6","dak1"],
        lyrics: [
            { chars: ["回","去"," ","回","去","找","命","里","的","伴","侣"], jp: ["wui4","heoi3","","wui4","heoi3","zaau2","ming6","lei5","dik1","bun6","leoi5"] },
            { chars: ["别","要","他","为","你","等","下","去"], jp: ["bit6","jiu3","taa1","wai4","nei5","dang2","haa6","heoi3"] },
            { chars: ["待","你","好","是","我","不","规","矩","我","有","罪"], jp: ["doi6","nei5","hou2","si6","ngo5","bat1","kwai1","geoi2","ngo5","jau5","zeoi6"] },
            { chars: ["其","实","不","对","但","我","想","试","下","去"], jp: ["kei4","sat6","bat1","deoi3","daan6","ngo5","soeng2","si3","haa6","heoi3"] },
            { chars: ["是","否","会","变","合","拍","一","对"], jp: ["si6","fau2","wui6","bin3","hap6","paak3","jat1","deoi3"] },
            { chars: ["你","别","赔","罪","越","自","责","心","许"], jp: ["nei5","bit6","pui4","zeoi6","jyut6","zi6","zaak3","sam1","heoi2"] },
            { chars: ["一","起","错","讲","不","上","谁","害","了","谁"], jp: ["jat1","hei2","co3","gong2","bat1","soeng6","seoi4","hoi6","liu5","seoi4"] },
            { chars: ["愿","你","先","撇","下","我"], jp: ["jyun6","nei5","sin1","pit3","haa6","ngo5"] },
            { chars: ["似","熄","灭","灯","火"], jp: ["ci5","sik1","mit6","dang1","fo2"] },
            { chars: ["从","此","永","决","像","隔","着","河"], jp: ["cung4","ci2","wing5","kyut3","zoeng6","gaak3","zoek6","ho4"] },
            { chars: ["期","望","你","的","婚","姻","于","谷","底","找","到","突","破"], jp: ["kei4","mong6","nei5","dik1","fan1","jan1","jyu1","guk1","dai2","zaau2","dou3","dat6","po3"] },
            { chars: ["回","首","与","我","这","段","情","不","愧","爱","过"], jp: ["wui4","sau2","jyu5","ngo5","ze5","dyun6","cing4","bat1","kwai5","ngoi3","gwo3"] },
            { chars: ["尚","有","他","爱","护","我"], jp: ["soeng6","jau5","taa1","ngoi3","wu6","ngo5"] },
            { chars: ["我","不","幸","福","么"], jp: ["ngo5","bat1","hang6","fuk1","maa1"] },
            { chars: ["留","低","爱","侣","抛","开","枷","锁"], jp: ["lau4","dai1","ngoi3","leoi5","paau1","hoi1","gaa1","so2"] },
            { chars: ["其","实","有","些","怯","懦","情","愿","家","里","坐"], jp: ["kei4","sat6","jau5","se1","hip3","no6","cing4","jyun6","gaa1","lei5","zo6"] },
            { chars: ["还","听","到","你","亦","过","得","不","错"], jp: ["waan4","ting1","dou3","nei5","jik6","gwo3","dak1","bat1","co3"] },
            { chars: ["唯","盼","你","故","事","到","结","局"], jp: ["wai4","paan3","nei5","gu3","si6","dou3","git3","guk6"] },
            { chars: ["完","美","里","那","美","中","不","足"], jp: ["jyun4","mei5","lei5","naa5","mei5","zung1","bat1","zuk1"] },
            { chars: ["会","是","我"], jp: ["wui6","si6","ngo5"] },
            { chars: ["明","晚","难","免","的","难","过","的","时","间"], jp: ["ming4","maan5","naan4","min5","dik1","naan4","gwo3","dik1","si4","gaan1"] },
            { chars: ["没","我","可","让","你","不","习","惯"], jp: ["mut6","ngo5","ho2","joeng6","nei5","bat1","zaap6","gwaan3"] },
            { chars: ["下","了","班","就","与","他","归","家","吃","晚","饭"], jp: ["haa6","liu5","baan1","zau6","jyu5","taa1","gwai1","gaa1","hek3","maan5","faan6"] },
            { chars: ["情","话","很","冷","愈","对","感","觉","愈","淡"], jp: ["cing4","waa6","han2","laang5","jyu6","deoi3","gam2","gok3","jyu6","daam6"] },
            { chars: ["万","千","怨","偶","后","悔","嗟","叹"], jp: ["maan6","cin1","jyun3","ngau5","hau6","fui3","ze1","taan3"] },
            { chars: ["接","受","平","淡","谁","人","有","得","拣"], jp: ["zip3","sau6","ping4","daam6","seoi4","jan4","jau5","dak1","gaan2"] },
            { chars: ["总","好","过","偷","欢","过","然","后","要","还"], jp: ["zung2","hou2","gwo3","tau1","fun1","gwo3","jin4","hau6","jiu3","waan4"] },
            { chars: ["愿","你","先","撇","下","我","已","失","落","恋","歌"], jp: ["jyun6","nei5","sin1","pit3","haa6","ngo5","ji5","sat1","lok6","lyun2","go1"] },
            { chars: ["留","低","最","灿","烂","的","花","火"], jp: ["lau4","dai1","zeoi3","caan3","laan6","dik1","faa1","fo2"] },
            { chars: ["来","日","你","影","一","幅","一","家","亲","相","里","没","我"], jp: ["loi4","jat6","nei5","jing2","jat1","fuk1","jat1","gaa1","can1","soeng1","lei5","mut6","ngo5"] },
            { chars: ["仍","可","笑","笑","背","着","人","心","里","有","我"], jp: ["jing4","ho2","siu3","siu3","bui3","zoek6","jan4","sam1","lei5","jau5","ngo5"] },
            { chars: ["下","半","生","各","自","过"], jp: ["haa6","bun3","sang1","gok3","zi6","gwo3"] },
            { chars: ["也","不","尽","凄","楚"], jp: ["jaa5","bat1","zeon6","cai1","co2"] },
            { chars: ["怀","中","有","过","盛","开","花","朵"], jp: ["waai4","zung1","jau5","gwo3","sing6","hoi1","faa1","do2"] },
            { chars: ["除","掉","那","些","允","诺"," ","除","分","开","允","诺"], jp: ["ceoi4","diu6","naa5","se1","wan5","nok6","","ceoi4","fan1","hoi1","wan5","nok6"] },
            { chars: ["其","他","的","也","共","你","得","到","过"], jp: ["kei4","taa1","dik1","jaa5","gung6","nei5","dak1","dou3","gwo3"] },
            { chars: ["期","盼","你","那","愉","快","结","局"], jp: ["kei4","paan3","nei5","naa5","jyu4","faai3","git3","guk6"] },
            { chars: ["常","记","挂","那","美","中","不","足"], jp: ["soeng4","gei3","gwaa3","naa5","mei5","zung1","bat1","zuk1"] },
            { chars: ["会","是","我"], jp: ["wui6","si6","ngo5"] },
            { chars: ["愿","你","先","撇","下","我"], jp: ["jyun6","nei5","sin1","pit3","haa6","ngo5"] },
            { chars: ["似","熄","灭","灯","火"], jp: ["ci5","sik1","mit6","dang1","fo2"] },
            { chars: ["从","此","永","决","像","隔","着","河"], jp: ["cung4","ci2","wing5","kyut3","zoeng6","gaak3","zoek6","ho4"] },
            { chars: ["期","望","你","的","婚","姻","于","谷","底","找","到","突","破"], jp: ["kei4","mong6","nei5","dik1","fan1","jan1","jyu1","guk1","dai2","zaau2","dou3","dat6","po3"] },
            { chars: ["回","首","与","我","这","段","情","不","愧","爱","过"], jp: ["wui4","sau2","jyu5","ngo5","ze5","dyun6","cing4","bat1","kwai5","ngoi3","gwo3"] },
            { chars: ["尚","有","他","爱","护","我"], jp: ["soeng6","jau5","taa1","ngoi3","wu6","ngo5"] },
            { chars: ["我","不","幸","福","么"], jp: ["ngo5","bat1","hang6","fuk1","maa1"] },
            { chars: ["留","低","爱","侣","抛","开","枷","锁"], jp: ["lau4","dai1","ngoi3","leoi5","paau1","hoi1","gaa1","so2"] },
            { chars: ["其","实","有","些","怯","懦","情","愿","家","里","坐"], jp: ["kei4","sat6","jau5","se1","hip3","no6","cing4","jyun6","gaa1","lei5","zo6"] },
            { chars: ["还","听","到","你","亦","过","得","不","错"], jp: ["waan4","ting1","dou3","nei5","jik6","gwo3","dak1","bat1","co3"] },
            { chars: ["唯","盼","你","故","事","到","结","局"], jp: ["wai4","paan3","nei5","gu3","si6","dou3","git3","guk6"] },
            { chars: ["完","美","里","那","美","中","不","足"], jp: ["jyun4","mei5","lei5","naa5","mei5","zung1","bat1","zuk1"] },
            { chars: ["会","是","我"], jp: ["wui6","si6","ngo5"] }
        ]
    };
    if (typeof window !== 'undefined' && window.__songs) {
        window.__songs.push(song);
    }
})();
