// 歌曲：致少年时代

(function() {
    const song = {
        id: 1778517119067,
        title: "致少年时代",
        titleJyutping: ["zi3","siu2","nin4","si4","doi6"],
        artist: "古巨基",
        artistJyutping: ["gu2","geoi6","gei1"],
        lyricist: "林夕",
        lyricistJyutping: ["lam4","zik6"],
        composer: "方皓玟",
        composerJyutping: ["fong1","hou6","man4"],
        lyrics: [
            { chars: ["爱",
            "少",
            "年",
            "时",
            "代",
            " ",
            "放",
            "肆",
            "而",
            "无",
            "害"], jp: ["ngoi3",
            "siu2",
            "nin4",
            "si4",
            "doi6",
            "",
            "fong3",
            "si3",
            "ji4",
            "mou4",
            "hoi6"] },
            { chars: ["最",
            "爱",
            "着",
            "拖",
            "鞋",
            "跑",
            "屋",
            "邨",
            "似",
            "障",
            "碍",
            "赛"], jp: ["zeoi3",
            "ngoi3",
            "zoek6",
            "to1",
            "haai4",
            "paau2",
            "uk1",
            "cyun1",
            "ci5",
            "zoeng3",
            "ngoi6",
            "coi3"] },
            { chars: ["然",
            "后",
            "最",
            "怕",
            "背",
            "书",
            "里",
            "未",
            "懂",
            "装",
            "懂",
            "的",
            "感",
            "慨"], jp: ["jin4",
            "hau6",
            "zeoi3",
            "paa3",
            "bui3",
            "syu1",
            "lei5",
            "mei6",
            "dung2",
            "zong1",
            "dung2",
            "dik1",
            "gam2",
            "koi3"] },
            { chars: ["未",
            "料",
            "到",
            "将",
            "来",
            " ",
            "那",
            "强",
            "说",
            "的",
            "愁",
            " ",
            "已",
            "情",
            "怀",
            "不",
            "再"], jp: ["mei6",
            "liu6",
            "dou3",
            "zoeng1",
            "loi4",
            "",
            "naa5",
            "koeng4",
            "syut3",
            "dik1",
            "sau4",
            "",
            "ji5",
            "cing4",
            "waai4",
            "bat1",
            "zoi3"] },
            { paragraphBreak: true },
            { chars: ["羡",
            "慕",
            "你",
            "想",
            "哭",
            "与",
            "笑",
            "时",
            "哭",
            "与",
            "笑",
            "永",
            "未",
            "顾",
            "忌"], jp: ["sin6",
            "mou6",
            "nei5",
            "soeng2",
            "huk1",
            "jyu5",
            "siu3",
            "si4",
            "huk1",
            "jyu5",
            "siu3",
            "wing5",
            "mei6",
            "gu3",
            "gei6"] },
            { chars: ["烦",
            "人",
            "烦",
            "事",
            "不",
            "爱",
            "理",
            "便",
            "不",
            "去",
            "理",
            " ",
            "自",
            "闭",
            "天",
            "地"], jp: ["faan4",
            "jan4",
            "faan4",
            "si6",
            "bat1",
            "ngoi3",
            "lei5",
            "bin6",
            "bat1",
            "heoi3",
            "lei5",
            "",
            "zi6",
            "bai3",
            "tin1",
            "dei6"] },
            { chars: ["冥",
            "顽",
            "无",
            "知",
            " ",
            "却",
            "更",
            "会",
            "自",
            "由",
            "做",
            "你",
            "自",
            "己"], jp: ["ming4",
            "waan4",
            "mou4",
            "zi1",
            "",
            "koek3",
            "gang1",
            "wui6",
            "zi6",
            "jau4",
            "zou6",
            "nei5",
            "zi6",
            "gei2"] },
            { chars: ["只",
            "要",
            "想",
            "逃",
            "避",
            " ",
            "被",
            "窝",
            "总",
            "可",
            "以",
            "抱",
            "紧",
            "你"], jp: ["zi2",
            "jiu3",
            "soeng2",
            "tou4",
            "bei6",
            "",
            "bei6",
            "wo1",
            "zung2",
            "ho2",
            "ji5",
            "pou5",
            "gan2",
            "nei5"] },
            { paragraphBreak: true },
            { chars: ["爱",
            "偶",
            "像",
            "年",
            "代",
            " ",
            "会",
            "疯",
            "狂",
            "期",
            "待"], jp: ["ngoi3",
            "ngau5",
            "zoeng6",
            "nin4",
            "doi6",
            "",
            "wui6",
            "fung1",
            "kong4",
            "kei4",
            "doi6"] },
            { chars: ["最",
            "爱",
            "看",
            "颁",
            "奖",
            "礼",
            "歌",
            "星",
            "要",
            "角",
            "逐",
            "比",
            "赛"], jp: ["zeoi3",
            "ngoi3",
            "hon3",
            "baan1",
            "zoeng2",
            "lai5",
            "go1",
            "sing1",
            "jiu3",
            "gok3",
            "zuk6",
            "bei2",
            "coi3"] },
            { chars: ["还",
            "道",
            "最",
            "痛",
            "像",
            "高",
            "处",
            "荡",
            "千",
            "秋",
            "摔",
            "伤",
            "膝",
            "盖"], jp: ["waan4",
            "dou6",
            "zeoi3",
            "tung3",
            "zoeng6",
            "gou1",
            "cyu5",
            "dong6",
            "cin1",
            "cau1",
            "seot1",
            "soeng1",
            "sat1",
            "goi3"] },
            { chars: ["痛",
            "那",
            "么",
            "单",
            "纯",
            " ",
            "爱",
            "那",
            "么",
            "轻",
            "易",
            " ",
            "幼",
            "稚",
            "而",
            "可",
            "爱"], jp: ["tung3",
            "naa5",
            "maa1",
            "daan1",
            "seon4",
            "",
            "ngoi3",
            "naa5",
            "maa1",
            "hing1",
            "ji6",
            "",
            "jau3",
            "zi6",
            "ji4",
            "ho2",
            "ngoi3"] },
            { paragraphBreak: true },
            { chars: ["羡",
            "慕",
            "你",
            "想",
            "哭",
            "与",
            "笑",
            "时",
            "哭",
            "与",
            "笑",
            "永",
            "未",
            "顾",
            "忌"], jp: ["sin6",
            "mou6",
            "nei5",
            "soeng2",
            "huk1",
            "jyu5",
            "siu3",
            "si4",
            "huk1",
            "jyu5",
            "siu3",
            "wing5",
            "mei6",
            "gu3",
            "gei6"] },
            { chars: ["烦",
            "人",
            "烦",
            "事",
            "不",
            "爱",
            "理",
            "便",
            "不",
            "去",
            "理",
            " ",
            "自",
            "闭",
            "天",
            "地"], jp: ["faan4",
            "jan4",
            "faan4",
            "si6",
            "bat1",
            "ngoi3",
            "lei5",
            "bin6",
            "bat1",
            "heoi3",
            "lei5",
            "",
            "zi6",
            "bai3",
            "tin1",
            "dei6"] },
            { chars: ["冥",
            "顽",
            "无",
            "知",
            " ",
            "却",
            "更",
            "会",
            "自",
            "由",
            "做",
            "你",
            "自",
            "己"], jp: ["ming4",
            "waan4",
            "mou4",
            "zi1",
            "",
            "koek3",
            "gang1",
            "wui6",
            "zi6",
            "jau4",
            "zou6",
            "nei5",
            "zi6",
            "gei2"] },
            { chars: ["只",
            "要",
            "想",
            "逃",
            "避",
            " ",
            "被",
            "窝",
            "总",
            "可",
            "以",
            "抱",
            "紧",
            "你"], jp: ["zi2",
            "jiu3",
            "soeng2",
            "tou4",
            "bei6",
            "",
            "bei6",
            "wo1",
            "zung2",
            "ho2",
            "ji5",
            "pou5",
            "gan2",
            "nei5"] },
            { paragraphBreak: true },
            { chars: ["从",
            "前",
            "全",
            "为",
            "怕",
            "考",
            "试",
            "渴",
            "望",
            "能",
            "大",
            "个"], jp: ["cung4",
            "cin4",
            "cyun4",
            "wai4",
            "paa3",
            "haau2",
            "si3",
            "hot3",
            "mong6",
            "nang4",
            "daai6",
            "go3"] },
            { chars: ["今",
            "日",
            "我",
            " ",
            "偏",
            "担",
            "起",
            "更",
            "深",
            "功",
            "课"], jp: ["gam1",
            "jat6",
            "ngo5",
            "",
            "pin1",
            "daam1",
            "hei2",
            "gang1",
            "sam1",
            "gung1",
            "fo3"] },
            { chars: ["嫌",
            "从",
            "前",
            "未",
            "算",
            "闯",
            "够",
            "祸",
            "亦",
            "无",
            "悔",
            "当",
            "初"], jp: ["jim4",
            "cung4",
            "cin4",
            "mei6",
            "syun3",
            "cong2",
            "gau3",
            "wo6",
            "jik6",
            "mou4",
            "fui3",
            "dong1",
            "co1"] },
            { chars: ["成",
            "熟",
            "催",
            "促",
            "爱",
            "玩",
            "的",
            "你",
            " ",
            "已",
            "懂",
            "得",
            "太",
            "多"], jp: ["sing4",
            "suk6",
            "ceoi1",
            "cuk1",
            "ngoi3",
            "wun6",
            "dik1",
            "nei5",
            "",
            "ji5",
            "dung2",
            "dak1",
            "taai3",
            "do1"] },
            { paragraphBreak: true },
            { chars: ["妒",
            "忌",
            "你",
            "能",
            "想",
            "发",
            "泄",
            "时",
            "敢",
            "发",
            "泄",
            "拒",
            "绝",
            "皱",
            "眉"], jp: ["dou3",
            "gei6",
            "nei5",
            "nang4",
            "soeng2",
            "faat3",
            "sit3",
            "si4",
            "gam2",
            "faat3",
            "sit3",
            "keoi5",
            "zyut6",
            "zau3",
            "mei4"] },
            { chars: ["明",
            "明",
            "还",
            "未",
            "懂",
            "世",
            "故",
            "幻",
            "想",
            "世",
            "态",
            "无",
            "数",
            "滋",
            "味"], jp: ["ming4",
            "ming4",
            "waan4",
            "mei6",
            "dung2",
            "sai3",
            "gu3",
            "waan6",
            "soeng2",
            "sai3",
            "taai3",
            "mou4",
            "sou3",
            "zi1",
            "mei6"] },
            { chars: ["明",
            "明",
            "无",
            "知",
            " ",
            "世",
            "界",
            "却",
            "又",
            "原",
            "谅",
            "你",
            "自",
            "欺"], jp: ["ming4",
            "ming4",
            "mou4",
            "zi1",
            "",
            "sai3",
            "gaai3",
            "koek3",
            "jau6",
            "jyun4",
            "loeng6",
            "nei5",
            "zi6",
            "hei1"] },
            { chars: ["转",
            "眼",
            "天",
            "和",
            "地",
            " ",
            "便",
            "一",
            "板",
            "一",
            "眼",
            "约",
            "束",
            "你"], jp: ["zyun2",
            "ngaan5",
            "tin1",
            "wo4",
            "dei6",
            "",
            "bin6",
            "jat1",
            "baan2",
            "jat1",
            "ngaan5",
            "joek3",
            "cuk1",
            "nei5"] },
            { chars: ["假",
            "设",
            "可",
            "重",
            "遇",
            " ",
            "让",
            "今",
            "天",
            "的",
            "我",
            "轻",
            "抚",
            "你"], jp: ["gaa2",
            "cit3",
            "ho2",
            "cung5",
            "jyu6",
            "",
            "joeng6",
            "gam1",
            "tin1",
            "dik1",
            "ngo5",
            "hing1",
            "fu2",
            "nei5"] }
        ]
    };
    window.__songs.push(song);
})();
