// 歌曲：追风筝的孩子

(function() {
    const song = {
        id: 31,
        title: "追风筝的孩子",
        titleJyutping: ["zeoi1","fung1","zang1","dik1","haai4","zi2"],
        artist: "张敬轩",
        artistJyutping: ["zoeng1","ging3","hin1"],
        lyricist: "林若宁",
        lyricistJyutping: ["lam4","joek6","ning4"],
        composer: "季中平",
        composerJyutping: ["gwai3","zung1","ping4"],
        lyrics: [
            { chars: ["追","风","筝","一","对","傻","瓜"], jp: ["zeoi1","fung1","zang1","jat1","deoi3","so4","gwaa1"] },
            { chars: ["相","信","爱","情","童","话"], jp: ["soeng1","seon3","ngoi3","cing4","tung4","waa6"] },
            { chars: ["当","天","初","恋","想","过","成","家"], jp: ["dong1","tin1","co1","lyun2","soeng2","gwo3","sing4","gaa1"] },
            { chars: ["会","有","一","点","荒","谬","吗"], jp: ["wui6","jau5","jat1","dim2","fong1","mau6","maa1"] },
            { chars: ["爱","到","愁","云","伤","疤"], jp: ["ngoi3","dou3","sau4","wan4","soeng1","baa1"] },
            { chars: ["发","觉","信","仰","有","偏","差"], jp: ["faat3","gok3","seon3","joeng5","jau5","pin1","caa1"] },
            { paragraphBreak: true },
            { chars: ["那","初","恋","彷","似","流","沙"], jp: ["naa5","co1","lyun2","pong4","ci5","lau4","saa1"] },
            { chars: ["吹","散","无","从","留","下"], jp: ["ceoi1","saan3","mou4","cung4","lau4","haa6"] },
            { chars: ["你","的","风","筝","飘","过","篱","笆"], jp: ["nei5","dik1","fung1","zang1","piu1","gwo3","lei4","baa1"] },
            { chars: ["扑","向","短","促","艳","每","落","霞"], jp: ["pok3","hoeng3","dyun2","cuk1","jim6","mui5","lok6","haa4"] },
            { chars: ["你","变","了","个","插","画","家"], jp: ["nei5","bin3","liu5","go3","caap3","waak6","gaa1"] },
            { chars: ["我","变","了","个","作","曲","家"], jp: ["ngo5","bin3","liu5","go3","zok3","kuk1","gaa1"] },
            { chars: ["各","有","各","路","线","分","岔"], jp: ["gok3","jau5","gok3","lou6","sin3","fan1","caa3"] },
            { paragraphBreak: true },
            { chars: ["风","筝","飞","不","出","叹","息","桥"], jp: ["fung1","zang1","fei1","bat1","ceot1","taan3","sik1","kiu4"] },
            { chars: ["即","使","分","开","不","必","仰","天","长","啸"], jp: ["zik1","si2","fan1","hoi1","bat1","bit1","joeng5","tin1","coeng4","siu3"] },
            { chars: ["彼","此","之","间","即","使","各","有","车","票"], jp: ["bei2","ci2","zi1","gaan1","zik1","si2","gok3","jau5","ce1","piu3"] },
            { chars: ["失","散","于","繁","嚣"], jp: ["sat1","saan3","jyu1","faan4","hiu1"] },
            { chars: ["初","恋","的","风","景","有","过","不","少"], jp: ["co1","lyun2","dik1","fung1","ging2","jau5","gwo3","bat1","siu2"] },
            { paragraphBreak: true },
            { chars: ["彼","此","相","识","于","叹","息","桥"], jp: ["bei2","ci2","soeng1","sik1","jyu1","taan3","sik1","kiu4"] },
            { chars: ["开","开","心","心","影","张","爱","的","遗","照"], jp: ["hoi1","hoi1","sam1","sam1","jing2","zoeng1","ngoi3","dik1","wai4","ziu3"] },
            { chars: ["彼","此","之","间","即","使","各","有","车","票"], jp: ["bei2","ci2","zi1","gaan1","zik1","si2","gok3","jau5","ce1","piu3"] },
            { chars: ["失","散","于","繁","嚣"], jp: ["sat1","saan3","jyu1","faan4","hiu1"] },
            { chars: ["灰","风","的","初","吻","至","少","感","动","一","两","秒"], jp: ["fui1","fung1","dik1","co1","man5","zi3","siu2","gam2","dung6","jat1","loeng5","miu5"] },
            { paragraphBreak: true },
            { chars: ["断","了","线","那","风","筝"], jp: ["dyun6","liu5","sin3","naa5","fung1","zang1"] },
            { chars: ["到","哪","里","落","地","生","根"], jp: ["dou3","naa5","lei5","lok6","dei6","sang1","gan1"] },
            { chars: ["爱","过","你","仍","然","是","福","份"], jp: ["ngoi3","gwo3","nei5","jing4","jin4","si6","fuk1","fan6"] },
            { paragraphBreak: true },
            { chars: ["风","筝","飞","不","出","叹","息","桥"], jp: ["fung1","zang1","fei1","bat1","ceot1","taan3","sik1","kiu4"] },
            { chars: ["即","使","分","开","不","必","仰","天","长","啸"], jp: ["zik1","si2","fan1","hoi1","bat1","bit1","joeng5","tin1","coeng4","siu3"] },
            { chars: ["毕","竟","当","初","分","享","过","你","欢","笑"], jp: ["bat1","ging2","dong1","co1","fan1","hoeng2","gwo3","nei5","fun1","siu3"] },
            { chars: ["将","记","忆","燃","烧"], jp: ["zoeng1","gei3","jik1","jin4","siu1"] },
            { chars: ["初","恋","的","风","景","有","过","不","少"], jp: ["co1","lyun2","dik1","fung1","ging2","jau5","gwo3","bat1","siu2"] },
            { paragraphBreak: true },
            { chars: ["彼","此","相","识","于","叹","息","桥"], jp: ["bei2","ci2","soeng1","sik1","jyu1","taan3","sik1","kiu4"] },
            { chars: ["开","开","心","心","影","张","爱","的","遗","照"], jp: ["hoi1","hoi1","sam1","sam1","jing2","zoeng1","ngoi3","dik1","wai4","ziu3"] },
            { chars: ["彼","此","之","间","即","使","各","有","车","票"], jp: ["bei2","ci2","zi1","gaan1","zik1","si2","gok3","jau5","ce1","piu3"] },
            { chars: ["失","散","于","繁","嚣"], jp: ["sat1","saan3","jyu1","faan4","hiu1"] },
            { chars: ["灰","风","的","初","吻","至","少","感","动","一","两","秒"], jp: ["fui1","fung1","dik1","co1","man5","zi3","siu2","gam2","dung6","jat1","loeng5","miu5"] },
            { paragraphBreak: true },
            { chars: ["天","空","的","白","云"], jp: ["tin1","hung1","dik1","baak6","wan4"] },
            { chars: ["有","哪","朵","可","以","与","我","互","吻"], jp: ["jau5","naa5","do2","ho2","ji5","jyu5","ngo5","wu6","man5"] },
            { chars: ["穿","梭","的","路","人"], jp: ["cyun1","so1","dik1","lou6","jan4"] },
            { chars: ["每","个","都","可","与","我","合","衬"], jp: ["mui5","go3","dou1","ho2","jyu5","ngo5","hap6","can3"] },
            { chars: ["初","恋","那","个","烙","印"], jp: ["co1","lyun2","naa5","go3","lok3","jan3"] },
            { chars: ["掀","起","那","次","地","震"], jp: ["hin1","hei2","naa5","ci3","dei6","zan3"] },
            { chars: ["总","可","迫","使","我","锻","炼","勇","敢"], jp: ["zung2","ho2","baak1","si2","ngo5","dyun3","lin6","jung5","gam2"] },
            { paragraphBreak: true },
            { chars: ["彼","此","分","开","于","叹","息","桥"], jp: ["bei2","ci2","fan1","hoi1","jyu1","taan3","sik1","kiu4"] },
            { chars: ["失","恋","得","多"," ","应","该","更","聪","明","了"], jp: ["sat1","lyun2","dak1","do1","","jing3","goi1","gang1","cung1","ming4","liu5"] },
            { chars: ["即","使","心","一","死","都","要","有","心","跳"], jp: ["zik1","si2","sam1","jat1","sei2","dou1","jiu3","jau5","sam1","tiu3"] },
            { chars: ["一","下","不","能","少"], jp: ["jat1","haa6","bat1","nang4","siu2"] },
            { chars: ["坚","贞","的","心","境","还","是","要","动","摇"], jp: ["gin1","zing1","dik1","sam1","ging2","waan4","si6","jiu3","dung6","jiu4"] },
            { chars: ["风","筝","消","失","于","叹","息","桥"], jp: ["fung1","zang1","siu1","sat1","jyu1","taan3","sik1","kiu4"] },
            { chars: ["开","开","心","心","一","起","向","它","凭","吊"], jp: ["hoi1","hoi1","sam1","sam1","jat1","hei2","hoeng3","taa1","pang4","diu3"] },
            { chars: ["很","多","东","西","毕","竟","控","制","不","了"], jp: ["han2","do1","dung1","sai1","bat1","ging2","hung3","zai3","bat1","liu5"] },
            { chars: ["失","散","于","繁","嚣"], jp: ["sat1","saan3","jyu1","faan4","hiu1"] },
            { chars: ["都","多","得","一","个","你","当","日","跟","我","笑"], jp: ["dou1","do1","dak1","jat1","go3","nei5","dong1","jat6","gan1","ngo5","siu3"] },
            { paragraphBreak: true },
            { chars: ["纵","使","不","跳","了"], jp: ["zung3","si2","bat1","tiu3","liu5"] }
        ]
    };
    if (typeof window !== 'undefined' && window.__songs) {
        window.__songs.push(song);
    }
})();
