// 歌曲：重复犯错

(function() {
    const song =     {
        id: 1,
        title: "重复犯错",
        titleJyutping: ["cung4","fuk1","faan6","co3"],
        artist: "古巨基",
        artistJyutping: ["gu2","geoi6","gei1"],
        lyricist: "林夕",
        lyricistJyutping: ["lam4","zik6"],
        composer: "陈辉阳",
        composerJyutping: ["can4","fai1","joeng4"],
        lyrics: [
            { chars: ["不","知","你"," ","难","过","寂","寞"], jp: ["bat1","zi1","nei5","","naan4","gwo3","zik6","mok6"] },
            { chars: ["听","到","你","说"," ","毫","不","快","乐"], jp: ["ting1","dou3","nei5","syut3","","hou4","bat1","faai3","lok6"] },
            { chars: ["令","我","想"," ","我","这","一","生"], jp: ["ling6","ngo5","soeng2","","ngo5","ze2","jat1","saang1"] },
            { chars: ["往","后","娱","乐"," ","亦","难","快","乐"], jp: ["wong5","hau6","jyu4","lok6","","jik6","naan4","faai3","lok6"] },
            { chars: ["如","若","我","还","尊","重","爱","情"], jp: ["jyu4","joek6","ngo5","waan4","zyun1","zung6","oi3","cing4"] },
            { chars: ["无","谓","问","那","次","飞","关","岛","畅","泳"], jp: ["mou4","wai6","man6","naa5","ci3","fei1","gwaan1","dou2","coeng3","wing6"] },
            { chars: ["其","实","你"], jp: ["kei4","sat6","nei5"] },
            { chars: ["找","不","到","任","何","的","高","兴"], jp: ["zaau2","bat1","dou3","jam6","ho4","dik1","gou1","hing3"] },
            { chars: ["也","许","跟","我","吃","喝","进","睡"], jp: ["jaa5","heoi2","gan1","ngo5","hek3","hot3","zeon3","seoi6"] },
            { chars: ["会","一","生","都","使","你","有","阴","影"], jp: ["wui5","jat1","saang1","dou1","si2","nei5","jau5","jam1","jing2"] },
            { chars: ["但","求","要","逃","命"], jp: ["daan6","kau4","jiu3","tou4","ming6"] },
            { paragraphBreak: true },
            { chars: ["仿","佛","以","往","接","吻","过","程"], jp: ["fong2","fat6","ji5","wong5","zip3","man5","gwo3","cing4"] },
            { chars: ["无","异","于","吻","过","路","人"], jp: ["mou4","ji6","jyu1","man5","gwo3","lou6","jan4"] },
            { chars: ["所","以","细","雪","无","声"], jp: ["so2","ji5","sai3","syut3","mou4","sing1"] },
            { chars: ["突","然","之","间"], jp: ["dat6","jin4","zi1","gaan1"] },
            { chars: ["很","喜","欢","你","恨","我"], jp: ["han2","hei2","fun1","nei5","han6","ngo5"] },
            { chars: ["我","从","未","爱","到"], jp: ["ngo5","cung4","mei6","oi3","dou3"] },
            { chars: ["要","生","生","死","死","那","么","多"], jp: ["jiu3","saang1","saang1","sei2","sei2","naa5","me1","do1"] },
            { chars: ["结","束","感","情","最","悲","壮","结","果"], jp: ["git3","cuk1","gam2","cing4","zeoi3","bei1","zong3","git3","gwo2"] },
            { chars: ["原","来","似"], jp: ["jyun4","loi4","ci5"] },
            { chars: ["以","掌","心","扑","火"], jp: ["ji5","zoeng2","sam1","puk1","fo2"] },
            { chars: ["未","算","得","到"], jp: ["mei6","syun3","dak1","dou3"] },
            { chars: ["偏","得","到","你","是","哪","位","错"], jp: ["pin1","dak1","dou3","nei5","si6","naa5","wai2","co3"] },
            { chars: ["难","道","你","我","以","相","恋","失","恋","去","切","磋"], jp: ["naan4","dou6","nei5","ngo5","ji5","soeng1","lyun2","sat1","lyun2","heoi3","cit3","co1"] },
            { chars: ["会","令","情","侣","受","苦","已","是","爱"], jp: ["wui5","ling6","cing4","leoi5","sau6","fu2","ji5","si6","oi3"] },
            { chars: ["但","我","答","应","我"], jp: ["daan6","ngo5","daap3","jing1","ngo5"] },
            { chars: ["永","不","要","重","复","犯","错"], jp: ["wing5","bat1","jiu3","cung4","fuk1","faan6","co3"] },
            { paragraphBreak: true },
            { chars: ["最","惨","恋","爱","会","有","过","程"], jp: ["zeoi3","caam2","lyun2","oi3","wui5","jau5","gwo3","cing4"] },
            { chars: ["到","沙","滩","多","一","次","看","星","星"], jp: ["dou3","saa1","taan1","do1","jat1","ci3","hon3","sing1","sing1"] },
            { chars: ["亦","难","以","偿","命"], jp: ["jik6","naan4","ji5","soeng4","ming6"] },
            { chars: ["当","初","与","你","有","过","爱","情"], jp: ["dong1","co1","jyu5","nei5","jau5","gwo3","oi3","cing4"] },
            { chars: ["同","样","一","吻","有","任","何","反","应"], jp: ["tung4","joeng6","jat1","man5","jau5","jam6","ho4","faan2","jing3"] },
            { chars: ["已","结","成","冰"], jp: ["ji5","git3","sing4","bing1"] },
            { paragraphBreak: true },
            { chars: ["如","若","我","还","尊","重","爱","情"], jp: ["jyu4","joek6","ngo5","waan4","zyun1","zung6","oi3","cing4"] },
            { chars: ["我","会","放","弃","了","呼","吸","般","镇","定"], jp: ["ngo5","wui5","fong3","hei3","liu5","fu1","kap1","baan1","zan3","ding6"] },
            { chars: ["唯","望","你"], jp: ["wai4","mong6","nei5"] },
            { chars: ["吻","别","时","做","回","些","反","应"], jp: ["man5","bit6","si4","zou6","wui4","se1","faan2","jing3"] },
            { chars: ["没","有","感","情","不","怨","命"], jp: ["mut6","jau5","gam2","cing4","bat1","jyun3","ming6"] },
            { paragraphBreak: true },
            { chars: ["突","然","之","间"], jp: ["dat6","jin4","zi1","gaan1"] },
            { chars: ["很","喜","欢","你","恨","我"], jp: ["han2","hei2","fun1","nei5","han6","ngo5"] },
            { chars: ["我","从","未","爱","到"], jp: ["ngo5","cung4","mei6","oi3","dou3"] },
            { chars: ["要","生","生","死","死","那","么","多"], jp: ["jiu3","saang1","saang1","sei2","sei2","naa5","me1","do1"] },
            { chars: ["结","束","感","情","最","悲","壮","结","果"], jp: ["git3","cuk1","gam2","cing4","zeoi3","bei1","zong3","git3","gwo2"] },
            { chars: ["原","来","似"], jp: ["jyun4","loi4","ci5"] },
            { chars: ["以","掌","心","扑","火"], jp: ["ji5","zoeng2","sam1","puk1","fo2"] },
            { chars: ["未","算","得","到"], jp: ["mei6","syun3","dak1","dou3"] },
            { chars: ["偏","得","到","你","是","哪","位","错"], jp: ["pin1","dak1","dou3","nei5","si6","naa5","wai2","co3"] },
            { chars: ["难","道","你","我","以","相","恋","失","恋","去","切","磋"], jp: ["naan4","dou6","nei5","ngo5","ji5","soeng1","lyun2","sat1","lyun2","heoi3","cit3","co1"] },
            { chars: ["会","令","情","侣","受","苦","已","是","爱"], jp: ["wui5","ling6","cing4","leoi5","sau6","fu2","ji5","si6","oi3"] },
            { chars: ["但","我","答","应","我"], jp: ["daan6","ngo5","daap3","jing1","ngo5"] },
            { chars: ["永","不","要","重","复","犯","错"], jp: ["wing5","bat1","jiu3","cung4","fuk1","faan6","co3"] },
            { paragraphBreak: true },
            { chars: ["回","味","过","去","每","一","吻"], jp: ["wui4","mei6","gwo3","heoi3","mui5","jat1","man5"] },
            { chars: ["真","切","得"], jp: ["zan1","cit3","dak1"] },
            { chars: ["于","嘴","边","掠","过"], jp: ["jyu1","zeoi2","bin1","loek6","gwo3"] },
            { chars: ["你","的","内","心","竟","在","避","我"], jp: ["nei5","dik1","noi6","sam1","ging2","zoi6","bei6","ngo5"] }
        ]
    };
    if (typeof window !== 'undefined' && window.__songs) {
        window.__songs.push(song);
    }
})();
