// 歌曲：野孩子

(function() {
    const song = {
        id: 343,
        title: "野孩子",
        titleJyutping: ["je5","haai4","zi2"],
        artist: "杨千嬅",
        artistJyutping: ["joeng4","cin1","waa6"],
        lyricist: "黄伟文",
        lyricistJyutping: ["wong4","wai5","man4"],
        composer: "雷颂德",
        composerJyutping: ["leoi4","zung6","dak1"],
        lyrics: [
            { chars: ["就","算","只","谈","一","场","感","情"], jp: ["zau6","syun3","zi2","taam4","jat1","coeng4","gam2","cing4"] },
            { chars: ["除","外","都","是","一","时","虚","荣"], jp: ["ceoi4","ngoi6","dou1","si6","jat1","si4","heoi1","wing4"] },
            { chars: ["不","等","于","在","蜜","月","套","房","游","玩","过"], jp: ["bat1","dang2","jyu1","zoi6","mat6","jyut6","tou3","fong4","jau4","wun6","gwo3"] },
            { chars: ["就","可","自","入","自","出","仙","境"], jp: ["zau6","ho2","zi6","jap6","zi6","ceot1","sin1","ging2"] },
            { chars: ["情","愿","获","得","你","的","尊","敬"], jp: ["cing4","jyun6","wok6","dak1","nei5","dik1","zyun1","ging3"] },
            { chars: ["承","受","太","高","傲","的","罪","名"], jp: ["sing4","sau6","taai3","gou1","ngou6","dik1","zeoi6","ming4"] },
            { chars: ["挤","得","进","你","臂","弯"], jp: ["zai1","dak1","zeon3","nei5","bei3","waan1"] },
            { chars: ["如","情","怀","渐","冷"], jp: ["jyu4","cing4","waai4","zim6","laang5"] },
            { chars: ["未","算","孤","苦","也","伶","仃"], jp: ["mei6","syun3","gu1","fu2","jaa5","ling4","ding1"] },
            { paragraphBreak: true },
            { chars: ["明","知","爱","这","种","男","孩","子"], jp: ["ming4","zi1","ngoi3","ze5","zung2","naam4","haai4","zi2"] },
            { chars: ["也","许","只","能","如","此"], jp: ["jaa5","heoi2","zi2","nang4","jyu4","ci2"] },
            { chars: ["但","我","会","成","为","你","最","牵","挂","的","一","个","女","子"], jp: ["daan6","ngo5","wui6","sing4","wai4","nei5","zeoi3","hin1","gwaa3","dik1","jat1","go3","neoi5","zi2"] },
            { chars: ["朝","朝","暮","暮","让","你","猜","想","如","何","驯","服","我"], jp: ["ciu4","ciu4","mou6","mou6","joeng6","nei5","caai1","soeng2","jyu4","ho4","seon4","fuk6","ngo5"] },
            { chars: ["若","果","亲","手","抱","住"], jp: ["joek6","gwo2","can1","sau2","pou5","zyu6"] },
            { chars: ["或","者","不","必","如","此"], jp: ["waak6","ze2","bat1","bit1","jyu4","ci2"] },
            { paragraphBreak: true },
            { chars: ["许","多","旁","人","说","我","不","太","明","了","男","孩","子"], jp: ["heoi2","do1","pong4","jan4","syut3","ngo5","bat1","taai3","ming4","liu5","naam4","haai4","zi2"] },
            { chars: ["不","受","命","令","就","是","一","种","最","坏","名","字"], jp: ["bat1","sau6","ming6","ling6","zau6","si6","jat1","zung2","zeoi3","waai6","ming4","zi6"] },
            { chars: ["笑","我","这","个","毫","无","办","法","管","束","的","野","孩","子"], jp: ["siu3","ngo5","ze5","go3","hou4","mou4","baan6","faat3","gun2","cuk1","dik1","je5","haai4","zi2"] },
            { chars: ["连","没","有","幸","福","都","不","介","意"], jp: ["lin4","mut6","jau5","hang6","fuk1","dou1","bat1","gaai3","ji3"] },
            { paragraphBreak: true },
            { chars: ["若","我","依","然","坚","持","忠","诚"], jp: ["joek6","ngo5","ji1","jin4","gin1","ci4","zung1","sing4"] },
            { chars: ["难","道","你","又","适","合","安","定"], jp: ["naan4","dou6","nei5","jau6","sik1","hap6","on1","ding6"] },
            { chars: ["真","可","惜"], jp: ["zan1","ho2","sik1"] },
            { chars: ["说","要","吻","我","的","还","未","吻"], jp: ["syut3","jiu3","man5","ngo5","dik1","waan4","mei6","man5"] },
            { chars: ["自","己","就","自","梦","中","甦","醒"], jp: ["zi6","gei2","zau6","zi6","mung6","zung1","sou1","sing2"] },
            { chars: ["离","场","是","否","有","点","失","敬"], jp: ["lei4","coeng4","si6","fau2","jau5","dim2","sat1","ging3"] },
            { chars: ["或","是","更","轰","烈","的","剧","情"], jp: ["waak6","si6","gang1","gwang1","lit6","dik1","kek6","cing4"] },
            { chars: ["必","需","有","这","结","果","才","能","怀","念","我"], jp: ["bit1","seoi1","jau5","ze5","git3","gwo2","coi4","nang4","waai4","nim6","ngo5"] },
            { chars: ["让","我","于","荒","野","驰","骋"], jp: ["joeng6","ngo5","jyu1","fong1","je5","ci4","cing2"] },
            { paragraphBreak: true },
            { chars: ["明","知","爱","这","种","男","孩","子"], jp: ["ming4","zi1","ngoi3","ze5","zung2","naam4","haai4","zi2"] },
            { chars: ["也","许","只","能","如","此"], jp: ["jaa5","heoi2","zi2","nang4","jyu4","ci2"] },
            { chars: ["但","我","会","成","为","你","最","牵","挂","的","一","个","女","子"], jp: ["daan6","ngo5","wui6","sing4","wai4","nei5","zeoi3","hin1","gwaa3","dik1","jat1","go3","neoi5","zi2"] },
            { chars: ["朝","朝","暮","暮","让","你","猜","想","如","何","驯","服","我"], jp: ["ciu4","ciu4","mou6","mou6","joeng6","nei5","caai1","soeng2","jyu4","ho4","seon4","fuk6","ngo5"] },
            { chars: ["若","果","亲","手","抱","住"], jp: ["joek6","gwo2","can1","sau2","pou5","zyu6"] },
            { chars: ["或","者","不","必","如","此"], jp: ["waak6","ze2","bat1","bit1","jyu4","ci2"] },
            { paragraphBreak: true },
            { chars: ["许","多","旁","人","说","我","不","太","明","了","男","孩","子"], jp: ["heoi2","do1","pong4","jan4","syut3","ngo5","bat1","taai3","ming4","liu5","naam4","haai4","zi2"] },
            { chars: ["不","受","命","令","就","是","一","种","最","坏","名","字"], jp: ["bat1","sau6","ming6","ling6","zau6","si6","jat1","zung2","zeoi3","waai6","ming4","zi6"] },
            { chars: ["笑","我","这","个","毫","无","办","法","管","束","的","野","孩","子"], jp: ["siu3","ngo5","ze5","go3","hou4","mou4","baan6","faat3","gun2","cuk1","dik1","je5","haai4","zi2"] },
            { chars: ["连","没","有","幸","福","都","不","介","意"], jp: ["lin4","mut6","jau5","hang6","fuk1","dou1","bat1","gaai3","ji3"] },
            { paragraphBreak: true },
            { chars: ["明","知","爱","这","种","男","孩","子"], jp: ["ming4","zi1","ngoi3","ze5","zung2","naam4","haai4","zi2"] },
            { chars: ["也","许","只","能","如","此"], jp: ["jaa5","heoi2","zi2","nang4","jyu4","ci2"] },
            { chars: ["但","我","会","成","为","你","最","牵","挂","的","一","个","女","子"], jp: ["daan6","ngo5","wui6","sing4","wai4","nei5","zeoi3","hin1","gwaa3","dik1","jat1","go3","neoi5","zi2"] },
            { chars: ["朝","朝","暮","暮","让","你","猜","想","如","何","驯","服","我"], jp: ["ciu4","ciu4","mou6","mou6","joeng6","nei5","caai1","soeng2","jyu4","ho4","seon4","fuk6","ngo5"] },
            { chars: ["若","果","亲","手","抱","住"], jp: ["joek6","gwo2","can1","sau2","pou5","zyu6"] },
            { chars: ["或","者","不","必","如","此"], jp: ["waak6","ze2","bat1","bit1","jyu4","ci2"] },
            { paragraphBreak: true },
            { chars: ["许","多","旁","人","说","我","不","太","明","了","男","孩","子"], jp: ["heoi2","do1","pong4","jan4","syut3","ngo5","bat1","taai3","ming4","liu5","naam4","haai4","zi2"] },
            { chars: ["不","受","命","令","就","是","一","种","最","坏","名","字"], jp: ["bat1","sau6","ming6","ling6","zau6","si6","jat1","zung2","zeoi3","waai6","ming4","zi6"] },
            { chars: ["我","也","笑","我","原","来","是","个","天","生","的","野","孩","子"], jp: ["ngo5","jaa5","siu3","ngo5","jyun4","loi4","si6","go3","tin1","sang1","dik1","je5","haai4","zi2"] },
            { chars: ["连","没","有","幸","福","都","不","介","意"], jp: ["lin4","mut6","jau5","hang6","fuk1","dou1","bat1","gaai3","ji3"] }
        ]
    };
    if (typeof window !== 'undefined' && window.__songs) {
        window.__songs.push(song);
    }
})();
