// 歌曲：飞女正传

(function() {
    const song = {
        id: 363,
        title: "飞女正传",
        titleJyutping: ["fei1","neoi5","zing3","cyun4"],
        artist: "杨千嬅",
        artistJyutping: ["joeng4","cin1","waa6"],
        lyricist: "林夕",
        lyricistJyutping: ["lam4","zik6"],
        composer: "蔡德才",
        composerJyutping: ["coi3","dak1","coi4"],
        lyrics: [
            { chars: ["越","过","生","死","一","刻","跟","你","电","单","车","之","中","峡","路","再","相","逢"], jp: ["jyut6","gwo3","sang1","sei2","jat1","hak1","gan1","nei5","din6","daan1","ce1","zi1","zung1","haap6","lou6","zoi3","soeng1","fung4"] },
            { chars: ["大","概","你","嘴","边","伤","口","与","我","发","端","都","一","般","大","紫","大","红"], jp: ["daai6","koi3","nei5","zeoi2","bin1","soeng1","hau2","jyu5","ngo5","faat3","dyun1","dou1","jat1","bun1","daai6","zi2","daai6","hung4"] },
            { chars: ["下","半","生","不","要","只","要","下","秒","钟"], jp: ["haa6","bun3","sang1","bat1","jiu3","zi2","jiu3","haa6","miu5","zung1"] },
            { chars: ["再","不","敢","吻","你","你","便","再","失","踪"], jp: ["zoi3","bat1","gam2","man5","nei5","nei5","bin6","zoi3","sat1","zung1"] },
            { chars: ["抑","或","有"], jp: ["jik1","waak6","jau5"] },
            { chars: ["谁","高","呼"], jp: ["seoi4","gou1","fu1"] },
            { chars: ["不","要","动"], jp: ["bat1","jiu3","dung6"] },
            { paragraphBreak: true },
            { chars: ["未","怕","挨","紧","颈","边","穿","过","横","飞","的","子","弹"], jp: ["mei6","paa3","aai1","gan2","geng2","bin1","cyun1","gwo3","waang4","fei1","dik1","zi2","daan6"] },
            { chars: ["跟","你","去","走","难"], jp: ["gan1","nei5","heoi3","zau2","naan4"] },
            { chars: ["但","怕","结","婚","生","子","的","平","庸","麻","木","地","活","着"], jp: ["daan6","paa3","git3","fan1","sang1","zi2","dik1","ping4","jung4","maa4","muk6","dei6","wut6","zoek6"] },
            { chars: ["亦","一","样","难"], jp: ["jik6","jat1","joeng6","naan4"] },
            { chars: ["若","与","不","心","爱","的","每","夜","晚","餐"], jp: ["joek6","jyu5","bat1","sam1","ngoi3","dik1","mui5","je6","maan5","caan1"] },
            { chars: ["也","不","知","哪","个","故","事","更","悲","惨"], jp: ["jaa5","bat1","zi1","naa5","go3","gu3","si6","gang1","bei1","caam2"] },
            { chars: ["只","愿","我"], jp: ["zi2","jyun6","ngo5"] },
            { chars: ["能","够","与","你","过","得","今","晚"], jp: ["nang4","gau3","jyu5","nei5","gwo3","dak1","gam1","maan5"] },
            { paragraphBreak: true },
            { chars: ["世","界","将","我","包","围"], jp: ["sai3","gaai3","zoeng1","ngo5","baau1","wai4"] },
            { chars: ["誓","死","都","一","齐"], jp: ["sai6","sei2","dou1","jat1","cai4"] },
            { chars: ["壮","观","得","有","如"], jp: ["zong3","gun1","dak1","jau5","jyu4"] },
            { chars: ["悬","崖","的","婚","礼"], jp: ["jyun4","ngaai4","dik1","fan1","lai5"] },
            { chars: ["也","许","生","于","世","上","无","重","要","作","为"], jp: ["jaa5","heoi2","sang1","jyu1","sai3","soeng6","mou4","cung5","jiu3","zok3","wai4"] },
            { chars: ["仍","有","这","种","真","爱","会","留","低"], jp: ["jing4","jau5","ze5","zung2","zan1","ngoi3","wui6","lau4","dai1"] },
            { paragraphBreak: true },
            { chars: ["我","已","不","顾","安","危","誓","死","都","一","齐"], jp: ["ngo5","ji5","bat1","gu3","on1","ngai4","sai6","sei2","dou1","jat1","cai4"] },
            { chars: ["看","不","起","这","个","繁","华","盛","世"], jp: ["hon3","bat1","hei2","ze5","go3","faan4","waa4","sing6","sai3"] },
            { chars: ["纵","使","天","主","不","忍","心","我","们","如","垃","圾","般","污","秽"], jp: ["zung3","si2","tin1","zyu2","bat1","jan2","sam1","ngo5","mun4","jyu4","laap6","saap3","bun1","wu1","wai3"] },
            { chars: ["抱","着","你","不","枉","献","世"], jp: ["pou5","zoek6","nei5","bat1","wong2","hin3","sai3"] },
            { paragraphBreak: true },
            { chars: ["别","理","三","餐","一","宿"], jp: ["bit6","lei5","saam1","caan1","jat1","suk1"] },
            { chars: ["得","到","牧","师","的","祝","福"], jp: ["dak1","dou3","muk6","si1","dik1","zuk1","fuk1"] },
            { chars: ["需","要","那","种","运"], jp: ["seoi1","jiu3","naa5","zung2","wan6"] },
            { chars: ["让","我","满","足","于","飞","车","之","中"], jp: ["joeng6","ngo5","mun5","zuk1","jyu1","fei1","ce1","zi1","zung1"] },
            { chars: ["抱","紧","苦","恋","的","做","一","类","人"], jp: ["pou5","gan2","fu2","lyun2","dik1","zou6","jat1","leoi6","jan4"] },
            { chars: ["面","对","这","都","市","所","有","霓","虹","灯"], jp: ["min6","deoi3","ze5","dou1","si5","so2","jau5","ngai4","hung4","dang1"] },
            { chars: ["我","敢","说","我","爱","到","动","魄","惊","心"], jp: ["ngo5","gam2","syut3","ngo5","ngoi3","dou3","dung6","paak3","ging1","sam1"] },
            { chars: ["不","负","你"], jp: ["bat1","fu6","nei5"] },
            { chars: ["陪","过","我","刹","那","的","兴","奋"], jp: ["pui4","gwo3","ngo5","caat3","naa5","dik1","hing1","fan5"] },
            { paragraphBreak: true },
            { chars: ["世","界","将","我","包","围"], jp: ["sai3","gaai3","zoeng1","ngo5","baau1","wai4"] },
            { chars: ["誓","死","都","一","齐"], jp: ["sai6","sei2","dou1","jat1","cai4"] },
            { chars: ["壮","观","得","有","如"], jp: ["zong3","gun1","dak1","jau5","jyu4"] },
            { chars: ["悬","崖","的","婚","礼"], jp: ["jyun4","ngaai4","dik1","fan1","lai5"] },
            { chars: ["也","许","生","于","世","上","无","重","要","作","为"], jp: ["jaa5","heoi2","sang1","jyu1","sai3","soeng6","mou4","cung5","jiu3","zok3","wai4"] },
            { chars: ["仍","有","这","种","真","爱","耀","眼","生","辉"], jp: ["jing4","jau5","ze5","zung2","zan1","ngoi3","jiu6","ngaan5","sang1","fai1"] },
            { paragraphBreak: true },
            { chars: ["我","已","不","顾","安","危","誓","死","都","一","齐"], jp: ["ngo5","ji5","bat1","gu3","on1","ngai4","sai6","sei2","dou1","jat1","cai4"] },
            { chars: ["看","不","起","这","个","繁","华","盛","世"], jp: ["hon3","bat1","hei2","ze5","go3","faan4","waa4","sing6","sai3"] },
            { chars: ["纵","使","天","主","不","忍","心","我","们","如","垃","圾","般","污","秽"], jp: ["zung3","si2","tin1","zyu2","bat1","jan2","sam1","ngo5","mun4","jyu4","laap6","saap3","bun1","wu1","wai3"] },
            { chars: ["抱","着","你","不","枉","献","世"], jp: ["pou5","zoek6","nei5","bat1","wong2","hin3","sai3"] },
            { paragraphBreak: true },
            { chars: ["世","界","将","我","包","围"], jp: ["sai3","gaai3","zoeng1","ngo5","baau1","wai4"] },
            { chars: ["誓","死","都","一","齐"], jp: ["sai6","sei2","dou1","jat1","cai4"] },
            { chars: ["壮","观","得","有","如"], jp: ["zong3","gun1","dak1","jau5","jyu4"] },
            { chars: ["悬","崖","的","婚","礼"], jp: ["jyun4","ngaai4","dik1","fan1","lai5"] },
            { chars: ["也","许","生","于","世","上","无","重","要","作","为"], jp: ["jaa5","heoi2","sang1","jyu1","sai3","soeng6","mou4","cung5","jiu3","zok3","wai4"] },
            { chars: ["仍","有","生","死","之","交","可","超","越","一","切"], jp: ["jing4","jau5","sang1","sei2","zi1","gaau1","ho2","ciu1","jyut6","jat1","cit3"] },
            { paragraphBreak: true },
            { chars: ["我","已","不","顾","安","危","誓","死","都","一","齐"], jp: ["ngo5","ji5","bat1","gu3","on1","ngai4","sai6","sei2","dou1","jat1","cai4"] },
            { chars: ["爱","得","起","你"], jp: ["ngoi3","dak1","hei2","nei5"] },
            { chars: ["为","何","还","忌","讳"], jp: ["wai4","ho4","waan4","gei6","wai5"] },
            { chars: ["也","许","出","生","当","天","本","以","为","谁","待","我","像","公","仔"], jp: ["jaa5","heoi2","ceot1","sang1","dong1","tin1","bun2","ji5","wai4","seoi4","doi6","ngo5","zoeng6","gung1","zai2"] },
            { chars: ["最","后","却","苦","恋","蚂","蚁"], jp: ["zeoi3","hau6","koek3","fu2","lyun2","maa6","ngai5"] },
            { paragraphBreak: true },
            { chars: ["难","自","爱","都","懂","得","怎","相","爱"], jp: ["naan4","zi6","ngoi3","dou1","dung2","dak1","zam2","soeng1","ngoi3"] },
            { chars: ["找","得","到","一","个","人","共","我","分","享","这","身","世"], jp: ["zaau2","dak1","dou3","jat1","go3","jan4","gung6","ngo5","fan1","hoeng2","ze5","san1","sai3"] },
            { chars: ["还","未","算","失","礼"], jp: ["waan4","mei6","syun3","sat1","lai5"] }
        ]
    };
    if (typeof window !== 'undefined' && window.__songs) {
        window.__songs.push(song);
    }
})();
